### ISSUE TITLE
RFE - a one liner defining Ansible and a link to its homepage would improve this readme

### ISSUE THREAD

**Issue by kern3020** [openedx-unsupported/configuration#1]
Hello,

The readme for this module starts out with the heading Ansible. It would help the reader if a short description was provided like: Ansible software for configuring and managing computers. Also, this readme would be a handy place to provide a URL to the home page for Ansible http://ansible.cc/docs/

-jk

**Comment by jarv** [comment]
Agreed - we are in the process of cleaning up our configuration management repo and thinking about switching from Ansible to puppet.  I'll clarify that in the README.  Thanks for the feedback! -John

**Comment by kern3020** [comment]
This as been addressed.
