### ISSUE TITLE
Vagrant devstack install broken

### ISSUE THREAD

**Issue by EntilZha** [openedx-unsupported/configuration#1008]
It seems like a change was recently made in:
https://github.com/edx/configuration/commit/dba2c375a5ce37591595b82a1e825e3eb202cc05
To the vagrant file:
https://github.com/edx/configuration/blob/master/vagrant/release/devstack/Vagrantfile

When I run through the default instructions for running a devstack here:
https://github.com/edx/configuration/wiki/edX-Developer-Stack

I get the following error

```
$vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* The following settings shouldn't exist: insert_key
```

Commenting this newline out allows the installation to finish and vagrant ssh functions

**Comment by hkim823** [comment]
Can you tell us what version of Vagrant you are running?  It was put in even though it's on by default for someone who was experiencing issues with ssh.

**Comment by EntilZha** [comment]
Using Vagrant 1.3.5.

Perhaps I should use a newer version and the docs should be updated to reflect the version bump for vagrant?

**Comment by jarv** [comment]
I ran into this same issue today, if you download the latest version of Vagrant it will fix the problem.
I will update the wiki.
