### ISSUE TITLE
Using vagrant to setup in ubuntu 13.10 requires to manually install nfs

### ISSUE THREAD

**Issue by leourbina** [openedx-unsupported/configuration#1009]
When using the devstack vagrant image to setup a development environment under ubuntu 13.10, executing `vagrant up` exits with an error.

Traceback:

```
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:
SSH:
* It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```

The issue is solved after installing `nfs-common`

**Comment by hkim823** [comment]
The devstack uses NFS at this time to make it easier to work on files, but it's not entirely neccesary,and if you don't want to use it, you can comment out those lines in the Vagrantfile.  

I'm a bit surprised that nfs-common isn't installed by default on a Desktop environment Ubuntu installation.  I made a change to the wiki instructions to make note that NFS should be installed prior to use.
