### ISSUE TITLE
Issue found on TASK: [edxapp | install python base-requirements] *****************************

### ISSUE THREAD

**Issue by pabloariasmora** [openedx-unsupported/configuration#1015]
I was following the installation steps on https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation

But it always file on the task  TASK: [edxapp | install python base-requirements] 

Here is the log file of the pip command, as far as I see is not picking up the 0.0.3 url, an

 Downloading from URL https://pypi.python.org/packages/2.7/d/django-filter/django_filter-0.6-py2.py3-none-any.whl#m           d5=2da307b0f63edd5cfc9c14974d58aaee (from https://pypi.python.org/simple/django-filter/)
Downloading/unpacking django-followit==0.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 2           1))
  Getting page https://pypi.python.org/simple/django-followit/
  URLs to search for versions for django-followit==0.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base           .txt (line 21)):
- https://pypi.python.org/simple/django-followit/0.0.3
- https://pypi.python.org/simple/django-followit/
  Getting page https://pypi.python.org/simple/django-followit/0.0.3
  Could not fetch URL https://pypi.python.org/simple/django-followit/0.0.3: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/django-followit/0.0.3 when looking for download links for django-foll           owit==0.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 21))
  Analyzing links from page https://pypi.python.org/simple/django-followit/
    Found link https://pypi.python.org/packages/source/d/django-followit/django-followit-0.0.1.tar.gz#md5=84e33089d6           9cdc4f728d3bb9f897f5aa (from https://pypi.python.org/simple/django-followit/), version: 0.0.1
    Found link https://pypi.python.org/packages/source/d/django-followit/django-followit-0.0.3.tar.gz#md5=d5a675c5cd           570ca91a5fb376153096ec (from https://pypi.python.org/simple/django-followit/), version: 0.0.3
  Ignoring link https://pypi.python.org/packages/source/d/django-followit/django-followit-0.0.1.tar.gz#md5=84e33089d           69cdc4f728d3bb9f897f5aa (from https://pypi.python.org/simple/django-followit/), version 0.0.1 doesn't match ==0.0.3
  Cleaning up...
  Removing temporary dir /edx/app/edxapp/venvs/edxapp/build...
  Exception:
  Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/download.py", line 546, in unpack_http_ur           l
    resp = session.get(target_url, stream=True)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 395,            in get
    return self.request('GET', url, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 383,            in request
    resp = self.send(prep, *_send_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 486,            in send
    r = adapter.send(request, *_kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 387,            in send
    raise Timeout(e)
  Timeout: (<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1cde6d0>, 'Connectio           n to pypi.python.org timed out. (connect timeout=15)')

Any clue?

**Comment by defance** [comment]
Look like network issue. Your server (or VM) cannot connect to pypi.python.org. Is it behind firewall or something?

**Comment by pabloariasmora** [comment]
I was thinking about that but all the others pip commands on ansible are working fine.

Here the pip log, as far as I see somehow pip is ignoring the 0.03 file found and since it test first the 0.0.1 and is not the same as 0.0.3 it get stuck :-1:  and then timeout any idea?

BTW, thanks for the response

 Getting page https://pypi.python.org/simple/django-followit/0.0.3
  Could not fetch URL https://pypi.python.org/simple/django-followit/0.0.3: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/django-followit/0.0.3 when looking for download links for django-followit==0.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 21))
  Analyzing links from page https://pypi.python.org/simple/django-followit/
    Found link https://pypi.python.org/packages/source/d/django-followit/django-followit-0.0.1.tar.gz#md5=84e33089d69cdc4f728d3bb9f897f5aa (from https://pypi.python.org/simple/django-followit/), version: 0.0.1
    Found link https://pypi.python.org/packages/source/d/django-followit/django-followit-0.0.3.tar.gz#md5=d5a675c5cd570ca91a5fb376153096ec (from https://pypi.python.org/simple/django-followit/), version: 0.0.3
  Ignoring link https://pypi.python.org/packages/source/d/django-followit/django-followit-0.0.1.tar.gz#md5=84e33089d69cdc4f728d3bb9f897f5aa (from https://pypi.python.org/simple/django-followit/), version 0.0.1 doesn't match ==0.0.3
Cleaning up...

**Comment by hkim823** [comment]
I see a 0.0.3 version of followit, https://pypi.python.org/packages/source/d/django-followit/django-followit-0.0.3.tar.gz#md5=d5a675c5cd570ca91a5fb376153096ec that being said, workon the edxapp virtualenv and manually install it and see if you can get past this error.

**Comment by pabloariasmora** [comment]
the problem is that if I try to do the manual installation on the Virtualenv, and try again it will retry to install the file and failed again with the same error, since I dont have a way to override the edx/app/edxapp/edx-platform/requirements/edx/base.txt :-(

**Comment by hkim823** [comment]
It shouldn't try to reinstall it as long as it's in the right virtualenv since pip will see it as being already installed.

**Comment by pku9104038** [comment]
According to my experience, pypi.python.org server connection is not so reliable. I am from Chinese behide the great firewall. I have setup a devpi server locally, and mapping pypi to the server, all the package will be cached once they have been accessed.

**Comment by fmyzjs** [comment]
Please set up roles/common/defaults/main.yml  ,modify "COMMON_PYPI_MIRROR_URL"

**Comment by e0d** [comment]
This just looks like PyPi not behaving correctly.

If you follow this link,
https://pypi.python.org/simple/django-followit/0.0.3/, you will get a 404.

If you go here, https://pypi.python.org/simple/django-followit/, you will
see the package that you want, but notice that the directory structure does
not correspond to where PIP is looking.

If you install manually from that link, I think you'll be able to move
forward.

sudo -u edxapp /edx/app/edxapp/venvs/edxapp/bin/pip install
https://pypi.python.org/packages/source/d/django-followit/django-followit-0.0.3.tar.gz#md5=d5a675c5cd570ca91a5fb376153096ec

Best,

Ed
e0d on github.

**Comment by pabloariasmora** [comment]
Thanks Everybody for the advice.

I end up manually installing the package list, I notice that some how if the requirement list is more that 23 I always get the same message regarding of the package name, so I split the list in 3, and that complete the installation. The problem as some of you said is with pip installer :-1: 

Thanks again for all the advice
