### ISSUE TITLE
lms-preview failed

### ISSUE THREAD

**Issue by pku9104038** [openedx-unsupported/configuration#1027]
I have deploy a sandbox and try to create a new course. But I can not use the "preview" button or "View Live" button to view the course. The url in the address bar always like this http://courses/xxxxxxxxxxxxxx, there is not host ip in it. If i add the ip address by hand, i can see the staffview. 
I try to add lms-preview sites in sandbox.yml nginx_sites vars, but it can not fix this problem. 

Is there a option to open the lms-preview/view live feature? and how to do ?

Thanks

**Comment by pku9104038** [comment]
Anybody can give me a hand ？

**Comment by jarv** [comment]
@pku9104038 sorry for the delay in getting back to you.

There are a couple things you want to verify, one is that in /edx/app/edxapp there is an antry for PREVIEW_LMS_BASE, it should be set to the preview hostname.  The other is that you have a CNAME for the preview url.

For example if my edX website URL is "http://jarv.example.com" my PREVIEW_LMS_BASE would be set to "preview.jarv.example.com" and I would create a CNAME for "preview.jarv.example.com" that also points to the edX server.

That should be all that is necessary. You do not need a separate nginx virtual host for preview.
