### ISSUE TITLE
Ubuntu Instructions should mention SSHD config changes

### ISSUE THREAD

**Issue by spawnflagger** [openedx-unsupported/configuration#1031]
On the documentation page: https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation , it should mention that the installation process changes the /etc/ssh/sshd_config and sets PasswordAuthentication to "no".

While I have remote console access, there are some users that might not, and this would prevent them from logging into their VM after a reboot.

It should be mentioned in the instructions that users need to upload private key and use PublicKeyAuthentication (recommended), or edit the sshd_config file after installing but before rebooting.

Or change the behavior of the installer so it doesn't make changes to SSH configuration.

**Comment by pku9104038** [comment]
My suggestion is make the default value of PasswordAuthentication to "yes".  This will keep pass word and key authentication available.

**Comment by hkim823** [comment]
I'm really not a fan of password authentication for the security implications it has.  It's highly insecure when running something in production.  Our devstack now takes this into account, but it's not something that I would ever recommend to anyone running a production server.  

I think the "These instructions will potentially destroy the server they are run on, you should only do them on a virtual machine." warning is sufficient but I will add a line in the wiki

**Comment by spawnflagger** [comment]
As a sysadmin, we have to trust that running an install script with root privileges only does what it says it will do (install EdX and supporting packages in this case), and won't use root access to make other changes to the system (it might have been mentioned in the log file, but I'm only looking for error messages when it's 350+ steps that the installer runs).  I know the wiki instructions page is for creating a stand-alone VM, and that's what what I used them for - development not production.
I also agree that using PublicKey auth instead of passwords is best, but not always practical.

Eventually would be nice to see another separate Wiki page for all the steps for a "production" environment, multiple tiers and VMs, security hardening, bandwidth and storage requirements, sizing/scaling, etc.  (some customers would use EC2, and CloudFormation and/or vagrant with some EdX-provided AMIs could automate most of that - but other customers would want to run on private clouds/clusters).

**Comment by pku9104038** [comment]
@spawnflagger I agree with you. I have meet this problem several times before I find out that the ssh log in via password have been blocked. In my opinion, this level configuration can not modified by a auto configuration task of application deployment. It must operate by sysadmin.

**Comment by e0d** [comment]
@spawnflagger I don't think you can trust any scripts, ours included, that are run as root on machines that you are responsible for managing.  Further, I would not recommend that anyone run our scripts for a production deployment without thoroughly reviewing them and reading all of the log output.  The configuration repository contains the ansible scripts as we run them against our servers and, as such, represents our best practices.  That said, stating this more clearly on the wiki is a reasonable ask.
