### ISSUE TITLE
Non-AWS Cloud platform supported ?

### ISSUE THREAD

**Issue by wzymaster** [openedx-unsupported/configuration#1033]
Hi,
   I am wondering if OpenEdx will support non-AWS Cloud platform, like IBM SoftLayer ? 

  Is there an  abstract layer in OpenEdx to support various Cloud providers ? 

thanks
Leo Wu

**Comment by e0d** [comment]
We have no current support for provisioning the infrastructure in other clouds.  Obviously, cloud formation is Amazon specific, and even for Amazon deployments it has it's drawbacks.

That said, the Ansible portion of our code will work in other environments for configuring the servers.  Ansible uses the notion of an inventory to target servers.  There are inventory providers for other cloud platforms like GCE, though I'm not aware of one for Softlayer.  However, ansible can use simple inventories that are nothing more than a list of IPs or hostnames.

**Comment by jarv** [comment]
Adding to what @e0d said there is nothing AWS specific in these instructions - https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation if you want to try to install the entire edX stack on a single Ubuntu 12.04 server.

**Comment by wzymaster** [comment]
thanks for the quick reply very much.  I am wondering where I can find the codes to handle provisioning of a host on Cloud Platform ? I would like to see if  it is easy to inject our IBM SoftLayer provision driver into it .

Please advise it. thanks a lot !

**Comment by e0d** [comment]
You can run our continuous integration play against your server.

This assumes you have virtualenv wrapper installed and you can already ssh to your server.  We currently require Ubuntu 12.04LTS

```
git clone git@github.com:edx/configuration.git
cd configuration
mkvirtualenv edx-configuration
pip install -r requirements.txt
cd playbooks/edx-east
ansible-playbook -i '<YOUR_SERVERS_IP>,' edx_continuous_integration.yml
```
