### ISSUE TITLE
Setup LMS Preview in a production stack

### ISSUE THREAD

**Issue by louyihua** [openedx-unsupported/configuration#1051]
It seems that the lms-preview feature is not enabled in the production stack, as I can't find the nginx configuration for lms-preview, neither the supervisord process. How can I enable it?
PS: The 'view live' feature works correctly, but the preview feature does not work as what it says -- it is just the same the the 'view live' feature.

**Comment by pku9104038** [comment]
hi I meet the same problem int sandbox, and the "view live" do not work too. could you give me a hand about how to make view live work? 
Seams you come from China,hope that can share more info about local deployment of Chinese version in the feature with you.

**Comment by hkim823** [comment]
In ansible, the variable to set is EDXAPP_PREVIEW_LMS_BASE which you can set as preview.localhost or whatever is appropriate.
