### ISSUE TITLE
Build a release box compatible with vagrant-lxc

### ISSUE THREAD

**Issue by aboudreault** [openedx-unsupported/configuration#1058]
I would like to build a vagrant release boxes compatible with vagrant lxc. Is there any documentation how injera box has been built?

**Comment by feanil** [comment]
@aboudreault the base boxes are built using the base vagrant files: https://github.com/edx/configuration/tree/master/vagrant/base

If you have a configuration environment setup, you should be able to go into those folders and run `vagrant up`

If you don't have a configuration environment setup, clone the repo and run a `pip install -r requirements.txt` in the top-level directory before running `vagrant up` in one of the base vagrant directories.

**Comment by aboudreault** [comment]
@feanil Thank you!
