### ISSUE TITLE
It's difficult to work in other repos with devstack

### ISSUE THREAD

**Issue by nedbat** [openedx-unsupported/configuration#1059]
If a developer wants to build XBlocks, they need the xblock-sdk repo.  That repo isn't cloned by default.  If I clone it myself, I need to NFS-mount it so it's available in the guest OS.
Could we make this simpler?  Could a single directory be mounted, with repos cloned within it?  What's the advice for XBlock authors using devstack?

**Comment by feanil** [comment]
@nedbat right now I don't have any advice and I haven't worked with the xblock sdk myself.  I'd be happy to work with you to get it to be a part of devstack if that makes sense.  It seems like it would also make sense to have a separate vagrant image for xblock development with the workbench and sdk.

**Comment by nedbat** [comment]
BTW, looks like #1060 is the same issue?  Both arose from my conversation with Bob Light.
