### ISSUE TITLE
Add a "XBlock howto" to Developing-on-the-edX-Developer-Stack wiki 

### ISSUE THREAD

**Issue by robertlight** [openedx-unsupported/configuration#1060]
The wiki page: Developing-on-the-edX-Developer-Stack needs a section on how to develop XBlock code within the devstack environment (ideally with add'l notes about pycharm setup).

Ideally, it should take you through cloning the XBlock and xblock-sdk repos to give you a simple "hello world" working workbench.

**Comment by feanil** [comment]
@robertlight thanks for raising the issue, @mhoeber, @singingwolfboy @nedbat   does something like this already exist elsewhere?

**Comment by robertlight** [comment]
I'm more than willing to do the grunt work to write such a doc...but I will need some help and/or a basic outline of how to do XBlock development within a devstack to get started.

oops... I mistakenly closed it...meant to update.

**Comment by mhoeber** [comment]
@robertlight   thanks for initiating this.  Ultimately we'd want to include this in http://edx.readthedocs.org/projects/userdocs/en/latest/

If you want to contribute to the wiki as a start, or directly in RST under docs/en-us/developers, that would be great.  Let me know if I can be of help.

**Comment by singingwolfboy** [comment]
@mhoeber: you might want to mention that our Sphinx-based docs are currently maintained in the edx-platform wiki: https://github.com/edx/edx-platform/tree/master/docs/en_us/developers/source. We started maintaining documentation there, and the scope of the documentation has grown to include more than just edx-platform -- in the future, we may migrate our docs out of that repo and into a dedicated docs repo, but we don't have plans to do that just yet.

**Comment by robertlight** [comment]
Xavier referred me to the following:
https://github.com/edx/edx-platform/blob/master/docs/en_us/developers/source/xblocks.rst#testing

it looks like it is at least a good starting point!
