### ISSUE TITLE
Trouble Installing Production Stack

### ISSUE THREAD

**Issue by paradise-os** [openedx-unsupported/configuration#1066]
I am a high school senior working on a project to create an online math course, and have chosen edX as the LMS.

I can't seem to install the edX production stack in a virtual machine (Ubuntu server 64-bit). With the one-step Vagrant install, I get:
"Resolving raw.github.com (raw.github.com)... failed: Temporary failure in name resolution
wget: unable to resolve host address 'raw.github.com' "

When I tried the manual install, everything worked until I got to the command to clone into the configuration directory. I get the following error:
"fatal: HTTP request failed"

Has anyone encountered these issues and/or know any possible solutions to them. Time is of the essence. Thanks in advance.

**Comment by jarv** [comment]
This looks like it might be a temprary error with github, do you see it reliably failing on the same task?

**Comment by hkim823** [comment]
Check from your VM itself that it has outbound network access to GitHub as well as other services.  You didn't say where you are hosting your Ubuntu box.

**Comment by paradise-os** [comment]
It failed yesterday as well as this morning, so I would find it strange if it was "temporary" (I'd think a major site would get things resolved more quickly). The Ubuntu VM is being hosted locally on an external hard drive attached to this laptop. apt-get services and so on DO work, but I will try a simple wget from github and see if that continues to fail. Thanks for the quick replies.

**Comment by hkim823** [comment]
Did you download our vagrant release injera box or are you building Ubuntu from an ISO in your VM?

**Comment by paradise-os** [comment]
hklm823: I'm building from an ISO.

All: Hmm...not having any luck with anything at this point (apt, wget commands...none of it works now). I'll have to troubleshoot when I get home this afternoon.

**Comment by hkim823** [comment]
I'm going to suggest that if you are already running this in VirtualBox, try to use the vagrant boxes we provide for ease of use.
