### ISSUE TITLE
unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials

### ISSUE THREAD

**Issue by ahmadio** [openedx-unsupported/configuration#1075]
I'm getting this error and seems like missing ansible values! or I don't understand what.

```
TASK: [edxlocal | setup the migration db user] ******************************** 
failed: [localhost] => {"failed": true, "item": ""}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials

FATAL: all hosts have already failed -- aborting
```

**Comment by hkim823** [comment]
What play did you run when you got that error?  Can you explain your environment a bit more?

**Comment by ahmadio** [comment]
I was running this command according to instructions in github wiki for installing on ubuntu 12.04

```
cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
```

my environment is a docker container based on ubuntu 12.04 image

**Comment by hkim823** [comment]
I wonder if Docker is doing some sort of initial MySQL setup that our configuration setup isn't taking into account.  Those instructions are based on a very clean installation of Ubuntu 12.04.  You maybe able to put in the information that it's requesting inside of https://github.com/edx/configuration/blob/master/playbooks/roles/common/defaults/main.yml and try it again

**Comment by ahmadio** [comment]
Thanks Han, will try and get back again
