### ISSUE TITLE
Does not install; enters an invalid state

### ISSUE THREAD

**Issue by pmitros** [openedx-unsupported/configuration#1084]
Install fails. Machine never boots. See terminal log below. Ubuntu 13.04

root@lm2:/home/pmitros/devstack# dpkg -i ~pmitros/Downloads/virtualbox-4.3_4.3.10-93012~Ubuntu~raring_amd64.deb 
(Reading database ... 451570 files and directories currently installed.)
Unpacking virtualbox-4.3 (from .../virtualbox-4.3_4.3.10-93012~Ubuntu~raring_amd64.deb) ...
Setting up virtualbox-4.3 (4.3.10-93012~Ubuntu~raring) ...
addgroup: The group `vboxusers' already exists as a system group. Exiting.
Stopping VirtualBox kernel modules ...done.
Uninstalling old VirtualBox DKMS kernel modules ...done.
Trying to register the VirtualBox kernel modules using DKMS ...done.
Starting VirtualBox kernel modules ...done.
Processing triggers for ureadahead ...
Processing triggers for shared-mime-info ...
Unknown media type in type 'all/all'
Unknown media type in type 'all/allfiles'
Unknown media type in type 'uri/mms'
Unknown media type in type 'uri/mmst'
Unknown media type in type 'uri/mmsu'
Unknown media type in type 'uri/pnm'
Unknown media type in type 'uri/rtspt'
Unknown media type in type 'uri/rtspu'
Processing triggers for bamfdaemon ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils ...
Processing triggers for gnome-menus ...
Processing triggers for hicolor-icon-theme ...
root@lm2:/home/pmitros/devstack# dpkg -i ~pmitros/Downloads/vagrant_1.6.2_x86_64.deb 
(Reading database ... 452317 files and directories currently installed.)
Preparing to replace vagrant 1:1.5.1 (using .../vagrant_1.6.2_x86_64.deb) ...
Unpacking replacement vagrant ...
Setting up vagrant (1:1.6.2) ...
root@lm2:/home/pmitros/devstack# exit
pmitros@lm2:~/devstack$ vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vbguest (0.10.0)'!
pmitros@lm2:~/devstack$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 8000 => 8000 (adapter 1)
    default: 8001 => 8001 (adapter 1)
    default: 18080 => 18080 (adapter 1)
    default: 8765 => 8765 (adapter 1)
    default: 9200 => 9200 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

**Comment by feanil** [comment]
@pmitros we do not currently support edx running on machines other than ubuntu 12.04.
