### ISSUE TITLE
NFS mounts fail

### ISSUE THREAD

**Issue by pmitros** [openedx-unsupported/configuration#1089]
The install process gets this far. At this point, it locks up. ssh to the machine shows no folders mounted. I've ran into this issue many times. The only resolution I've seen was a reboot of the host machine. 

Ubuntu 13.10. 

This command does not help: 
vagrant ssh -c 'sudo ln -s /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions'

Log below: 

(edx)pmitros@pmitros:~/devstack$ vagrant reload
==> default: Attempting graceful shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 8000 => 8000 (adapter 1)
    default: 8001 => 8001 (adapter 1)
    default: 18080 => 18080 (adapter 1)
    default: 8765 => 8765 (adapter 1)
    default: 9200 => 9200 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
GuestAdditions 4.2.24 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
[sudo] password for pmitros: 
nfsd running
exportfs: duplicated export entries:
exportfs:       192.168.33.10:/home/pmitros/devstack/edx-platform
exportfs:       192.168.33.10:/home/pmitros/devstack/edx-platform
exportfs: duplicated export entries:
exportfs:       192.168.33.10:/home/pmitros/devstack/cs_comments_service
exportfs:       192.168.33.10:/home/pmitros/devstack/cs_comments_service
exportfs: duplicated export entries:
exportfs:       192.168.33.10:/home/pmitros/devstack/ora
exportfs:       192.168.33.10:/home/pmitros/devstack/ora
==> default: Mounting NFS shared folders...

**Comment by hkim823** [comment]
I have seen this when AnyConnect was in use and even after it's closed some setting prevents NFS mounts from working.  My only fix was a total reboot as well.

**Comment by hkim823** [comment]
I noticed in the output that you're running VB 4.2.24 (or at least it looks like it).  Or at least your guest is running that version of Guest Editions.  You can use https://github.com/dotless-de/vagrant-vbguest to keep VB Guest Editions in sync between your host and guest.  That may help the issue.  Can you post a gist of your Vagrantfile as well?

**Comment by hkim823** [comment]
As for the AnyConnect issue, I hear a work around is to get rid of any existing Host-Only network adapters in VirtualBox.  If you go to VirtualBox - Preferences - Network, get rid of any existing host only adapters, doing a vagrant up will reload them as needed.
