### ISSUE TITLE
Error to start rabbitmq 

### ISSUE THREAD

**Issue by geekaia** [openedx-unsupported/configuration#1090]
I've tried to install edx-production 

wget https://raw.github.com/edx/configuration/master/util/install/vagrant.sh -O - | bash

I've received this error 

TASK: [rabbitmq | start rabbit nodes] ****************************************\* 
failed: [localhost] => {"failed": true, "item": ""}
msg:  \* Stopping message broker rabbitmq-server
- message broker already stopped
  ...done.
- Starting message broker rabbitmq-server
- FAILED - check /var/log/rabbitmq/startup_{log, _err}
  ...fail!

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=221  changed=58   unreachable=0    failed=1

**Comment by e0d** [comment]
What class of machine is this?  Can you verify that disk space are memory are still available?

**Comment by marqpdx** [comment]
I saw this was closed, but i just made an install on Ubuntu 12.0.4 and i got the same error. Install went fine and it all worked until what appears to be one of the last steps. The site is available, and it appears management commands work, but not sure if this issue is critical.

Thanks,
m

**Comment by feanil** [comment]
Can you provide the info that e0d asked from the original user, but for
your setup?

**Comment by marqpdx** [comment]
HI feanil, thanks for getting back to me.

It's a KVM (tried OpenVZ but lack of proper file system settings killed that).

2048 MB ram total. 

when i run free -tom is says there is 6000mb total and 478M used, so i don't think memory is a problem. plenty of disk space.

thanks!
m

**Comment by feanil** [comment]
Have you taken a look at /var/log/rabbitmq/startup_log and startup_err?
Can you post them here?

**Comment by marqpdx** [comment]
The only line in either file (in _log) was:
ERROR: epmd error for host "108": badarg (unknown POSIX error)

To make the install work, i had to change the myhostname = 108 setting in main.cf (/etc/postfix/) to point to my domain name. Not sure what that '108' is all about, but i did see it in that setting, so maybe there is another place i need to set the hostname?
