### ISSUE TITLE
Ansible scripts unicode issue 

### ISSUE THREAD

**Issue by marcotuts** [openedx-unsupported/configuration#1116]
While installing the ansible scripts on an Ubuntu 12.04 Precise LTS machine. (AWS EC2)

Any thoughts on how to resolve this? 

ssh'ed into box, ran the following:
wget https://raw.github.com/edx/configuration/master/util/install/vagrant.sh -O - | bash

.......
TASK: [edxapp | Install edx-platform npm dependencies] ************************
changed: [localhost]

TASK: [edxapp | install python pre-requirements] ******************************
ok: [localhost]

TASK: [edxapp | install python base-requirements] *****************************
failed: [localhost] => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i https://pypi.python.org/simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt ", "delta": "0:12:40.345896", "end": "2014-05-24 16:32:00.496092", "item": "", "rc": 1, "start": "2014-05-24 16:19:20.150196"}
stderr: Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/**init**.py", line 185, in main
    return command.main(cmd_args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 39: ordinal not in range(128)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/ubuntu/edx_sandbox.retry

localhost                  : ok=135  changed=22   unreachable=0    failed=1

**Comment by feanil** [comment]
@marcotuts this is related to the terminal you started out with not being set to use UTF-8(http://stackoverflow.com/questions/10561923/unicodedecodeerror-ascii-codec-cant-decode-byte-0xef-in-position-1)

You can set the lang to use UTF-8 by default by adding the following to your environment.

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```
