### ISSUE TITLE
error instatalling edx on ubuntu 14.04 amazon ec2 

### ISSUE THREAD

**Issue by minasami** [openedx-unsupported/configuration#1141]
TASK: [edxapp | gather  static assets with rake] ******************************
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:04.043433", "end": "2014-06-01 21:14:40.486741", "item": "lms", "rc": 1, "start": "2014-06-01 21:14:36.443308"}
stderr: pip install -r requirements/edx/paver.txt
paver update_assets lms --settings=aws
2014-06-01 17:14:38,256 INFO 27496 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
/usr/bin/env: node: No such file or directory
rake aborted!
Command failed with status (1): [paver update_assets lms --settings=aws...]
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in`call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `sh'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in`sh'
/edx/app/edxapp/edx-platform/rakelib/assets_deprecated.rake:25:in `block in deprecated'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in`call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in`each'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:184:in`block in invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:170:in`invoke'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:101:in`block (2 levels) in top_level'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:101:in`block in top_level'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:95:in`top_level'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:160:in`standard_exception_handling'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
Tasks: TOP => lms:gather_assets:aws
(See full trace by running task with --trace)
stdout: Requirement already satisfied (use --upgrade to upgrade): Paver==1.2.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): psutil==1.2.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): lazy==1.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): path.py==3.0.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): watchdog==0.7.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from lazy==1.1->-r requirements/edx/paver.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.09 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from watchdog==0.7.1->-r requirements/edx/paver.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): argh>=0.8.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from watchdog==0.7.1->-r requirements/edx/paver.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from watchdog==0.7.1->-r requirements/edx/paver.txt (line 6))
Cleaning up...
Task lms:gather_assets:aws has been deprecated. Use paver update_assets lms --settings=aws instead.
---> pavelib.assets.update_assets
---> pavelib.prereqs.install_prereqs
python manage.py lms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
node_modules/.bin/coffee --compile`find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"`
## Captured Task Output:

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_prereqs
python manage.py lms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"`

Build failed running pavelib.assets.update_assets: Subprocess return code: 127
failed: [localhost] => (item=cms) => {"changed": true, "cmd": "SERVICE_VARIANT=cms rake cms:gather_assets:aws ", "delta": "0:00:03.433625", "end": "2014-06-01 21:14:44.067304", "item": "cms", "rc": 1, "start": "2014-06-01 21:14:40.633679"}
stderr: pip install -r requirements/edx/paver.txt
paver update_assets cms --settings=aws
2014-06-01 17:14:42,330 INFO 27561 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
/usr/bin/env: node: No such file or directory
rake aborted!
Command failed with status (1): [paver update_assets cms --settings=aws...]
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in`call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `sh'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in`sh'
/edx/app/edxapp/edx-platform/rakelib/assets_deprecated.rake:25:in `block in deprecated'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in`call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in`each'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:184:in`block in invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:170:in`invoke'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:101:in`block (2 levels) in top_level'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:101:in`block in top_level'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:95:in`top_level'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:160:in`standard_exception_handling'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
Tasks: TOP => cms:gather_assets:aws
(See full trace by running task with --trace)
stdout: Requirement already satisfied (use --upgrade to upgrade): Paver==1.2.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): psutil==1.2.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): lazy==1.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): path.py==3.0.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): watchdog==0.7.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from lazy==1.1->-r requirements/edx/paver.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.09 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from watchdog==0.7.1->-r requirements/edx/paver.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): argh>=0.8.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from watchdog==0.7.1->-r requirements/edx/paver.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from watchdog==0.7.1->-r requirements/edx/paver.txt (line 6))
Cleaning up...
Task cms:gather_assets:aws has been deprecated. Use paver update_assets cms --settings=aws instead.
---> pavelib.assets.update_assets
---> pavelib.prereqs.install_prereqs
python manage.py cms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
node_modules/.bin/coffee --compile`find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"`
## Captured Task Output:

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_prereqs
python manage.py cms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"`

Build failed running pavelib.assets.update_assets: Subprocess return code: 127

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/ubuntu/edx_sandbox.retry

localhost                  : ok=190  changed=40   unreachable=0    failed=1

**Comment by jarv** [comment]
We only support ubuntu precise at this time

**Comment by capital-tower** [comment]
## @jarv  I'm using Ubuntu 12.04 and getting a similar error: Captured Task Output:

---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_ruby_prereqs
bundle install --quiet
---> pavelib.prereqs.install_node_prereqs
npm config set registry http://registry.npmjs.org/
npm install
---> pavelib.prereqs.install_python_prereqs
pip install -q --exists-action w -r requirements/edx/pre.txt
pip install -q --exists-action w -r requirements/edx/github.txt

Build failed running pavelib.prereqs.install_prereqs: Subprocess return code: 1

What can this be??
