### ISSUE TITLE
error instatalling edx on ubuntu 14.04 amazon ec2 

### ISSUE THREAD

**Issue by minasami** [openedx-unsupported/configuration#1142]
when i try to to install the edx platform it gives me this error 
TASK: [edxapp | db migrate] ***************************************************
skipping: [localhost]

TASK: [edxapp | gather  static assets with rake] ******************************
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:04.043433", "end": "2014-06-01 21:14:40.486741", "item": "lms", "rc": 1, "start": "2014-06-01 21:14:36.443308"}
stderr: pip install -r requirements/edx/paver.txt
paver update_assets lms --settings=aws
2014-06-01 17:14:38,256 INFO 27496 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
/usr/bin/env: node: No such file or directory
rake aborted!
Command failed with status (1): [paver update_assets lms --settings=aws...]
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in`call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `sh'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in`sh'
/edx/app/edxapp/edx-platform/rakelib/assets_deprecated.rake:25:in `block in deprecated'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in`call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in`each'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:184:in`block in invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:170:in`invoke'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:101:in`block (2 levels) in top_level'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:101:in`block in top_level'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:95:in`top_level'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:160:in`standard_exception_handling'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
Tasks: TOP => lms:gather_assets:aws
(See full trace by running task with --trace)
stdout: Requirement already satisfied (use --upgrade to upgrade): Paver==1.2.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): psutil==1.2.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): lazy==1.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): path.py==3.0.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): watchdog==0.7.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from lazy==1.1->-r requirements/edx/paver.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.09 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from watchdog==0.7.1->-r requirements/edx/paver.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): argh>=0.8.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from watchdog==0.7.1->-r requirements/edx/paver.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from watchdog==0.7.1->-r requirements/edx/paver.txt (line 6))
Cleaning up...
Task lms:gather

**Comment by feanil** [comment]
Rake relies on `/usr/bin/env` which seems to not be available on your
system.  What OS are you running this on?

**Comment by hkim823** [comment]
@feanil Ubuntu 14.04 which is currently unsupported.  Please use Ubuntu 12.04 64 bit which is supported by Canonical until April 2017

**Comment by scivm** [comment]
I fixed it like this on ubuntu 14.04

Run vagrant.sh script until failure
comment out mongodb in /var/tmp/configuration/playbooks/edx_sandbox.yml - mongo installation is not idempotent in 14.04 (not sure about others)
ln -s /usr/bin/nodejs /usr/bin/node
cd /var/tmp/configuration/playbooks
ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
