### ISSUE TITLE
trying install on ubuntu 12.04

### ISSUE THREAD

**Issue by minasami** [openedx-unsupported/configuration#1157]
it gives me this error 
TASK: [rbenv | check ruby-build installed] ************************************
failed: [localhost] => {"changed": true, "cmd": ["test", "-x", "/usr/local/bin/ruby-build"], "delta": "0:00:00.013386", "end": "2014-06-03 01:48:08.205916", "item": "", "rc": 1, "start": "2014-06-03 01:48:08.192530"}
...ignoring

TASK: [rbenv | if ruby-build exists, which versions we can install] ***********
skipping: [localhost]

TASK: [rbenv | create temporary directory] ************************************
changed: [localhost]

TASK: [rbenv | clone ruby-build repo] *****************************************
changed: [localhost]

TASK: [rbenv | install ruby-build] ********************************************
changed: [localhost]

TASK: [rbenv | remove temporary directory] ************************************
changed: [localhost]

TASK: [rbenv | check ruby {{edxapp_ruby_version}} installed] ******************
failed: [localhost] => {"changed": true, "cmd": "rbenv versions | grep 1.9.3-p374 ", "delta": "0:00:00.090982", "end": "2014-06-03 01:48:09.795811", "item": "", "rc": 1, "start": "2014-06-03 01:48:09.704829"}
...ignoring

TASK: [rbenv | install ruby {{edxapp_ruby_version}}] **************************
failed: [localhost] => {"changed": true, "cmd": "rbenv install 1.9.3-p374 ", "delta": "0:01:45.444968", "end": "2014-06-03 01:49:55.410207", "item": "", "rc": 1, "start": "2014-06-03 01:48:09.965239"}
stderr: Downloading yaml-0.1.6.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/7da6971b4bd08a986dd2a61353bc422362bd0edcc67d7ebaac68c95f74182749
Installing yaml-0.1.6...
Installed yaml-0.1.6 to /edx/app/edxapp/.rbenv/versions/1.9.3-p374

Downloading ruby-1.9.3-p374.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/0d0e32a3554867e3eddbb23fbf30a72c4748622e010c23e31302d899fc005574
Installing ruby-1.9.3-p374...

BUILD FAILED

Inspect or clean up the working tree at /tmp/ruby-build.20140603014810.23169
Results logged to /tmp/ruby-build.20140603014810.23169.log

Last 10 log lines:
make[2]: **\* No rule to make target `../../.ext/common/openssl', needed by`install-rb-default'.  Stop.
make[2]: **\* Waiting for unfinished jobs....
make[2]: Leaving directory `/tmp/ruby-build.20140603014810.23169/ruby-1.9.3-p374/ext/syck'
make[2]: Leaving directory`/tmp/ruby-build.20140603014810.23169/ruby-1.9.3-p374/ext/openssl'
make[1]: **\* [ext/openssl/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
linking shared-object dl/callback.so
make[2]: Leaving directory `/tmp/ruby-build.20140603014810.23169/ruby-1.9.3-p374/ext/dl/callback'
make[1]: Leaving directory`/tmp/ruby-build.20140603014810.23169/ruby-1.9.3-p374'
make: **\* [build-ext] Error 2

FATAL: all hosts have already failed -- aborting

**Comment by e0d** [comment]
Can you provide the play you are using, the error seems to be related to not having openssl available.

**Comment by ghost** [comment]
Try it again.it will work.

e0d notifications@github.com于2014年6月3日星期二写道：

**Comment by jp-io** [comment]
issue --> Task: mongo | waiting for mongo server to start
output --> timeout when waiting for localhost:27017
retry --> use: --limit @/home/user/edx_sandbox.retry

My question is: how can I run this "--limit @/home/user/edx_sandbox.retry" part to fix the installation?

**Comment by hkim823** [comment]
The "limit" is for hosts, not for the job.  You should re-run the job as it is that's causing you to hang up.
