### ISSUE TITLE
Where are MongoDB files?

### ISSUE THREAD

**Issue by lucasguerreiro** [openedx-unsupported/configuration#1161]
Hi

I'm starting to work on changing some backend files from EdX, I'm starting to work on the database now.

Where can I find those files that initialize the mongo database and where are the main files of the mongodb?

Thanks in advance!

**Comment by hkim823** [comment]
To get a better handle on how Mongo is installed, please look at the role. 

 https://github.com/edx/configuration/tree/master/playbooks/roles/mongo
