### ISSUE TITLE
how to access LMS in amazon ec2 instance?

### ISSUE THREAD

**Issue by minasami** [openedx-unsupported/configuration#1169]
i did the configuration and everything went right but when i type (my instance public ip)/80
it didn'n give me the LMS page . what should i do ?

**Comment by feanil** [comment]
Sounds like an nginx issue.  Do you see any errors in the nginx logs?
`/edx/var/log/nginx`

**Comment by hkim823** [comment]
I'm going to close this issue, please raise this again if you are still having issues.
