### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by ghost** [openedx-unsupported/configuration#1173]
```TASK: [edxapp | code sandbox | start apparmor service] ***********************\* 
failed: [localhost] => {"failed": true, "item": ""}
msg:  \* Starting AppArmor profiles
- AppArmor not available as kernel LSM.
  ...fail!

FATAL: all hosts have already failed -- aborting```

how to do? thank you

**Comment by hkim823** [comment]
What version of configuration are you using?

**Comment by ghost** [comment]
master.

**Comment by hkim823** [comment]
You should be using the release branch of configuration unless there's something specifically in master that you need.  https://github.com/edx/configuration/pull/1148 is maybe causing this issue @feanil any thoughts?

**Comment by ghost** [comment]
thank you for you help.  what is different between master and release?

**Comment by feanil** [comment]
It looks like you may have both selinux and apparmor installed and there are some issues with your configuration(http://ubuntuforums.org/showthread.php?t=1776873)  What version of ubuntu is this on?

**Comment by ghost** [comment]
What is the reason of this problem please?

**Comment by ghost** [comment]
ubuntu 12.04.4

**Comment by hkim823** [comment]
Master is the latest and greatest changes including bugs that could come from them in scenarios like this one, release is what we cut periodically and is a known entity, in general you should be building edx from the release branch of configuration.

If you are using the /edx/app/update script, it's running with the deploy tag, and the change that's listed in the script requires more than the deploy tag. 

In all if you want to use the configuration repo at master, and edx-platform at master, you need to manually run ansible without the deploy tag.  If this is a vagrant devstack, you can do this by doing a vagrant provision.

**Comment by ghost** [comment]
thank you very much.
