### ISSUE TITLE
Default Ansible Behavior May Change

### ISSUE THREAD

**Issue by rayhooker** [openedx-unsupported/configuration#1192]
I wanted to bring up an issue.  In playbooks/roles/devpi/tasks/main.yml,  it appears that the task "Create Symlink for venv supervisor" expects Ansible to use the with-items from the previous task:
- name: create a symlink for venv python, pip
  file: >
    src="{{ devpi_venv_bin }}/{{ item }}"
    dest={{ COMMON_BIN_DIR }}/{{ item }}.devpi
    state=link
  notify: restart devpi
  with_items:
  - python
  - pip
- name: create a symlink for venv supervisor
  file: >
    src="{{ devpi_supervisor_venv_bin }}/supervisorctl"
    dest={{ COMMON_BIN_DIR }}/{{ item }}.devpi
    state=link

I am experimenting with Ansible 1.6.3.  It appears that behavior has changed.  It flagged "item" as an unknown variable.   I had to copy the with_items from the previous task to get it to work.

**Comment by jarv** [comment]
Great catch! this looks like a copy-and-paste bug from the previous task.  Fixed in https://github.com/edx/configuration/pull/1193/files
