### ISSUE TITLE
Please solve this problem! --- edX Ubuntu 12.04 64 bit Installation getting errors.

### ISSUE THREAD

**Issue by anqsdwe** [openedx-unsupported/configuration#1280]
I just followed the install instructions and stuck with errors for 2 days. 

I downloaded Ubuntu 12.04 64 bit and installed on this computer and then updated as instruction said.
sudo apt-get update -y
sudo apt-get upgrade -y
sudo reboot
(I installed ubuntu desktop instead of ubuntu server because GUI is more understandable for me and it was so hard to configure wifi connection on the command line.)

and then I  did
wget https://raw.github.com/edx/configuration/master/util/install/vagrant.sh -O - | bash

It was so easy ! just one step installation! 
but if only there were not errors..
while progressing ..
 wget https://raw.github.com/edx/configuration/master/util/install/vagrant.sh -O - | bash

there were many 'ok's ,skippings, and changed. and I could find just 2 errors which colored red (one of them was ignored though.)
## first one that was ignored.

TASK: [edxapp | create checksum for requirements, package.json and Gemfile] **\* 
failed: [localhost] => {"changed": true, "cmd": "/usr/bin/md5sum /edx/app/edxapp/edx-platform/requirements/edx/pre.txt /edx/app/edxapp/edx-platform/requirements/edx/post.txt /edx/app/edxapp/edx-platform/requirements/edx/base.txt /edx/app/edxapp/edx-platform/requirements/edx/custom.txt /edx/app/edxapp/edx-platform/requirements/edx/paver.txt /edx/app/edxapp/edx-platform/requirements/edx-sandbox/post.txt /edx/app/edxapp/edx-platform/requirements/edx-sandbox/base.txt 2>/dev/null > /var/tmp/edxapp.req.new ", "delta": "0:00:00.002606", "end": "2014-07-07 16:25:45.636213", "item": "", "rc": 1, "start": "2014-07-07 16:25:45.633607"}
## lastly, second one that looks very critical.

TASK: [edxapp | install python post-post requirements] ***********************\* 
failed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/github.txt) => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i https://pypi.python.org/simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt ", "delta": "0:01:03.146343", "end": "2014-07-07 16:27:47.413264", "item": "/edx/app/edxapp/edx-platform/requirements/edx/github.txt", "rc": 1, "start": "2014-07-07 16:26:44.266921"}
stderr: error: The requested URL returned error: 403 while accessing https://github.com/appliedsec/pygeoip.git/info/refs
fatal: HTTP request failed
stdout: --use-mirrors has been deprecated and will be removed in the future. Explicit uses of --index-url and/or --extra-index-url is suggested.
Obtaining django-staticfiles from git+https://github.com/edx/django-staticfiles.git@d89aae2a82f2b#egg=django-staticfiles (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 10))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-staticfiles clone (to d89aae2a82f2b)
  Could not find a tag or branch 'd89aae2a82f2b', assuming commit.
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/src/django-staticfiles/setup.py) egg_info for package django-staticfiles

```
warning: no previously-included files matching '*.pyc' found anywhere in distribution
```

  Installing extra requirements: 'egg'
Obtaining django-pipeline from git+https://github.com/edx/django-pipeline.git@88ec8a011e481918fdc9d2682d4017c835acd8be#egg=django-pipeline (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 11))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-pipeline clone (to 88ec8a011e481918fdc9d2682d4017c835acd8be)
  Could not find a tag or branch '88ec8a011e481918fdc9d2682d4017c835acd8be', assuming commit.
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/src/django-pipeline/setup.py) egg_info for package django-pipeline

  Installing extra requirements: 'egg'
Obtaining django-wiki from git+https://github.com/edx/django-wiki.git@cd0b2b31997afccde519fe5b3365e61a9edb143f#egg=django-wiki (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 12))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-wiki clone (to cd0b2b31997afccde519fe5b3365e61a9edb143f)
  Could not find a tag or branch 'cd0b2b31997afccde519fe5b3365e61a9edb143f', assuming commit.
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/src/django-wiki/setup.py) egg_info for package django-wiki

  Installing extra requirements: 'egg'
Obtaining lettuce from git+https://github.com/gabrielfalcao/lettuce.git@cccc3978ad2df82a78b6f9648fe2e9baddd22f88#egg=lettuce (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 13))
  Updating /edx/app/edxapp/venvs/edxapp/src/lettuce clone (to cccc3978ad2df82a78b6f9648fe2e9baddd22f88)
  Could not find a tag or branch 'cccc3978ad2df82a78b6f9648fe2e9baddd22f88', assuming commit.
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/src/lettuce/setup.py) egg_info for package lettuce

  Installing extra requirements: 'egg'
Obtaining pystache-custom from git+https://github.com/dementrock/pystache_custom.git@776973740bdaad83a3b029f96e415a7d1e8bec2f#egg=pystache_custom-dev (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 14))
  Updating /edx/app/edxapp/venvs/edxapp/src/pystache-custom clone (to 776973740bdaad83a3b029f96e415a7d1e8bec2f)
  Could not find a tag or branch '776973740bdaad83a3b029f96e415a7d1e8bec2f', assuming commit.
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/src/pystache-custom/setup.py) egg_info for package pystache-custom

  Installing extra requirements: 'egg'
Obtaining zendesk from git+https://github.com/eventbrite/zendesk.git@d53fe0e81b623f084e91776bcf6369f8b7b63879#egg=zendesk (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 15))
  Updating /edx/app/edxapp/venvs/edxapp/src/zendesk clone (to d53fe0e81b623f084e91776bcf6369f8b7b63879)
  Could not find a tag or branch 'd53fe0e81b623f084e91776bcf6369f8b7b63879', assuming commit.
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/src/zendesk/setup.py) egg_info for package zendesk

  Installing extra requirements: 'egg'
Obtaining django-ipware from git+https://github.com/un33k/django-ipware.git@42cb1bb1dc680a60c6452e8bb2b843c2a0382c90#egg=django-ipware (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 16))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-ipware clone (to 42cb1bb1dc680a60c6452e8bb2b843c2a0382c90)
  Could not find a tag or branch '42cb1bb1dc680a60c6452e8bb2b843c2a0382c90', assuming commit.
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/src/django-ipware/setup.py) egg_info for package django-ipware

  Installing extra requirements: 'egg'
Obtaining pygeoip from git+https://github.com/appliedsec/pygeoip.git@95e69341cebf5a6a9fbf7c4f5439d458898bdc3b#egg=pygeoip (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 17))
  Updating /edx/app/edxapp/venvs/edxapp/src/pygeoip clone (to 95e69341cebf5a6a9fbf7c4f5439d458898bdc3b)
  Complete output from command /usr/bin/git fetch -q:

---

Cleaning up...
Command /usr/bin/git fetch -q failed with error code 128 in /edx/app/edxapp/venvs/edxapp/src/pygeoip
Storing debug log for failure in /edx/app/edxapp/.pip/pip.log
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/local.txt)

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=156  changed=26   unreachable=0    failed=1  

---

could anyone please find out what is problem??
after I stuck with this errors, I did 'manual installation' but got same errors.

Thanks for any help, It would be so appreciated.

**Comment by hkim823** [comment]
This points to a problem with your network getting to PyPi / Github to download certain requirements.  Please check your firewall / network settings on your network to make sure you have full access to things online.  

An easier way to stand up edX is maybe to look at the Virtualbox images that can be called via Vagrant.  

https://github.com/edx/configuration/wiki/edx-Production-stack--installation-using-Vagrant-Virtualbox

**Comment by anqsdwe** [comment]
Thanks! Kim! I turned firewall off using command 'sudo ufw dlsable'
but, same errors happens  ...
and I figured out that wifi is disconnected and connected repeatedly while progressing installation!

Thank you so much!
