### ISSUE TITLE
error rbenv

### ISSUE THREAD

**Issue by johnfelipe** [openedx-unsupported/configuration#1287]
![errorinstallation](https://cloud.githubusercontent.com/assets/428820/3503186/90471e2e-062c-11e4-9860-d940560ba017.png)

Is normal?

**Comment by johnfelipe** [comment]
nothing happend, installation success

**Comment by e0d** [comment]
Yes this is normal, the task in question is specified to ignore errors and registers a var if ruby is already installed.  We'll likely be moving away from this pattern as it can cause confusion.
