### ISSUE TITLE
COMMON_SSH_PASSWORD_AUTH to "Yes" and dont work with putty or winscp

### ISSUE THREAD

**Issue by johnfelipe** [openedx-unsupported/configuration#1288]
Hi, please tell me how to do for ssh input with putty or winscp, i ready change COMMON_SSH_PASSWORD_AUTH to "Yes" and dont workm tnks

![ssherror](https://cloud.githubusercontent.com/assets/428820/3509847/3f23b646-06a0-11e4-8707-2fddc81c615f.png)

**Comment by e0d** [comment]
Can you confirm that `/etc/ssh/sshd_config` contain the correct value for PasswordAuthentication.

In the interest of full disclosure, we don't use this feature and recommend you don't either ;).  You may or may not be aware, but our plays will setup key based ssh for you using the keys you have uploaded to github.  All you need is:

```
COMMON_USER_INFO:
  - name: johnfelipe
    github: true
    type: admin
```

In your vars file.

**Comment by johnfelipe** [comment]
/etc/ssh/sshd_config put

COMMON_USER_INFO:
- name: johnfelipe
  github: true
  type: admin

or tell me how enter with winscp and/or putty

**Comment by johnfelipe** [comment]
please give me dummy instruction for enter with winscp and/or putty, tnks a lot

**Comment by hkim823** [comment]
At this point you may have already locked yourself out of the server, with no way back in.  We don't use SSH password based authentication so it's hard to test any changes, even if your config does say yes.  You may have to just tear down the VM / server and try again.  

/etc/ssh/sshd_config is not where you put in COMMON_USER_INFO, rather it's one of the variables you can pass during ansible.

**Comment by johnfelipe** [comment]
In this moment @hkim823 , how enter with winscp and putty?

**Comment by johnfelipe** [comment]
Hi again, please give me some instruction for enter with putty and/or winscp
