### ISSUE TITLE
how enter with putty and/or winscp

### ISSUE THREAD

**Issue by johnfelipe** [openedx-unsupported/configuration#1309]
https://github.com/edx/configuration/issues/1288#issuecomment-48348491, please tell me how enter with putty?, tnks

**Comment by feanil** [comment]
@johnfelipe if you do not already have a user with SSH access using your public key to authenticate, you won't be able to get back onto that server and will have to build a new one,  is this an EC2 machine?  If so, you'll need to ssh using the user 'ubuntu' and the public key associted with that user when you brought up the machine.

**Comment by johnfelipe** [comment]
where is that public key?

**Comment by feanil** [comment]
I don't know but you can see a fingerprint for the public key in the keypairs section of the aws ec2 console.  If you look at the instance in the aws console, you'll see it has an associated keypair that is the ssh key you need to log on to the box with.

**Comment by feanil** [comment]
More info here: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html

**Comment by johnfelipe** [comment]
but my appliance is in vmware in ubuntu no EC2, in this moment i have other functionally instance but older how enter with putty?

**Comment by feanil** [comment]
For VMWare instances you will probably have to re-build them, It is good to setup the instance with a user that uses ssh-keys for access before running the ansible plays that way you can ssh into the box using the private key associated with the user.  Here's some instructions for how to use SSH Keys with Putty.

**Comment by johnfelipe** [comment]
where is path for ssh-keys?

**Comment by hkim823** [comment]
You will have to destroy and rebuild this server.  You are locked out at this point if you didn't pre create a key pair to use to log into the server since it's not set to only log in using ssh key pairs.

**Comment by johnfelipe** [comment]
Tnks i will create one, tnks a lot
