### ISSUE TITLE
Unable to find a suitable fs

### ISSUE THREAD

**Issue by waqasraz** [openedx-unsupported/configuration#1312]
TASK: [edxapp | code sandbox | (bootstrap) load code sandbox profile] ********\* 
failed: [localhost] => {"changed": true, "cmd": ["apparmor_parser", "-r", "/etc/apparmor.d/code.sandbox"], "delta": "0:00:00.044226", "end": "2014-07-12 14:55:13.517294", "item": "", "rc": 1, "start": "2014-07-12 14:55:13.473068"}
stderr: Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=139  changed=16   unreachable=0    failed=1

**Comment by feanil** [comment]
Hello, what OS are you running this on?  Is it ubuntu 12.04 LTS?

**Comment by waqasraz** [comment]
yes it is. I think some one mentioned that this error is because of Openvz and apparmor incompatibility.

**Comment by hkim823** [comment]
That's correct, OpenVZ and AppArmor do not mix.

**Comment by waqasraz** [comment]
I bought another vm that is not openvz. I am still getting the same error. If i go 

$: apparmor_parser

I'll get this

$: Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.

The kernel is 

3.8.13-xxxx-grs-ipv6-64-vps
