### ISSUE TITLE
TASK: [edxapp | install python base-requirements] how to solve this problem?

### ISSUE THREAD

**Issue by ThePanguan** [openedx-unsupported/configuration#1316]
TASK: [edxapp | install python base-requirements] ****************************\* 
failed: [localhost] => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i https://pypi.python.org/simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt ", "delta": "0:07:13.471059", "end": "2014-07-14 12:45:58.423001", "item": "", "rc": 2, "start": "2014-07-14 12:38:44.951942"}
stdout: --use-mirrors has been deprecated and will be removed in the future. Explicit uses of --index-url and/or --extra-index-url is suggested.
Downloading/unpacking git+https://github.com/mfogel/django-settings-context-processor.git (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 131))
  Cloning https://github.com/mfogel/django-settings-context-processor.git to /tmp/pip-vrGaGI-build
  Running setup.py (path:/tmp/pip-vrGaGI-build/setup.py) egg_info for package from git+https://github.com/mfogel/django-settings-context-processor.git

Downloading/unpacking git+https://github.com/mitocw/django-cas.git (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 134))
  Cloning https://github.com/mitocw/django-cas.git to /tmp/pip-omHTQo-build
  Running setup.py (path:/tmp/pip-omHTQo-build/setup.py) egg_info for package from git+https://github.com/mitocw/django-cas.git

Downloading/unpacking beautifulsoup4==4.1.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 7))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/beautifulsoup4/setup.py) egg_info for package beautifulsoup4

Downloading/unpacking beautifulsoup==3.2.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 8))
  Downloading BeautifulSoup-3.2.1.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/beautifulsoup/setup.py) egg_info for package beautifulsoup

Downloading/unpacking bleach==1.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 9))
  Downloading bleach-1.4.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/bleach/setup.py) egg_info for package bleach

Downloading/unpacking html5lib==0.999 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 10))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/html5lib/setup.py) egg_info for package html5lib

Downloading/unpacking boto==2.13.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 11))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/boto/setup.py) egg_info for package boto

```
warning: no files found matching 'boto/mturk/test/*.doctest'
warning: no files found matching 'boto/mturk/test/.gitignore'
```

Downloading/unpacking celery==3.0.19 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 12))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/celery/setup.py) egg_info for package celery
    Upgrade: no old version found.

```
no previously-included directories found matching '*.pyc'
```

Downloading/unpacking dealer==0.2.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 13))
  Downloading dealer-0.2.3.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/dealer/setup.py) egg_info for package dealer

```
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.orig' found under directory '*'
```

Downloading/unpacking distribute>=0.6.28,<0.7 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 14))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/distribute/setup.py) egg_info for package distribute

Downloading/unpacking django-babel-underscore==0.1.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 15))
  Downloading django_babel_underscore-0.1.0-py2.py3-none-any.whl
Downloading/unpacking django-celery==3.0.17 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 16))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-celery/setup.py) egg_info for package django-celery

```
no previously-included directories found matching 'bin/*.pyc'
no previously-included directories found matching 'tests/*.pyc'
no previously-included directories found matching 'docs/*.pyc'
no previously-included directories found matching 'extra/*.pyc'
no previously-included directories found matching 'djcelery/*.pyc'
no previously-included directories found matching 'docs/.build'
no previously-included directories found matching 'examples/*.pyc'
```

Downloading/unpacking django-countries==1.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 17))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-countries/setup.py) egg_info for package django-countries

Downloading/unpacking django-extensions==1.2.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 18))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-extensions/setup.py) egg_info for package django-extensions

Downloading/unpacking django-filter==0.6.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 19))
  Downloading django_filter-0.6-py2.py3-none-any.whl
Downloading/unpacking django-followit==0.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 20))
  Downloading django-followit-0.0.3.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-followit/setup.py) egg_info for package django-followit

```
warning: no files found matching 'tox.ini'
warning: no previously-included files matching '*.pyc' found under directory 'followit'
warning: manifest_maker: MANIFEST.in, line 5: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...

no previously-included directories found matching 'dist'
no previously-included directories found matching 'build'
warning: manifest_maker: MANIFEST.in, line 8: unknown action 'global'

warning: no previously-included files found matching 'settings.py'
warning: no previously-included files found matching 'manage.py'
warning: no previously-included files found matching '__init__.py'
warning: no previously-included files found matching 'urls.py'
warning: manifest_maker: MANIFEST.in, line 13: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...

warning: manifest_maker: MANIFEST.in, line 14: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...
```

Downloading/unpacking django-keyedcache==1.4-6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 21))
  Downloading django-keyedcache-1.4-6.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-keyedcache/setup.py) egg_info for package django-keyedcache

```
warning: no files found matching '*' under directory 'keyedcache/templatetags'
```

Downloading/unpacking django-kombu==0.9.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 22))
  Downloading django-kombu-0.9.4.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-kombu/setup.py) egg_info for package django-kombu

Downloading/unpacking django-mako==0.1.5pre (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 23))
  Downloading django-mako-0.1.5pre.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-mako/setup.py) egg_info for package django-mako

Downloading/unpacking django-model-utils==1.4.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 24))
  Downloading django-model-utils-1.4.0.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-model-utils/setup.py) egg_info for package django-model-utils

Downloading/unpacking django-masquerade==0.1.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 25))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-masquerade/setup.py) egg_info for package django-masquerade

Downloading/unpacking django-mptt==0.5.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 26))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-mptt/setup.py) egg_info for package django-mptt

```
warning: no files found matching '*.json' under directory 'mptt'
```

Downloading/unpacking django-openid-auth==0.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 27))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-openid-auth/setup.py) egg_info for package django-openid-auth

Downloading/unpacking django-robots==0.9.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 28))
  Downloading django-robots-0.9.1.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-robots/setup.py) egg_info for package django-robots

Downloading/unpacking django-sekizai==0.6.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 29))
  Downloading django-sekizai-0.6.1.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-sekizai/setup.py) egg_info for package django-sekizai

Downloading/unpacking django-ses==0.4.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 30))
  Downloading django-ses-0.4.1.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-ses/setup.py) egg_info for package django-ses

Downloading/unpacking django-storages==1.1.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 31))
  Downloading django-storages-1.1.5.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-storages/setup.py) egg_info for package django-storages

Downloading/unpacking django-threaded-multihost==1.4-1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 32))
  Downloading django-threaded-multihost-1.4-1.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-threaded-multihost/setup.py) egg_info for package django-threaded-multihost
    zip_safe flag not set; analyzing archive contents...

```
Installed /edx/app/edxapp/venvs/edxapp/build/django-threaded-multihost/setuptools_hg-0.4-py2.7.egg
```

Downloading/unpacking django-method-override==0.1.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 33))
  Downloading django-method-override-0.1.0.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django-method-override/setup.py) egg_info for package django-method-override

Downloading/unpacking djangorestframework==2.3.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 34))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/djangorestframework/setup.py) egg_info for package djangorestframework

Downloading/unpacking django==1.4.12 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 35))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/django/setup.py) egg_info for package django

Downloading/unpacking feedparser==5.1.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 36))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/feedparser/setup.py) egg_info for package feedparser

Downloading/unpacking firebase-token-generator==1.3.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 37))
  Downloading firebase-token-generator-1.3.2.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/firebase-token-generator/setup.py) egg_info for package firebase-token-generator

Downloading/unpacking fs==0.4.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 38))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/fs/setup.py) egg_info for package fs

Downloading/unpacking GitPython==0.3.2.RC1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 39))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/GitPython/setup.py) egg_info for package GitPython

```
warning: no files found matching 'README'
```

Downloading/unpacking glob2==0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 40))
  Downloading glob2-0.3.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/glob2/setup.py) egg_info for package glob2

Downloading/unpacking gunicorn==0.17.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 41))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/gunicorn/setup.py) egg_info for package gunicorn

Downloading/unpacking lazy==1.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 42))
  Downloading lazy-1.1.zip
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/lazy/setup.py) egg_info for package lazy

Downloading/unpacking lxml==3.0.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 43))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/lxml/setup.py) egg_info for package lxml
    Building lxml version 3.0.1.
    Building without Cython.
    Using build configuration of libxslt 1.1.26
    Building against libxml2/libxslt in the following directory: /usr/lib/x86_64-linux-gnu

```
warning: no previously-included files found matching '*.py'
warning: no files found matching '*.txt' under directory 'src/lxml/tests'
```

Downloading/unpacking mako==0.9.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 44))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/mako/setup.py) egg_info for package mako

```
warning: no files found matching '*.xml' under directory 'examples'
warning: no files found matching '*.mako' under directory 'examples'
warning: no files found matching 'ez_setup.py'
no previously-included directories found matching 'doc/build/output'
```

Downloading/unpacking Markdown==2.2.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 45))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/Markdown/setup.py) egg_info for package Markdown

Downloading/unpacking mongoengine==0.7.10 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 46))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/mongoengine/setup.py) egg_info for package mongoengine
    0.7.10

```
no previously-included directories found matching 'docs/_build'
```

Downloading/unpacking networkx==1.7 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 47))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/networkx/setup.py) egg_info for package networkx

```
warning: no files found matching 'scripts/*'
warning: no files found matching 'networkx/tests/*.txt'
warning: no files found matching 'networkx/*/*/tests/*.txt'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc/build'
no previously-included directories found matching 'doc/source/reference/generated'
no previously-included directories found matching 'doc/source/examples'
no previously-included directories found matching 'doc/source/static/examples'
no previously-included directories found matching 'doc/source/templates/gallery.html'
```

Downloading/unpacking nltk==2.0.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 48))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/nltk/setup.py) egg_info for package nltk
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpjaeQVL
    Now working in /tmp/tmpjaeQVL/distribute-0.6.21
    Building a Distribute egg in /edx/app/edxapp/venvs/edxapp/build/nltk
    /edx/app/edxapp/venvs/edxapp/build/nltk/distribute-0.6.21-py2.7.egg

```
warning: no previously-included files matching '*~' found anywhere in distribution
```

Downloading/unpacking nose==1.3.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 49))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/nose/setup.py) egg_info for package nose

```
no previously-included directories found matching 'doc/.build'
```

Downloading/unpacking oauthlib==0.6.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 50))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/oauthlib/setup.py) egg_info for package oauthlib

Downloading/unpacking paramiko==1.9.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 51))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/paramiko/setup.py) egg_info for package paramiko

Downloading/unpacking path.py==3.0.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 52))
  Downloading path.py-3.0.1.zip
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/path.py/setup.py) egg_info for package path.py

Downloading/unpacking Pillow==1.7.8 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 53))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/Pillow/setup.py) egg_info for package Pillow

```
warning: no previously-included files found matching '.hgignore'
warning: no previously-included files found matching '.hgtags'
warning: no previously-included files found matching 'BUILDME.bat'
warning: no previously-included files found matching 'make-manifest.py'
warning: no previously-included files found matching 'SHIP'
warning: no previously-included files found matching 'SHIP.bat'
warning: no previously-included files matching '*' found under directory 'Tests'
```

Requirement already satisfied (use --upgrade to upgrade): pip>=1.4 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 54))
Downloading/unpacking polib==1.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 55))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/polib/setup.py) egg_info for package polib

Downloading/unpacking pycrypto>=2.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 56))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/pycrypto/setup.py) egg_info for package pycrypto

Downloading/unpacking pygments==1.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 57))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/pygments/setup.py) egg_info for package pygments

Downloading/unpacking pygraphviz==1.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 58))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/pygraphviz/setup.py) egg_info for package pygraphviz
    Trying pkg-config
    library_path=
    include_path=/usr/include/graphviz

```
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc/build'
```

Downloading/unpacking pymongo==2.4.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 59))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/pymongo/setup.py) egg_info for package pymongo

Downloading/unpacking pyparsing==2.0.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 60))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/pyparsing/setup.py) egg_info for package pyparsing

Downloading/unpacking python-memcached==1.48 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 61))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/python-memcached/setup.py) egg_info for package python-memcached

Downloading/unpacking python-openid==2.2.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 62))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/python-openid/setup.py) egg_info for package python-openid

```
warning: no files found matching 'CHANGELOG'
warning: no files found matching '*.css' under directory 'doc'
warning: no files found matching '*.html' under directory 'doc'
```

Downloading/unpacking python-dateutil==2.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 63))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/python-dateutil/setup.py) egg_info for package python-dateutil

Downloading/unpacking python-social-auth==0.1.23 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 64))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/python-social-auth/setup.py) egg_info for package python-social-auth

Downloading/unpacking pytz==2012h (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 65))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/pytz/setup.py) egg_info for package pytz

```
warning: no files found matching '*.pot' under directory 'pytz'
warning: no previously-included files found matching 'test_zdump.py'
```

Downloading/unpacking pysrt==0.4.7 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 66))
  Downloading pysrt-0.4.7.tar.gz
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/pysrt/setup.py) egg_info for package pysrt

Downloading/unpacking PyYAML==3.10 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 67))
  Running setup.py (path:/edx/app/edxapp/venvs/edxapp/build/PyYAML/setup.py) egg_info for package PyYAML

Downloading/unpacking requests==2.3.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 68))
Downloading/unpacking requests-oauthlib==0.4.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 69))
  Downloading requests_oauthlib-0.4.1-py2.py3-none-any.whl
Downloading/unpacking scipy==0.11.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 70))
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/download.py", line 572, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/download.py", line 433, in _download_url
    for chunk in resp_read(4096):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/download.py", line 421, in resp_read
    chunk_size, decode_content=False):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 240, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 187, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 561, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 241, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 160, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out

Storing debug log for failure in /edx/app/edxapp/.pip/pip.log

FATAL: all hosts have already failed -- aborting

**Comment by hkim823** [comment]
This is a network error, make sure that you have a stable internet connection that's not blocked by firewalls or proxies.
