### ISSUE TITLE
Cloudformation Error

### ISSUE THREAD

**Issue by juliedavila** [openedx-unsupported/configuration#1317]
It seems there is an issue with the some security groups randomly, I am getting a 'security group sg-xxxx' does not exist as an event when launching the edx-reference-architecture.json template. And the security group it fails so far changes every time, it is not consistent.

**Comment by feanil** [comment]
You may be running into the limits of your AWS account. The reference architecture is fairly large as it has all of the pieces that we use here at edx.  However depending on what you're use case looks like, it may be overkill to use it.  Below are the general limit we ask for from AWS support if we want to build from cloudformation:

EC2 Instances: 100
EIPs: 50
AutoScalingGroups: 50
LaunchConfigurations: 200
LoadBalancers: 100

**Comment by juliedavila** [comment]
For a particular org, they are wanting that full beast. I'll ensure those limits and report back success/failure

**Comment by juliedavila** [comment]
That was it. thanks.
