### ISSUE TITLE
What to do after Reference Architecture CloudFormation completes? Not clear.

### ISSUE THREAD

**Issue by juliedavila** [openedx-unsupported/configuration#1335]
I was able to get the reference architecture of `edx-reference-architecture.json` up and running just fine (we do have a requirement for that massive setup). 

However, it's not clear proceed from there or how to leverage the provided ansible-playbooks to go ahead and configure all of the servers. I've looked at the playbooks and the only one that looks relevant is the vagrant-fullstack play, but I'm pretty sure that's not what I need.

Apologies in advance if I missed something completely obvious, thanks.

**Comment by feanil** [comment]
If you look here(https://github.com/edx/configuration/tree/master/playbooks/edx-east) you'll see a lot more plays.  There is one for each cluster that is brought up in VPC.  You can run them against that cluster by using the limit tag of the ansible-playbook.

**Comment by juliedavila** [comment]
Got it. Thank you!
