### ISSUE TITLE
install production stack on a single Ubuntu12.04

### ISSUE THREAD

**Issue by ichz** [openedx-unsupported/configuration#1343]
According edX Ubuntu 12.04 64 bit Installation to install the final step:

```
cd /var/tmp/configuration/playbooks/edx-east

sudo ansible-playbook -c local --limit "localhost:127.0.0.1" ../edx_sandbox.yml \
-i "localhost," -e 'EDXAPP_PREVIEW_LMS_BASE=preview.example.com  EDXAPP_LMS_BASE=example.com  EDXAPP_LMS_PREVIEW_NGINX_PORT=80 EDXAPP_CMS_NGINX_PORT=80 EDXAPP_LMS_NGINX_PORT=80 edx_platform_version=master '
```

I should replace  example.com with abc.com (eg abc.com)? 
It should be:

```
sudo ansible-playbook -c local --limit "localhost:127.0.0.1" ../edx_sandbox.yml \
-i "localhost,abc.com" -e 'EDXAPP_PREVIEW_LMS_BASE=preview.abc.com  EDXAPP_LMS_BASE=abc.com  EDXAPP_LMS_PREVIEW_NGINX_PORT=80 EDXAPP_CMS_NGINX_PORT=80 EDXAPP_LMS_NGINX_PORT=80 edx_platform_version=master '
```

Is right?
Thank you!

**Comment by hkim823** [comment]
to take the standard settings you shouldn't need to do a -e at all, only if you are overriding the default settings to something other than the defaults.

**Comment by ichz** [comment]
Thank you! 
Do you mean to delete the "-e" only and leave the rest unchanged?

and
before run following coding

```
cd /var/tmp/configuration/playbooks/edx-east

sudo ansible-playbook -c local --limit "localhost:127.0.0.1" ../edx_sandbox.yml \
-i "localhost," -e 'EDXAPP_PREVIEW_LMS_BASE=preview.example.com  EDXAPP_LMS_BASE=example.com  EDXAPP_LMS_PREVIEW_NGINX_PORT=80 EDXAPP_CMS_NGINX_PORT=80 EDXAPP_LMS_NGINX_PORT=80 edx_platform_version=master '
```

should i set up /var/tmp/configuration/playbooks/roles/edxapp/defaults/main.yml ? 
for example(e.g:abc.com) : EDXAPP_LMS_BASE = 'abc.com' ?

**Comment by hkim823** [comment]
You can override the defaults in main.yml using a -e to supply addition variables.  

Please note that the line

```
cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
```

Is by default all you should need to do to install edx on that box.
