### ISSUE TITLE
Looking for Dependencies, Requirements, Packages, etc.

### ISSUE THREAD

**Issue by jbkc85** [openedx-unsupported/configuration#1354]
Is there any documentation on exactly what is needed to run edX?  I understand its all in this ansible file, but having a clear cut doc on 'you need this this and this' would be nice.  I could very well be missing it, so please if I am point me in the right direction!

**Comment by hkim823** [comment]
I think looking at https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation will give you an idea what's required to install a single instance sandbox of edX.  For edx-platform in particular, look inside the requirements directory and see what's being called there.
