### ISSUE TITLE
use global python packages when possible

### ISSUE THREAD

**Issue by trungpham** [openedx-unsupported/configuration#1367]
add virtualenv_site_packages=yes to the pip module.

This will speed up subsequent roles setup since it won't waste hours trying to download and recompile the C extensions.

See: http://docs.ansible.com/pip_module.html

FYI, the ORA role takes close to half an hour to recompile the C extensions each time I redeploy it... Quite unnecessary if it can reuse the global packages.

**Comment by feanil** [comment]
@trungpham It is true that using pre compiled versions of packages will speed things up here, those versions often tend to be out of date and make it difficult to run multiple applications when their requirements differ.  The plan is to eventually move to [wheel files](http://wheel.readthedocs.org/en/latest/) but there is currently other work that is taking priority.

**Comment by trungpham** [comment]
If pip cannot find the matching version in the global packages, then won't it download and compile the matching version into the local virtualenv?

In theory, we should be okay as long as the requirements.txt explicitly sets the version number of the python packages.

**Comment by feanil** [comment]
Unfortunately I don't think this is true for all packages right now.

**Comment by feanil** [comment]
Have you been able to run tests to see how much of a time difference this is if we do use system packages?

**Comment by trungpham** [comment]
yes, 5 seconds vs. 20 mins.

**Comment by trungpham** [comment]
downloading a native python package does not consume too much time. it's only bad when pip has to compile the C extension.

Anyway, all of edx-platform requirements seem to explicitly sets the version number. but some of the ora requirements don't have the version number set. Can we ask the devs to set the version number? It's good practice to set the version number...

**Comment by feanil** [comment]
Can you put in a PR with the change?

**Comment by trungpham** [comment]
okay.

**Comment by trungpham** [comment]
https://github.com/edx/configuration/pull/1369
