### ISSUE TITLE
Error Building with the AWS Console

### ISSUE THREAD

**Issue by ngocchung75** [openedx-unsupported/configuration#137]
I choice Upload a Template File and add file edx-reference-architecture.json and click button continue error occurred:

ValidateTemplate failed: Template error: resource RabbitMQScaleUpPolicy has missing or circular dependencies: RabbitMQServerASGroup.

Please help me. Thank you

**Comment by feanil** [comment]
Hi, This was fixed by pull request https://github.com/edx/configuration/pull/142
