### ISSUE TITLE
updating basic nginx auth not working

### ISSUE THREAD

**Issue by UXE** [openedx-unsupported/configuration#1372]
I added those vars to server-vars.yml and did `sudo /edx/bin/update edx-platform master` with no effect.
still getting the old `edx` `edx` auth which is the default aws installation conf.

```
# Set global htpasswd credentials
COMMON_ENABLE_BASIC_AUTH: True
COMMON_HTPASSWD_USER: "user*****"
COMMON_HTPASSWD_PASS: "p@ss*****"
```

even when trying to disable it by `COMMON_ENABLE_BASIC_AUTH: False`, it will still ask for auth.

**Comment by jarv** [comment]
@UXE can you take a look at the contents of `/edx/app/nginx/nginx.htpasswd` as well as your lms nginx configuration in `/edx/app/nginx/sites-enabled/lms` to see if it has the new credentials you set or whether the lms nginx configuration is configured for basic auth after the ansible run? If not you may want to try restarting nginx with a `sudo service nginx restart`

**Comment by UXE** [comment]
I checked this file before changing those conf, and after .... it is the
same in every case: edx as user and a hashed password,  even when disabling
the feature at all.

and I don't think resarting edx is necessary as I run edx update script
after each edite on server-vars.

Thanks
Ahmad

**Comment by hkim823** [comment]
I wonder if they're not getting overwritten if they already exists.  Try to remove it manually and see if it works after running the update script again.

**Comment by UXE** [comment]
@hkim823 I tried, didn't work.

**Comment by hkim823** [comment]
If you manually edit /edx/app/nginx/nginx.htpasswd does it change?  Does it get overwritten if you run the update script?

**Comment by ahmadio** [comment]
No it doesnot

**Comment by ahmadio** [comment]
Sorry I got confused, actually it does reflect manual changes, and I only managed to change the user name successfully as I don't know the encryption needed for the password

**Comment by hkim823** [comment]
if you put it in as plain text when nginx is restarted, it should rehash the password in the file

**Comment by ahmadio** [comment]
I will check

**Comment by hkim823** [comment]
I've had some time to look into this a bit deeper.  `sudo /edx/bin/update edx-platform master` does not actually call the nginx role which is the role that sets COMMON_HTPASSWD_USER and COMMON_HTPASSWD_PASS thus why it doesn't matter if you edit server-vars.yml since that var is never used in the play.  

I think that you may have to manually run the nginx role itself using the run_role.yml play.  If you want to put in a PR with the logic to change this behavior so that the edxapp play will also run the nginx role (or the part to just reset passwords) please do so.

**Comment by ndubbaka** [comment]
These steps worked for me in turning off basic auth.
sudo vi /edx/app/nginx/sites-enabled/lms 
{code}
location / {
         satisfy any;

```
 allow 127.0.0.1;
 allow all;

 auth_basic off;

 index index.html
 proxy_set_header X-Forwarded-Proto https;
try_files $uri @proxy_to_lms_app;
```

  }
{code}
sudo service nginx restart
