### ISSUE TITLE
Error while installing: "No Rakefile found"

### ISSUE THREAD

**Issue by ghost** [openedx-unsupported/configuration#1373]
I'm getting the following error when I run `sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"`. I'm trying to install edX on Ubuntu 12.04.

```
TASK: [edxapp | gather  static assets with rake] ******************************
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:00.099276", "end": "2014-08-07 07:19:47.397273", "item": "lms", "rc": 1, "start": "2014-08-07 07:19:47.297997"}
stderr: rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)
failed: [localhost] => (item=cms) => {"changed": true, "cmd": "SERVICE_VARIANT=cms rake cms:gather_assets:aws ", "delta": "0:00:00.078862", "end": "2014-08-07 07:19:47.631337", "item": "cms", "rc": 1, "start": "2014-08-07 07:19:47.552475"}
stderr: rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
```

**Comment by jarv** [comment]
@grokavi  unfortunately an update was made on edx-platform that is no longer compatible with the configuration release branch. To work around it you can switch to the master branch of configuration. I assume you are following the ubuntu 12.04 instructions, if so you do a `git checkout master` before running ansible.

**Comment by ghost** [comment]
I realised a little while ago that `paver` is being used instead of `rake`. Thanks for pointing out the correct branch.
