### ISSUE TITLE
make rabbitmq vhost configurable

### ISSUE THREAD

**Issue by trungpham** [openedx-unsupported/configuration#1380]
The underlaying xqueue, ora, and celery code allow configuring the RabbitMQ vhost. However, there's no way to pass in the vhost setting when ansible builds the *.env.json files. Therefore, the vhost will be defaulted to '/' within xqueue, ora, and celery.

**Comment by hkim823** [comment]
Can you explain more the usage of why you want to set this?

**Comment by trungpham** [comment]
I want to be able to reuse my existing rabbitmq cluster that is serving another app, rather than setting up a brand new rabbitmq cluster for edx. Rabbitmq has a concept of virtualhost that can cleanly keep the data under different namespaces.

**Comment by trungpham** [comment]
@feanil lol. I have the code in my repo. I will submit a pull request soon.
