### ISSUE TITLE
while trying to install script for openedx, getting following error

### ISSUE THREAD

**Issue by catftp** [openedx-unsupported/configuration#1381]
TASK: [mongo | install mongo server and recommends] ***************************
failed: [localhost] => {"failed": true, "item": ""}
stderr: E: There are problems and -y was used without --force-yes

stdout: Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be DOWNGRADED:
  mongodb-10gen
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 3 not upgraded.
Need to get 0 B/87.9 MB of archives.
After this operation, 420 kB disk space will be freed.

msg: 'apt-get install 'mongodb-10gen=2.4.7' ' failed: E: There are problems and -y was used without --force-yes

FATAL: all hosts have already failed -- aborting

**Comment by hkim823** [comment]
Looking at https://github.com/edx/configuration/blob/master/playbooks/roles/mongo/tasks/main.yml looks like we need to add force=yes

Can you put in a PR for this?

**Comment by catftp** [comment]
still having same error.

On Fri, Aug 8, 2014 at 7:05 PM, Han Su Kim notifications@github.com wrote:

> Looking at
> https://github.com/edx/configuration/blob/master/playbooks/roles/mongo/tasks/main.yml
> looks like we need to add force=yes
> 
> Can you put in a PR for this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/edx/configuration/issues/1381#issuecomment-51606267.

## 

Thanks & Regards

Muhammad Ahsan

**Comment by hkim823** [comment]
Here's the PR that should fix the issue https://github.com/edx/configuration/pull/1399
