### ISSUE TITLE
Upgrade ansible version to 1.7

### ISSUE THREAD

**Issue by rohitkode** [openedx-unsupported/configuration#1382]
I used the ansible version specified in the requirements file and hit this bug:
https://github.com/ansible/ansible/issues/7413

Basically, the module apt_repository fails behind a proxy. I tried applying the patch to 1.5.5 but that did not fix the problem. 
However, after upgrading to 1.7, the playbook (common.yml in this case) and the task add-apt-repository succeeded.

The ansible version needs to be bumped up to the latest stable version (1.7) in the requirements.txt

**Comment by hkim823** [comment]
We cannot upgrade at this time above Ansible 1.5.x due to $ vars that are inside may plays.  All of those vars need to be refactored and then tested with newer versions of Ansible before we can move forward.
