### ISSUE TITLE
Problem With Server Certificate "arn:aws:iam::372153017832:server-certificate/dummy"

### ISSUE THREAD

**Issue by elimence** [openedx-unsupported/configuration#143]
Cloud formation stack creation breaks with the following error

```
Server Certificate not found for the key: arn:aws:iam::372153017832:server- certificate/dummy
```

Other services report the following status

```
Deletion complete
```

While others seem to be permanently stuck on the following Creating

I tried to setup the stack after the merged with Feanil Patel's code.

**Comment by feanil** [comment]
When you're provisioning the cloudformation stack, you are presented with a bunch of properties to update.  One of them is an ssl certificate that can be used by your stack's load balancers.  The reason this is failing is because the default is pointing to one in our AWS account so you cannot reach it.  You need to upload an SSL certificate to AWS and then provide its AWS URI as a property.

**Comment by maximfilippov** [comment]
Hello Feanil, we're trying to set up an instance of edx, and we're having the same problem. Could you please explain what kind of ssl certificate we need to upload? thanks a bunch!

**Comment by feanil** [comment]
Hello, you need an ssl certificate to validate the domain you are going to be using this with.  Take a look at the instructions here to see how to generate SSL certificates.

https://devcenter.heroku.com/articles/ssl-certificate-self

**Comment by maximfilippov** [comment]
Thanks so much feanil! 
I managed to pretty much figure that part out I think. Are there any other properties that need to be modified from the template that we upload in cloud formation? We're following the instructions to the letter, are there any other traps you could think of?

Thanks a million!

Max Filippov

**Comment by feanil** [comment]
The ec2 key pair also needs to be updated to one that exists in your was
environment.

**Comment by maximfilippov** [comment]
Feanil I'm sorry to bother you again, but we are running into another slight problem. I have created a self signed certificate but I did not put a specific hostname. Now i'm getting in trouble for it! the stack has formed correctly (although some stuff is still pending it seems), but when we're running the 3 manual commands we are shown a java error saying that hostname on certificate doesn't match. Any suggestions on what we could use as an appropriate hostname?

Kind Regards,

Maxim

**Comment by feanil** [comment]
Hi Maxim,

It sounds like you are seeing an error while using the ec2 cli tools.  I
haven't run into that issue and am not sure what would be causing it,
perhaps ask on the AWS forums as they might have a better idea over there.
I'm not sure why using those commands would cause certificate issues unless
your java keystore is not setup correctly.

-Feanil

**Comment by maximfilippov** [comment]
Hello Feanil, I'm coming back to bother you again (really sorry!).

Now we have all the stuff configured, how/where do we actually load all the platform code to AWS ?

Thanks so much,

Max

**Comment by feanil** [comment]
Take a look on the wiki:
https://github.com/edx/configuration/wiki/AWS-Installation

There is a section on provisioning the stack.

**Comment by maximfilippov** [comment]
We've done all the steps, but when we used ansible to run the cloud formation playbook we just end up with 2 extra ec2 instances (on top of the 12 ec2 instances we ended up with when doing cloud formation configuration through the aws web console). When we ssh into these 2 new instances we don't see anything to run. Maybe I'm just not understanding how this thing works! Because we've done all the steps and they seem to all have worked fine!

**Comment by feanil** [comment]
Seems like you're having trouble undrestanding what ansible does.  Look at
the comments inside 'cloudformation.yml' to see what that playbook does.
To provision the stack you probably want to use a different playbook.  Take
a look at 'feanil_deploy.yml' under edx-east as an example.

**Comment by rirathod** [comment]
Hi feanil,

I have a uploaded a self-signed server certificate to my aws account. However, when I specify the ARN of this cert in cloud formation template, I get following error:

"Server Certificate not found for the key: arn:aws:iam::************:server-certificate/cert-name"

I used this certificate when creating an ELB via console. However, when I use the same certificate to create another elb using cloudformation template, to throws above error. Can these certs be used only by on aws elb ?

Thanks.

**Comment by feanil** [comment]
Hi @rirathod this seems unrelated to this closed issue, also what cloudformation template were you using, the configuration repo has stopped supporting using cloudformation to provision the platform a long time ago.

**Comment by rirathod** [comment]
@feanil .. I was working on my project which is independent of yours and just had a doubt so asked. Anyways, I did figure out on what I was doing wrong. I have 2 aws accounts and was trying to attach account1's server certificate to account2's elb. In short, the certificate name was the problem and I fixed it. Thanks.
