### ISSUE TITLE
Bind IP not set properly in case of mongo cluster

### ISSUE THREAD

**Issue by rohitkode** [openedx-unsupported/configuration#1450]
Due to the usage of an incorrect variable, the bind ip does not get set correctly in case
of mongo cluster 
https://github.com/edx/configuration/blob/master/playbooks/roles/mongo/templates/mongodb.conf.j2#L15

There is no var named 'mongo_clustered'. The correct var should be 'MONGO_CLUSTERED'.

**Comment by feanil** [comment]
Closing this since we can track this via the PR you've opened.
