### ISSUE TITLE
Configuring AMI Instance: Rake fails

### ISSUE THREAD

**Issue by dbrgn** [openedx-unsupported/configuration#1474]
I provisioned a new Amazon EC2 instance (m3.medium) with the official AMI (eu-west-1: ami-6d2fe51a).

When updating the configuration for the first time, the rake task fails:

```
TASK: [edxapp | gather  static assets with rake] ****************************** 
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:00.284912", "end": "2014-08-26 08:54:23.577638", "item": "lms", "rc": 1, "start": "2014-08-26 08:54:23.292726"}
stderr: rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:584:in `raw_load_rakefile'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:89:in `block in load_rakefile'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:88:in `load_rakefile'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:72:in `block in run'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
(See full trace by running task with --trace)
failed: [localhost] => (item=cms) => {"changed": true, "cmd": "SERVICE_VARIANT=cms rake cms:gather_assets:aws ", "delta": "0:00:00.264593", "end": "2014-08-26 08:54:24.134418", "item": "cms", "rc": 1, "start": "2014-08-26 08:54:23.869825"}
stderr: rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:584:in `raw_load_rakefile'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:89:in `block in load_rakefile'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:88:in `load_rakefile'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:72:in `block in run'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
(See full trace by running task with --trace)

FATAL: all hosts have already failed -- aborting
```

**Comment by hkim823** [comment]
Generally when it can't gather static assets lately the problem is malformed JSON or something in the *.env.json files that isn't valid for one reason or another.  Has this happened again since you tried?

**Comment by dbrgn** [comment]
I just spun up a new EC2 instance using the AMI and the error still occurs.

As the traceback states, `No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)`. Isn't this some issue with the directory structure of the repository?

**Comment by hkim823** [comment]
The AMI is a bit old so if you pull in new versions of edx-platform code it may not work with the currrent AMI that's available.  New AMIs are being released soon, that being said, try doing a sudo /edx/bin/update configuration master and then do a sudo /edx/bin/update edx-platform master

**Comment by taz-gnu** [comment]
Have the same issue updating a box build using the Ubuntu 12.04 64 bit instructions. Am getting the exact same rake errors. 

was able to reload master (as per thread #1373) with 
git checkout master

but didn't help.

Tried /edx/bin/update configuration master. It failed as well with:

TASK: [edx_ansible | git checkout edx_ansible repo into edx_ansible_code_dir] ***
failed: [localhost] => {"failed": true, "item": ""}
msg: Failed to checkout master

Help..

**Comment by taz-gnu** [comment]
I took a snapshot of my server and tried a reinstall from scratch with 
wget https://raw.github.com/edx/configuration/master/util/install/vagrant.sh -O - | bash 

This vagrant is getting the same rake errors as well?

**Comment by taz-gnu** [comment]
Tried a 
sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost," --limit @/home/../edx_sandbox.retry 
for good measure.. 

no luck

**Comment by taz-gnu** [comment]
As this incident occurred on a production service, the workaround of; export course material, rebuild from scratch, import class material, was used to get the service back up. 

This clears my incident but it is expected that other admins will encounter this issue when attempting an update.

**Comment by dbrgn** [comment]
Has a new AMI been released, has the bug been fixed, or why has this ticket been closed? :)

**Comment by hkim823** [comment]
Bugs have been fixed if you do a sudo /edx/bin/update configuration release before trying to do a sudo /edx/bin/update edx-platform nameofbranch

**Comment by taz-gnu** [comment]
I kept a copy of my failed vm for further testing. Was able to confirm the rake errors I was experiencing have been cleared. Thanks

**Comment by dbrgn** [comment]
Great, seems to work now. Thanks!
