### ISSUE TITLE
After I run the edx_sandbox.yml locally, the installation process stuck at TASK: [restart edxapp]

### ISSUE THREAD

**Issue by patrickshan** [openedx-unsupported/configuration#148]
Hi, I am trying running the edx_sandbox.yml locally on an ec2 instance with command "/opt/ansible/bin/ansible-playbook -vvv --user=ubuntu edx_sandbox.yml -i inventory.ini -e 'secure_dir=secure_example' --connection=local". (Yeah, I already remove the cofniguration for create instance ) 

I came across several problems. First one is the script can not create 'wwc' database. the second one is it failed to change  '/opt/edx/lib/python2.7/site-packages/django_openid_auth/models.py'. But these two problems can be manully fixed. 

After running for a while, it stuck at:
  TASK: [restart edxapp] ********************************************************

Does anyone know what's the problem with this ?

**Comment by jbau** [comment]
Sometimes the edxapp upstart job hangs (we've experienced this ourselves at Stanford).
You might want to manually log into your instance and sudo stop edxapp and then sudo start edxapp
sometime rebooting the instance will also fix this.

**Comment by patrickshan** [comment]
Hi jbau, thanks for your reply. 

Yeah, after I manually killed that process ( sudo stop edxapp doesn't work too) the process has been finished successfully.

**Comment by patrickshan** [comment]
ubuntu@domU:/proc/13874$ ps auxwww | grep 13874
root     13874  0.0  0.0   4400   608 ?        Ss   03:09   0:00 /bin/sh -e /proc/self/fd/9
ubuntu   15557  0.0  0.0   8104   920 pts/0    S+   03:15   0:00 grep --color=auto 13874
ubuntu@domU:/proc/13874$ sudo status edxapp
edxapp start/pre-start, process 13874

hmm, weird. It seems the start process also stuck there.

**Comment by jbau** [comment]
are the gunicorn processes for lms and cms running?

take a look at /etc/init/edxapp 

it's basically just a controller for starting lms\* and cms.  Also look in /var/log/upstart/[edxapp|lms|cms].log to see if any error messages.

**Comment by patrickshan** [comment]
It seems to be lms-xml's problem. lms-xml failed to start because of this error:
pymongo.errors.ConfigurationError: Unknown option data_dir

**Comment by jbau** [comment]
lms-xml is somewhat legacy--I would just run without it if you're just trying to setup edxapp from scratch (i.e you can remove it from service_variants_enabled

**Comment by patrickshan** [comment]
Okay. Thank you very much for all the help :)

**Comment by patrickshan** [comment]
Hi, is there any documentation for the Email setting. I came across this error when I tried to register a new account:

Could not send activation e-mail.

I am not sure if there is any configuration file I can add the email relay server.

**Comment by jbau** [comment]
You need to properly set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY values, I believe.

**Comment by patrickshan** [comment]
Okay. So I can not configure the mail relay server manually.

**Comment by jbau** [comment]
well, you can, with some work.  You just have to edit edx-platform/lms/envs/aws.py

to set EMAIL_BACKEND and EMAIL_\* to whatever you find useful.  

Though currently some of those settings are not configurable in ansible, but editing the file manually will definitely work (though they'll get clobbered with the next ansible run--we'll have to fix that (we're open to pull requests))

**Comment by patrickshan** [comment]
Thanks jbau. 
Because I am running the smtp server on that host, I changed EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' in edx-platform/lms/envs/aws.py. Currently the email function works fine.

**Comment by elimence** [comment]
Hi Patrick, have you been able to run edx on ec2? i am trying to do so and
would appreciate any help.

**Comment by patrickshan** [comment]
Yes. I have installed edx on ec2. I haven't tested all the functions but it seems to be fine now. There are several problem I came across during the installation included in my first thread.

**Comment by jarv** [comment]
WRT email I have a pull (https://github.com/edx/configuration/pull/147) that's about to be merged which will change the default to use localhost instead of AWS which will allow activations to work. It also removes the need for the secure_dir variable definitions.  I will update the README.

**Comment by patrickshan** [comment]
Cool. This will remove the dependency of AWS account information and make it more convenient.

**Comment by patrickshan** [comment]
By the way, is the cs_comments_service included in this configuration ?

**Comment by feanil** [comment]
It is not but there is work ongoing for a new ansible role for the comment service..

**Comment by patrickshan** [comment]
Thanks feanil.
Is there any document I can refer to for the installation of cs_comments_service ? I didn't found any installation document for it especially for installed edx-platform.

**Comment by feanil** [comment]
No I don't think there is anything currently documented about the
cs_comments_service installation.  However it is a sinitra ruby application
so documentation on production sinitra applications is probably the right
place to look.

**Comment by patrickshan** [comment]
Cool. Thanks feanil :)
