### ISSUE TITLE
Problem with ssh command in "Connecting to host in stack"

### ISSUE THREAD

**Issue by elimence** [openedx-unsupported/configuration#153]
I am setting up the edx stack and have come to the point where i need to connect to host in the stack using ssh. Here's the [url](https://github.com/edx/configuration#connecting-to-hosts-in-the-stack).
I added these lines to my ~/.ssh/config file:

```
Host *.us-west-1.compute-internal
  ProxyCommand ssh -W %h:%p vpc-us-west-1-jumpbox
  ForwardAgent yes

Host vpc-us-west-1-jumpbox
  HostName 54.236.202.101
  ForwardAgent yes
```

after modifying to this:

```
Host *.us-east-1.compute-internal
  ProxyCommand ssh -W %h:%p vpc-us-east-1-jumpbox
  ForwardAgent yes

Host vpc-us-east-1-jumpbox
  HostName 54.236.202.101
  ForwardAgent yes
```

**I changed the region from us-west-1 to us-east-1**
Because i realised the region for the instances created by the stack are in us east 1
**I also changed the HostName to one of the elastic ips created by the stack**

When i tried testing with the given command:

```
ssh ip-10-0-10-1.us-west-1.compute.internal
```

I had the following error:

```
ssh: Could not resolve hostname ip-10-0-10-1.us-west-1.compute.internal: No such file or directory
```

**I realised that in the config file, we had something like _compute-internal_ at the end of the hostname, while in the command, we had _compute.internal_. I wonder if this is the cause?**

But i had the same error even after changing from dot to hyphen.
I am wondering if i made any unnecessary changes or overlooked any.

**Comment by e0d** [comment]
I suspect that you don't have host name resolution enabled in your VPC.  If
you dig that hostname from your jump box,  does it resolve?

If not,  you can enable host name resolution or address your machines by
their internal, 10-dot IPs.

Best,

Ed.

**Comment by elimence** [comment]
Thanks, but i don't really know how to get this done,
I would be glad if you could direct me on how to check the hostname from my
jump box and how to get it working if it's the cause.
Also, was i right to make those edits?
Thanks.

**Comment by e0d** [comment]
OK, looking more closely at you changes, I'm not sure that they are correct.  Have you successfully run the cloud formation template and created the servers?  If so, from the AWS cloud formation UI, look at the resources tab and find the IP of your bastion box.  That's the IP that you will need to use to configure your jumpbox, not 54.236.202.101.

Best,

Ed.

**Comment by elimence** [comment]
Yes, i have completed the server creation and after following your
instructions, i found the right IP.
I know have this error showing up when i run the command

```
Permission denied (publickey).
ssh_exchange_identification: Connection closed by remote host
```

I wonder if i need to use any key file?
Also, since the ssh config file has "compute-internal"
And the ssh connection has "compute.internal"
Which one should i change?

Thanks.

**Comment by e0d** [comment]
Try adding the AWS key such that ssh will have it available:

ssh-add ~/where/you/dowloaded/aws.pem

**Comment by elimence** [comment]
I have the key i created in the .ssh directory, (i have used chmod 400 on it), i also run the ssh-add command.
However, i still get that same error:

```
Permission denied (publickey).
ssh_exchange_identification: Connection closed by remote host
```

**Comment by e0d** [comment]
Can you do:

`> ssh -i ~/where/you/dowloaded/aws.pem ec2_user@<right_ip>`

?

**Comment by elimence** [comment]
Yes, it works, i am able to ssh into an instance with the following promt:

```
ubuntu@ip-10-0-0-77:~$
```

I guess i should move on to the boto part "Finding your hosts via boto"
?

**Comment by feanil** [comment]
Yes.

**Comment by elimence** [comment]
I have realized that continuing with this approach would really cost a lot of money, hence the project i would like to undertake would not be sustainable. Is there any alternative i could use that would be less expensive?

**Comment by jarv** [comment]
Hi elimence - You can install the entire edX stack on a single server (without setting up a VPC) by following these instructions. https://github.com/edx/configuration/wiki#installation
That would be the cheapest option since it only requires a single ec2 instance, it does not however give you any redundancy and I'm not sure how it will perform under load.

-John

**Comment by elimence** [comment]
Thanks John, I'm trying that out now.
I'll let you know how it works.

Best Wishes.
Samuel A.

**Comment by elimence** [comment]
Hi, I have tried out the instructions at the link you gave me, but i run into an error.
I have appended the output of the command.

```
PLAY [Configure instance(s)] ************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Create 'edx' users group] ********************************************** 
ok: [localhost]

TASK: [Add user 'ubuntu' to 'edx' group] ************************************** 
ok: [localhost]

TASK: [Creating admin users] ************************************************** 
skipping: [localhost] => (item=admin_users)

TASK: [Copying ssh keys for admin users] ************************************** 
skipping: [localhost] => (item=admin_keys)

TASK: [Creating env users] **************************************************** 
skipping: [localhost] => (item=env_users)

TASK: [Copying ssh keys for env users] **************************************** 
skipping: [localhost] => (item=env_keys)

TASK: [Group adm passwordless sudo] ******************************************* 
ok: [localhost]

TASK: [Add user www-data] ***************************************************** 
ok: [localhost]

TASK: [Create application root] *********************************************** 
ok: [localhost]

TASK: [Create upload directory] *********************************************** 
ok: [localhost]

TASK: [Create data dir] ******************************************************* 
ok: [localhost]

TASK: [Create staticfiles dir] ************************************************ 
ok: [localhost]

TASK: [Install role-independent useful system packages] *********************** 
ok: [localhost]

TASK: [Create log directory] ************************************************** 
ok: [localhost]

TASK: [Create alias from app_base_dir to the log_base_dir] ******************** 
failed: [localhost] => {"failed": true, "item": ""}
msg: absolute paths are required

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/tmp/ansible/edx_sandbox.retry

localhost                  : ok=15   changed=0    unreachable=0    failed=1   
```

**Comment by jarv** [comment]
I saw this same error recently, will check it out and let you know when it is fixed

**Comment by elimence** [comment]
Thanks :)
