### ISSUE TITLE
LMS/CMS service failed to restart

### ISSUE THREAD

**Issue by wzymaster** [openedx-unsupported/configuration#1567]
after pull the latest release build, I always get the below error in restart edxapp: and edxapp_worker:

unix:///edx/var/supervisor/supervisor.sock no such file

It's a known issue ?

**Comment by hkim823** [comment]
how are you calling supervisor?

**Comment by wzymaster** [comment]
I am using the guide at https://github.com/edx/configuration/wiki/edX-Managing-the-Production-Stack to restart edxapp: and edxapp_worker after restart nginx :

 sudo /edx/bin/supervisorctl -c /edx/etc/supervisord.conf restart edxapp:
 sudo /edx/bin/supervisorctl -c /edx/etc/supervisord.conf restart edxapp_worker:

**Comment by wzymaster** [comment]
I am using other parts in the guide to start/stop nginx and other services like below : 

sudo service nginx stop
sudo service supervisor stop
sudo service supervisor.devpi stop
sudo pkill -u www-data
sudo service nginx start
sudo service supervisor start
sudo service supervisor.devpi start

**Comment by hkim823** [comment]
yeah weird, it should just work, what if you take out the `-c /edx/etc/supervisord.conf` part?

**Comment by feanil** [comment]
It sounds like supervisor is not running.  Can you run `sudo status
supervisor`?

**Comment by wzymaster** [comment]
root@openEdx-dev:~# sudo status supervisor
supervisor start/running, process 651

Can you explan to me what "unix:///edx/var/supervisor/supervisor.sock" mean ? what action should I take if I hit it again ? 

I have to roll back my server to old snapshot so that can't reproduce it any more

**Comment by hkim823** [comment]
It's a generic error that basically says it can't do the thing you want it to do because it doesn't know about the process you are trying to run.  How it got to that state is unclear.  Closing this issue for now.
