### ISSUE TITLE
What is the direct link to base box in Vagrant method?

### ISSUE THREAD

**Issue by perpi** [openedx-unsupported/configuration#1604]
> The first time you create the virtual machine (VM) instance, Vagrant will download the base box, which is about 2GB ([Read more...](https://github.com/edx/configuration/wiki/edx-Production-stack--installation-using-Vagrant-Virtualbox))

What's the direct link to the base box? I want to download it manually by a download manager because of some connection issues on my internet.

If you share the link, I'll download it manually and then it will be penetrated by `vagrant box add edx edx.box` ([More details](https://docs.vagrantup.com/v2/cli/box.html))
- I'm using Virtualbox v4.3.16

**Comment by hkim823** [comment]
The link is inside the Vagrantfile itself.  Take a look https://github.com/edx/configuration/blob/master/vagrant/release/devstack/Vagrantfile
