### ISSUE TITLE
A template is missing apache_port variable that now is a  list of apache_ports

### ISSUE THREAD

**Issue by marcore** [openedx-unsupported/configuration#1624]
It seems that in `playbooks/roles/apache/templates/lms.j2` there is stille a refs to apache_port that is not a variable anymore due to #836

**Comment by hkim823** [comment]
Good catch and it should probably be apache_ports instead of apache_port, @carsongee can you confirm?

**Comment by carsongee** [comment]
Yeah, I was just looking up how to add multiple ports to a virtualhost declaration
