### ISSUE TITLE
SSH Access Issue

### ISSUE THREAD

**Issue by catftp** [openedx-unsupported/configuration#1633]
can any one guide me through to access my edx machine through SSH. by default password access is disabled, then how can i access through keys or if i want to enable access through password.

**Comment by hrnya** [comment]
Make sure you have this line in `/etc/ssh/sshd_config`.

```
PasswordAuthentication yes
```

**Comment by hkim823** [comment]
If you haven't setup your keys before losing access, then you are locked out.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
