### ISSUE TITLE
Getting Started Problem

### ISSUE THREAD

**Issue by ajhenley** [openedx-unsupported/configuration#1647]
Where are the setup instructions?

I see the automated install and the manual install, but there doesn't seem to be a clear list of what to do next. Yes everything starts automatically, but I have buttons with names like "Sign into My Your Platform Name Here" and it isn't clear where to go to set "Your Platform Name Here".

I also see a bunch of stuff related to how to turn themeing on, but no clear idea about where to go to do it. I can see why class2go got folded into openedx, but where I was quickly able to get going once I struggled through the install on class2go, with openedx the install goes fairly smoothly, but it is the configuration that is confusing...

**Comment by hrnya** [comment]
> I have buttons with names like "Sign into My Your Platform Name Here" and it isn't clear where to go to set "Your Platform Name Here".

You set the `PLATFORM_NAME` in `/edx/app/edxapp/{lms,cms}.env.json`.

**Comment by devalih** [comment]
In short clone configuration repo, edit any playbooks/roles/*/defaults/main.yml in all the roles you're interested in installing.

EX.
playbooks/roles/edxapp/defaults/main.yml
playbooks/roles/forum/defaults/main.yml

Optionally you can put your edits on server_vars file on the server so you can get a cleaner way of overriding props.

This's not the official way, but at least this's what I have done and worked with me like a charm :)

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
