### ISSUE TITLE
bundler: cannot change to directory

### ISSUE THREAD

**Issue by dbrgn** [openedx-unsupported/configuration#1694]
I checked out the `aspen.1` branch (234f3f4) and I'm trying to deploy the `vagrant-fullstack` configuration to an EC2 Ubuntu 12.04 host.

I'm getting the following error:

```
TASK: [edxapp | gem install bundler] ****************************************** 
failed: [54.93.163.111] => {"failed": true, "rc": 258}
msg: cannot change to directory '/edx/app/edxapp/edx-platform
': path does not exist

FATAL: all hosts have already failed -- aborting
```

I'm on Ansible 1.7.2.

**Comment by hrnya** [comment]
Please check if your host has `nfs-kernel-server` installed.

```
apt-get install nfs-kernel-server
```

**Comment by dbrgn** [comment]
Do you mean the target host or my local system? I installed it on the target and it did not help.

This looks more like a problem with the ansible variables. There seems to be a newline in the path and I can't figure out why.

**Comment by dbrgn** [comment]
The problem was the indentation. Apparently this was fixed by https://github.com/edx/configuration/commit/e0207b5d846647de44cbe9c75027f5008488da5e, but it's not included in the `aspen.1` branch.

In the blogpost for the aspen release it is claimed that the named release has been extensively tested. As this is a plain syntax error, I must be using the wrong deployment configuration. How is the deployment supposed to work? I'm using the following command to deploy onto a fresh Ubuntu 12.04 instance on EC2:

```
/usr/bin/env ansible-playbook -i inventory.ini vagrant-fullstack.yml
```

**Comment by singingwolfboy** [comment]
@dbrgn did you try using Ansible 1.5.5, as is specified in the `requirements.txt` file? https://github.com/edx/configuration/blob/aspen.1/requirements.txt#L1

Unfortunately, the ansible scripts in the configuration repo don't currently support the latest version of Ansible -- many of the scripts were written before Ansible 1.6 came out with some backwards-incompatible changes.

**Comment by dbrgn** [comment]
Thanks @singingwolfboy, that helped partially. I was on Ansible 1.7.2 before.

Now I'm having migration issues, but I'll post them in a separate issue :)
