### ISSUE TITLE
Rake does not run after initial provisioning

### ISSUE THREAD

**Issue by yuvadm** [openedx-unsupported/configuration#170]
After provisioning, all rake commands in edx-platform fail - https://github.com/edx/edx-platform/issues/426

Rake is running an old version:

``` bash
$ rake --version
rake, version 0.9.2.2
```

This might be the cause of the problem, that can be solved by upgrading rake to v10.1 (as suggested).

**Comment by yuvadm** [comment]
This is turning out to be a very serious issue that restricts any ability of running any type of admin command.

Effectively, an instance cannot be administered properly without the ability to run rake.

**Comment by jarv** [comment]
Closing, please try again using the devstack or prodstack docs:
https://github.com/edx/configuration/wiki/edX-Developer-Stack
https://github.com/edx/configuration/wiki/edX-Production-Stack
against the latest release and let us know if you run into any issues.
-John

**Comment by tummykung** [comment]
I use the newest release but run into an error:

```
edxapp@precise64:~/edx-platform$ rake assets[lms,devstack]
./manage.py lms --settings devstack preprocess_assets --traceback 
xmodule_assets common/static/xmodule
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee` 
sh: 1: node_modules/.bin/coffee: not found
rake aborted!
Command failed with status (127): [node_modules/.bin/coffee --compile `find l...]
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `sh'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in `sh'
/edx/app/edxapp/edx-platform/rakelib/assets.rake:86:in `block (3 levels) in <top (required)>'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:215:in `block (2 levels) in invoke_prerequisites_concurrently'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/promise.rb:63:in `call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/promise.rb:63:in `chore'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/promise.rb:45:in `work'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/thread_pool.rb:103:in `process_queue_item'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/thread_pool.rb:117:in `block (2 levels) in start_thread'
Tasks: TOP => assets => assets:all => assets:coffee
(See full trace by running task with --trace)
```

**Comment by tummykung** [comment]
and here is the result when running the above command with --trace: https://gist.github.com/tummykung/9934b539e4e4b0e1d215

**Comment by e0d** [comment]
Is this an instance that was upgraded from a prior version of the configuration code?  The gist suggests an incomplete installation.  I assume that this returns nothing:

ls -l /edx/app/edxapp/edx-platform/node_modules/.bin/coffee

**Comment by tummykung** [comment]
Yes. It returns nothing.

Perhaps I did not setup edx-platform correctly? When I ran vagrant up and vagrant ssh from `configuration/vagrant/release/dosa/devstack`, I see an empty `edx-platform` folder so I git clone the `edx-platform` repo there. Am I not supposed to do so?

**Comment by wedaly** [comment]
@tummykung The Ansible deploy scripts should handle cloning the repo and performing other one-time setup.  These will run automatically the first time you do `vagrant up`, but if they failed for any reason you'll need to re-run them manually with:

```
vagrant provision
```

If you see an error message about Ansible not being available, make sure you have the configuration requirements installed:

```
cd configuration
sudo pip install -r requirements.txt
```
