### ISSUE TITLE
Running the edX Developer Stack: Error on running paver lms

### ISSUE THREAD

**Issue by karan23** [openedx-unsupported/configuration#1703]
0 down vote favorite

I am following edx tutorial to run devstack(from http://edx-installing-configuring-and-running.readthedocs.org/en/latest/devstack/run_devstack.html#default-accounts-on-devstack) I am getting an error while running command "paver lms" .

Error is as follow :

edxapp@precise64:~/edx-platform$ paver devstack lms
---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py lms --settings=devstack preprocess_assets
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    from safe_lxml import defuse_xml_libs
ImportError: No module named safe_lxml
## Captured Task Output:

---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py lms --settings=devstack preprocess_assets

Build failed running pavelib.servers.devstack: Subprocess return code: 1

Please guide me what needs to be done to run the command.

**Comment by manishpathak99** [comment]
Facing the same issue. 
@karan23 Did you find any solution ? Please share if found.

**Comment by carlseverson** [comment]
I am having the exact same issue. Has there been any resolution?

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
