### ISSUE TITLE
Error in the instalation

### ISSUE THREAD

**Issue by kickfliph** [openedx-unsupported/configuration#1712]
Hey every one. I'm trying to install EDX using Ubuntu 14.04.  I get this error: 
TASK: [edxapp | code sandbox | Use libblas for 3gf] ***************************
failed: [localhost] => {"changed": true, "cmd": ["update-alternatives", "--set", "libblas.so.3gf", "/usr/lib/libblas/libblas.so.3gf"], "delta": "0:00:00.007854", "end": "2014-11-19 22:36:16.390894", "item": "", "rc": 2, "start": "2014-11-19 22:36:16.383040"}
stderr: update-alternatives: error: no alternatives for libblas.so.3gf

FATAL: all hosts have already failed -- aborting

I'm using your man from: https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation to have my installation done. I trid using the vagrant.sh and the Manual installation, but with the same result.

Thanks for all your help.

**Comment by e0d** [comment]
14.04 isn't currently supported, there are probably a lot of updates that will need to be made.  If you would like to work through them, we can try to help. 

Upgrading is on our road map, but we're not actively working in it yet.

This looks like a change to one of the core libraries that we are installing, perhaps the package has been renamed or deprecated.  Either way, we'll need to figure out what 14.04 compatible package can be used here.

**Comment by kickfliph** [comment]
Thanks for answering so soon. So what Linux Distribution do you all use for EDX?, and if you have any man for it?. I prefer Debian or any distribution base on it. Any help for me to go on will be nice because in this point i'm stock.

Thanks for all the help.

**Comment by e0d** [comment]
We are currently on ubuntu precise, 12.04.

Ed.

**Comment by jp-bpl** [comment]
@kickfliph check out this out, worked for me: https://github.com/edx/configuration/issues/1652
@e0d this issue also comes up when installing aspen on Ubuntu 12.04

**Comment by littleBro** [comment]
This worked for me:
1) Find the file: 
/var/tmp/configuration/playbooks/roles/edxapp/tasks/python_sandbox_env.yml
2) Change this:
command: update-alternatives –set libblas.so.3gf /usr/lib/libblas/libblas.so.3gf
to:
command: update-alternatives –set libblas.so.3 /usr/lib/libblas/libblas.so.3
and this:
command: update-alternatives –set liblapack.so.3gf /usr/lib/lapack/liblapack.so.3gf
to:
command: update-alternatives –set liblapack.so.3 /usr/lib/lapack/liblapack.so.3

**Comment by firaskafri** [comment]
Thanks @littleBro

**Comment by juanmacoo** [comment]
Indeed, Thank you very much @littleBro

**Comment by jessp01** [comment]
Just in case someone else ends up here, the /var/tmp file is a cached copy, the place to change is:
/edx/app/edx_ansible/edx_ansible/playbooks/roles/edxapp/tasks/python_sandbox_env.yml
