### ISSUE TITLE
failed to provision dev stack with the npm error‏

### ISSUE THREAD

**Issue by liudongqing** [openedx-unsupported/configuration#1714]
I am trying to setup a dev stack and got the error when provisioning as following

---

==> default: failed: [localhost] => {"changed": true, "cmd": "npm install ", "d
lta": "0:00:34.691789", "end": "2014-11-24 09:50:44.491105", "item": "", "rc":
55, "start": "2014-11-24 09:50:09.799316"}
==> default: stderr: npm WARN package.json edx@0.1.0 No repository field.
==> default: npm ERR! Error: UNKNOWN, symlink '../coffee-script/bin/coffee'
==> default: npm ERR! If you need help, you may report this _entire_ log,
==> default: npm ERR! including the npm and node versions, at:
==> default: npm ERR!     http://github.com/npm/npm/issues
==> default:
==> default: npm ERR! System Linux 3.2.0-23-generic
==> default: npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
==> default: npm ERR! cwd /edx/app/edxapp/edx-platform
==> default: npm ERR! node -v v0.10.31
==> default: npm ERR! npm -v 1.4.23
==> default: npm ERR! path ../coffee-script/bin/coffee
==> default: npm ERR! code UNKNOWN
==> default: npm ERR! errno -1
==> default: npm ERR!
==> default: npm ERR! Additional logging details can be found in:
==> default: npm ERR!     /edx/app/edxapp/edx-platform/npm-debug.log
==> default: npm ERR! not ok code 0

Any suggestion on how to debug and fix it?

-dq

**Comment by feanil** [comment]
What is in the npm-debug.log file?

Also can you tell me about where you're running into this error if I wanted to re-produce it?  Is it on an Ubuntu 12.04 Machine, on a vagrant image?  What is your version of the configuration repo?

**Comment by liudongqing** [comment]
I am trying to install it in Windows host, and I follow the guide on wiki about symlink error.https://github.com/edx/configuration/wiki/edX-Developer-Stack#windows . But still same. I had switched to a Mac host. 

Thanks for response.
