### ISSUE TITLE
TASK: [edxapp | gather  static assets with paver] fails when using custom theme

### ISSUE THREAD

**Issue by lucianolev** [openedx-unsupported/configuration#1730]
Using a custom theme in /edx/app/edx_ansible/server-vars.yml following [this](https://github.com/edx/edx-platform/wiki/Stanford-Theming#provisioning-method) guide causes an error when doing assets-related stuff:

ValueError: The file 'themes/claseabierta/images/sunrise.jpg' could not be found with <cms.lib.django_require.staticstorage.OptimizedCachedRequireJsStorage object at 0x5ad64d0>.

This happens in a vanilla install using the AMI from Amazon. After some investigation, I've found that the problem happens because custom_theme is set to true also for the CMS (which doesn't support themes apparently), in cms.env.json. Setting back to false (and also cleaning the THEME_NAME to "") and compiling the assets manually solves the problem.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
