### ISSUE TITLE
Installation of Full Stack (Producation) fails for npm dependencies for Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by spipriya** [openedx-unsupported/configuration#1737]
I was trying to deploy open edx on IBM Softlayer using the Wiki https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation..
I get the following error & the installation fails: 

TASK: [edxapp | Install edx-platform npm dependencies] ************************
failed: [localhost] => {"changed": true, "cmd": "npm install ", "delta": "0:00:00.870940", "end": "2014-12-10 03:04:09.775749", "item": "", "rc": 1, "start": "2014-12-10 03:04:08.904809"}
stderr: npm WARN package.json edx@0.1.0 No repository field.
npm ERR! Error: Attempt to unlock uglify-js@2.4.15, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 3.2.0-72-virtual
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /edx/app/edxapp/edx-platform
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /edx/app/edxapp/edx-platform/npm-debug.log
npm ERR! not ok code 0

FATAL: all hosts have already failed -- aborting

Any leads how to fix this ?

**Comment by ajhenley** [comment]
Did the AWS install and then I did an update against the aws image (WHICH MAKES NO SENSE!!!! Why have an image that if it doesn't work?) I get the same error.

**Comment by e0d** [comment]
Coming to this late.  The AMIs are cut when we do releases.  We would like to produce them more frequently, but don't have the time to do that at the moment.  Are you saying that AMI didn't function or was broken after you updated?  As far as I know that AMI works, but, as I said, it is the code at a particular release.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
