### ISSUE TITLE
Prodution stack wiki page is missing

### ISSUE THREAD

**Issue by usernamenumber** [openedx-unsupported/configuration#1757]
Several places on the wiki, including the front page, link to https://github.com/edx/configuration/wiki/edX-Production-Stack, but there doesn't appear to be a page there (anymore?).

**Comment by e0d** [comment]
I've intentionally renamed Production stack to Full stack and missed some of the links.  Though Full Stack is production like, I would not recommend it for any non-trivial deployment of edX.  I wanted the name to reflect that.
