### ISSUE TITLE
Error while Install Open edX on server 

### ISSUE THREAD

**Issue by Basmah-am** [openedx-unsupported/configuration#1758]
Hello everyone 

I follow this guide to install edx platform on Ubuntu server (https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation)
when I tried the below command

git clone -b release https://github.com/edx/configuration

I got an error ,please refer to the attachment 

also when I tried to access the link in the error from the browser  (https://github.com/edx/configuration/info/refs) I got 404 page not found 

I think info/refs file was removed from github 

any suggestions  ? 
![screenshot 2014-12-28 08 11 13](https://cloud.githubusercontent.com/assets/10328077/5563114/bd847204-8e69-11e4-9d63-e5c07aca5279.png)

**Comment by e0d** [comment]
I believe this is a proxy server issue on your end.

Can you clone any repos on github over https?

**Comment by Basmah-am** [comment]
unfortunately I cant clone any repos on github ,do you know how to fix proxy setting 

thank you
