### ISSUE TITLE
RFC: Common var refactoring proposal

### ISSUE THREAD

**Issue by e0d** [openedx-unsupported/configuration#1760]
Currently we setup common vars in `roles/common/default/main.yml`  Often these values are used downstream when roles that depend on common are applied.

For example, the common directories used by roles are set up like so:

```
COMMON_BASE_DIR: /edx
COMMON_DATA_DIR: "{{ COMMON_BASE_DIR}}/var"
COMMON_APP_DIR: "{{ COMMON_BASE_DIR}}/app"
COMMON_LOG_DIR: "{{ COMMON_DATA_DIR }}/log"
```

This is all well and good, however, it means that roles cannot access shared vars without including common in their play.  Common is side-effecting, so this isn't always desirable, and is always slower than it could be.

I'm thinking that it would be useful to pull these vars into a separate role that only loads the vars and never produces any side-effects, say, `edx-globals`.  Common would have a hard dependency on this role.

Thoughts?

@carsongee @feanil @fredsmith @jarv @maxrothman

**Comment by jarv** [comment]
I think I like that approach, here are the other options as I see them. (3) is the only one worth consideration I think.
1. Use the [include_vars](http://docs.ansible.com/include_vars_module.html) module to include the common vars at the beginning of each task file (pros: doesn't require a role dependency / cons: not as elegant and requires a relative path)
2. Add an include_vars: to every play that pulls in the common vars where needed (pros: is more explicit I guess? / cons: it's a lot of repetition in our playbooks)
3. Add the vars to `group_vars/all`.  I think this is the ansible-way to do it although it sits above role defaults in the [not very well documented var priority order](https://gist.github.com/jarv/e8f807b2e5f5d7e427f7)  (pros: always included / cons: it assumes that you want _every_ role to include those vars)

**Comment by carsongee** [comment]
I'm :+1: on using a role since that works nicely with `roles_path`.  `group_vars/all` doesn't work if you run your plays from somewhere other than `edx/configuration` and other than -e it dominates other vars.  The include_vars also doesn't work with `roles_path`, and in fact it might be nice to also apply this approach other places we use `include_vars`, of which I know I'm guilty and is the reason I know it doesn't work with `roles_path` :stuck_out_tongue_winking_eye:

**Comment by feanil** [comment]
:+1:  to this approach.

**Comment by maxrothman** [comment]
Given that this is merged, I'm closing it. If necessary, it can be reopened.
