### ISSUE TITLE
RFC: remove edx-east and edx-west

### ISSUE THREAD

**Issue by e0d** [openedx-unsupported/configuration#1765]
I think it makes sense to have a canonical set of plays for installing services.  I think our current setup makes things a little more confusing for anyone approaching the config repo and trying to get things done.

I'm not sure what the best thing to do here is, but wanted to solicit opinions.  I think it's probably inevitable that deployments will need to customize their plays, so perhaps we need default plays here and our own repos for any environment or deployment specific exceptions.  I assume that @carsongee does something along these lines.

Thoughts?

@jbau @feanil @fredsmith @maxrothman

**Comment by snachx** [comment]
+1 looking forward to this for a long time!

**Comment by danielmcquillen** [comment]
+1 

Somewhat tangential: even a few more comments in the Ansible files would really help sort canonical things from context-specific things. Maybe even a level similar to what you see in, for example, the [e2.ini file for Ansible EC2](https://raw.githubusercontent.com/ansible/ansible/stable-1.9/plugins/inventory/ec2.ini).

**Comment by kdmccormick** [comment]
+1
