### ISSUE TITLE
502 bad gateway error after reboot

### ISSUE THREAD

**Issue by musixhine** [openedx-unsupported/configuration#1770]
I got the internal server error message, so I reboot the server. Then I get 502 bad gateway error from nginx.... This happened several times, every time they just re install the edx linux image... I double checked the nginx configuration this time, it was fine......

**Comment by feanil** [comment]
Have you looked at the application logs?  It sounds like there may be a problem with your instance of edx.  Take a look at '/edx/var/log/lms/edx.log' if you are running a standard install.
