### ISSUE TITLE
Theme Issue

### ISSUE THREAD

**Issue by cyberdeepak** [openedx-unsupported/configuration#1799]
I did the following steps, but i am not able to use custom theme(Stanford theme) in edx platform. Can someone help me to resolve this issue?

Step :1
OPENEDX_RELEASE=aspen.1 wget https://raw.githubusercontent.com/edx/configuration/master/util/install/vagrant.sh -O - | bash
Step :2
Then created user and demo course based on the following one
https://github.com/edx/configuration/wiki/edX-Managing-the-Full-Stack

Step: 3
Created server-vars.yml file in /edx/app/edx_ansible/

Step: 4
Add the following lines to /edx/app/edx_ansible/server-vars.yml

edxapp_use_custom_theme: true
edxapp_theme_name: 'default'
edxapp_theme_source_repo: 'https://github.com/Stanford-Online/edx-theme.git'
edxapp_theme_version: 'HEAD'

Step: 5 
Run the provisioning scripts  - sudo /edx/bin/update edx-platform release

Error: - I am getting the following error and build fails

TASK: [edxapp | gather  static assets with paver] *****************************
changed: [localhost] => (item=lms)
failed: [localhost] => (item=cms) => {"changed": true, "cmd": "SERVICE_VARIANT=cms paver update_assets cms --settings=aws ", "delta": "0:05:29.794875", "end": "2015-01-25 18:32:50.124015", "item": "cms", "rc": 1, "start": "2015-01-25 18:27:20.329140"}

Looking forward. Thanks.

**Comment by feanil** [comment]
@singingwolfboy Do we have documentation somewhere for how to setup aspen with theming?

**Comment by singingwolfboy** [comment]
edX does not have any such documentation, as far as I am aware, although @mhoeber may know more than me. The best place to get support for Stanford theming is from Stanford via the [edx-code mailing list](https://groups.google.com/forum/#!forum/edx-code). The Stanford theming system has a lot of problems, and was built specifically to accomodate Stanford's theming needs without regards to anyone else's theming needs, so it may not work the way you want. The Open Source team at edX is in the process of building a robust, complete, documented theming system for the edX platform, but that work is still in the very early stages, and won't be usable for awhile.

**Comment by mhoeber** [comment]
Yes, for help with Stanford theme I would start with the mailing list.  We will have full theming documentation with the release of the new theming system.

**Comment by jp-bpl** [comment]
Just btw: Is there any ETA on the new theming system?

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
