### ISSUE TITLE
Installation fails in [edxapp | add ppas for current versions of nodejs]

### ISSUE THREAD

**Issue by nkanish2002** [openedx-unsupported/configuration#1800]
Hi,

I was trying to install edx on my machine running on Ubuntu 12.04 using the One step installation step given on https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation when the following failure occurred. Can someone tell me how to fix it?

Failure log:-

TASK: [edxapp | add ppas for current versions of nodejs] *********************\* 
failed: [localhost] => {"failed": true, "item": "", "parsed": false}
invalid output was: SUDO-SUCCESS-efxphyxvlmnjzhrkrdouludptqmwzjgn
Traceback (most recent call last):
  File "/home/anish/.ansible/tmp/ansible-tmp-1422275978.74-113667977211335/apt_repository_1.8", line 1818, in <module>
    main()
  File "/home/anish/.ansible/tmp/ansible-tmp-1422275978.74-113667977211335/apt_repository_1.8", line 436, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/deprecation.py", line 98, in deprecated_function
    return func(_args, *_kwds)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 441, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/precise/Release.gpg  Could not connect to ppa.launchpad.net:80 (91.189.95.83). - connect (113: No route to host)
, W:Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/precise/Release.gpg  Unable to connect to ppa.launchpad.net:http:
, W:Failed to fetch http://ppa.launchpad.net/tualatrix/ppa/ubuntu/dists/precise/Release.gpg  Unable to connect to ppa.launchpad.net:http:
, W:Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/precise/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
, W:Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/precise/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
, W:Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/precise/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
, W:Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/precise/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
, W:Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/precise/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
, W:Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/precise/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
, W:Failed to fetch http://ppa.launchpad.net/tualatrix/ppa/ubuntu/dists/precise/main/source/Sources  Unable to connect to ppa.launchpad.net:http:
, W:Failed to fetch http://ppa.launchpad.net/tualatrix/ppa/ubuntu/dists/precise/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
, W:Failed to fetch http://ppa.launchpad.net/tualatrix/ppa/ubuntu/dists/precise/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
, W:Failed to fetch http://ppa.launchpad.net/tualatrix/ppa/ubuntu/dists/precise/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
, E:Some index files failed to download. They have been ignored, or old ones used instead.

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/anish/edx_sandbox.retry

localhost                  : ok=146  changed=110  unreachable=0    failed=1   

Thanks

**Comment by feanil** [comment]
It looks like you failed to connect to ppa.launchpad.net. Seems like a network issue on your end.
**apt.cache.FetchFailedException: W:Failed to fetch http://ppa.launchpad.net/chris-lea/node.js/ubuntu/dists/precise/Release.gpg Could not connect to ppa.launchpad.net:80 (91.189.95.83). - connect (113: No route to host)**
