### ISSUE TITLE
One-liner install script

### ISSUE THREAD

**Issue by natea** [openedx-unsupported/configuration#181]
I made a small bash script which encapsulates the commands that are run on the server. https://gist.github.com/natea/6084836/raw/779c43a959e84948ff1d946898ac94e9556ab042/edx-install.sh

So now the entire install process can be executed with this one line from the client machine (no need to login to the server):

```
curl -O https://gist.github.com/natea/6084836/raw/779c43a959e84948ff1d946898ac94e9556ab042/edx-install.sh && ssh -i ~/.ssh/yourkey.pem ubuntu@ec2-xxx-xxx-xxx-xxx.compute-1.amazonaws.com 'bash -s' < edx-install.sh
```

You need to replace yourkey.pem with whatever your private key is, and ec2-xxx-xxx-xxx with whatever your EC2 public hostname is.

**Comment by natea** [comment]
This version is a bit shorter:

```
wget https://tinyurl.com/edx-install && ssh -i ~/.ssh/<yourkey>.pem ubuntu@ec2-<x.x.x.x>.compute-1.amazonaws.com 'bash -s' < edx-install.sh
```

**Comment by natea** [comment]
Or if you prefer curl:

```
curl -LO https://tinyurl.com/edx-install && ssh -i ~/.ssh/yourkey.pem ubuntu@ec2-xxx-xxx-xxx-xxx.compute-1.amazonaws.com 'bash -s' < edx-install
```

**Comment by tummykung** [comment]
I used the given script but it gave me:

TASK: [edxlocal | create a mongodb user for edxapp] ***************************
failed: [localhost] => {"failed": true, "item": ""}
msg: the python pymongo module is required

So from the wiki page it seems that we need to run

sudo pip install -r requirements.txt

as well.

**Comment by natea** [comment]
yeah, the requirements need to get run but I think Ansible will do that for you. 

@tummykung this is another option if you want to use the VirtualBox image. https://github.com/natea/edx-in-a-box

**Comment by jarv** [comment]
closing this until we decide whether a script install is necessary for the ubuntu server install.
