### ISSUE TITLE
Restart LMS and Studio

### ISSUE THREAD

**Issue by elimence** [openedx-unsupported/configuration#183]
Hi,
I set up edx on ec2, but i realised i was running out of disk space, and so i created a snapshot of my volume and used it to create a larger volume, after attaching it to the instance, i could no longer access lms and studio with my instance's ip.

I tried restarting gunicorn and nginx, but nothing changed.
I'm thinking of starting the whole process over, but surely, there's a better way to get this working.
Thanks.

**Comment by patrickshan** [comment]
Check the lms/cms processes. Maybe they are stuck by some other services such as lms-xml. I have come across this problem before.
