### ISSUE TITLE
Ubuntu vs Vagrant installation - Documentation

### ISSUE THREAD

**Issue by edudemy** [openedx-unsupported/configuration#1832]
Hi,

I recently tried the Ubuntu installation of openedx with virtualbox Ubuntu guest VM on Mac OS host, But I am not able to access LMS (http://192.168.33.10) from the host browser.  Whereas I am able to access it on the other  vagrant aspen.1 installation from the host OS.  Would try the devstack installation next. But If someone could point out how to access LMS with Ubuntu installation, I would be grateful

Regards,
Ed

**Comment by feanil** [comment]
@edudemy With our vagrant images, we configure the VM to use the IP you stated above and to forward a few ports locally.  Look here: https://github.com/edx/configuration/blob/master/vagrant/release/devstack/Vagrantfile#L84-L89

If you did not do something similar with your guest VM,  you may not be able to access it like you do one of the vagrant images.

**Comment by edudemy** [comment]
@feanil Thanks for the pointer. That works with Vagrant images. However, I could not find the corresponding documentation for clean Ubuntu installation mentioned in the configuration wiki. 
https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation

Also, I experimented with the network settings on the Virtualbox (non-vagrant) Ubuntu guest.
By setting the network adapter to bridged mode, I was able to access the LMS on 192.168.1.11.

But still, I am not able to access the CMS. Nor, the LMS in NAT, Port forwarding mode.
It would help, if the documentation for Ubuntu installation is elaborated a bit, to include above details.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
