### ISSUE TITLE
Is there a windows setup guide?

### ISSUE THREAD

**Issue by zxcfer** [openedx-unsupported/configuration#1833]
I have found the installation guide https://github.com/edx/configuration/wiki/edX-Developer-Stack, but it didn't work in windows. Then I followed https://github.com/edx/configuration/wiki/Vagrant-troubleshooting, and go to symlinks problem. I cloned the edx-platform and executed the git commands, but I don't know how to mix that source with vagrant.

If somebody has already installed edx on windows would be great.

**Comment by feanil** [comment]
@iwxfer there has been some work from the community on this, take a look at this post on the mailing list.

https://groups.google.com/forum/#!searchin/edx-code/birch$20windows/edx-code/Mn1sjCZbyOU/AqsJUGKW4tAJ
