### ISSUE TITLE
Customize signup emails and html

### ISSUE THREAD

**Issue by elimence** [openedx-unsupported/configuration#184]
How can i customize the email messages sent out after registration.
Also i would like to update the homepage to the new one used by edx, it's there a recommended way of doing this?
Thanks

**Comment by jarv** [comment]
Hi elimence - please use the github issue list to report bugs related to edX configuration management, not ask questions.  For general questions you should use the edx-code list. https://groups.google.com/forum/#!forum/edx-code
-John
