### ISSUE TITLE
Cannot apply stanford theme

### ISSUE THREAD

**Issue by brenthmiras** [openedx-unsupported/configuration#1850]
After setting up a fullstack instance in aws, and creating server-vars.yml, running sudo /edx/bin/update edx-platform master as described here https://github.com/edx/edx-platform/wiki/Stanford-Theming fails. These are the output of the console: 

TASK: [edxapp | checkout edx-platform repo into {{edxapp_code_dir}}] *********\* 
failed: [localhost] => {"failed": true, "item": ""}
msg: Failed to download remote objects and refs

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/ubuntu/edxapp.retry

localhost                  : ok=6    changed=0    unreachable=0    failed=1

**Comment by e0d** [comment]
I believe you can fix this by changing to the edxapp code directory and running

sudo -u edxapp git remote prune origin

**Comment by mmarkov** [comment]
I believe you mean `sudo -u edxapp git remote prune origin`

**Comment by shubhdev** [comment]
In case it says "fatal: unrecognized argument: origin". Any suggestions?

**Comment by e0d** [comment]
@shubhdev I've amended my comment to avoid confusion, but @mmarkov is correct, use that command.
