### ISSUE TITLE
What is the reason why 64 bit architecture is required for the Ubuntu server install?

### ISSUE THREAD

**Issue by Travincal** [openedx-unsupported/configuration#1864]
If I wanted to install in a 32 bit machine, would I need to change many things?

I read that JVM is set to 64bits, but are there other things that depend on the 64 architecture?

Thanks

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
