### ISSUE TITLE
Always get "internal server error" message. 

### ISSUE THREAD

**Issue by musixhine** [openedx-unsupported/configuration#1871]
Always get "internal server error" message. The connection is fine. Is this a nginx related issue? We always get this error message and can't resolve it until reboot the server...

**Comment by yrchen** [comment]
@musixhine Hi, do you use fullstack Vagrant image? Please try to check your MySQL service is running correctly. If not, we might meet the same issue that MySQL server crashes regularly.

**Comment by musixhine** [comment]
Thanks! good point. I will check the DB status next time when I get the error msg again.

**Comment by deepande** [comment]
Hi,
I have the same problem. Mysql stops all of a sudden and the site throws Internal Server Error. What can we do to prevent these crashes.

**Comment by yrchen** [comment]
@deepande Check memory. MySQL service will crash if system out of memory.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
