### ISSUE TITLE
edX platform pre-installed image on Windows

### ISSUE THREAD

**Issue by abdelram** [openedx-unsupported/configuration#1876]
Hello All
Is there an edX platform a pre-installed image to launch edX in windows ?.
if not, is there an easy way to install edx platform on windows
thank you

**Comment by axilleas** [comment]
Follow these intructions https://github.com/edx/configuration/wiki/edx-Full-stack--installation-using-Vagrant-Virtualbox

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
