### ISSUE TITLE
Edited main.yml in order to customize active link and email address, but failed.

### ISSUE THREAD

**Issue by musixhine** [openedx-unsupported/configuration#1880]
I edited main.yml in /edx/app/edx_ansible/edx_ansible/playbooks/y/edxapp/defaults
then I restarted the server. but nothing was changed... I still receive email from @example.com with a "localhost" active link....

**Comment by axilleas** [comment]
Did you run Ansible again to take effect?

**Comment by musixhine** [comment]
I ran  "ansible-playbook main.yml" but it asked me to specify an inventory path.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
