### ISSUE TITLE
util/json_lint.sh does not exist in precommit hook call and thus commit fails

### ISSUE THREAD

**Issue by axilleas** [openedx-unsupported/configuration#1893]
The precommit hook uses `util/json_lint.sh` which does not exist and thus commit fails.
Is this a leftover or am I missing something?

https://github.com/edx/configuration/blob/master/git-hooks/pre-commit.in#L9

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
