### ISSUE TITLE
error while executing cmd "paver devstack lms"

### ISSUE THREAD

**Issue by xiongsenlin** [openedx-unsupported/configuration#1943]
I operated as page https://github.com/edx/configuration/wiki/edX-Developer-Stack.
but when executing "paver devstack lms" to start lms:

npm WARN package.json edx@0.1.0 No repository field.
-|/--|/--|-|npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.7.5
npm ERR! path ../coffee-script/bin/cake
npm ERR! code UNKNOWN
npm ERR! errno -1

npm ERR! UNKNOWN, symlink '../coffee-script/bin/cake'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.7.5
npm ERR! path npm-debug.log.f38a280d7df3bb2eecef0b812ba0ab8f
npm ERR! code ETXTBSY
npm ERR! errno 62

npm ERR! ETXTBSY, rename 'npm-debug.log.f38a280d7df3bb2eecef0b812ba0ab8f'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /edx/app/edxapp/edx-platform/npm-debug.log
## Captured Task Output:

---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
test `npm config get registry` = "http://registry.npmjs.org/" || (echo setting registry; npm config set registry http://registry.npmjs.org/)
npm install

Build failed running pavelib.servers.devstack: Subprocess return code: 255

**Comment by hanyonggihub** [comment]
Hi, these days I am installing devstack edx ,  I have some questions about this and can i get your email?

**Comment by hanyonggihub** [comment]
My main problem is that when i enterth command "vagrant up", the return is faild, and i can not the problem.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
