### ISSUE TITLE
Erorr on Run the edx_sandbox.yml playbook in the configuration/playbooks directory

### ISSUE THREAD

**Issue by tabatabaei** [openedx-unsupported/configuration#1957]
when i excute this command
cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"

show 22 ok 1 changed and 1 failed
failed: [localhost] => (item=/etc/update-motd.d/51-cloudguest) => {"failed": true, "item": "/etc/update-motd.d/51-cloudguesr" ,"path": "/etc/update-motd.d/51-cloudguest", "state": "absent"}
msg: file (/etc/update-motd.d/51-cloudguest) us absent, cannot continue

**Comment by eemirtekin** [comment]
Hello @tabatabaei 

You must create file 
nano /etc/update-motd.d/51-cloudguest 
ctrl + O
crtl + Enter

**Comment by tabatabaei** [comment]
tanks but i carest empty file 
"sudo nano /etc/update-motd.d/51-cloudguest"
and try this command again 
 cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
but show this error 
failed: [localhost] => {"failed": true}
msg: failed to fetch PPA information, error was: Request failed: <urlopen error [Errno -3] Temporary failure in name resolution 
FATAL: all hosts have already failed -- aborting

**Comment by e0d** [comment]
That's a temporary networking issue, try again.

Ed

**Comment by tabatabaei** [comment]
i don't have problem in internet and have access to the internet 
trying don't work but install git manual  and skip this error but show this error 
TASK: [rbenv | install bundler] *****************
fialed: [localhost] => {"changed": true, "cmd": "gem install bundler -v 1.3.2", "delta":  "0:04:07.850461", "end": "2015-05-10 21:12:25.514668", "rc": 2, "start": "2015-05-10 21:08:17.664207", "warnings": []}
stderr:ERROR: Could not find a valid gem 'bundler' (= 1.3.2) in any repository 
WARNING: Error fetching data: to many connection resets (production.s3.rubygems.org/latest_specs.4.8.gz) 
ERROR: Possible alternatives: bundler
 FATAL: all hosts have already failed -- aborting

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
