### ISSUE TITLE
Erorr on run the edx_sandbox.yml playbook for Ubuntu 12.04.5 Server 64bit

### ISSUE THREAD

**Issue by sdgdsffdsfff** [openedx-unsupported/configuration#1968]
when I excute this command
cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"

TASK: [edxapp | code sandbox | Use libblas for 3gf] ***************************
failed: [localhost] => {"changed": true, "cmd": ["update-alternatives", "--set", "libblas.so.3gf", "/usr/lib/libblas/libblas.so.3gf"], "delta": "0:00:00.063058", "end": "2015-04-28 13:35:02.043844", "item": "", "rc": 2, "start": "2015-04-28 13:35:01.980786"}
stderr: update-alternatives: error: no alternatives for libblas.so.3gf.

FATAL: all hosts have already failed -- aborting

Any ideas?
Thanks

**Comment by feanil** [comment]
Is liblapack-dev installed on this machine? That should have pulled in
libblas-3gf I believe.  Are you running this on ubuntu 12.04?

**Comment by sdgdsffdsfff** [comment]
Thank you for feanil answer.
libblas.so.3gf --> libblas.so.3
