### ISSUE TITLE
Configurations for sandbox environment

### ISSUE THREAD

**Issue by patrickshan** [openedx-unsupported/configuration#197]
Hi there,

I have used the ubuntu 12.04 playbook to install the sandbox on a single server. I found the configuration for lms&cms is a bit confused. Do we have any documentation about the configuration ? Such as:
cms.env.json:
"COMMENTS_SERVICE_URL" : "" # the format is something like "http://127.0.0.1:4567"
"PREVIEW_LMS_BASE": "www.mysite.com" # is this the right way to do this? Although I have set this, it seems there are still some "View Live" link broken in cms.

and also many other configurations. 

Or is there any fully configured files I can get some ideas about them ? especially for cms.env.json and lms.env.json

**Comment by elimence** [comment]
Please ask this on the [mailing list](http://groups.google.com/forum/#!forum/edx-code), since this place is reserved for reporting bugs as i was told not long ago :)

**Comment by elimence** [comment]
I happen to be interested in the answer to this as well, please do post it to the forums or i can if you please.
