### ISSUE TITLE
How can I run edx-platform on CentOS 64bit?

### ISSUE THREAD

**Issue by sdgdsffdsfff** [openedx-unsupported/configuration#1994]
I want to run edx-platform on CentOS,but I don't know how to do it.

Thanks.

**Comment by tabris17** [comment]
It seems impossible

**Comment by feanil** [comment]
@sdgdsffdsfff did you look at the open edx operations mailing list?   https://groups.google.com/forum/#!searchin/openedx-ops/centos/openedx-ops/EbGgAUfZyAw/RPJaHwwhBBoJ
