### ISSUE TITLE
Error on TASK: [stop edxapp services]

### ISSUE THREAD

**Issue by elimence** [openedx-unsupported/configuration#201]
In reference to issue #196, the first error (regarding file permissions) was resolved after merging pull requests [199](https://github.com/edx/configuration/issues/199) and [200](https://github.com/edx/configuration/pull/200).

It still doesn't deploy as another error has shown up.

```
TASK: [stop edxapp services] ************************************************** 
failed: [localhost] => {"failed": true, "item": ""}
msg: stop: Job has already been stopped: edxapp


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/tmp/ansible/edx_sandbox.retry

localhost                  : ok=98   changed=25   unreachable=0    failed=1  
```

When i try to access lms or studio, i get this error:

```
502 Bad Gateway
___________________________________
nginx/1.1.19
```

**Comment by e0d** [comment]
I've just encountered this issue and the cause was that the services where hung in a starting state.

```
$ /opt/edx$ sudo service edxapp status
edxapp stop/pre-start, process 748
$ /opt/edx$ sudo service edxapp stop
stop: Job has already been stopped: edxapp
```

In this case edxapp was not going to start because of an issue earlier in the deployment, killing the services and re-running ansible fixed the issue.
