### ISSUE TITLE
Error during installation with rabbitmq

### ISSUE THREAD

**Issue by sdgdsffdsfff** [openedx-unsupported/configuration#2012]
TASK: [rabbitmq | start rabbit nodes] *****************************************
failed: [localhost] => {"failed": true, "item": ""}
msg: rmdir: failed to remove `/var/run/rabbitmq': Directory not empty

FATAL: all hosts have already failed -- aborting

**Comment by e0d** [comment]
Are you installing this on a server that already was running rabbitmq?  Are you trying to upgrade edx?  Need more information.

**Comment by sdgdsffdsfff** [comment]
root@host:~# apt-get purgerabbitmq-server
root@host:~# apt-get install rabbitmq-server
- Starting message broker rabbitmq-server
- FAILED - check /var/log/rabbitmq/startup_{log, _err}

invoke-rc.d: initscript rabbitmq-server, action "start" failed.
dpkg: error processing rabbitmq-server (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 rabbitmq-server
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
