### ISSUE TITLE
Erorr on install apparmor-utils(Ubuntu 12.04)

### ISSUE THREAD

**Issue by sdgdsffdsfff** [openedx-unsupported/configuration#2016]
TASK: [edxapp | install system packages on which LMS and CMS rely] ************
failed: [localhost] => {"failed": true}
stderr: E: Unable to correct problems, you have held broken packages.

stdout: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apparmor-utils : Depends: libterm-readkey-perl but it is not going to be installed
                  Depends: librpc-xml-perl but it is not going to be installed

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 's3cmd' 'pkg-config' 'apparmor-utils' 'ipython' 'nodejs' 'libfreetype6-dev'' failed: E: Unable to correct problems, you have held broken packages.

FATAL: all hosts have already failed -- aborting

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
