### ISSUE TITLE
How to Manage the server with --settings other than aws

### ISSUE THREAD

**Issue by farazmir** [openedx-unsupported/configuration#2022]
I have successfully deployed Open edX on an openstack private internal cloud Ubuntu 12.04 instance. Reading https://github.com/edx/configuration/wiki/edX-Managing-the-Full-Stack i see it is specific to asw.
1. Do i omit --settings aws while managing my instance?
2. How do I check the settings currently being used?
3. After deployment I wasnt sure how to edit things like "Your Platform Name Here", default system email account for communication etc

**Comment by farazmir** [comment]
found the answer to 3.
How can I change my platform name or site image?
See https://github.com/edx/edx-platform/wiki/Naive-(Basic)-Theming

**Comment by brucellino** [comment]
Hi @farazmir - we are also having issues with the AWS settings. How did you do the db migration ?

**Comment by feanil** [comment]
@farazmir '--settings aws' is a bit misleading.  Those are our production settings that read a bunch of config from json.  They are not actually aws specific.  By default any full stack setup should be using the aws.py settings file.

**Comment by brucellino** [comment]
Thanks for the response, but I'm afraid I still don't understand why our migrations don't work. 

We haven't been able to do db migration at all. I'm curious as to how the syncdb and migrate task is actually executed and where i can find these settings.

**Comment by farazmir** [comment]
@feanil thanks for the clarification. those settings just worked fine

**Comment by feanil** [comment]
@brucellino since @farazmir 's original issues are resolved, I'm gonna close this issue.  If you've read through this wiki page: https://github.com/edx/configuration/wiki/edX-Managing-the-Full-Stack and are still having issues please open up a separate issue.
