### ISSUE TITLE
Create the Devstack virtual machine failed 

### ISSUE THREAD

**Issue by gammoudiisoumaya** [openedx-unsupported/configuration#2037]
hello !
i have problem when i use to install the Open edX Developer Stack
at the first I had problem with the virtualbox version :
GuestAdditions versions on your host (4.3.28) and guest (4.3.16) do not match
so i install the virtualbox 4.3.16 but now i have new problem :
==> default: stdin: is not a tty
==> default:  [WARNING]: It is unneccessary to use '{{' in loops, leave variables in loop
==> default: expressions bare.

**Comment by e0d** [comment]
There is not enough information to help you here.  The warnings you paste
are likely not fatal.  Please provide information about what is not working.

For example can you ssh into the box using > vagrant ssh?

Ed

**Comment by gammoudiisoumaya** [comment]
yes  I can connect when i use vagrant ssh but when i run the following command 
"paver devstack lms" 
i got :
"Build failed: Unknown task: devstack" 

soumaya@ubuntu:~$ cd devstack/
soumaya@ubuntu:~/devstack$ sudo vagrant ssh
[sudo] password for soumaya: 
Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64)
- Documentation:  https://help.ubuntu.com/
  New release '14.04.1 LTS' available.
  Run 'do-release-upgrade' to upgrade to it.

---
-         _ __  __                                                *
-   _   _| |\ \/ /                                                *
- / -_) _` | >  <                                                 *
- _**\**,_|/_/_\                                                *
-                                                                 *
-  Instructions and troubleshooting:                              *
-  https://github.com/edx/configuration/wiki/edX-Developer-Stack  *
  *******************************************************************
  Last login: Sat May 23 11:59:55 2015 from 10.0.2.2
  vagrant@precise64:~$ sudo su edxapp
  edxapp@precise64:~/edx-platform$ paver devstack lms
  Build failed: Unknown task: devstack
  edxapp@precise64:~/edx-platform$ paver devstack lms --fast
  Build failed: Unknown task: devstack

**Comment by e0d** [comment]
You are simply in the wrong directory.  Paver expects to  be run from /edx/app/edxapp/edx-platform.  The instructions suggest that sourcing the env script will update your working directory, but that is clearly not working and I'd argue a bad idea any way.

Ed.

## 

Edward Zarecor
e0d@edx.org
e0d on github
