### ISSUE TITLE
Error on accessing profile or dashboard

### ISSUE THREAD

**Issue by shubhdev** [openedx-unsupported/configuration#2038]
**Note: If there is anyone who has successfully installed devstack on windows, please tell me as I need help desperately.This is my first time using open-edx,vagrant and the first time i am trying to contribute to an open-source project.**
After a lot of issues, i have finally been able to run LMS on devstack.I am using vagrant with VM Box on Windows 8.1 as the host OS.
The default home page is shown successfully, but on login the server throws an error
`(1054, "Unknown column 'course_modes_coursemode.sku' in 'field list'").`
However the login is successful, as can be seen on the server output in the cmd. Also on pressing the back button this is what is shown.
![image](https://cloud.githubusercontent.com/assets/8546935/7810903/bf9bdcec-03c3-11e5-8384-16592ad1d56e.png)
As it can be seen, the staff login was successful.
![image](https://cloud.githubusercontent.com/assets/8546935/7810953/102f3cee-03c4-11e5-935b-227ea439711e.png)
On trying to access "Discussion",the following database error is thrown:
`Exception Value: (1146, "Table 'edxapp.course_groups_coursecohortssettings' doesn't exist")`
On trying to access the profile, the error is:
`Exception Type:  UserAPIInternalError
Exception Value:    
An unexpected error occurred when calling 'get_account_settings' with arguments '(<User: staff>, u'staff')' and keyword arguments '{}': DatabaseError(1054, "Unknown column 'auth_userprofile.bio' in 'field list'")`

Its clear that all are database errors.I should also mention that i had to run mongod manually using the following command: `sudo mongod --config /etc/mongod.conf`

I have to tell you though, that my installation process was not at all smooth, and i did some workarounds to overcome the errors during provisioning.Is it possible that provisioning error might have caused the DB error? Can anyone post the complete log of a successful provisioning.
Please help me resolve this issue.

**Comment by feanil** [comment]
@shubhdev the errors you are seeing seem to be related to migrations you have not run.  The models are trying to use tables and colums that don't exist.

**Comment by shubhdev** [comment]
Sorry but i am completely unfamiliar with mongodb. How do i run these said migrations? When do i need to run them(as it was not mentioned in the installation process).

**Comment by feanil** [comment]
The developer docs here: https://github.com/edx/configuration/wiki/edX-Developer-Stack show you how to manage your devstack and if you search for database migrations, it will show it how to run those as well.  FYI, these are not mongo migrations, the lms uses both a mongo and mysql database and these are mysql migrations managed through 'South' for Django.
