### ISSUE TITLE
Max retries error in discussion service

### ISSUE THREAD

**Issue by rhndg** [openedx-unsupported/configuration#2048]
I am running devstack using vagrant on Vm box with windows 8.1 as the host.
on trying to use the discussion service on lms i get the following error: `HTTPConnectionPool(host='localhost', port=18080): Max retries exceeded with url: /api/v1/users/4?complete=True&request_id=af7b958b-4509-40b0-9385-f101401b4e7a (Caused by <class 'socket.error'>: [Errno 111] Connection refused)`

![image](https://cloud.githubusercontent.com/assets/8816134/7829517/ba75ec1a-0460-11e5-9d15-1fb4996b95b0.png)

please help me resolve this error

**Comment by feanil** [comment]
@rhndg have you verified that the forums are actually running on your devstack?  It's failing to connect to them meaning that the service it is trying to connect to is not actually running.  You can find more info on how to run with devstack here: https://github.com/edx/configuration/wiki/edX-Developer-Stack and I suggest directing further questions to the edx-code mailing list which has a lot more people watching it, including others who may have run into the same problems.
