### ISSUE TITLE
Installing open-edx on Ubuntu 14.04 64-bit server

### ISSUE THREAD

**Issue by shubhdev** [openedx-unsupported/configuration#2073]
Hi, is there any verified method for installing open edx on a Ubuntu 14.04 server. Why do the official docs contain installation guide for 12.04 only?

**Comment by e0d** [comment]
We don't currently support 14.04, though we plan to and I  dont think it
would be a big effort.  If you would like to help realize 14.04 support you
can use the same install script and report any bugs you find.  Big extra
credit for also fixing them.  If you are interested I  can help you get
started.

**Comment by shubhdev** [comment]
I would love to, but i am running short on a deadline.I would love to do it as soon as i am free.

**Comment by clarkyu** [comment]
when try "sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,", shows "ERROR: debug is not a legal parameter in an Ansible task or handler".

**Comment by e0d** [comment]
This is most likely related to ansible not having been updated.  Make sure
you have activated the virtual environment and that you are running ansible
version ansible 1.9.1-edx.2.

Best,

Ed.

**Comment by clarkyu** [comment]
Task Failed: TASK: [common | update the ssh motd on Ubuntu]

**Comment by clarkyu** [comment]
thank you very much.

**Comment by e0d** [comment]
Where are you installing, this issue is usually related to non-aws install.  It's something I have a fix for, but want to know your environment.

**Comment by clarkyu** [comment]
actually, I'm install it onto aliyun in Hongkong, which is powered by Alibaba.

**Comment by clarkyu** [comment]
actually, I'm installing it onto aliyun in Hongkong, which is powered by Alibaba.

**Comment by clarkyu** [comment]
actually, I'm install it onto aliyun in Hong Kong, which is powered by Alibaba.

**Comment by clarkyu** [comment]
actually, I'm installing it onto aliyun in Hong Kong, which is powered by Alibaba.

**Comment by clarkyu** [comment]
a alibaba cloud service, similar to AWS.

**Comment by e0d** [comment]
https://github.com/edx/configuration/compare/e0d/docker-latest?expand=1

That is a big, incomplete PR, but look at the changes to  playbooks/roles/common/tasks/main.yml.

The idea is to pull this out of common as it's AWS specific in order to support more platforms more easily.  For now, you would need to remove this lines from your local version.

**Comment by clarkyu** [comment]
I removed all SSH lines from main.yml. For now, it works well. You're really appreciated!

**Comment by clarkyu** [comment]
Task Failed: TASK: [edxapp | code sandbox | use libblas for 3gf]

**Comment by jyotichauhan** [comment]
Find the file: 

```
  /var/tmp/configuration/playbooks/roles/edxapp/tasks/python_sandbox_env.yml
```

Change this:

command: update-alternatives –set libblas.so.3gf /usr/lib/libblas/libblas.so.3gf

to:

command: update-alternatives –set libblas.so.3 /usr/lib/libblas/libblas.so.3

and this:

command: update-alternatives –set liblapack.so.3gf /usr/lib/lapack/liblapack.so.3gf

to:

command: update-alternatives –set liblapack.so.3 /usr/lib/lapack/liblapack.so.3

**Comment by sbalde** [comment]
Hello Guy,

I'm trying to install open-edx on Ubuntu 14.04 64bit. Unfortunately, once the install reach the [edxapp | restart edxapp_workers] TASK, it doesn't go further.

TASK: [edxapp | import courses including static data] *************************
skipping: [localhost] => (item=EDXAPP_XML_COURSES)

TASK: [edxapp | delete courses that were fully imported] **********************
skipping: [localhost] => (item=EDXAPP_XML_COURSES)

TASK: [edxapp | create an archive of course data and course static dirs] ******
skipping: [localhost]

TASK: [edxapp | upload archive to s3] *****************************************
skipping: [localhost]

TASK: [edxapp | remove archive from disk] *************************************
skipping: [localhost]

TASK: [edxapp | update supervisor configuration] ******************************
changed: [localhost]

TASK: [edxapp | ensure edxapp has started] ************************************
skipping: [localhost] => (item=lms)
skipping: [localhost] => (item=cms)

TASK: [edxapp | ensure edxapp_workers has started] ****************************
ok: [localhost] => (item={'queue': 'low', 'service_variant': 'cms', 'monitor': True, 'concurrency': 3})
ok: [localhost] => (item={'queue': 'default', 'service_variant': 'cms', 'monitor': True, 'concurrency': 4})
ok: [localhost] => (item={'queue': 'high', 'service_variant': 'cms', 'monitor': True, 'concurrency': 1})
ok: [localhost] => (item={'queue': 'low', 'service_variant': 'lms', 'monitor': True, 'concurrency': 1})
ok: [localhost] => (item={'queue': 'default', 'service_variant': 'lms', 'monitor': True, 'concurrency': 3})
ok: [localhost] => (item={'queue': 'high', 'service_variant': 'lms', 'monitor': True, 'concurrency': 4})
ok: [localhost] => (item={'queue': 'high_mem', 'service_variant': 'lms', 'monitor': False, 'concurrency': 2, 'max_tasks_per_child': 1})

TASK: [edxapp | create symlinks from the venv bin dir] ************************
changed: [localhost] => (item=python)
changed: [localhost] => (item=pip)
changed: [localhost] => (item=django-admin.py)

TASK: [edxapp | create symlinks from the repo dir] ****************************
changed: [localhost] => (item=manage.py)

TASK: [edxapp | remove read-only ssh key] *************************************
skipping: [localhost]

TASK: [edxapp | get instance information] *************************************
skipping: [localhost]

TASK: [edxapp | tag instance with edx_platform version] ***********************
skipping: [localhost]

TASK: [edxapp | tag instance  with edxapp theme version] **********************
skipping: [localhost]

TASK: [edxapp | set_fact edxapp_installed=true] *******************************
ok: [localhost]

TASK: [edxapp | restart edxapp] ***********************************************
skipping: [localhost] => (item=lms)
skipping: [localhost] => (item=cms)

TASK: [edxapp | restart edxapp_workers] ***************************************
changed: [localhost] => (item={'queue': 'low', 'service_variant': 'cms', 'monitor': True, 'concurrency': 3})
changed: [localhost] => (item={'queue': 'default', 'service_variant': 'cms', 'monitor': True, 'concurrency': 4})

It seems to be hung at this point.

Does anyone ever had such issue?

Thanks in advance for your help

**Comment by potato70** [comment]
@e0d  i am installing edx on ubuntu 14.04 and i would really appreciate your help, when i try installing edx cypress edition by 

export OPENEDX_RELEASE=named-release/cypress
wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash

i get the following error :

TASK: [edx_ansible | git checkout edx_ansible repo into edx_ansible_code_dir] **\* 
failed: [localhost] => {"failed": true}
msg: Failed to checkout release

FATAL: all hosts have already failed -- aborting

Please advise me what to do?! 

much appreciated.

**Comment by e0d** [comment]
Hmm, we don't fully support 14.04, but there are some related PRs and the changes are not too invasive.

Are you altering the script locally?  Because if you look at:

https://raw.githubusercontent.com/edx/configuration/named-release/cypress/util/install/sandbox.sh

You will notice that the script should exit if you are not on 12.04.

Either way, the issue seems to be that the OPENEDX_RELEASE variable isn't available in the script and you are falling through to using the release branch.  You need to figure out why that's happening.

I've just downloaded the script to a 14.04 docker container, removed the check, exported OPENEDX_RELEASE and things are working as expected.

**Comment by fhiggins** [comment]
@e0d 

I'm trying to set up edX on an Ubuntu 14.04 system inside my LAN to learn it before trying anything on AWS.
I followed the recommended modifications on this page and it took me pretty far, but not all the way.
I would be happy to forward a log file, if it helps your testing for 14.04 - if there exists a log file.
- Created an edX directory off of my home path.
- Executed a bash shell as superuser from _my home path_/edX.
  `sudo bash`
- Grabbed the cypress release to get the sandbox.sh to _my home path_/edX.

```
export OPENEDX_RELEASE=named-release/cypress
wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh
```
- Edited sandbox.sh to change 12.04 to 14.04 (as above).
- Ran sandbox.sh script.
  Failure with "3gf" files as above - made corrections as above.
- Cut the two commands below out of sandbox.sh to run by hand.

```
export   EXTRA_VARS="-e edx_platform_version=$OPENEDX_RELEASE \
    -e certs_version=$OPENEDX_RELEASE \
    -e forum_version=$OPENEDX_RELEASE \
    -e xqueue_version=$OPENEDX_RELEASE \
  "
cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost," $EXTRA_VARS
```
- Ran for quite some time (over 2 hours), finally:

```
TASK: [aws | update the ssh motd on Ubuntu] *********************************** 
changed: [localhost] => (item=/etc/update-motd.d/10-help-text)
failed: [localhost] => (item=/usr/share/landscape/landscape-sysinfo.wrapper) => {"failed": true, "item": "/usr/share/landscape/landscape-sysinfo.wrapper", "path": "/usr/share/landscape/landscape-sysinfo.wrapper", "state": "absent"}
msg: file (/usr/share/landscape/landscape-sysinfo.wrapper) is absent, cannot continue
...
changed: [localhost] => (item=/etc/update-motd.d/91-release-upgrade)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @<my home path>/edx_sandbox.retry

localhost                  : ok=533  changed=278  unreachable=0    failed=1   
```

By the way, what does the following line mean:
`to retry, use: --limit @<my home path>/edx_sandbox.retry`

Finally, are there any instructions for un-installing when I want to move to another machine. I'm new with using VM's so any useful links are appreciated.
Thanks.

**Comment by delamux** [comment]
Hello, I have a VPS in strato, is not possible installa ubuntu 12.04 I have 14.04 and I have this error:

>  [edxapp | code sandbox | (bootstrap) load code sandbox profile] ********\* 
> failed: [localhost] => {"changed": true, "cmd": ["apparmor_parser", "-r", "/etc/apparmor.d/code.sandbox"], "delta": "0:00:00.001981", "end": "2016-09-01 14:45:06.547516", "rc": 1, "start": "2016-09-01 14:45:06.545535", "warnings": []}
> stderr: Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
> Use --subdomainfs to override.TASK:

**Comment by deepak-vyas** [comment]
hi,
Ihave an error,
please help me out 
root@jumpbox2:/# ansible-playbook -c local ./edx/app/edx_ansible/edx_ansible/playbooks/edx_sandbox.yml -i "jumpbox"
ERROR: Unable to find an inventory file, specify one with -i ?

**Comment by arbabnazar** [comment]
@deepak-vyas can you try that:

```
root@jumpbox2:/# ansible-playbook -c local ./edx/app/edx_ansible/edx_ansible/playbooks/edx_sandbox.yml -i "127.0.0.1,"
```
