### ISSUE TITLE
Install fails - git-core/ppa - failed to fetch PPA information

### ISSUE THREAD

**Issue by fisharebest** [openedx-unsupported/configuration#2079]
I am having problems installing edx (although I have installed it succesfully many times before).

Adding `ansible-playbook -vvvv` gives the following:

```
TASK: [common | Add git apt repository] ***************************************
<localhost> REMOTE_MODULE apt_repository_1.8 repo="ppa:git-core/ppa" validate_certs=no
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1433413805.25-220204289028273 && echo $HOME/.ansible/tmp/ansible-tmp-1433413805.25-220204289028273']
<localhost> PUT /tmp/tmpNpZrQP TO /home/ubuntu/.ansible/tmp/ansible-tmp-1433413805.25-220204289028273/apt_repository_1.8
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=jawfykavhqfelylhiexgporhauyvvsdk] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-jawfykavhqfelylhiexgporhauyvvsdk; /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1433413805.25-220204289028273/apt_repository_1.8; rm -rf /home/ubuntu/.ansible/tmp/ansible-tmp-1433413805.25-220204289028273/ >/dev/null 2>&1'"'"''
failed: [localhost] => {"failed": true, "item": ""}
msg: failed to fetch PPA information, error was: Request failed: <urlopen error [Errno 111] Connection refused>
```

It would seem to be failing to install the PPA.  However, I can install this manually with no problem using `sudo apt-add-repository ppa:git-core/ppa`.

The only thing different between this server and my previous (successful) installs is that this one is behind a firewall, and needs to access the internet via a proxy (`http_proxy` and `https_proxy` are defined in `/etc/environment`.).  Clearly parts of the install script are using the proxy (since the earlier `pip install` works).

Do I need to specify the proxy settings anywhere else?  Any other suggestions?

**Comment by feanil** [comment]
What version of ansible are you using, it looks like this is using
apt_repository from 1.8.  As far as I know there is nothing in ansible
logic that requires proxies.  However if the machine that is trying to do
this is behind a firewall and you have proxies setup for yourself, you
should make sure to set them up for ansible as well.

**Comment by fisharebest** [comment]
> What version of ansible are you using

I have a clean install of Ubuntu 12.04, and am running the "one line" installer.

```
$ ansible --version
ansible 1.5.5
```

> you should make sure to set them up for ansible as well

Not sure how I do this.  I found https://docs.ansible.com/playbooks_environment.html but it describes editing the application-configuration files, and I'm out my depth with those.

**Comment by fisharebest** [comment]
I can confirm that it is a proxy issue - I moved the server from our internal network to the DMZ network, and things are OK.
