### ISSUE TITLE
Error in task "git add apt repository"

### ISSUE THREAD

**Issue by shubhdev** [openedx-unsupported/configuration#2086]
Hi, I am trying to install open edx on Ubuntu 12.04 server.
On running the command : 

```
sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost," --limit @/home/cs1130258/edx_sandbox.retry
```

It gives the following error: 

```
TASK: [common | Add git apt repository] *************************************** 
failed: [localhost] => {"failed": true, "item": ""}
msg: failed to fetch PPA information, error was: Request failed: <urlopen error timed out>

FATAL: all hosts have already failed -- aborting
```

I am behind a proxy, and i know this looks like a connection issue. But i have set the correct environment variables, so i dont know whats causing the issue.
So, based on the task description, I followed this link : http://stackoverflow.com/questions/19109542/installing-latest-version-of-git-in-ubuntu
And was able to do it outside of ansible. So i commented this task in playbooks/roles/tasks/main.yml
and the on running the ansible command again, I proceeded forward only to get stuck at

```
TASK: [mongo | add the mongodb signing key] *********************************** 
failed: [localhost] => {"failed": true, "item": "", "traceback": "Traceback (most recent call last):\n  File \"/home/cs1130258/.ansible/tmp/ansible-tmp-1434018924.96-171722615493809/apt_key\", line 144, in download_key\n    return rsp.read()\nAttributeError: 'NoneType' object has no attribute 'read'\n"}
msg: error getting key id from url

FATAL: all hosts have already failed -- aborting
```

Any ideas on what might be causing this?
Can this error be related to the first error?

**Comment by feanil** [comment]
This looks like a firewall issue with the server you're trying to setup open-edx on.  Have you verified that you can manually add PPAs to this server?

**Comment by shubhdev** [comment]
Yes, I can manually add them. Actually,I was able to complete the installation. I faced a bunch of similar errors, completed them manually,and then removed the tasks from ansible playbooks.

**Comment by feanil** [comment]
Were the task that you replaced all related to network access?

**Comment by shubhdev** [comment]
yes.So,I guess it must be some problem with my machine.

**Comment by vinkle** [comment]
I am facing the same problem. Can you please tell me how you have perform the tasks manually ..

**Comment by shubhdev** [comment]
These are all specific to what I had to do.They might not work for you.
So,the task is shown on the console like : 

```
TASK[some_name|another_name]
```

So from the playbooks directory(you must already be there while running the ansible command) go into the roles directory.  find the directory "some_name" and in it go to tasks->main.yml(sometimes the commands were in deploy.yml). In main.yml find the task with name "another_name". see what it does, google how to do that, for example i googled: "how to add apt repository". If you are able to run them manually,run them and then comment them out from main.yml. 

##### NOTE :

  sometimes there will be variables in the command like {var_name}. Their values can be found in playbooks/roles/some_name/defaults.

**Comment by vinkle** [comment]
Thank you so much shubhdev.

**Comment by walabus** [comment]
VM behind a proxy. I resolved it with the following 2 steps:

Set up proxy environment variables

export http_proxy=http://<user>:<pwd>@<proxy_url>:<port_number>
export https_proxy=http://<user>:<pwd>@<proxy_url>:<port_number>

Run the add-apt-repository command again as sudo with the -E option that preserves the user environment:

sudo -E add-apt-repository ppa:git-core/ppa
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

Then rerun: sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"

Resources:
http://stackoverflow.com/questions/19109542/installing-latest-version-of-git-in-ubuntu
http://docs.mongodb.org/manual/tutorial/install-mongodb-on-debian/
