### ISSUE TITLE
TASK: [xqwatcher | restart xqwatcher] ERROR

### ISSUE THREAD

**Issue by AlbertBrian** [openedx-unsupported/configuration#2096]
Fresh Ubuntu 12.04 & Ubuntu 14.04 same one error, I collected logs and checks as much as possible.

TASK: [xqwatcher | restart xqwatcher] *****************************************
failed: [localhost] => {"failed": true}
msg: xqwatcher: stopped
## xqwatcher: ERROR (abnormal termination)

LOGS
- /edx/var/log/xqwatcher/supervisord.log

First time error:
2015-06-14 15:09:21,427 WARN No file matches via include "/edx/app/xqwatcher/supervisor/conf.d/*.conf"
2015-06-14 15:09:21,433 INFO RPC interface 'supervisor' initialized
2015-06-14 15:09:21,433 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2015-06-14 15:09:21,433 INFO RPC interface 'supervisor' initialized
2015-06-14 15:09:21,433 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-06-14 15:09:21,433 INFO supervisord started with pid 6025

Everytime error:
2015-06-14 15:09:30,044 INFO spawned: 'xqwatcher' with pid 6302
2015-06-14 15:09:30,094 INFO exited: xqwatcher (exit status 0; not expected)
2015-06-14 15:09:30,312 INFO spawned: 'xqwatcher' with pid 6324
2015-06-14 15:09:30,357 INFO exited: xqwatcher (exit status 0; not expected)
2015-06-14 15:09:32,362 INFO spawned: 'xqwatcher' with pid 6329
2015-06-14 15:09:32,402 INFO exited: xqwatcher (exit status 0; not expected)
2015-06-14 15:09:35,406 INFO spawned: 'xqwatcher' with pid 6332
2015-06-14 15:09:35,453 INFO exited: xqwatcher (exit status 0; not expected)
2015-06-14 15:09:36,454 INFO gave up: xqwatcher entered FATAL state, too many start retries too quickly
- /edx/var/log/xqwatcher/xqwatcher-stdout.log
  No xqueue watchers configured 
  No xqueue watchers configured 
  No xqueue watchers configured 
  No xqueue watchers configured 
  ....
  ---------------------------------------

Check command line:
# sudo /edx/app/xqwatcher/venvs/supervisor/bin/supervisorctl -c /edx/app/xqwatcher/supervisor/supervisord.conf status xqwatcher

xqwatcher                        FATAL     Exited too quickly (process log may have details)
# sudo /edx/app/xqwatcher/venvs/supervisor/bin/supervisorctl -c /edx/app/xqwatcher/supervisor/supervisord.conf restart xqwatcher

xqwatcher: ERROR (not running)
xqwatcher: ERROR (abnormal termination)
# sudo /edx/app/xqwatcher/venvs/supervisor/bin/supervisorctl -c /edx/app/xqwatcher/supervisor/supervisord.conf start xqwatcher
## xqwatcher: ERROR (abnormal termination)

Here I used no specific branch and head, ansible version comes 1.9.1 with edx, I am not sure what the branch was, please tell me if you know:

cd /var/tmp
git clone https://github.com/edx/configuration.git
cd /var/tmp/configuration
sudo pip install -r requirements.txt

**Comment by AlbertBrian** [comment]
I have found something which I am not sure if it is the issue xqwatcher can not start and restart. But there is an issue of 'environment' in /var/tmp/configuration/playbooks/roles/xqwatcher/templates/edx/app/supervisor/conf.d/xqwatcher.conf.j2. 

For example, look at 'enviroment' in /var/tmp/configuration/playbooks/roles/xqueue/templates/xqueue.conf.j2:
environment={% if COMMON_ENABLE_NEWRELIC_APP %}NEW_RELIC_APP_NAME={{ XQUEUE_NEWRELIC_APPNAME }},NEW_RELIC_LICENSE_KEY={{ NEWRELIC_LICENSE_KEY }},{% endif -%}PID=/var/tmp/xqueue.pid,PORT={{ xqueue_gunicorn_port }},ADDRESS={{ xqueue_gunicorn_host }},LANG={{ XQUEUE_LANG }},DJANGO_SETTINGS_MODULE=xqueue.aws_settings,SERVICE_VARIANT="xqueue"

However, 'environment' in /var/tmp/configuration/playbooks/roles/xqwatcher/templates/edx/app/supervisor/conf.d/xqwatcher.conf.j2:
environment={% if COMMON_ENABLE_NEWRELIC_APP %}NEW_RELIC_APP_NAME={{ XQWATCHER_NEWRELIC_APPNAME }},NEW_RELIC_LICENSE_KEY={{ NEWRELIC_LICENSE_KEY }},{% endif -%}

It misses something after {% endif -%}, results a wrong line in /edx/app/xqwatcher/supervisor/conf.d/xqwatcher.conf
environment=killasgroup=true

That should be: 
environment=xxx
killasgroup=true

**Comment by AlbertBrian** [comment]
@singingwolfboy , @feanil : may you take a look? someone also has got this issue. And in /edx/app/xqwatcher/supervisor/conf.d/xqwatcher.conf, there is a line: environment=killasgroup=true

https://groups.google.com/forum/?#!msg/edx-code/hCXhZQt3Mvw/Qg4swyWziGsJ

**Comment by AlbertBrian** [comment]
We have discussion here: https://groups.google.com/forum/#!topic/edx-code/D22R1kRUqKE

**Comment by fisharebest** [comment]
Is there a way to tell the installer to ignore this error, or to prevent it installing the xqwatcher module (which I gather is not essential).

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
