### ISSUE TITLE
Server error after "Site_Name" update

### ISSUE THREAD

**Issue by farazmir** [openedx-unsupported/configuration#2107]
Hi, I modified lms_env_conf.json and changed "site_name": "localhost" to "site_name": "mysite.com" and immediately got the "Server error" page. Then i reverted the change and restarted edxapp: and even rebooted the server but i still get the Server error page.

What am I doing wrong? how can I bring it back to life?

Are lms_env_conf.json and cms_env_conf.json the right places to setup environment variables?

Thanks

**Comment by feanil** [comment]
Have you looked at the logs to see what the issue might be? The logs will be under `/edx/var/log/lms/edx.log`

**Comment by farazmir** [comment]
this message keeps repeating in my log
Jun 22 10:32:34 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  1155] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 22 10:32:37 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  1180] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 22 10:32:39 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  1228] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 22 10:32:42 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  1354] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 22 10:32:45 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  1375] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 22 10:32:47 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  1414] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 22 10:32:50 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  1448] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 22 10:32:53 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  1563] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 22 10:32:55 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  1588] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 22 10:32:58 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  1624] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 22 10:33:01 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  1736] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 22 10:33:04 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  2140] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125

**Comment by feanil** [comment]
That message is just at startup, seems like the app is not starting up correctly.  Take a look in `/edx/var/log/supervisor/lms-stderr.log`

**Comment by farazmir** [comment]
I dont see lms-stderr.log in that folder

**Comment by farazmir** [comment]
@feanil previously posted log is incomplete as I noticed it overflowed.

following is some more relevant information in the error log:

```
Jun 23 12:41:51 edxserver [service_variant=lms][celery.redirected][env:sandbox] WARNING [edxserver  1784] [log.py:282] - /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning:
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
Jun 23 12:41:51 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1791] [consumer.py:479] - Connected to amqp://celery:**@127.0.0.1:5672//
Jun 23 12:41:51 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1784] [consumer.py:479] - Connected to amqp://celery:**@127.0.0.1:5672//
Jun 23 12:41:51 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1782] [consumer.py:479] - Connected to amqp://celery:**@127.0.0.1:5672//
Jun 23 12:41:51 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1794] [consumer.py:479] - Connected to amqp://celery:**@127.0.0.1:5672//
Jun 23 12:41:51 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1791] [consumer.py:567] - mingle: searching for neighbors
Jun 23 12:41:51 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1794] [consumer.py:567] - mingle: searching for neighbors
Jun 23 12:41:51 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1784] [consumer.py:567] - mingle: searching for neighbors
Jun 23 12:41:51 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1782] [consumer.py:567] - mingle: searching for neighbors
Jun 23 12:41:52 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  2619] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 23 12:41:52 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1791] [consumer.py:585] - mingle: all alone
Jun 23 12:41:52 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1794] [consumer.py:585] - mingle: all alone
Jun 23 12:41:52 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1782] [consumer.py:585] - mingle: all alone
Jun 23 12:41:52 edxserver [service_variant=lms][celery.worker.consumer][env:sandbox] INFO [edxserver  1784] [consumer.py:585] - mingle: all alone
Jun 23 12:41:52 edxserver [service_variant=lms][celery.redirected][env:sandbox] WARNING [edxserver  1791] [log.py:282] - celery@edx.lms.core.low.edxserver ready.
Jun 23 12:41:52 edxserver [service_variant=lms][celery.redirected][env:sandbox] WARNING [edxserver  1794] [log.py:282] - celery@edx.lms.core.high.edxserver ready.
Jun 23 12:41:52 edxserver [service_variant=lms][celery.redirected][env:sandbox] WARNING [edxserver  1782] [log.py:282] - celery@edx.lms.core.high_mem.edxserver ready.
Jun 23 12:41:52 edxserver [service_variant=lms][celery.redirected][env:sandbox] WARNING [edxserver  1784] [log.py:282] - celery@edx.lms.core.default.edxserver ready.
Jun 23 12:41:55 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  2952] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
```

**Comment by farazmir** [comment]
@feanil what is the right way to update lms.env.json and cms,env,json?

I edited and rebooted the server. Is that how its done?

following are the logs i got after browsing the site while only LMS and CMS are running doing so

```
root@edxserver:/edx/app/edxapp/edx-platform# /edx/bin/supervisorctl -c /edx/etc/supervisord.conf stop discern discern_celery \
>   forum ora ora_celery xqueue xqueue_consumer xserver edxapp_worker:

root@edxserver:/edx/app/edxapp/edx-platform# tail -f /edx/var/log/{lms,cms,nginx}/*log

==> /edx/var/log/nginx/access.log <==
- - 10.1.xxx.xx - - [24/Jun/2015:09:39:40 -0700]  "-" 400 0 0.000 "-" "-"

==> /edx/var/log/lms/edx.log <==
Jun 24 09:39:43 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  22878] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 24 09:39:47 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  22894] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 24 09:39:50 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  22910] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125
Jun 24 09:39:54 edxserver [service_variant=lms][dd.dogapi][env:sandbox] INFO [edxserver  22928] [dog_stats_api.py:66] - Initializing dog api to use statsd: localhost, 8125

==> /edx/var/log/nginx/error.log <==
2015/06/24 09:39:54 [error] 24903#0: *47 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.xxx.xx, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "edx.mycompany.com"

==> /edx/var/log/nginx/access.log <==
- - 10.1.xxx.xx - - [24/Jun/2015:09:39:54 -0700]  "GET / HTTP/1.1" 502 1555 0.001 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"
- - 10.1.xxx.xx - - [24/Jun/2015:09:39:54 -0700]  "GET /favicon.ico HTTP/1.1" 200 34894 0.000 "http://edx.mycompany.com/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"

```

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
