### ISSUE TITLE
edx LMS oauth2 authentication not working

### ISSUE THREAD

**Issue by sukla80** [openedx-unsupported/configuration#2114]
When I am trying to run edxinsight urls which gets authenticated from LMS ( trusted client created & settings are done on edx anlytics dashboard's local.py (have put in base.py also)
SOCIAL_AUTH_EDX_OIDC_KEY = '38a1a88fc95c582d26f0'
SOCIAL_AUTH_EDX_OIDC_SECRET = '5505a094af996cf5a6de56989a1e9424462f24ba'
SOCIAL_AUTH_EDX_OIDC_URL_ROOT = 'http://localhost:80/oauth2'
SOCIAL_AUTH_EDX_OIDC_ID_TOKEN_DECRYPTION_KEY = SOCIAL_AUTH_EDX_OIDC_SECRET
ENABLE_AUTO_AUTH = False
ENABLE_COURSE_PERMISSIONS = True
 It gets connected to LMS with url localhost:/oauth2/authorize/?nonce=...........
but says page not found.
Please tell me what is the problem

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
