### ISSUE TITLE
"This comment needs updating"-- what is the recommend way to do a production deploy of Open edX?

### ISSUE THREAD

**Issue by marisawallace** [openedx-unsupported/configuration#2120]
From https://github.com/edx/configuration/wiki/edX-Full-Stack:

> We do not recommend using fullstack for your production installation of edX. (this comment needs updating)

If you do not recommend using the Full Stack for a production installation, what do you recommend? I am currently in the process of setting up a production instance of Open edX.

**Comment by paultannenbaum** [comment]
I too would like to know the recommended installation process for a production instance

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
