### ISSUE TITLE
Manuel installation error on Ubuntu 12.04 

### ISSUE THREAD

**Issue by eemirtekin** [openedx-unsupported/configuration#2123]
TASK: [edxapp | install python base-requirements] ****************************\* 
failed: [localhost] => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i https://pypi.python.org/simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt ", "delta": "0:01:20.812623", "end": "2015-07-01 08:33:44.796749", "item": "", "rc": 1, "start": "2015-07-01 08:32:23.984126"}
stdout: You are using pip version 6.0.8, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DEPRECATION: --use-mirrors has been deprecated and will be removed in the future. Explicit uses of --index-url and/or --extra-index-url is suggested.
Collecting beautifulsoup4==4.1.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 7))
  Downloading beautifulsoup4-4.1.3.tar.gz (58kB)
Collecting beautifulsoup==3.2.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 8))
  Downloading BeautifulSoup-3.2.1.tar.gz
Collecting bleach==1.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 9))
  Downloading bleach-1.4.tar.gz
Collecting html5lib==0.999 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 10))
  Downloading html5lib-0.999.tar.gz (885kB)
Collecting boto==2.32.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 11))
  Downloading boto-2.32.1-py2.py3-none-any.whl (1.2MB)
Collecting celery==3.1.18 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 12))
  Downloading celery-3.1.18-py2.py3-none-any.whl (515kB)
Collecting cssselect==0.9.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 13))
  Downloading cssselect-0.9.1.tar.gz
Collecting dealer==2.0.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 14))
  Downloading dealer-2.0.4-py2.py3-none-any.whl
Collecting defusedxml==0.4.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 15))
  Downloading defusedxml-0.4.1.tar.gz (48kB)
Collecting distribute<0.7,>=0.6.28 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 16))
  Downloading distribute-0.6.49.tar.gz (724kB)
Collecting django-babel-underscore==0.1.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 17))
  Downloading django_babel_underscore-0.1.0-py2.py3-none-any.whl
Collecting django-celery==3.1.16 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 18))
  Downloading django_celery-3.1.16-py2-none-any.whl (65kB)
Collecting django-countries==3.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 19))
  Downloading django-countries-3.3.tar.gz (245kB)
Collecting django-extensions==1.2.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 20))
  Downloading django-extensions-1.2.5.tar.gz (285kB)
Collecting django-filter==0.6.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 21))
  Downloading django_filter-0.6-py2.py3-none-any.whl
Collecting django-followit==0.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 22))
  Downloading django-followit-0.0.3.tar.gz
    warning: manifest_maker: MANIFEST.in, line 5: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...
    warning: manifest_maker: MANIFEST.in, line 8: unknown action 'global'
    warning: manifest_maker: MANIFEST.in, line 13: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...
    warning: manifest_maker: MANIFEST.in, line 14: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...
Collecting django-keyedcache==1.4-6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 23))
  Downloading django-keyedcache-1.4-6.tar.gz
Collecting django-kombu==0.9.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 24))
  Downloading django-kombu-0.9.4.tar.gz
Collecting django-mako==0.1.5pre (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 25))
  Downloading django-mako-0.1.5pre.tar.gz
Collecting django-model-utils==1.4.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 26))
  Downloading django-model-utils-1.4.0.tar.gz
Collecting django-masquerade==0.1.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 27))
  Downloading django-masquerade-0.1.6.tar.gz (527kB)
Collecting django-mptt==0.5.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 28))
  Downloading django-mptt-0.5.5.tar.gz (76kB)
Collecting django-openid-auth==0.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 29))
  Downloading django-openid-auth_0.4.tar.gz (77kB)
Collecting django-robots==0.9.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 30))
  Downloading django-robots-0.9.1.tar.gz
Collecting django-sekizai==0.6.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 31))
  Downloading django-sekizai-0.6.1.tar.gz
Collecting django-ses==0.4.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 32))
  Downloading django-ses-0.4.1.tar.gz
Collecting django-simple-history==1.6.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 33))
  Downloading django_simple_history-1.6.1-py2.py3-none-any.whl
Collecting django-storages==1.1.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 34))
  Downloading django-storages-1.1.5.tar.gz
Collecting django-threaded-multihost==1.4-1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 35))
  Downloading django-threaded-multihost-1.4-1.tar.gz
    zip_safe flag not set; analyzing archive contents...
    Installed /tmp/pip-build-uUiMHW/django-threaded-multihost/setuptools_hg-0.4-py2.7.egg
Collecting django-method-override==0.1.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 36))
  Downloading django-method-override-0.1.0.tar.gz
Collecting djangorestframework==2.3.14 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 37))
  Downloading djangorestframework-2.3.14-py2.py3-none-any.whl (298kB)
Collecting django==1.4.20 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 38))
  Downloading Django-1.4.20.tar.gz (7.9MB)
Collecting elasticsearch==0.4.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 39))
  Downloading elasticsearch-0.4.5-py2.py3-none-any.whl (42kB)
Collecting facebook-sdk==0.4.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 40))
  Downloading facebook-sdk-0.4.0.tar.gz
Collecting feedparser==5.1.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 41))
  Downloading feedparser-5.1.3.tar.bz2 (202kB)
Collecting firebase-token-generator==1.3.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 42))
  Downloading firebase-token-generator-1.3.2.tar.gz
Collecting GitPython==0.3.2.RC1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 43))
  Downloading GitPython-0.3.2.RC1.tar.gz (313kB)
Collecting glob2==0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 44))
  Downloading glob2-0.3.tar.gz
Collecting gunicorn==0.17.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 45))
  Downloading gunicorn-0.17.4.tar.gz (372kB)
Collecting httpretty==0.8.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 46))
  Downloading httpretty-0.8.3.tar.gz (40kB)
Collecting lazy==1.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 47))
  Downloading lazy-1.1.zip
Collecting lxml==3.3.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 48))
  Downloading lxml-3.3.6.tar.gz (3.5MB)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.3.6.
    Building without Cython.
    Using build configuration of libxslt 1.1.26
    Building against libxml2/libxslt in the following directory: /usr/lib/x86_64-linux-gnu
Collecting mako==0.9.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 49))
  Downloading Mako-0.9.1.tar.gz (421kB)
Collecting Markdown==2.2.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 50))
  Downloading Markdown-2.2.1.tar.gz (260kB)
Collecting meliae==0.4.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 53))
  meliae is potentially insecure and unverifiable.
  Downloading https://launchpad.net/meliae/trunk/0.4/+download/meliae-0.4.0.tar.gz (64kB)
  Requested meliae==0.4.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 53)), but installing version None
Collecting mongoengine==0.7.10 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 54))
  Downloading mongoengine-0.7.10.tar.gz (98kB)
    0.7.10
Collecting networkx==1.7 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 55))
  Downloading networkx-1.7.tar.gz (728kB)
Collecting nltk==2.0.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 56))
  Downloading nltk-2.0.5.tar.gz (954kB)
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmp8a2xp7
    Now working in /tmp/tmp8a2xp7/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-uUiMHW/nltk
    /tmp/pip-build-uUiMHW/nltk/distribute-0.6.21-py2.7.egg
Collecting nose==1.3.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 57))
  Downloading nose-1.3.3.tar.gz (274kB)
Collecting oauthlib==0.7.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 58))
  Downloading oauthlib-0.7.2.tar.gz (106kB)
Collecting paramiko==1.9.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 59))
  Downloading paramiko-1.9.0.tar.gz (814kB)
Collecting path.py==7.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 60))
  Downloading path.py-7.2.zip
Collecting Pillow==2.7.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 61))
  Downloading Pillow-2.7.0.tar.gz (7.4MB)
Collecting polib==1.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 62))
  Downloading polib-1.0.3.tar.gz (149kB)
Collecting pycrypto>=2.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 63))
  Downloading pycrypto-2.6.1.tar.gz (446kB)
Collecting pygments==2.0.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 64))
  Downloading Pygments-2.0.1-py2-none-any.whl (672kB)
Collecting pygraphviz==1.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 65))
  Downloading pygraphviz-1.1.tar.gz (90kB)
    Trying pkg-config
    library_path=
    include_path=/usr/include/graphviz
Collecting PyJWT==1.0.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 66))
  Downloading PyJWT-1.0.1-py2.py3-none-any.whl
Collecting pymongo==2.7.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 67))
  Downloading pymongo-2.7.2.tar.gz (381kB)
Collecting pyparsing==2.0.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 68))
  Downloading pyparsing-2.0.1.tar.gz (1.1MB)
Collecting python-memcached==1.48 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 69))
  Downloading python-memcached-1.48.tar.gz (40kB)
Collecting python-openid==2.2.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 70))
  Downloading python-openid-2.2.5.tar.gz (301kB)
Collecting python-dateutil==2.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 71))
  Downloading python-dateutil-2.1.tar.gz (152kB)
Collecting python-social-auth==0.2.11 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 72))
  Downloading python_social_auth-0.2.11-py2-none-any.whl (264kB)
Collecting python-saml==2.1.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 73))
  Downloading python_saml-2.1.3-py2-none-any.whl (57kB)
Collecting pytz==2015.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 74))
  Downloading pytz-2015.2-py2.py3-none-any.whl (476kB)
Collecting pysrt==0.4.7 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 75))
  Downloading pysrt-0.4.7.tar.gz
Collecting PyYAML==3.10 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 76))
  Downloading PyYAML-3.10.tar.gz (241kB)
    skipping 'ext/_yaml.c' Cython extension (up-to-date)
Collecting requests==2.3.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 77))
  Downloading requests-2.3.0-py2.py3-none-any.whl (452kB)
Collecting requests-oauthlib==0.4.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 78))
  Downloading requests_oauthlib-0.4.1-py2.py3-none-any.whl
Collecting rfc6266==0.0.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 79))
  Downloading rfc6266-0.0.4.tar.gz
Collecting scipy==0.14.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 80))
  Downloading scipy-0.14.0.tar.gz (10.2MB)
Collecting Shapely==1.2.16 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 81))
  Downloading Shapely-1.2.16.tar.gz (96kB)
    /tmp/pip-build-uUiMHW/Shapely/setup.py:9: Warning: Failed to import distribute_setup, continuing without distribute.
      Warning)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'requires_external'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'metadata_version'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'requires_python'
      warnings.warn(msg)
Collecting singledispatch==3.4.0.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 82))
  Downloading singledispatch-3.4.0.2.tar.gz
Collecting sorl-thumbnail==11.12 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 83))
  Downloading sorl-thumbnail-11.12.tar.gz (46kB)
Collecting sortedcontainers==0.9.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 84))
  Downloading sortedcontainers-0.9.2.tar.gz
Collecting South==1.0.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 85))
  Downloading South-1.0.1.tar.gz (98kB)
Collecting stevedore==0.14.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 86))
  Downloading stevedore-0.14.1.tar.gz (357kB)
    Installed /tmp/pip-build-uUiMHW/stevedore/pbr-0.11.0-py2.7.egg
    [pbr] Processing SOURCES.txt
    warning: LocalManifestMaker: standard file '-c' not found
Collecting sure==1.2.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 87))
  Downloading sure-1.2.3.tar.gz
Collecting sympy==0.7.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 88))
  Downloading sympy-0.7.1.tar.gz (3.6MB)
    package init file 'sympy/assumptions/tests/__init__.py' not found (or not a regular file)
    package init file 'sympy/concrete/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/core/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/external/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/functions/combinatorial/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/functions/elementary/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/functions/special/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/galgebra/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/geometry/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/integrals/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/logic/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/matrices/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/ntheory/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/parsing/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/physics/quantum/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/physics/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/plotting/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/polys/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/printing/pretty/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/printing/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/series/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/simplify/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/slow_tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/solvers/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/statistics/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/tensor/tests/**init**.py' not found (or not a regular file)
    package init file 'sympy/utilities/tests/**init**.py' not found (or not a regular file)
Collecting xmltodict==0.4.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 89))
  Downloading xmltodict-0.4.1.tar.gz
Collecting django-ratelimit-backend==0.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 90))
  Downloading django-ratelimit-backend-0.6.tar.gz
Collecting unicodecsv==0.9.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 91))
  Downloading unicodecsv-0.9.4.tar.gz
Collecting django-require==1.0.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 92))
  Downloading django-require-1.0.6.tar.gz (7.5MB)
Collecting pyuca==1.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 93))
  Downloading pyuca-1.1.tar.gz (525kB)
Collecting reportlab==3.1.44 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 96))
  Downloading reportlab-3.1.44.tar.gz (1.9MB)
    ################################################
    #Attempting install of _rl_accel & pyHnj
    #extensions from '/tmp/pip-build-uUiMHW/reportlab/src/rl_addons/rl_accel'
    ################################################
    ################################################
    #Attempting install of _renderPM
    #extensions from '/tmp/pip-build-uUiMHW/reportlab/src/rl_addons/renderPM'
    will use package libart 2.3.12
    # installing with freetype version 21
    ################################################
    Downloading standard T1 font curves
    Finished download of standard T1 font curves
    ()
    ########## SUMMARY INFO #########
    ################################################
    #Attempting install of _rl_accel & pyHnj
    #extensions from '/tmp/pip-build-uUiMHW/reportlab/src/rl_addons/rl_accel'
    ################################################
    ################################################
    #Attempting install of _renderPM
    #extensions from '/tmp/pip-build-uUiMHW/reportlab/src/rl_addons/renderPM'
    will use package libart 2.3.12
    # installing with freetype version 21
    ################################################
    Downloading standard T1 font curves
    Finished download of standard T1 font curves
Collecting pdfminer==20140328 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 99))
  Downloading pdfminer-20140328.tar.gz (4.1MB)
Collecting watchdog==0.7.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 102))
  Downloading watchdog-0.7.1.tar.gz (83kB)
Collecting dogapi==1.2.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 105))
  Downloading dogapi-1.2.1.tar.gz
Collecting newrelic==2.46.0.37 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 106))
  Downloading newrelic-2.46.0.37.tar.gz (656kB)
Collecting sphinx==1.1.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 109))
  Downloading Sphinx-1.1.3.tar.gz (2.6MB)
Collecting sphinx-rtd-theme==0.1.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 110))
  Downloading sphinx_rtd_theme-0.1.5.tar.gz (210kB)
Collecting Babel==1.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 113))
  Downloading Babel-1.3.tar.gz (3.4MB)
Collecting transifex-client==0.10 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 114))
  Downloading transifex-client-0.10.tar.gz (68kB)
Collecting ipaddr==2.1.11 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 117))
  Downloading ipaddr-2.1.11.tar.gz
Collecting django-cors-headers==0.13 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 120))
  Downloading django-cors-headers-0.13.tar.gz
Collecting django-debug-toolbar==1.2.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 123))
  Downloading django_debug_toolbar-1.2.2-py2.py3-none-any.whl (202kB)
Collecting astroid==1.3.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 126))
  Downloading astroid-1.3.4-py2.py3-none-any.whl (174kB)
Collecting bok-choy==0.4.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 127))
  Downloading bok_choy-0.4.1.tar.gz (42kB)
Collecting chrono==1.0.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 128))
  Downloading chrono-1.0.2-py2.py3-none-any.whl
Collecting coverage==3.7 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 129))
  Downloading coverage-3.7.tar.gz (283kB)
Collecting ddt==0.8.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 130))
  Downloading ddt-0.8.0-py2.py3-none-any.whl
Collecting diff-cover==0.7.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 131))
  Downloading diff_cover-0.7.3.tar.gz
Collecting django-crum==0.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 132))
  Downloading django-crum-0.5.tar.gz
Collecting django-nose==1.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 133))
  Downloading django-nose-1.3.tar.gz
Collecting factory-boy==2.2.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 134))
  Downloading factory_boy-2.2.1.tar.gz (71kB)
Collecting flaky==2.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 135))
  Downloading flaky-2.0.3.tar.gz
Collecting freezegun==0.1.11 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 136))
  Downloading freezegun-0.1.11.tar.gz
Collecting lettuce==0.2.20 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 137))
  Downloading lettuce-0.2.20.tar.gz (54kB)
Collecting mock-django==0.6.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 138))
  Downloading mock-django-0.6.6.tar.gz
Collecting mock==1.0.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 139))
  Downloading mock-1.0.1.tar.gz (818kB)
Collecting nose-exclude (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 140))
  Downloading nose-exclude-0.3.0.tar.gz
Collecting nose-ignore-docstring (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 141))
  Downloading nose-ignore-docstring-0.2.tar.gz
Collecting nosexcover==1.0.7 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 142))
  Downloading nosexcover-1.0.7.tar.gz
Collecting pep8==1.5.7 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 143))
  Downloading pep8-1.5.7-py2.py3-none-any.whl
Collecting PyContracts==1.7.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 144))
  Downloading PyContracts-1.7.1.tar.gz (59kB)
Collecting pylint==1.4.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 145))
  Downloading pylint-1.4.2-py2.py3-none-any.whl (431kB)
Collecting python-subunit==0.0.16 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 146))
  Downloading python-subunit-0.0.16.tar.gz (82kB)
Collecting pyquery==1.2.9 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 147))
  Downloading pyquery-1.2.9.zip (45kB)
Collecting radon==1.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 148))
  Downloading radon-1.2-py2.py3-none-any.whl
Collecting rednose==0.4.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 149))
  Downloading rednose-0.4.3.tar.gz
Collecting selenium==2.42.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 150))
  Downloading selenium-2.42.1.tar.gz (2.5MB)
Collecting splinter==0.5.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 151))
  Downloading splinter-0.5.4.tar.gz
Collecting testtools==0.9.34 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 152))
  Downloading testtools-0.9.34.tar.gz (195kB)
Collecting analytics-python==0.4.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 155))
  Downloading analytics-python-0.4.4.tar.gz
Collecting mailsnake==1.6.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 158))
  Downloading mailsnake-1.6.2.tar.gz
    file mailsnake.py (for module mailsnake) not found
Collecting jsonfield==1.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 159))
  Downloading jsonfield-1.0.3.tar.gz
Collecting six (from bleach==1.4->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 9))
  Downloading six-1.9.0-py2.py3-none-any.whl
Collecting billiard<3.4,>=3.3.0.20 (from celery==3.1.18->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 12))
  Downloading billiard-3.3.0.20.tar.gz (150kB)
Collecting kombu<3.1,>=3.0.25 (from celery==3.1.18->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 12))
  Downloading kombu-3.0.26-py2.py3-none-any.whl (238kB)
Collecting markey>=0.4 (from django-babel-underscore==0.1.0->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 17))
  Downloading markey-0.5-py2.py3-none-any.whl
Collecting django-babel>=0.3.4 (from django-babel-underscore==0.1.0->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 17))
  Downloading django_babel-0.4.0-py2.py3-none-any.whl
Collecting django-classy-tags>=0.3.1 (from django-sekizai==0.6.1->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 31))
  Downloading django_classy_tags-0.6.2-py2-none-any.whl
Collecting urllib3<2.0,>=1.5 (from elasticsearch==0.4.5->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 39))
  Downloading urllib3-1.10.4-py2-none-any.whl (79kB)
Collecting gitdb>=0.5.1 (from GitPython==0.3.2.RC1->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 43))
  Downloading gitdb-0.6.4.tar.gz (400kB)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from lazy==1.1->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 47))
Collecting MarkupSafe>=0.9.2 (from mako==0.9.1->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 49))
  Downloading MarkupSafe-0.23.tar.gz
Collecting isodate==0.5.0 (from python-saml==2.1.3->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 73))
  Downloading isodate-0.5.0.tar.gz
Collecting M2Crypto==0.22.3 (from python-saml==2.1.3->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 73))
  Downloading M2Crypto-0.22.3.tar.gz (74kB)
Collecting dm.xmlsec.binding==1.3.2 (from python-saml==2.1.3->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 73))
  Downloading dm.xmlsec.binding-1.3.2.tar.gz (119kB)
    Error: cannot get XMLSec1 pre-processor and compiler flags; do you have the `libxmlsec1` development package installed?
    Complete output from command python setup.py egg_info:
    Error: cannot get XMLSec1 pre-processor and compiler flags; do you have the `libxmlsec1` development package installed?

```
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-uUiMHW/dm.xmlsec.binding
```

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=180  changed=137  unreachable=0    failed=1   

root@suedx:/var/tmp/configuration/playbooks#

**Comment by e0d** [comment]
Thanks for reporting this.  The cause is a change to the platform repository that requires a new OS dependency.  The code to install it has been added to master of the config repo, but the build scripts are using the older release branch.  We're discussing how to unravel this internally.

In the meantime, you should be able to work around the issue by doing:

```
sudo apt-get update
sudo apt-get install libxmlsec1-dev swig
```

**Comment by eemirtekin** [comment]
Hi @e0d;
Thank you for the/your quick reply.
issue resolved it.

**Comment by FremanZhang** [comment]
@e0d resolved!! Thanks!
