### ISSUE TITLE
Vagrant Fullstack Configuration

### ISSUE THREAD

**Issue by arusso1290** [openedx-unsupported/configuration#2126]
Dear all,
I've installed openEdX fullstack on a server with public IP and public domain. I'm made an SSL certificate with StartSSL. I want to configure my instance with SSL. I understand that I have to modify /edx/app/edx_ansible/server_vars.yaml file.

In fact I've modified this file as follows:
EDXAPP_LMS_NGINX_PORT: '80'
EDXAPP_LMS_SSL_PORT : '443'
EDX_ANSIBLE_DUMP_VARS: true
COMMON_ENABLE_BASIC_AUTH : false
NGINX_ENABLE_SSL: true
NGINX_SSL_CERTIFICATE: 'ssl-unified.crt'
NGINX_SSL_KEY: 'ssl.key'

After that, I've launched these commands 
1) /edx/bin/update configuration master 
2) /edx/bin/update edx-platform master

Unfortunately, servers (both Studio and LMS) don't work.

According to you, where is the mistake?
Please help me.

Thanks in advance,
Andrea.

**Comment by feanil** [comment]
The `NGINX_SSL_CERTIFICATE` and `NGINX_SSL_KEY` should be absolute paths to your keys.  Also, I would look at the NGINX and LMS logs to make sure that something else isn't wrong.

**Comment by arusso1290** [comment]
Hi Feanil,

I have to configure my server in order to communicate with SCORMCloud services (following framework in this blog article: http://blog.jazkarta.com/2015/02/08/adding-scorm-packages-to-open-edx-via-scormcloud-and-lti/).
I installed vagrant fullstack on my server with public domain and public IP and I modified Vagrant file with these port combination: 8000 -> 80, 8001->18010, 44300->443.
I modified /edx/app/edx_ansible/server_vars.yaml as follow:

EDXAPP_LMS_NGINX_PORT: '80'
EDXAPP_LMS_SSL_NGINX_PORT: '443'
EDX_ANSIBLE_DUMP_VARS: true
COMMON_ENABLE_BASIC_AUTH : false
NGINX_ENABLE_SSL: true
NGINX_SSL_CERTIFICATE: '/etc/ssl/certs/ssl-unified.crt'
NGINX_SSL_KEY: '/etc/ssl/private/ssl.key'

After that I launched update commands, and I observe ssl service only on port 44300 but not on 8000. How can I redirect https request to 8000 on 44300? Can you help me? 

Thanks in advance,
Andrea

**Comment by feanil** [comment]
If you look on the actual vagrant box do you see that it is accepting connections on 443?

**Comment by arusso1290** [comment]
Hi feanil,

If i launch from my browser https://edocmooc.eu:44300, it connects correctly to openedx instance, so i think that vagrant box accept https connection on 443. The problem is that i want to accept on 8000 http connection and https connection. Can I do this?

Thanks  a lot,
Andrea

**Comment by feanil** [comment]
@arusso1290 I don't think that it is possible for nginx to accept both SSL and non-SSL connections on the same port.
