### ISSUE TITLE
Shibboleth role and documentation

### ISSUE THREAD

**Issue by fmarco76** [openedx-unsupported/configuration#2130]
I am installing OpenEdx with shibboleth and followed your wiki. After all the steps I have several problems I am fixing. Among theme there is a problem with the navigation.html template. To login with shibboleth the login button should send to the `/shib-login` page but the template has not an if to distinguish between local login and shibboleth. At the end I edited the file modifying the login link. You should fix the code with an if or clarify how to solve the problem in the wiki.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
