### ISSUE TITLE
can't read /edx/app/edxapp/edx-platform/requirements/edx/post.txt

### ISSUE THREAD

**Issue by jsgang** [openedx-unsupported/configuration#2139]
TASK: [edxapp | Updating requirement files for git mirror] *******************\* 
failed: [localhost] => {"changed": true, "cmd": ["/bin/sed", "-i", "-e", "s/github\.com/github.com/g", "/edx/app/edxapp/edx-platform/requirements/edx/pre.txt", "/edx/app/edxapp/edx-platform/requirements/edx/post.txt", "/edx/app/edxapp/edx-platform/requirements/edx/base.txt", "/edx/app/edxapp/edx-platform/requirements/edx/paver.txt", "/edx/app/edxapp/edx-platform/requirements/edx/github.txt", "/edx/app/edxapp/edx-platform/requirements/edx-sandbox/post.txt", "/edx/app/edxapp/edx-platform/requirements/edx-sandbox/local.txt", "/edx/app/edxapp/edx-platform/requirements/edx-sandbox/base.txt"], "delta": "0:00:00.003310", "end": "2015-07-10 00:30:47.398826", "item": "", "rc": 2, "start": "2015-07-10 00:30:47.395516"}
stderr: /bin/sed: can't read /edx/app/edxapp/edx-platform/requirements/edx/post.txt: No such file or directory

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
