### ISSUE TITLE
install python base-requirements error

### ISSUE THREAD

**Issue by mandichen** [openedx-unsupported/configuration#2148]
This issue shows up when I'm trying to install fullstack. 

TASK: [edxapp | install python base-requirements] ****************************\* 
fatal: [localhost] => error while evaluating conditional: not inst.stat.exists or new.stat.md5 != inst.stat.md5

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

Any advice?

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
