### ISSUE TITLE
Installing open-edx on Ubuntu 12.04 64-bit server ERROR in:  [edxapp | install python base-requirements]

### ISSUE THREAD

**Issue by skhorus** [openedx-unsupported/configuration#2154]
Greetings, i'm trying to install Openedx in Ubuntu 12.04 Server. But i'm getting an error in:
TASK: [edxapp | install python base-requirements] *****************************

Here are the screenshots of the error:

![captura de pantalla 2015-07-17 a la s 14 43 23](https://cloud.githubusercontent.com/assets/13385778/8755922/17d09292-2c94-11e5-94b0-b50f2dc0fb07.png)

![captura de pantalla 2015-07-17 a la s 14 43 35](https://cloud.githubusercontent.com/assets/13385778/8755670/53dc88e2-2c92-11e5-944f-85dfc192cee3.png)

I've tried to install all the base requirements manually and changing PYPI_COMMON_URL but nothing works. Any advice?

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
