### ISSUE TITLE
Owner of /opt/wwc/forum/.bashrc Changed

### ISSUE THREAD

**Issue by hanwentao** [openedx-unsupported/configuration#216]
The owner of `/opt/wwc/forum/.bashrc` is changed from forum to root during a single run of ansible-playbook, and will cause a permission denied error in the second run.

```
TASK: [rbenv | ensure .bashrc exists] *****************************************
failed: [localhost] => {"changed": true, "cmd": "touch /opt/wwc/forum/.bashrc ", "delta": "0:00:00.029351", "end": "2013-08-16 10:57:59.306023", "item": "", "rc": 1, "start": "2013-08-16 10:57:59.276672"}
stderr: touch: cannot touch `/opt/wwc/forum/.bashrc': Permission denied
```

**Comment by solitaryr** [comment]
This bit me as well.  Once I chowned forum:forum /opt/wwc/forum/.bashrc, I was able to retry successfully.

**Comment by jarv** [comment]
This issue should be fixed in the Dosa release, please let us know if you still have issues.
