### ISSUE TITLE
Error while installation devstack on linux mint 17.1

### ISSUE THREAD

**Issue by nik-sergeson** [openedx-unsupported/configuration#2163]
==> default: Collecting isodate==0.5.0 (from python-saml==2.1.3->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 72))
==> default:   Downloading isodate-0.5.0.tar.gz
==> default: Collecting M2Crypto==0.22.3 (from python-saml==2.1.3->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 72))
==> default:   Downloading M2Crypto-0.22.3.tar.gz (74kB)
==> default: Collecting dm.xmlsec.binding==1.3.2 (from python-saml==2.1.3->-r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 72))
==> default:   Downloading dm.xmlsec.binding-1.3.2.tar.gz (119kB)
==> default:     Error: cannot get XMLSec1 pre-processor and compiler flags; do you have the `libxmlsec1` development package installed?
==> default:     Complete output from command python setup.py egg_info:
==> default:     Error: cannot get XMLSec1 pre-processor and compiler flags; do you have the `libxmlsec1` development package installed?
==> default:  
==> default:     ----------------------------------------
==> default:     Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5OGn8l/dm.xmlsec.binding
==> default: 
==> default: FATAL: all hosts have already failed -- aborting
==> default: 
==> default: PLAY RECAP *******************************************************************\* 
==> default:            to retry, use: --limit @/root/vagrant-devstack.retry
==> default: 
==> default: localhost                  : ok=171  changed=40   unreachable=0    failed=1 

I have libxmlsec1-dev installed.

**Comment by nik-sergeson** [comment]
Solved using  shell provisioner.

**Comment by venuiiit08** [comment]
facing the same problem... waiting for the response

**Comment by VenuRean** [comment]
facing the same problem..
waiting for responce

**Comment by nik-sergeson** [comment]
1.Example is given here:
[Vagrant docs](http://docs.vagrantup.com/v2/getting-started/provisioning.html).
Put to the sh file following:

```
apt-get update 
apt-get install libxmlsec1-dev
apt-get install swig
```

2.Or you can install newer named release(Cypress RC3 doesn't have such problems):
[Atlassian](https://openedx.atlassian.net/wiki/display/DOC/Named+Releases)

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
