### ISSUE TITLE
Complete the documentation how to install the New Relic within Open Edx

### ISSUE THREAD

**Issue by leijianbin** [openedx-unsupported/configuration#2167]
Hello,

I am not sure if the dev stack support the new relic or not? I check the playbook in the github repo, it looks like it should be. But I can't find any documentation to help. Just wonder anyone can help? 

Thx

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
