### ISSUE TITLE
customize the source of Preview video for a course

### ISSUE THREAD

**Issue by wzymaster** [openedx-unsupported/configuration#2169]
As I see so far, all preview videos must be from youtube. 

Unfortunately, we are looking for various source here. Can we customize the source of preview videos for a course in Edx ? 

thanks.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
