### ISSUE TITLE
Stanford Theme OpenEdXLogo.png not display logo

### ISSUE THREAD

**Issue by kapil1v** [openedx-unsupported/configuration#2189]
I am new to Openedx and working on custom Stanford theme. Everything works fine except custom logo as it did not display OpenEdXLogo.png IMAGE.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
