### ISSUE TITLE
Creating and accessing an edx instance on aws

### ISSUE THREAD

**Issue by maximfilippov** [openedx-unsupported/configuration#219]
Hello guys,

We've finished the whole instructions for configuring servers on aws. Could you please point us out to next steps i.e. how do we actually deploy and get the code to run?

Thanks so much,

Max

**Comment by elimence** [comment]
which set of instructions did you follow?
Using cloud formation or using ansible? etc.

**Comment by maximfilippov** [comment]
We've used cloud formation!

**Comment by e0d** [comment]
@maximfilippov Have you looked at this: https://github.com/edx/configuration/wiki/AWS-Installation

**Comment by maximfilippov** [comment]
Ha that's the only thing i've been looking at for the past few days! But its not telling me how to deploy & run code as well as access the platform!

**Comment by e0d** [comment]
Have you run ansible?  That will deploy the code.

**Comment by maximfilippov** [comment]
Running the configuration playbook seems to only configure the stack. We have done that through the was console so that's the done. Now we want to actually upload and run the code actual code (not just the server configuration stuff that we have done already).

Many thanks!

**Comment by e0d** [comment]
Have you created the full VPC version or are you trying to build a sandbox that runs multiple services?

**Comment by maximfilippov** [comment]
We are trying to create the full platform. By following the instructions we end up with a VPC running 12 ec2 instances i.e. we have what seems to be the full stack configured.

**Comment by maximfilippov** [comment]
Wait a minute… I'm realising that I have launched the configuration playbook with ansible using the same stack name (say STACK1) that I used for the stack I had configured through the console (which of course messed up the whole stack).

Are you telling me that if I specify a new stack name (say STACK2) and launch the configuration playbook i'll have all the code loaded on STACK1?

That would be very awesome!

**Comment by jarv** [comment]
@maximfilippov We don't have polished docs available yet for running edX in a vpc.  It's something we plan to do eventually though it may not happen for awhile.

**Comment by disisid** [comment]
I have created an edx single ec2 instance using the config wiki. I have also configured using ansible playbook from edx master.

 sudo ansible-playbook -c local --limit "localhost:127.0.0.1" \
./edx_sandbox.yml -i "localhost," -e "edx_platform_commit=master"

However I cannot access LMS or CMS on public IP port 18010 or 18000. The public IP is http://ec2-54-254-185-46.ap-southeast-1.compute.amazonaws.com/ 

I was getting data not received error while accessing these ports. Can you please guide me on this?

**Comment by elimence** [comment]
Where there any error messages when during the setup process?
Also i'd advice you setup an elastic IP as opposed to using the default public DNS (not that i think this is the cause, but at the least, it's cleaner)

You should also check to see if the nginx and gunicorn are running, or even try restarting them (assuming you aren't using something else in their stead)

**Comment by disisid** [comment]
Although there were no errors. I used ansible on the server yesterday.
Today when I sshed into the server and ran these commands
sudo service gunicorn status
sudo service edxapp status

these services were not recognised. Should I run ansible again?

Although sudo service nginx status returns nginx running.

**Comment by disisid** [comment]
So I executed ansible again. This time it failed at elasticsearch

TASK: [elasticsearch | Ensure elasticsearch is enabled and started] **********\* 
failed: [localhost] => {"failed": true, "item": ""}
msg:  \* Starting ElasticSearch Server
   ...fail!

FATAL: all hosts have already failed -- aborting
PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/ubuntu/edx_sandbox.retry

localhost                  : ok=175  changed=44   unreachable=0    failed=1   

Now gunicorn is still unrecognised as well as edxapp. elasticsearch shouldn't affect gunicorn or edxapp as such. Anyone - please guide.
