### ISSUE TITLE
installing openedx on ubuntu 14.04 : in elasticsearch

### ISSUE THREAD

**Issue by jyotichauhan** [openedx-unsupported/configuration#2191]
I struck with this error . Please help me in resoving this and suggest something

TASK:  [elasticsearch | download elasticsearch] *******************************\* 
failed: [localhost] => {"failed": true, "item": ""}
msg: Failed to validate the SSL certificate for download.elasticsearch.org:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible

FATAL: all hosts have already failed -- aborting

**Comment by smaeda-ks** [comment]
see this.

https://github.com/edx/configuration/pull/1912

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
