### ISSUE TITLE
Error in running paver devstack lms on windows 7(Error: Cannot find module )

### ISSUE THREAD

**Issue by vikas1885** [openedx-unsupported/configuration#2219]
Hi i am doing fresh devstack installation . I am getting following Error while running
paver devstack lms
or
paver update_assets lms --settings=devstack

I am using VM with windows 7.
Please Help,Any guidance or suggestions would be appreciated.  Thanks for the consideration.
# Console Log

edxapp@precise64:~/edx-platform$ paver update_assets lms --settings=devstack
---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
Ruby prereqs unchanged, skipping...
---> pavelib.prereqs.install_node_prereqs
Node prereqs unchanged, skipping...
python manage.py lms --settings=devstack preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/a
pp/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.
coffee"`

module.js:340
    throw err;
          ^
Error: Cannot find module '/edx/app/edxapp/edx-platform/node_modules/lib/coffee-
script/command'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/edx/app/edxapp/edx-platform/node_modules/.bin/..\cof
fee-script\bin\coffee:7:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
## Captured Task Output:

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py lms --settings=devstack preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/a
pp/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.
coffee"`

Build failed running pavelib.assets.update_assets: Subprocess return code: 8

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
