### ISSUE TITLE
TASK: [git checkout edx-platform repo into $app_base_dir]

### ISSUE THREAD

**Issue by plejik-zz** [openedx-unsupported/configuration#223]
TASK: [git checkout edx-platform repo into $app_base_dir]
We have some proxy, and link like git:// cant work here, so where i can find source with this parameters or maybe someone change it in code to https, which work very well with htttps_proxy= on linux

**Comment by feanil** [comment]
It's already pointing to the https url.

https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/vars/main.yml#L205

**Comment by samah-EC3** [comment]
checkout edx-platform repo into {{edxapp_code_dir}}] stucked can i download localy from git and use locally without download from internet  can help me
