### ISSUE TITLE
TASK: [supervisor | update supervisor configuration] Fails when updating edx-platform

### ISSUE THREAD

**Issue by elimence** [openedx-unsupported/configuration#2235]
I'm running the final release of cypress which works ok. Also I've got it to use a forked version of edx-platform and I've been able to update the repo a couple times.
A couple days ago I tried running `sudo /edx/bin/update edx-platform jupiter` a number of times, all of which fail with the below error message. When I check the status of running services, I see that all the edxapp_workers have stopped and one cms worker says 'stopping'

Any help is appreciated, thanks 

``` bash
TASK: [supervisor | start supervisor] *****************************************
ok: [localhost]

TASK: [supervisor | wait for web port to be available] ************************
skipping: [localhost]

TASK: [supervisor | update supervisor configuration] **************************
failed: [localhost] => {"changed": true, "cmd": "/edx/app/supervisor/venvs/supervisor/bin/supervisorctl -c /edx/app/supervisor/supervisord.conf update ", "delta": "0:00:06.634842", "end": "2015-08-24 09:46:46.499054", "item": "", "rc": 2, "start": "2015-08-24 09:46:39.864212", "stdout_lines": ["edxapp_worker: stopped", "error: <class 'xmlrpclib.Fault'>, <Fault 91: 'STILL_RUNNING'>: file: /usr/lib/python2.7/xmlrpclib.py line: 794"]}
stdout: edxapp_worker: stopped
error: <class 'xmlrpclib.Fault'>, <Fault 91: 'STILL_RUNNING'>: file: /usr/lib/python2.7/xmlrpclib.py line: 794

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/edu4africa/edxapp.retry

localhost                  : ok=59   changed=6    unreachable=0    failed=1
```

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
