### ISSUE TITLE
Amazon-specific error when updating motd

### ISSUE THREAD

**Issue by fisharebest** [openedx-unsupported/configuration#2242]
On a clean install on Ubuntu 12.04, I get the error

```
$ export OPENEDX_RELEASE=named-release/cypress
$ wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash

...

TASK: [aws | update the ssh motd on Ubuntu] ***********************************
changed: [localhost] => (item=/etc/update-motd.d/10-help-text)
changed: [localhost] => (item=/usr/share/landscape/landscape-sysinfo.wrapper)
failed: [localhost] => (item=/etc/update-motd.d/51-cloudguest) => {"failed": true, "item": "/etc/update-motd.d/51-cloudguest", "path": "/etc/update-motd.d/51-cloudguest", "state": "absent"}
msg: file (/etc/update-motd.d/51-cloudguest) is absent, cannot continue
changed: [localhost] => (item=/etc/update-motd.d/91-release-upgrade
```

This file `/etc/update-motd.d/51-cloudguest` is not present on default builds of Ubuntu, it is only present on AWS builds.

As a workaround, `sudo touch /etc/update-motd.d/51-cloudguest` prior to installation.

**Comment by shaidar** [comment]
Ran into the same issue and creating the file on the Ubuntu server fixed it.

**Comment by e0d** [comment]
This will be fixed up stream in the next week or so, but it is always
helpful to share the details of your solution on the list.

Best,

Ed

**Comment by shaidar** [comment]
@e0d Thanks for the update and I agree about sharing the details, however @fisharebest had already posted all the details and the solution, so didn't see the need to duplicate.

**Comment by michalmikolajczyk** [comment]
:+1:
