### ISSUE TITLE
common | Add git apt repository

### ISSUE THREAD

**Issue by ksripathi** [openedx-unsupported/configuration#2247]
TASK: [common | Add git apt repository] **************************************\* 
failed: [localhost] => {"failed": true, "item": ""}
msg: failed to fetch PPA information, error was: Request failed: <urlopen error [Errno 111] Connection refused>

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=11   changed=1    unreachable=0    failed=1

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
