### ISSUE TITLE
TASK: [install python base-requirements] hangs.

### ISSUE THREAD

**Issue by akrishkevich** [openedx-unsupported/configuration#225]
I'm using a vanilla Ubuntu 12.04 (precise). All I did was
1. Created a user and added it to sudoers
2. apt-get update and upgrade
3. Followed instructions on the edX/configuration page.

I tried this three times, it always hangs on TASK: [install python base-requirements].

Can someone confirm or comment?
# 

Here's the output log:
./edx_sandbox.yml -i "localhost,"

PLAY [Configure instance(s)] *************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [localhost]

TASK: [common | Create 'edx' users group] ************************************\* 
changed: [localhost]

TASK: [common | Add user 'ubuntu' to 'edx' group] ****************************\* 
changed: [localhost]

TASK: [common | Creating admin users] ****************************************\* 
skipping: [localhost] => (item=admin_users)

TASK: [common | Copying ssh keys for admin users] ****************************\* 
skipping: [localhost] => (item=admin_keys)

TASK: [common | Creating env users] ******************************************\* 
skipping: [localhost] => (item=env_users)

TASK: [common | Copying ssh keys for env users] ******************************\* 
skipping: [localhost] => (item=env_keys)

TASK: [common | Group adm passwordless sudo] *********************************\* 
changed: [localhost]

TASK: [common | Add user www-data] *******************************************\* 
ok: [localhost]

TASK: [common | Create application root] *************************************\* 
changed: [localhost]

TASK: [common | Create upload directory] *************************************\* 
changed: [localhost]

TASK: [common | Create data dir] *********************************************\* 
changed: [localhost]

TASK: [common | Create staticfiles dir] **************************************\* 
changed: [localhost]

TASK: [common | Install role-independent useful system packages] *************\* 
changed: [localhost]

TASK: [common | Create log directory] ****************************************\* 
changed: [localhost]

TASK: [common | Create alias from app_base_dir to the log_base_dir] **********\* 
changed: [localhost]

TASK: [common | Create convenience link from log_base_dir to system logs] ****\* 
changed: [localhost]

TASK: [common | Touch edx log file into place] *******************************\* 
changed: [localhost]

TASK: [common | Set permissions on edx log file] *****************************\* 
changed: [localhost]

TASK: [common | upload sudo config for key forwarding as root] ***************\* 
changed: [localhost]

TASK: [common | Install python and pip] **************************************\* 
ok: [localhost] => (item=python2.7,python-pip,python2.7-dev)

TASK: [common | pip install virtualenv] **************************************\* 
changed: [localhost]

TASK: [common | pip install virtualenvwrapper] *******************************\* 
changed: [localhost]

TASK: [common | create edx virtualenv directory] *****************************\* 
changed: [localhost]

TASK: [common | create the edx virtualenv directory initial contents] ********\* 
changed: [localhost]

TASK: [common |  pip install gunicorn] ***************************************\* 
changed: [localhost]

TASK: [common | Install rsyslog configuration for edX] ***********************\* 
changed: [localhost]

TASK: [common | Install logrotate configuration for edX] *********************\* 
changed: [localhost]

TASK: [common | Touch tracking file into existence] **************************\* 
changed: [localhost]

TASK: [common | Set permissions on tracking file] ****************************\* 
changed: [localhost]

TASK: [common | Install logrotate configuration for tracking file] ***********\* 
changed: [localhost]

TASK: [nginx | Install nginx] ************************************************\* 
changed: [localhost]

TASK: [nginx | Copying nginx config edx-release] *****************************\* 
skipping: [localhost]

TASK: [nginx | Creating nginx config link edx-release] ***********************\* 
skipping: [localhost]

TASK: [nginx | Copying nginx config basic-auth] ******************************\* 
skipping: [localhost]

TASK: [nginx | Creating nginx config link basic-auth] ************************\* 
skipping: [localhost]

TASK: [nginx | Write out default htpasswd file] ******************************\* 
changed: [localhost]

TASK: [nginx | Create nginx log file location (just in case)] ****************\* 
changed: [localhost]

TASK: [nginx | Removing default nginx config and restart (enabled)] **********\* 
changed: [localhost]

TASK: [nginx | Set up nginx access log rotation] *****************************\* 
changed: [localhost]

TASK: [nginx | Set up nginx access log rotation] *****************************\* 
changed: [localhost]

TASK: [nginx | Removing default nginx config (available)] ********************\* 
changed: [localhost]

TASK: [nginx | Register the fact that nginx has run] *************************\* 
changed: [localhost]

TASK: [nginx | make sure nginx has started] **********************************\* 
changed: [localhost]

TASK: [edxlocal | install python-pymongo (req for ansible)] ******************\* 
changed: [localhost]

TASK: [edxlocal | install python-mysqldb (req for ansible)] ******************\* 
changed: [localhost]

TASK: [edxlocal | install mysql server and recommends] ***********************\* 
changed: [localhost]

TASK: [edxlocal | create a database for edxapp] ******************************\* 
changed: [localhost]

TASK: [edxlocal | create a database for xqueue] ******************************\* 
changed: [localhost]

TASK: [edxlocal | create a database for ora] *********************************\* 
changed: [localhost]

TASK: [edxlocal | install mongo server and recommends] ***********************\* 
changed: [localhost]

TASK: [edxlocal | stop mongo service] ****************************************\* 
changed: [localhost]

TASK: [edxlocal | move mongodb to /mnt] **************************************\* 
changed: [localhost]

TASK: [edxlocal | create mongodb symlink] ************************************\* 
changed: [localhost]

TASK: [edxlocal | start mongo service] ***************************************\* 
changed: [localhost]

TASK: [edxlocal | wait for mongo server to start] ****************************\* 
ok: [localhost]

TASK: [edxlocal | create a mongodb user for edxapp] **************************\* 
changed: [localhost]

TASK: [edxlocal | create a mongodb user for forums] **************************\* 
changed: [localhost]

TASK: [edxlocal | install memcached] *****************************************\* 
changed: [localhost]

TASK: [Change permissions on datadir] ****************************************\* 
changed: [localhost]

TASK: [Change owner on staticfiles] ******************************************\* 
ok: [localhost]

TASK: [Create theming directory] *********************************************\* 
changed: [localhost]

TASK: [install a bunch of system packages on which LMS and CMS rely] *********\* 
changed: [localhost]

TASK: [create lms application config] ****************************************\* 
changed: [localhost]

TASK: [create lms auth file] *************************************************\* 
changed: [localhost]

TASK: [Create lms log target directory] **************************************\* 
changed: [localhost]

TASK: [nginx | Copying nginx config lms] *************************************\* 
changed: [localhost]

TASK: [nginx | Creating nginx config link lms] *******************************\* 
changed: [localhost]

TASK: [nginx | Copying nginx config lms-backend] *****************************\* 
changed: [localhost]

TASK: [nginx | Creating nginx config link lms-backend] ***********************\* 
changed: [localhost]

TASK: [writing lms upstart script to /etc/init] ******************************\* 
changed: [localhost]

TASK: [writing edx-worker-lms upstart script to /etc/init] *******************\* 
skipping: [localhost]

TASK: [create lms-xml application config] ************************************\* 
changed: [localhost]

TASK: [create lms-xml auth file] *********************************************\* 
changed: [localhost]

TASK: [Create lms-xml log target directory] **********************************\* 
changed: [localhost]

TASK: [nginx | Copying nginx config lms-xml] *********************************\* 
changed: [localhost]

TASK: [nginx | Creating nginx config link lms-xml] ***************************\* 
changed: [localhost]

TASK: [nginx | Copying nginx config lms-xml-backend] *************************\* 
changed: [localhost]

TASK: [nginx | Creating nginx config link lms-xml-backend] *******************\* 
changed: [localhost]

TASK: [writing lms-xml upstart script to /etc/init] **************************\* 
changed: [localhost]

TASK: [writing edx-worker-lms-xml upstart script to /etc/init] ***************\* 
skipping: [localhost]

TASK: [create cms application config] ****************************************\* 
changed: [localhost]

TASK: [create cms auth file] *************************************************\* 
changed: [localhost]

TASK: [nginx | Copying nginx config cms] *************************************\* 
changed: [localhost]

TASK: [nginx | Creating nginx config link cms] *******************************\* 
changed: [localhost]

TASK: [nginx | Copying nginx config cms-backend] *****************************\* 
changed: [localhost]

TASK: [nginx | Creating nginx config link cms-backend] ***********************\* 
changed: [localhost]

TASK: [Create CMS log target directory] **************************************\* 
changed: [localhost]

TASK: [writing cms upstart script to /etc/init] ******************************\* 
changed: [localhost]

TASK: [writing edx-worker-cms upstart script to /etc/init] *******************\* 
skipping: [localhost]

TASK: [create lms application config] ****************************************\* 
changed: [localhost]

TASK: [create lms auth file] *************************************************\* 
changed: [localhost]

TASK: [Create lms-preview log target directory] ******************************\* 
changed: [localhost]

TASK: [nginx | Copying nginx config lms-preview] *****************************\* 
changed: [localhost]

TASK: [nginx | Creating nginx config link lms-preview] ***********************\* 
changed: [localhost]

TASK: [nginx | Copying nginx config lms-preview-backend] *********************\* 
changed: [localhost]

TASK: [nginx | Creating nginx config link lms-preview-backend] ***************\* 
changed: [localhost]

TASK: [writing lms-preview upstart script to /etc/init] **********************\* 
changed: [localhost]

TASK: [creating edxapp upstart script] ***************************************\* 
changed: [localhost]

TASK: [create edx-workers upstart script] ************************************\* 
skipping: [localhost]

TASK: [Install npm] **********************************************************\* 
ok: [localhost]

TASK: [Create 'www' user (replicating historical environment)] ***************\* 
changed: [localhost]

TASK: [Create ruby base] *****************************************************\* 
changed: [localhost]

TASK: [rbenv | install build depends] ****************************************\* 
ok: [localhost] => (item=build-essential,git,libcurl4-openssl-dev,libmysqlclient-dev,libreadline-dev,libssl-dev,libxml2-dev,libxslt1-dev,zlib1g-dev)

TASK: [rbenv | update rbenv repo] ********************************************\* 
changed: [localhost]

TASK: [rbenv | add rbenv to path] ********************************************\* 
changed: [localhost]

TASK: [rbenv | add rbenv initialization to profile] **************************\* 
changed: [localhost]

TASK: [rbenv | check ruby-build installed] ***********************************\* 
failed: [localhost] => {"changed": true, "cmd": ["test", "-x", "/usr/local/bin/ruby-build"], "delta": "0:00:00.004445", "end": "2013-08-25 03:19:52.122206", "item": "", "rc": 1, "start": "2013-08-25 03:19:52.117761"}
...ignoring

TASK: [rbenv | create temporary directory] ***********************************\* 
changed: [localhost]

TASK: [rbenv | clone ruby-build repo] ****************************************\* 
changed: [localhost]

TASK: [rbenv | install ruby-build] *******************************************\* 
changed: [localhost]

TASK: [rbenv | remove temporary directory] ***********************************\* 
changed: [localhost]

TASK: [rbenv | check ruby 1.9.3-p374 installed] ******************************\* 
failed: [localhost] => {"changed": true, "cmd": "RBENV_ROOT=/opt/www/.rbenv rbenv versions | grep 1.9.3-p374 ", "delta": "0:00:00.053208", "end": "2013-08-25 03:19:54.437263", "item": "", "rc": 1, "start": "2013-08-25 03:19:54.384055"}
...ignoring

TASK: [rbenv | install ruby 1.9.3-p374] **************************************\* 
changed: [localhost]

TASK: [rbenv | set global ruby 1.9.3-p374] ***********************************\* 
changed: [localhost]

TASK: [rbenv | rehash] *******************************************************\* 
changed: [localhost]

TASK: [stop edxapp services] *************************************************\* 
ok: [localhost]

TASK: [stop edx workers] *****************************************************\* 
skipping: [localhost]

TASK: [git checkout edx-platform repo into $app_base_dir] ********************\* 
changed: [localhost]

TASK: [create platform code dir] *********************************************\* 
changed: [localhost]

TASK: [checkout theme] *******************************************************\* 
skipping: [localhost]

TASK: [sets permissions on platform code dir and contents] *******************\* 
changed: [localhost]

TASK: [gem | gem install bundler] ********************************************\* 
changed: [localhost]

TASK: [bundle | bundle install] **********************************************\* 
changed: [localhost]

TASK: [Install edx-platform npm dependencies] ********************************\* 
changed: [localhost]

TASK: [install python pre-requirements] **************************************\* 
changed: [localhost]

TASK: [install python base-requirements] *************************************\*

**Comment by asia653** [comment]
Why was this closed?

**Comment by blackyboy** [comment]
Same error facing .. How to solve it ?

**Comment by pchiu33** [comment]
This is a non-issue.
Installing Python requirements just takes time, so be patient or add more computing power (cpu/ram).

**Comment by blackyboy** [comment]
oh ok thanks let me try it in VPS then

**Comment by engmsaleh** [comment]
I'm installing EDX on single VPS and I got the same as above plus a lot off errors
like
failed: [localhost] => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i http://localhost:4040/root/pypi/+simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt ", "delta": "0:03:04.282931", "end": "2013-12-22 17:49:09.674895", "item": "", "rc": 137, "start": "2013-12-22 17:46:05.391964"}
stderr: Killed
stdout: Obtaining file:///edx/app/edxapp/edx-platform/common/lib/calc (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 2))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/calc

**Comment by jarv** [comment]
@engmsaleh since the original issue is a few months old can you open a new github issue for this?
I did notice some issues with github today which may be related since we pull down checkout some python libraries from there. If you are still having problems let us know.

**Comment by deependersingla** [comment]
@jarv  Any update? I am facing the same issue.
