### ISSUE TITLE
configuration error elasticsearch failed on port 9200 9300

### ISSUE THREAD

**Issue by plejik-zz** [openedx-unsupported/configuration#226]
when i make 
    ansible-playbook -c local --limit "localhost:127.0.0.1" \
    ./edx_sandbox.yml -i "localhost,"

have error 

```
ok: [localhost] => (item={'host': 'localhost', 'port': '4567', 'service': 'sinatra'})
ok: [localhost] => (item={'host': u'localhost', 'port': '27017', 'service': 'mongo'})
ok: [localhost] => (item={'host': u'localhost', 'port': '28017', 'service': 'mongo'})
```

failed: [localhost] => (item={'host': u'localhost', 'port': '9200', 'service': 'elasticsearch'}) => {"elapsed": 10, "failed": true, "item": {"host": "localhost", "port": "9200", "service": "elasticsearch"}}
    msg: Timeout when waiting for 127.0.0.1:9200
    failed: [localhost] => (item={'host': u'localhost', 'port': '9300', 'service': 'elasticsearch'}) => {"elapsed": 10, "failed": true, "item": {"host": "localhost", "port": "9300", "service": "elasticsearch"}}
    msg: Timeout when waiting for 127.0.0.1:9300

i look at issue https://github.com/edx/configuration/issues/204, but there problem start from with sinatra

**Comment by plejik-zz** [comment]
syslog.log

`Aug 25 17:25:27 kpt3 ansible-get_url: Invoked with src=None force=False use_proxy=True url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.2.deb selevel=None seuser=None serole=None content=None dest=/var/tmp/elasticsearch-0.90.2.deb setype=None mode=None owner=None group=None backup=None 
Aug 25 17:25:28 kpt3 ansible-command: Invoked with executable=/bin/bash shell=True args=dpkg -i /var/tmp/elasticsearch-0.90.2.deb   removes=None creates=/usr/share/elasticsearch/bin/elasticsearch chdir=None 
Aug 25 17:25:29 kpt3 ansible-file: Invoked with src=None force=None selevel=None seuser=None recurse=False state=directory content=None serole=None diff_peek=None mode=None path=/opt/wwc/forum owner=None group=None validate=None backup=None setype=None 
Aug 25 17:25:29 kpt3 ansible-user: Invoked with comment=None ssh_key_bits=2048 ssh_key_passphrase=None force=False uid=None non_unique=False home=/opt/wwc/forum append=False ssh_key_type=rsa ssh_key_comment=ansible-generated group=None system=False state=present shell=/bin/bash ssh_key_file=None groups=None password=NOT_LOGGING_PASSWORD name=forum createhome=True remove=False login_class=None generate_ssh_key=None 
Aug 25 17:25:29 kpt3 ansible-file: Invoked with src=None force=None selevel=None seuser=None recurse=False state=directory content=None serole=None diff_peek=None mode=None path=/opt/wwc/forum owner=forum group=forum validate=None backup=None setype=None 
Aug 25 17:25:29 kpt3 ansible-apt: Invoked with upgrade=None force=False package=build-essential,git,libcurl4-openssl-dev,libmysqlclient-dev,libreadline-dev,libssl-dev,libxml2-dev,libxslt1-dev,zlib1g-dev purge=False state=present update_cache=None pkg=build-essential,git,libcurl4-openssl-dev,libmysqlclient-dev,libreadline-dev,libssl-dev,libxml2-dev,libxslt1-dev,zlib1g-dev default_release=None install_recommends=False cache_valid_time=None 
Aug 25 17:25:30 kpt3 ansible-git: Invoked with force=True dest=/opt/wwc/forum/.rbenv update=True repo=https://github.com/sstephenson/rbenv.git depth=None version=v0.4.0 remote=origin 
Aug 25 17:25:34 kpt3 ansible-command: Invoked with executable=None shell=True args=touch /opt/wwc/forum/.bashrc  removes=None creates=None chdir=None 
Aug 25 17:25:35 kpt3 ansible-file: Invoked with src=/root/.ansible/tmp/ansible-1377465934.95-96417893447666/bash_profile force=None dest=/opt/wwc/forum/.bash_profile selevel=None seuser=None recurse=False state=file content=None serole=None diff_peek=None mode=None path=/opt/wwc/forum/.bash_profile owner=forum group=forum validate=None backup=None setype=None 
Aug 25 17:25:35 kpt3 ansible-file: Invoked with src=ruby_env.j2 force=None dest=/opt/wwc/forum/ruby_env selevel=None seuser=None recurse=False state=file content=None serole=None diff_peek=None mode=None path=/opt/wwc/forum/ruby_env owner=forum group=forum validate=None backup=None setype=None 
Aug 25 17:25:35 kpt3 ansible-lineinfile: Invoked with src=None force=None insertbefore=None dest=/opt/wwc/forum/.bashrc selevel=None create=False seuser=None state=present backrefs=False content=None owner=None serole=None mode=None insertafter=None regexp=. /opt/wwc/forum/ruby_env line=. /opt/wwc/forum/ruby_env backup=False group=None setype=None 
Aug 25 17:25:35 kpt3 ansible-file: Invoked with src=/root/.ansible/tmp/ansible-1377465935.42-54814246283856/bash_profile force=None dest=/opt/wwc/forum/.bash_profile selevel=None seuser=None recurse=False state=file content=None serole=None diff_peek=None mode=None path=/opt/wwc/forum/.bash_profile owner=forum group=forum validate=None backup=None setype=None 
Aug 25 17:25:35 kpt3 ansible-command: Invoked with executable=None shell=False args=test -x /usr/local/bin/ruby-build removes=None creates=None chdir=None 
Aug 25 17:25:36 kpt3 ansible-command: Invoked with executable=None shell=True args=/opt/wwc/forum/.rbenv/bin/rbenv versions | grep 1.9.3-p448  removes=None creates=None chdir=None 
Aug 25 17:25:36 kpt3 ansible-command: Invoked with executable=None shell=True args=/opt/wwc/forum/.rbenv/shims/gem install bundler -v 1.3.2  removes=None creates=None chdir=None 
Aug 25 17:25:56 kpt3 ansible-file: Invoked with src=forum_env.j2 force=None dest=/opt/wwc/forum/forum_env selevel=None seuser=None recurse=False state=file content=None serole=None diff_peek=None mode=None path=/opt/wwc/forum/forum_env owner=forum group=forum validate=None backup=None setype=None 
Aug 25 17:25:56 kpt3 ansible-command: Invoked with executable=None shell=True args=touch /opt/wwc/forum/.bashrc  removes=None creates=None chdir=None 
Aug 25 17:25:57 kpt3 ansible-lineinfile: Invoked with src=None force=None insertbefore=None dest=/opt/wwc/forum/.bashrc selevel=None create=False seuser=None state=present backrefs=False content=None owner=None serole=None mode=None insertafter=None regexp=. /opt/wwc/forum/forum_env line=. /opt/wwc/forum/forum_env backup=False group=None setype=None 
Aug 25 17:25:57 kpt3 ansible-file: Invoked with src=cs_comments_service.conf.j2 force=None dest=/etc/init/cs_comments_service.conf selevel=None seuser=None recurse=False state=file content=None serole=None diff_peek=None mode=644 path=/etc/init/cs_comments_service.conf owner=root group=root validate=None backup=None setype=None 
Aug 25 17:25:57 kpt3 ansible-service: Invoked with pattern=None state=stopped enabled=None name=cs_comments_service arguments= 
Aug 25 17:25:57 kpt3 ansible-git: Invoked with force=True dest=/opt/wwc/forum/cs_comments_service update=True repo=https://github.com/edx/cs_comments_service.git depth=None version=HEAD remote=origin 
Aug 25 17:26:00 kpt3 ansible-command: Invoked with executable=/bin/bash shell=True args= /opt/wwc/forum/.rbenv/shims/bundle install  removes=None creates=None chdir=/opt/wwc/forum/cs_comments_service 
Aug 25 17:26:01 kpt3 ansible-service: Invoked with pattern=None state=restarted enabled=None name=cs_comments_service arguments= 
Aug 25 17:26:01 kpt3 ansible-wait_for: Invoked with host=127.0.0.1 connect_timeout=5 delay=0 state=started timeout=10 port=4567 
Aug 25 17:26:06 kpt3 ansible-wait_for: Invoked with host=127.0.0.1 connect_timeout=5 delay=0 state=started timeout=10 port=27017 
Aug 25 17:26:06 kpt3 ansible-wait_for: Invoked with host=127.0.0.1 connect_timeout=5 delay=0 state=started timeout=10 port=28017 
Aug 25 17:26:06 kpt3 ansible-wait_for: Invoked with host=127.0.0.1 connect_timeout=5 delay=0 state=started timeout=10 port=9200 
Aug 25 17:26:16 kpt3 ansible-wait_for: Invoked with host=127.0.0.1 connect_timeout=5 delay=0 state=started timeout=10 port=9300`

**Comment by plejik-zz** [comment]
Solved by 
`sudo add-apt-repository ppa:webupd8team/java
sudo apt-get install oracle-java7-installer`
and check
`java -version == javac -version`

**Comment by jarv** [comment]
I believe these issues should be resolved in the latest release, please retry and let us know if you have any problems.  Docs for installing the new devstack here - https://github.com/edx/configuration/wiki/edX-Developer-Stack
