### ISSUE TITLE
ValueError: The file 'css/base/font_face' could not be found with <openedx.core.lib.django_require.staticstorage.OptimizedCachedRequireJsStorage object at 0x7729d90

### ISSUE THREAD

**Issue by sbalde** [openedx-unsupported/configuration#2260]
Hello Guys,

I'm running a devstack with cypress release. I installed the IONISX theme made by @tusbar and cutomized it.
It was running well untill that i created new courses into studio. 
Now on LMS i have the following error "Syntax error: file to import not found or unreadable guandhal ............... on line 23 of lms/static/sass/lms-main.scss" (see the attached screenshots for more information)
I manually recompiled the assets but it doesn't resolve the issue.

PS: "guandhal" is the name of my theme. It's a cutomized theme using the IONISX bootstrap theme.

Anyone here had already faced something similar or not?

![screen shot 2015-09-01 at 23 34 02](https://cloud.githubusercontent.com/assets/11218855/9619809/de4170c4-5113-11e5-8c6e-678ab6593154.png)
![screen shot 2015-09-02 at 01 37 16](https://cloud.githubusercontent.com/assets/11218855/9619810/e2980606-5113-11e5-9550-19702cab401a.png)
![screen shot 2015-09-02 at 01 37 38](https://cloud.githubusercontent.com/assets/11218855/9619814/e62b4ae4-5113-11e5-9b0d-743808373ea0.png)

Thanks in advance for your time and help.

**Comment by tusbar** [comment]
Hi @sbalde 

Can you show me what’s in `/edx/app/edxapp/themes/guandhal/static/sass/_guandhal.scss`?

**Comment by sbalde** [comment]
Hey @tusbar,

Sorry for the delay, I restarted the VM and it seems to work now.
However is it normal that the _guandhal.css file is empty?

**Comment by tusbar** [comment]
@sbalde yeah, the theme does not override nor contain any Sass – only Less (based on Bootstrap).

Good to see you got it to work.

**Comment by sbalde** [comment]
@tusbar ok! Thanks man. I truly appreciate.

**Comment by ahyield** [comment]
I have the same issue :(
