### ISSUE TITLE
Cannot update 'Advanced Settings' values in Studio

### ISSUE THREAD

**Issue by jessp01** [openedx-unsupported/configuration#2270]
Hello all,

I have deployed using vagrant using instructions from here:
https://github.com/edx/configuration/wiki/edx-Full-stack--installation-using-Vagrant-Virtualbox

I am trying to enable the LTI component following instructions here:
http://edx-partner-course-staff.readthedocs.org/en/latest/exercises_tools/lti_component.html

When inputting '[lti]' into the 'Advanced Module List' textbox, I immediately get:
'You've made some changes
Your changes will not take effect until you save your progress. Take care with key and value formatting, as validation is not implemented.'

Upon hitting 'Save changes', I get: 
'Your policy changes have been saved.
Please note that validation of your policy key and value pairs is not currently in place yet. If you are having difficulties, please review your policy pairs.'

but the value is not saved.
This is true to any value I tried saving in the form, including the passport one.

I could not find any errors in the logs under /edx/var/log/ using:
# grep -i error /edx/var/log/\* -r

I also checked for ALLOW_ALL_ADVANCED_COMPONENTS
/edx/app/edxapp/edx-platform/cms/envs/bok_choy.env.json:        "ALLOW_ALL_ADVANCED_COMPONENTS": true,
/edx/app/edxapp/edx-platform/cms/env/devstack.py:
FEATURES['ALLOW_ALL_ADVANCED_COMPONENTS'] = True

I also tried adding:
/edx/app/edx_ansible/server-vars.yml
with:
EDXAPP_FEATURES:
    ALLOW_ALL_ADVANCED_COMPONENTS: true

and restarted the appedx: and appedx_worker:

still the same result.

Thanks in advance,

**Comment by feanil** [comment]
What version of the edx-platform are you running?

cd /edx/app/edxapp/edx-platform && git rev-parse HEAD

-Feanil

**Comment by jessp01** [comment]
# cd /edx/app/edxapp/edx-platform && git rev-parse HEAD

bde4dc5fdb6b470db0de361bc87038faf4f5471c

Thanks,

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by feanil** [comment]
Is that the version you expect?   the LTI related changes were not released
till after the Cypress release.

**Comment by jessp01** [comment]
I am using the Vagrant image as described here:
https://github.com/edx/configuration/wiki/edx-Full-stack--installation-using-Vagrant-Virtualbox

Do I need to upgrade it to a diff version?

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by jessp01** [comment]
Regardless, the initial issue is that it does not save any of the values I put in.. so we are not even at the level in which support is missing, I think.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
