### ISSUE TITLE
Error installing Cypress production stack

### ISSUE THREAD

**Issue by prabhanshu** [openedx-unsupported/configuration#2275]
I am facing error while compiling assests during installation of Cypress Instance. 

TASK: [edxapp | gather {{ item }} static assets with paver] *******************
<localhost> REMOTE_MODULE command /edx/bin/edxapp-update-assets-cms
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1441870803.72-32109300495463 && echo $HOME/.ansible/tmp/ansible-tmp-1441870803.72-32109300495463']
<localhost> PUT /tmp/tmpyX50x7 TO /root/.ansible/tmp/ansible-tmp-1441870803.72-32109300495463/command
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=lddvdavbaptpamrglqnbbltimgtgtway] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-lddvdavbaptpa
mrglqnbbltimgtgtway; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1441870803.72-32109300495463/command; rm -rf /root/.ansible/tmp/ansible-tmp
-1441870803.72-32109300495463/ >/dev/null 2>&1'"'"''
failed: [localhost] => (item=cms) => {"changed": true, "cmd": ["/edx/bin/edxapp-update-assets-cms"], "delta": "0:01:47.510786", "end": "2015-09-10 07:41:51.282506", "item": "cms", "
rc": 1, "start": "2015-09-10 07:40:03.771720", "warnings": []}
stderr: 2015-09-10 03:40:05,850 INFO 12531 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
stdout: ---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py cms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"`
---> pavelib.assets.compile_sass
sass --update --cache-location /tmp/sass-cache --default-encoding utf-8 --style compressed --quiet --load-path common/static --load-path common/static/sass --load-path lms/static/sass --load-path lms/static/certificates/sass --load-path cms/static/sass --load-path common/static/sass lms/static/sass:lms/static/css lms/static/certificates/sass:lms/static/certificates/css cms/static/sass:cms/static/css common/static/sass:common/static/css
## Captured Task Output:

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
python manage.py cms --settings=aws preprocess_assets
xmodule_assets common/static/xmodule
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"`
---> pavelib.assets.compile_sass
sass --update --cache-location /tmp/sass-cache --default-encoding utf-8 --style compressed --quiet --load-path common/static --load-path common/static/sass --load-path lms/static/sass --load-path lms/static/certificates/sass --load-path cms/static/sass --load-path common/static/sass lms/static/sass:lms/static/css lms/static/certificates/sass:lms/static/certificates/css cms/static/sass:cms/static/css common/static/sass:common/static/css

Build failed running pavelib.assets.update_assets: Subprocess return code: 1
<localhost> REMOTE_MODULE command /edx/bin/edxapp-update-assets-lms
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1441870911.3-85089422561894 && echo $HOME/.ansible/tmp/ansible-tmp-1441870911.3-85089422561894']
<localhost> PUT /tmp/tmpxOlmkn TO /root/.ansible/tmp/ansible-tmp-1441870911.3-85089422561894/command
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=iinqopdctypppiripgmcdqrfmlltvycy] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-iinqopdctypppiripgmcdqrfmlltvycy; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1441870911.3-85089422561894/command; rm -rf /root/.ansible/tmp/ansible-tmp-1441870911.3-85089422561894/ >/dev/null 2>&1'"'"''
changed: [localhost] => (item=lms) => {"changed": true, "cmd": ["/edx/bin/edxapp-update-assets-lms"], "delta": "0:01:58.908827", "end": "2015-09-10 07:43:50.258990", "item": "lms", "rc": 0, "start": "2015-09-10 07:41:51.350163", "stderr": "2015-09-10 03:41:52,857 INFO 12639 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125\n2015-09-10 03:42:37,145 INFO 12716 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125", "stdout": "---> pavelib.assets.update_assets\n---> pavelib.prereqs.install_ruby_prereqs\n---> pavelib.prereqs.install_node_prereqs\npython manage.py lms --settings=aws preprocess_assets\nxmodule_assets common/static/xmodule\n---> pavelib.assets.compile_coffeescript\nnode_modules/.bin/coffee --compile `find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name \"*.coffee\"`\n---> pavelib.assets.compile_sass\nsass --update --cache-location /tmp/sass-cache --default-encoding utf-8 --style compressed --quiet --load-path common/static --load-path common/static/sass --load-path lms/static/sass --load-path lms/static/certificates/sass --load-path cms/static/sass --load-path common/static/sass lms/static/sass:lms/static/css lms/static/certificates/sass:lms/static/certificates/css cms/static/sass:cms/static/css common/static/sass:common/static/css\npython manage.py lms --settings=aws collectstatic --noinput > /dev/null", "warnings": []}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/start_instance.retry

localhost                  : ok=175  changed=60   unreachable=0    failed=1
# Content of the yml file 

---
# Start Edx
- name: Start instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    disable_edx_services: False
    service_variants_enabled:
      - cms
      - lms
    migrate_db: "yes"
    openid_workaround: True
  roles:
  - role: nginx
    nginx_sites:
    - cms
    - lms
  - edxapp
  - { role: 'edxapp', celery_worker: True }
  - { role: "xqueue", update_users: True }
  - role: ora
    update_users: True

I think the issue is not really to lms or cms, whichever item comes first in "service_variants_enabled" gives the error. For example, if I change the sequence of lms and cms in "service_variants_enabled" (putting lms in first), then lms assest gives the same issue.

If I execute the commands of the file "/edx/bin/edxapp-update-assets-cms" and "/edx/bin/edxapp-update-assets-lms" separately, it works fine.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
