### ISSUE TITLE
Enabling search and filter by category

### ISSUE THREAD

**Issue by sbalde** [openedx-unsupported/configuration#2288]
Hello Guys,

I followed the tutorial in order to enable the edx-search. The search is working well on studio but unfortunately it seems that something is wrong on LMS.

In fact, the search form is displayed on lms but when I try to search a course on LMS, no matching world is found..

See below, attached screenshoots

In addition, I would like to be able to filter the courses on LMS by category such as "business", "science", "politique" etc.
Is this feature currently available on Open-Edx? If so, how can I make it run? Otherwise, could someone help me to build this feature orsimply provide me a documentation about how to do this?

I'm running open-edx on a hosted Ubuntu 14.04

Hey @tusbar, sorry to bother, but if you have any background about the above issue and the complementary feature, I would be grateful if you could help. Thanks in advance!

![index_capture1](https://cloud.githubusercontent.com/assets/11218855/9962476/2cdfa01a-5e26-11e5-9b8b-7b559802a4e8.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11218855/9962681/4a90df92-5e27-11e5-9fe3-a22add2526c1.PNG)

Regards,
sbalde

**Comment by sbalde** [comment]
HEllo Guys,

I'm still looking for some help regarding this topic.

Thanks in advance for your help

**Comment by apollinaire70** [comment]
Hello sbalde,
i want to know if you finaly resolved tour edx search probleme because i'm now in the same case and i want a help

**Comment by raulperula** [comment]
Hi,

I am also in the same situation. I would like to categorize courses in several levels (easy, medium, advance) but I have not found anything about this topic.

I appreciate some help.

**Comment by apollinaire70** [comment]
i used this setting bellow and the search slide bar appear propelythe same
as de find courses buttom but when i tried to find a course or all courses
the systeme told me i couldn't find any result from my search.
I just replaced the "SEARCH_SKIP_ENROLLMENT_START_DATE_FILTERING = False"
flag by turning False to True and my problem was resolved but with that,
you will find all courses even if you don't set enrollment start and end
date. So if you finaly find the solution to find only courses whose
enrollment start end end date are set please send me an email

/edx/app/edxapp/edx-platform/cms/envs/common.py

'ENABLE_COURSEWARE_INDEX': True,

'ENABLE_LIBRARY_INDEX': True,

# Default to no Search Engine

SEARCH_ENGINE = "search.elastic.ElasticSearchEngine"

ELASTIC_FIELD_MAPPINGS = {

```
"start_date": {

    "type": "date"

}
```

}

/edx/app/edxapp/edx-platform/lms/envs/common.py

# Courseware search feature

```
'ENABLE_COURSEWARE_SEARCH': True,
```

 # Dashboard search feature

```
'ENABLE_DASHBOARD_SEARCH': True,
```

 # Course discovery feature

```
'ENABLE_COURSE_DISCOVERY': True,
```

# Use None for the default search engine

SEARCH_ENGINE = "search.elastic.ElasticSearchEngine"

# Use LMS specific search initializer

SEARCH_INITIALIZER
= "lms.lib.courseware_search.lms_search_initializer.LmsSearchInitializer"

# Use the LMS specific result processor

SEARCH_RESULT_PROCESSOR
= "lms.lib.courseware_search.lms_result_processor.LmsSearchResultProcessor"

# Use the LMS specific filter generator

SEARCH_FILTER_GENERATOR
= "lms.lib.courseware_search.lms_filter_generator.LmsSearchFilterGenerator"

# Override to skip enrollment start date filtering in course search

SEARCH_SKIP_ENROLLMENT_START_DATE_FILTERING = False

2016-06-28 14:07 GMT+00:00 Raúl Pérula-Martínez notifications@github.com:

**Comment by apollinaire70** [comment]
sorry do not forget to restart the apache server

2016-06-28 16:15 GMT+00:00 apollinaire samiey apoosamiey@gmail.com:

**Comment by Suraj-KD** [comment]
Hi Everyone,


I have performed all the steps and sets all the value as mentioned above, but still this is not working for me.


Can anyone help me out in this?


Thanks 
Suraj

**Comment by cristianpoleyJS** [comment]
+1
