### ISSUE TITLE
connection timeout to upstream port 8000

### ISSUE THREAD

**Issue by isural** [openedx-unsupported/configuration#2290]
Hi All,

I have installed Edx latest version. I have one problem while creating new user from web part (not django command) and also got this while trying to login with inactivated new user (Before user activate the account). I get the following error. I have checked 8000 port saw python service listened this and had success to connect on this port via telnet. why i got this problem? Any idea?    

==> /edx/var/log/nginx/error.log <==
2015/09/19 08:08:23 [error] 29646#0: *281 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxxx.xxxx.xxx, server: , request: "POST /user_api/v1/account/registration/ HTTP/1.1", upstream: "http://127.0.0.1:8000/user_api/v1/account/registration/", host: "moocs.anadolu.edu.tr", referrer: "http://moocs.anadolu.edu.tr/register"

Also browser hangs a while and create account stays disabled a while during this error.

Thank you for your help

Irfan

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
