### ISSUE TITLE
issue configuration third party auth sml2 in open edx Cypress

### ISSUE THREAD

**Issue by violantl** [openedx-unsupported/configuration#2309]
Hello everyone,
I have configured the module saml Third Party Authentication in edx Cypress following the guide
http://edx-installing-configuring-and-running.readthedocs.org/en/latest/configuration/tpa/index.html.
I finished configuring, I run the command
./manage.py lms saml pull --settings = aws
I get the error
File "./manage.py", line 15, in <module>
     from safe_lxml import defuse_xml_libs
ImportError: No module named safe_lxml

I have verified that the module is installed in the path
/edx/app/edxapp/edx-platform/common/lib/safe_lxml

how can I fix it?

thank you

**Comment by feanil** [comment]
Are you running the manage command from the correct virtualenv?  I usually
run '/edx/bin/python.edxapp /edx/bin/manage.edxapp ...' Which will use the
correct virtualenv.

**Comment by jerrykurian** [comment]
I am getting the exact same issue. Were you able to figure out a solution?

**Comment by jerrykurian** [comment]
Works when i  use the suggestion given by feanil. 
/edx/bin/python.edxapp /edx/bin/manage.edxapp lms saml pull --settings=aws

Thanks.

**Comment by violantl** [comment]
I have solved

thank you

**Comment by apssdc-ghouse** [comment]
please provide us the comment

**Comment by apssdc-ghouse** [comment]
please provide us the solution, how you have solved the issue

**Comment by x3medima17** [comment]
@apssdc-ghouse, he used vitualenv, /edx/bin/python.edxapp

**Comment by awaisdar001** [comment]
Thanks @feanil  this worked for me. 👍
