### ISSUE TITLE
Bitnami AMI Distribution / Instructions Disconnect

### ISSUE THREAD

**Issue by WoodMath** [openedx-unsupported/configuration#2337]
Hi,

Because my attempts using a VirtualBox/Vagrant as well as standalone Ubunutu installation result in errors, I'm not able to resolve. I'm forced to use the Amazon Web services option, including the Bitnami application.

I've followed the instructions located at https://wiki.bitnami.com/Applications/Bitnami_Open_edX#How_to_install_CodeJail.3f regarding the installation of CodeJail. But I'm lost as to what do next.

Part of it stems from a disconnect between the edx Provided instructions and the Bitnami image. Specifically the instructions provided by edx regarding the AMI (https://github.com/edx/configuration/wiki/Single-AWS-server-installation-using-Amazon-Machine-Image), as well as many other places on this wiki, reference non existent locations (those with the /edx folder in the root location), on the Bitnami AMI image.

I've successfully opened the instance of the LMS login and STUDIO logins, through accessing the 80 and 18010 ports respectively, but am not able to proceed any further. I've tried the logins I provided to edX as well as the **user@example.com** / **edx** userid / password combination provided by bitnami but does not seem to work.

-Jeff

**Comment by HintikkaKimmo** [comment]
I just simply created the user IDs. I also have issues with Bitnami image some services are not starting correctly. Currently studio is giving HTTP 500 error but I see nothing in the logs. I thing I will work from the other side and setup the Vagrant environment. 

I am more experienced in that side. Once I have done that I report the steps here if needed.

**Comment by WoodMath** [comment]
Ok.

How did you create the user ids?

I was more concerned about the students. If my UserID / password that I created with edX doesn't work, and I manually had to create one, the students that register for the course would have to do the same.

**Comment by WoodMath** [comment]
Unfortunately, on my Vagrant instance I can't past the generic Warning from Vagrant saying there was a problem with the provided image :-/

**Comment by HintikkaKimmo** [comment]
Downloading it now so lets see 30 min before fully donwloaded and build. Using internet shared from my phone... 

On the user you SSH to the bitnami box and do this. For that you need to be in the folder where your pem key is. Something like this > ssh -i "YourKey.pem" ubuntu@your IP should get you in. 

Then you can do something like this > 

create a new user - sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws create_user -e user@example.com
set or change password - sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws changepassword user
set user to staff - sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws set_staff user@example.com
launch the django shell - sudo -u www-data /edx/bin/python.edxapp ./manage.py lms --settings aws shell
create superuser (with profile) - Replace "user@example.com" with the email address you want to use, and replace "user" with the first part of the email address that you used. So for example, if you use "staff+87@yourdomain.com" for the email address, the username will be "staff+87"

**Comment by HintikkaKimmo** [comment]
Hmm.. Just tested some of this with bitnami image. Seems that they have completely broken the folder structure. Bin folder is at /apps/edx/edx-platform/bin not where the documentation says it is.

**Comment by WoodMath** [comment]
FYI. My vagrant file is giving the following when I do **vagrant up**. Meaning while, I'm sure Vagrant would be ideal (as the majority of instructions are using Vagrant), I don't have much choice but to use AWS

**The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.**

**If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.**

**The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.**

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
