### ISSUE TITLE
Update the ssh motd on Ubuntu

### ISSUE THREAD

**Issue by ANtlord** [openedx-unsupported/configuration#2356]
Hello! I have an issue related to installation edx full stack. I follow this tutorial https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation. And it seems I am in the end of the way. I've got error `fatal: [localhost] => error while evaluating conditional: vagrant_home_dir.stat.exists == false`.

Does it check home directory of vagrant? Need I vagrant for installation on sandbox? Or something another?

Please help this installation is killing me :-)

I use Ubuntu 12.04 as pointed in the tutorial. Python 2.7.10. I've upgraded python, because I got issue related urllib3. Some about OpenSSL object.

Thanks!

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
