### ISSUE TITLE
Error during add the mongodb signing key  

### ISSUE THREAD

**Issue by ivb1960** [openedx-unsupported/configuration#2375]
TASK: [mongo | install python pymongo for mongo_user ansible module] **********
changed: [localhost]

TASK: [mongo | add the mongodb signing key] ***********************************
failed: [localhost] => {"failed": true}
msg: Failed to download key at http://docs.mongodb.org/10gen-gpg-key.asc: HTTP Error 404: Not Found

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=60   changed=49   unreachable=0    failed=1

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
