### ISSUE TITLE
I encounter a problem in "sudo pip install -r requirements.txt"

### ISSUE THREAD

**Issue by lingchong2015** [openedx-unsupported/configuration#2377]
I install open edx followed by "https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation", I adopt Manual installation step because my operation system is Ubuntu 14.04 64 bit, everything is OK until I run the following command in terminal:
sudo pip install -r requirements.txt
and the error informatiion is list followed:
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Collecting ansible==1.9.3-edx from git+https://github.com/edx/ansible.git@stable-1.9.3-rc1-edx#egg=ansible==1.9.3-edx (from -r requirements.txt (line 1))
  Cloning https://github.com/edx/ansible.git (to stable-1.9.3-rc1-edx) to /tmp/pip-build-c07XBi/ansible
fatal: unable to access 'https://github.com/edx/ansible.git/': Failed to connect to github.com port 443: 连接超时
  Complete output from command git clone -q https://github.com/edx/ansible.git /tmp/pip-build-c07XBi/ansible:

---

Command "git clone -q https://github.com/edx/ansible.git /tmp/pip-build-c07XBi/ansible" failed with error code 128 in None
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
and sometimes, the error information is this followed:
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Collecting ansible==1.9.3-edx from git+https://github.com/edx/ansible.git@stable-1.9.3-rc1-edx#egg=ansible==1.9.3-edx (from -r requirements.txt (line 1))
  Cloning https://github.com/edx/ansible.git (to stable-1.9.3-rc1-edx) to /tmp/pip-build-bic7aG/ansible
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack failed
  Complete output from command git clone -q https://github.com/edx/ansible.git /tmp/pip-build-bic7aG/ansible:

---

Command "git clone -q https://github.com/edx/ansible.git /tmp/pip-build-bic7aG/ansible" failed with error code 128 in None
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
I don't known the reason, could anyone help me solving it, thank you!

**Comment by erphao** [comment]
I had the same error,why?

**Comment by oldsyang** [comment]
I had the same error,why?
