### ISSUE TITLE
TASK: [common | Install python-pycurl] failed

### ISSUE THREAD

**Issue by lingchong2015** [openedx-unsupported/configuration#2378]
I install open edx followed by "https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation", I adopt Manual installation step because my operation system is Ubuntu 14.04 64 bit, everything is OK until I run the following command in terminal:
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
:/var/tmp/configuration# cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
The error information is as followed:
TASK: [common | Install python-pycurl] ***************************************\* 
failed: [localhost] => {"failed": true}
msg: Could not fetch updated apt files

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=10   changed=1    unreachable=0    failed=1  
Counld anybody help me please? Thank you!

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
