### ISSUE TITLE
Installing open-edx on AWS Ubuntu 14.04 64-bit server without bitnami

### ISSUE THREAD

**Issue by atulcool81** [openedx-unsupported/configuration#2405]
Hi, I am using free version of AWS with Amazon Machine Image (AMI) is: Ubuntu Server 14.04 LTS (HVM), SSD Volume Type, with t2.micro instance. I have tried installing using the instruction given on: https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation. But while running the command: 
wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash

The error is showing that it can't install on Ubuntu 14.04. So I tried the instruction given on: http://www.dangtrinh.com/2014/09/edx-platform-install-open-edx-on.html

Now after following all the instruction it, the web page is showing: 

Welcome to nginx!  
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.
For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.
Thank you for using nginx.

So, my problem is I don't know what to do next. As I am going through the instruction: https://github.com/edx/configuration/wiki/edX-Managing-the-Full-Stack

It seems files and directories are missing like: edx-platform folder are not there.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
