### ISSUE TITLE
Issue with grading in openedx Cypress

### ISSUE THREAD

**Issue by violantl** [openedx-unsupported/configuration#2463]
Hello everyone, 
I have installed open edx cypress on ubuntu12.04. I have created a course and configured on the grade course and the subsections of the course. When User A accesses openedx and makes the course get a certain score, the user A makes logoff from openedx. User B connects to open edx and opening the tab show the progress as was done and its score (the score obtained by the user A).
How can I fix this?

**Comment by e0d** [comment]
I have never seen or heard of this issue before.  Are you sure that you are logging out completely?  If you go to the user profile screen or look in the top right of the courseware does the username say user B?

**Comment by violantl** [comment]
I'm sure you attach screenshots. I forgot the course is one scorm uploaded Scorm Cloud
![a](https://cloud.githubusercontent.com/assets/12657396/11092616/0b49f336-8885-11e5-8e39-d879f3e91e48.jpg)
![b](https://cloud.githubusercontent.com/assets/12657396/11092617/0b4bae60-8885-11e5-8947-5d77e9be5fd5.jpg)

**Comment by e0d** [comment]
I suspect an issue with the SCORM integration.  How are you achieving that?  To start debugging, example the student state for these users in the courseware_studentmodule table for the course.  Is there state identical?

**Comment by violantl** [comment]
The SCORM is loaded following the istructions of the guide http://blog.jazkarta.com/2015/02/08/adding-scorm-packages-to-open-edx-via-scormcloud-and-lti/#comment-15934

I do not know how you enable debug mode in open edx to check the problem better.

**Comment by e0d** [comment]
Start by connecting directly to the database and examining the student state for each user.
