### ISSUE TITLE
Install in ubuntu 14.04 vmware

### ISSUE THREAD

**Issue by johnfelipe** [openedx-unsupported/configuration#2472]
```
TASK: [mysql | look for mysql 5.5] ********************************************
failed: [localhost] => {"changed": true, "cmd": "dpkg -L mysql-server-5.5", "delta": "0:00:00.016734", "end": "2015-11-13 00:15:20.200984", "rc": 1, "start": "2015-11-13 00:15:20.184250", "warnings": []}
stderr: dpkg-query: package 'mysql-server-5.5' is not installed
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.


TASK: [edxapp | code sandbox | Use libblas for 3gf] ***************************
failed: [localhost] => {"changed": true, "cmd": ["update-alternatives", "--set", "libblas.so.3gf", "/usr/lib/libblas/libblas.so.3gf"], "delta": "0:00:00.002699", "end": "2015-11-13 00:16:55.299929", "rc": 2, "start": "2015-11-13 00:16:55.297230", "warnings": []}
stderr: update-alternatives: error: no alternatives for libblas.so.3gf

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/notroot/edx_sandbox.retry

localhost                  : ok=146  changed=24   unreachable=0    failed=1
```

Please tell me how solved

**Comment by sbernesto** [comment]
Find the file:

  /var/tmp/configuration/playbooks/roles/edxapp/tasks/python_sandbox_env.yml
Change this:

command: update-alternatives –set libblas.so.3gf /usr/lib/libblas/libblas.so.3gf

to:

command: update-alternatives –set libblas.so.3 /usr/lib/libblas/libblas.so.3

and this:

command: update-alternatives –set liblapack.so.3gf /usr/lib/lapack/liblapack.so.3gf

to:

command: update-alternatives –set liblapack.so.3 /usr/lib/lapack/liblapack.so.3

**Comment by e0d** [comment]
Pr please, ideally backward compatible.

Best

e0d

**Comment by johnfelipe** [comment]
how install in 0.0.0.0 no localhost, my local ip is variable
Tnks

**Comment by johnfelipe** [comment]
https://groups.google.com/forum/#!topic/openedx-ops/JVTLfW-_tV4
Any help?

**Comment by OmarIthawi** [comment]
@johnfelipe please take a look at https://github.com/edx/configuration/pull/2517

We've successfully used it to deploy to 14.04 machines.
