### ISSUE TITLE
Local modifications exist in repository

### ISSUE THREAD

**Issue by Omnia87** [openedx-unsupported/configuration#2540]
Dear all,

I've been looking all over for solutions to this problem but to no avail. Has anyone ever managed to get edx running on a windows platform to begin with? I've been trying to get this up and running at work for weeks now and no matter what I do I always get back to the stupid error about local modifications existing in the repository. It only does this on the second attempt, after it first fails to deal with the symlinks and gives me protocol errors. Surely this is a known issue because I've been trying to do it on several windows builds and different pc's and it keeps happening.

Also, on another note, why aren't all users for the shared folders present? I have to go into the Vagrantfile and change some of the users to 'edxapp' manually each time to get it to proceed.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
