### ISSUE TITLE
CMS "View Live" button points to wrong location

### ISSUE THREAD

**Issue by vytotas** [openedx-unsupported/configuration#2543]
# Steps to reproduce:
- Use vagrant fullstack CMS
- Login as staff@example.com
- go to Demonstration Course: http://192.168.33.10:18010/course/course-v1:edX+DemoX+Demo_Course
- click "View Live" button (top right side of the page)
## Expected result:

user gets  to LMS page http://192.168.33.10/courses/course-v1:edX+DemoX+Demo_Course/jump_to/block-v1:edX+DemoX+Demo_Course+type@course+block@course
## Actual result

User gets wrong url: http://courses/course-v1:edX+DemoX+Demo_Course/jump_to/block-v1:edX+DemoX+Demo_Course+type@course+block@course

**Comment by jsgang** [comment]
you should set LMS_BASE in lms.env.json and cms.env.json
