### ISSUE TITLE
[Full stack manual install] Allow ssh authentication - doubt about file change

### ISSUE THREAD

**Issue by ghost** [openedx-unsupported/configuration#2573]
Hi guys,

following the guide at https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation
I reach the point where I have to switch the password ssh auth on and I need to change the file located at: `configuration/playbooks/roles/common/defaults/main.yml`

Now if I check that file there is nothing written inside but a message stating this 

> Common variables are defined in the common_vars role on which this role depends.  This is to allow sharing vars without creating side-effects.  Any vars requred by this role should be added to common_vars/defaults/main.yml

If I browse to that file there is the entry `COMMON_SSH_PASSWORD_AUTH`and I can set it to yes.
Now is this just an old wiki entry or I should change exactly that file located at common/defaults?

Thanks

**Comment by jsgang** [comment]
This file have change to configuration/playbooks/roles/common_vars/defaults/main.yml

**Comment by ghost** [comment]
Ok so we should change the wiki in order to point directly to that path
