### ISSUE TITLE
--use-mirror incompatible with pip version 7.1.2

### ISSUE THREAD

**Issue by mikhailklassen** [openedx-unsupported/configuration#2576]
After trying to update the edX platform running on AWS from the latest AMI following [these](https://github.com/edx/configuration/wiki/Single-AWS-server-installation-using-Amazon-Machine-Image) instructions, I run into the following problem.

```
TASK: [edxapp | install python base-requirements] ***************************** 
failed: [localhost] => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i https://pypi.python.org/simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt ", "delta": "0:00:00.213446", "end": "2015-12-10 16:57:39.199154", "item": "", "rc": 2, "start": "2015-12-10 16:57:38.985708"}
stderr: 
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --use-mirrors

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ubuntu/edxapp.retry

localhost                  : ok=18   changed=8    unreachable=0    failed=1 
```

It appears that pip has changed to version 7.1.2, which no longer supports the --with-mirrors option. I believe this is a bug and it is preventing me from updating my AMI to the latest release.

**Comment by andreyfedoseev** [comment]
I guess that it was fixed in https://github.com/edx/configuration/commit/57e44e95da2ee1c23b7e5a7b4f74fc2ff7a97b66#diff-31a99e2a1e33dadc2542c5bb6ac6f086

As a quick fix you can remove all occurrences of `--use-mirrors` from `/edx/app/edx_ansible/edx_ansible/playbooks/roles/edxapp/tasks/deploy.yml`

**Comment by FremanZhang** [comment]
@andreyfedoseev Thanks a lot! Fixed as your instruction.

**Comment by mikhailklassen** [comment]
@andreyfedoseev Thank you!

**Comment by coldice** [comment]
I ran into the same problem when running the latest nightly.
