### ISSUE TITLE
/opt/wwc/edx-platform//manage.py lms --settings aws preprocess_assets --traceback

### ISSUE THREAD

**Issue by plejik-zz** [openedx-unsupported/configuration#260]
``/opt/wwc/edx-platform//manage.py lms --settings aws preprocess_assets --traceback 
Traceback (most recent call last):
  File "/opt/wwc/edx-platform//manage.py", line 90, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/wwc/edx-platform/lms/startup.py", line 9, in <module>
    settings.INSTALLED_APPS  # pylint: disable=W0104
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 95, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'lms.envs.aws' (Is it on sys.path?): No module named xblock.fields`
In file /usr/local/lib/python2.7/dist-packages/django/conf/**init**.py```

``````
 self.SETTINGS_MODULE = settings_module
try:
     93             mod = importlib.import_module(self.SETTINGS_MODULE)
     94         except ImportError, e:
     95             raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))```

asimble-playbook crash and stop at this string, what i should do?
``````

**Comment by feanil** [comment]
Hi Can you provide a bit more context for this.  It looks like your pythonpath is not set correctly.  Is this running in an ec2 instance? locally?  What command did you run?

**Comment by plejik-zz** [comment]
Run localy on server, issue it to update from master and not release , but i still dont know how use it for real project =(

**Comment by feanil** [comment]
Not sure what you mean by real project, if you just want to be building courses take a look at the vagrant images.

https://github.com/edx/configuration/wiki

If you want to run a production system of your own, you can find more info on that here: https://github.com/edx/configuration/wiki/AWS-Installation
