### ISSUE TITLE
Unable to add edx ppa apt key while running playbook common.yml  

### ISSUE THREAD

**Issue by DivyaMangotra** [openedx-unsupported/configuration#2604]
I am running the playbook ''common.yml" which was updated yesteday. It is failing at the task **"add edx ppa apt key"** with the following error:
stderr: gpg: requesting key 69464050 from http server pgp.mit.edu
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

stdout: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.OFNDDnqG80 --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver http://pgp.mit.edu --recv 69464050
gpgkeys: no key data found for http://pgp.mit.edu/

msg: gpg: requesting key 69464050 from http server pgp.mit.edu
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

FATAL: all hosts have already failed -- aborting

**Comment by arbabnazar** [comment]
@DivyaMangotra I have verified the above mentioned step and it worked for me, please re-run the playbook.

**Comment by FremanZhang** [comment]
@DivyaMangotra please refer to this https://github.com/edx/configuration/pull/2601
pgp server doesn't use http

**Comment by DivyaMangotra** [comment]
Worked. Thanks a ton.
