### ISSUE TITLE
Error when building from docker-compose.yml

### ISSUE THREAD

**Issue by dalareo** [openedx-unsupported/configuration#2617]
I get:

```
ERROR: Error: image edxops/nginx:v1 not found
```

**Comment by e0d** [comment]
Please note that this is still in the experimental, alpha phase.  I'll have
a look at that specific error when I have a chance.

Ed

**Comment by dalareo** [comment]
Images must be built first. Closing the issue

**Comment by dalareo** [comment]
Hey @e0d any progress making docker-compose working? I have built all the images but I cannnot guess the "links" between containers and env variables to make it run
