### ISSUE TITLE
ppa.edx.org seems offline

### ISSUE THREAD

**Issue by dmeziere** [openedx-unsupported/configuration#2633]
Unable to run Ansible, in the first steps, when it tries to "server_utils | Install system packages", the apt-get update crashes because of ppa.edx.org giving a 403. I tryed from two different locations, and with browsers as well. It's been 2 or 3 days long for now.

**Comment by e0d** [comment]
@dmeziere I'm unable to reproduce, I'd expect a 403 if you are trying to access from a brower.  I've just built a new box and python install from the PPA as expected.  Can you provide the output from ansible?

**Comment by dmeziere** [comment]
Thank you for your time.

[ansible_playbook.txt](https://github.com/edx/configuration/files/72245/ansible_playbook.txt)

[apt-get update.txt](https://github.com/edx/configuration/files/72246/apt-get.update.txt)

**Comment by e0d** [comment]
I see you are trying to install on 15.04, which we don't yet support.  We
have python for precise and lucid only in the ppa.

**Comment by dmeziere** [comment]
So it's not an issue. But i still don't understand why i can't even update my sources. Thank you.

**Comment by e0d** [comment]
What does sources.list look like.

**Comment by dmeziere** [comment]
Well, it should raise a 404 if Ubuntu 15.04 isn't supported. But the point is I can't even browse it with Iceweasel.

[ppa_edx_org.list.txt](https://github.com/edx/configuration/files/72460/ppa_edx_org.list.txt)

**Comment by e0d** [comment]
Should be easy to fix.  @feanil let's have a story for this.
