### ISSUE TITLE
There was an error while trying to write to Gemfile.lock

### ISSUE THREAD

**Issue by jsgang** [openedx-unsupported/configuration#2658]
TASK: [forum | install comments service bundle]  have err:
Using bundler (1.3.2) 
There was an error while trying to write to Gemfile.lock. It is likely that 
you need to allow write permissions for the file at path: 
/edx/app/forum/cs_comments_service/Gemfile.lock

**Comment by e0d** [comment]
I have a fix for this in a pr that should merge tomorrow.

**Comment by jsgang** [comment]
OK，thanks！

**Comment by fgyang** [comment]
There was an error while trying to write to Gemfile.lock. It is likely that 
you need to allow write permissions for the file at path: 
/edx/app/forum/cs_comments_service/Gemfile.lock
now also same problem

**Comment by fgyang** [comment]
how should I do?

**Comment by Anasgithub** [comment]
I have facing same problem while tryng to call **discussion-forum**:

you need to allow write permissions for the file at path: 
/edx/app/forum/cs_comments_service/Gemfile.lock

same problem

**Comment by e0d** [comment]
What version of the code are each of you running?  The commit should have fixed that issue: https://github.com/edx/configuration/commit/6207b9a

**Comment by touseefmurtaza** [comment]
I had the same issue, that's how i fixed mine.

If you are using **ZSH** then goto 

> profile -> command

 and check "Run command as a login shell" and close the terminal.
Fire up your terminal and initiate `bundle install` command.
