### ISSUE TITLE
ansible-bootstrap.sh file not found

### ISSUE THREAD

**Issue by eemirtekin** [openedx-unsupported/configuration#2693]
Hello All;
link is broken

https://raw.githubusercontent.com/edx/configuration/named-release/cypress/util/install/ansible-bootstrap.sh

**Comment by madvolume** [comment]
this is also broken, but it worked half an hour ago
https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh

**Comment by eemirtekin** [comment]
Thanks
it is working.
