### ISSUE TITLE
Cypress install is broken due to deleted `release` branch.

### ISSUE THREAD

**Issue by bardzusny** [openedx-unsupported/configuration#2709]
During regular install on EC2, following [edX Ubuntu 12.04 64 bit installation guide](https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation) to the letter.
### Error

Error happens during [`git checkout edx_ansible repo into edx_ansible_code_dir` task](https://github.com/edx/configuration/blob/master/playbooks/roles/edx_ansible/tasks/deploy.yml#L2). 

```
TASK: [edx_ansible | git checkout edx_ansible repo into edx_ansible_code_dir] ***
failed: [localhost] => {"failed": true}
msg: Failed to checkout release
FATAL: all hosts have already failed -- aborting 
PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/ubuntu/edx_sandbox.retry
localhost                  : ok=535  changed=273  unreachable=0    failed=1
```
### Reason

This is due to `edx_ansible` role configuration in [`named-release/cypress` branch](https://github.com/edx/configuration/blob/named-release/cypress.rc/playbooks/roles/edx_ansible/defaults/main.yml#L47) pointing to non-existent `release` branch. This was changed by #2296 in `master`, but left untouched on Cypress release branch.
### Workaround

Following [edX Ubuntu 12.04 64 bit installation guide](https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation): after encountering aforementioned error, edit `/var/tmp/configuration/playbooks/roles/edx_ansible/defaults/main.yml` and replace:

``` yaml
configuration_version: release
```

with:

``` yaml
configuration_version: "named-release/cypress"
```

Then re-launch `sandbox.sh` script.
### Solution

Straight solution would be to hotfix `named-release/cypress` branch with change described in **Workaround**. I am not sure what's the approach here to hotfixes on "frozen" release branches though (and thus not creating a PR). Another would be to restore `release` branch to keep Cypress release install process working.

Any better suggestions will be welcome - as it stands though, Cypress is still the last stable release, [described as being "supported"](https://openedx.atlassian.net/wiki/display/DOC/Open+edX+Releases). And thus it seems quite natural to assure that straightforward, working installation process is available.

**Comment by rpvilao-gymondo** [comment]
I'm running into the same issue when migrating and changing that is not working for me. Any clue how to do it?

**Comment by RizRiyz** [comment]
it's solved my issue

**Comment by bardzusny** [comment]
@nedbat could you provide a short comment on why this one was closed? (Sorry if fix was indeed backported to `named-release/cypress` branch - didn't touch edX lately.)

**Comment by nedbat** [comment]
@bardzusny with the release of Dogwood, Cypress is no longer supported.

**Comment by sigberto** [comment]
@bardzusny our fork still uses the cypress release. I'm trying to set up a devstack, but I'm running into this issue and the above fix doesn't work. Are there any other workarounds that you know of? Thanks!

**Comment by bardzusny** [comment]
@sigberto sorry, didn't set-up/work with Open edX for a while - thus won't be able to help you. Dogwood it is in the long-term, and switching to it is the only solution I can think of to be honest (and unavoidable in the future anyway).
