### ISSUE TITLE
'pycrypto' error when installing fullstack

### ISSUE THREAD

**Issue by danielmcquillen** [openedx-unsupported/configuration#2714]
I'm following the instructions to installing named-release/dogwood.rc fullstack on amazon, with the following steps:
- provision instance on EC2
- ssh in
- sudo apt-get update -y
- sudo apt-get upgrade -y
- sudo reboot
- ssh in
- export OPENEDX_RELEASE="named-release/dogwood.rc"
- sudo wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/ansible-bootstrap.sh -O - | sudo bash
- sudo wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash

The last step fails with the following trace from ansible:

`...
Found existing installation: pycrypto 2.4.1
Detected a distutils installed project ('pycrypto') which we cannot uninstall. The metadata provided by distutils does not contain a list of files which have been installed, so pip does not know which files to uninstall.
sudo: ansible-playbook: command not found
`

**Comment by abhinandanmalik** [comment]
Getting the same error on a new installation. This was working fine about a week ago.

**Comment by arbrandes** [comment]
This is pip 8.0.0's fault.  A simple fix is to force installation of pip 7.1.2 in sandbox.sh.  I'll issue a pull request referencing this issue momentarily.

**Comment by danielmcquillen** [comment]
Thanks @arbrandes. By the way, is this the place for these kind of bugs or on JIRA? I logged this issue there as well: https://openedx.atlassian.net/browse/PLAT-994

**Comment by danielmcquillen** [comment]
Tested #2716 on AWS and build completed without error.

**Comment by arbrandes** [comment]
@danielmcquillen, on JIRA vs. here:  good question.  From the bot's message on #2716, it seems issues here are fine, since they're automatically created on JIRA when one issues a PR here.

(I'm something of a newb where it comes to contributing to edx, so take that with a grain of salt.)
