### ISSUE TITLE
Running /edx/bin/update changes listen setting in nginx

### ISSUE THREAD

**Issue by danielmcquillen** [openedx-unsupported/configuration#2720]
I think this is a bug but perhaps my setup steps are missing something or are incorrect...

**To recreate**
1) Setup dogwood.rc on AWS using the normal published build steps.
2) Enable ports 80 and 18010 in security group.
3) Check that you can access lms and cms in your local browser.
4) ssh in to AWS instance.
5) Run `/edx/bin/update edx-platform named-release/dogwood.rc3`
6) Wait for process to finish.
7) Try to access lms and cms from your local browser

**Expected result**
You can still access lms and cms via browser.

**Actual result**
The cms is still available, but lms is blocked

**Analysis** 
If you check nginx sites-enabled file before doing the update, you'll see the correct port in the listen statement...

`ubuntu@my-aws-server:/etc/nginx/sites-enabled$ sudo cat /etc/nginx/sites-enabled/lms | grep listen
   listen 80 default;
`

And if you check the same file after the update, you'll see the wrong (?) port in the listen statement...

`ubuntu@my-aws-server:/etc/nginx/sites-enabled$ sudo cat /etc/nginx/sites-enabled/lms | grep listen
   listen 18000 default;
`

If you change the above line back to port 80, the site becomes available again.

Interesting that EDXAPP_LMS_NGINX_PORT is set to 80 in `playbooks/edx_sandbox.yml` https://github.com/edx/configuration/blob/a14c5ec7c949c6e578f1a3818410cc4070babf2d/playbooks/edx_sandbox.yml#L14

but in `playbooks/roles/edxapp/defaults/main.yml` it is set to 18000 https://github.com/edx/configuration/blob/b5aa3c2204d78b5e3654220915d7d493056b0335/playbooks/roles/edxapp/defaults/main.yml#L212

Perhaps this isn't a bug if it's expected that this variable should be set to 80 in server-vars.yml before running update, in that case perhaps the ["Updating Versions using edX repos"](https://github.com/edx/configuration/wiki/edX-Managing-the-Full-Stack#updating-versions-using-edx-repos) section in the Fullstack wiki documentation should be updated to include this step.

**Comment by mbdwey** [comment]
vote for this issue
i got the same issues using `named-release/dogwood` this release should be stable one but ....@@....
who think about the possibility off port change  !!

**Comment by edudemy** [comment]
I guess edx.org ec2 instance listens internally on 18000 vpc port fronted by the ELB instance.

**Comment by CrowbarKZ** [comment]
+1 I just run into the same issue

**Comment by aurishAtKnysys** [comment]
Thanks, saved the day

**Comment by Ivorforce** [comment]
+1 for issue and fix - we ran into this as well.
It's notable that our server-vars.yml did include _EDXAPP_LMS_BASE: server.com:80_ before running the update (at least after the most recent runs).

**Comment by codingec** [comment]
This is a bug and you should have the correct documentation to fix this
