### ISSUE TITLE
Problem updating edX

### ISSUE THREAD

**Issue by rodriguezdevera** [openedx-unsupported/configuration#2731]
Hello!
I'm trying to update edX platform using the update script:  
         sudo /edx/bin/update edx-platform master
And I am getting the next error:

TASK: [aws | lineinfile dest=/etc/network/interfaces.d/eth0.cfg regexp="^post-up /sbin/ifconfig eth0 mtu 1500" line="post-up /sbin/ifconfig eth0 mtu 1500" insertafter="^iface" ] ***
failed: [localhost] => {"failed": true, "rc": 257}
msg: Destination /etc/network/interfaces.d/eth0.cfg does not exist !

FATAL: all hosts have already failed -- aborting

When listing the directory /etc/network the iinterfaces.d directoy dosn't exist:

edxadmin@edx1-ubuntu12:$ sudo ls /etc/network -l
total 20
drwxr-xr-x   2 root root 4096 dic 23 10:15 if-down.d
drwxr-xr-x   2 root root 4096 dic 22 15:08 if-post-down.d
drwxr-xr-x   2 root root 4096 dic 22 15:08 if-pre-up.d
drwxr-xr-x   2 root root 4096 dic 23 10:15 if-up.d
-rw-r--r--     1 root root  488 dic  22 14:54 interfaces
lrwxrwxrwx  1 root root   12 dic   22 14:55 run -> /run/network

Any help?

**Comment by fgyang** [comment]
TASK: [forum | make Gemfile.lock writable by common_web_user] ****************\* 
failed: [localhost] => {"failed": true, "item": ""}
msg: this module requires key=value arguments (['path:', '/edx/app/forum/cs_comments_service/Gemfile.lock', 'owner:', 'www-data'])

the task:
- name:  git checkout forum repo into {{ forum_code_dir }}
  git: >
    dest={{ forum_code_dir }} repo={{ forum_source_repo }} version={{ forum_version }}
    accept_hostkey=yes
    force=yes
  sudo_user: "{{ forum_user }}"
  register: forum_checkout
  notify: restart the forum service
  tags:
  - install
  - install:code

# TODO: This is done as the common_web_user
- name: make Gemfile.lock writable by common_web_user
  file: >
    path: "{{ forum_code_dir}}/Gemfile.lock"
    owner: "{{ common_web_user }}"
  tags:
  - install
  - install:code
  - install:app-requirements

Any help?

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
