### ISSUE TITLE
bulk_email template

### ISSUE THREAD

**Issue by madvolume** [openedx-unsupported/configuration#2775]
Hello! I have some problems with changing bulk_email template.
I have no "bulk_email" page in my django admin interface and also my changings in [course_email_template](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/bulk_email/fixtures/course_email_template.json) do nothing.

What should i do to change default bulk email template? Help me plz

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
