### ISSUE TITLE
Developer Stack configuration wiki still refers to cypress release

### ISSUE THREAD

**Issue by coldice** [openedx-unsupported/configuration#2782]
The wiki guide on how to install the edX Developer Stack on [github](https://github.com/edx/configuration/wiki/edX-Developer-Stack) still refers to the deprecated cypress release. This is especially confusing, because the config script will ignore this and take the nightly instead. The wiki should probably refer to the place to find the latest stable release.

**Comment by nedbat** [comment]
Thanks, we've moved that page, and updated it.
