### ISSUE TITLE
problem installation open edx cypress in doker container

### ISSUE THREAD

**Issue by violantl** [openedx-unsupported/configuration#2785]
hi,I have a problem with the installation of open edx cypress in a container Doker ubuntu 12.04. The error is as follows:
TASK: [edxlocal | db user setup the edxapp] ***********************************
failed: [localhost] => {"failed": true}
msg: unable to connect to database, check login_user and login_password are correct or ~ / .my.cnf has the credentials

FATAL: Already all hosts have failed - aborting
I tried to create the ~ / .my.cnf files in / root on the description here

https://github.com/edx/configuration/wiki/Re-install-Open-edX-in-Ubuntu-12.04
not
I do not know what to enter as a user and password, since the installation is done by the script of ansible.

Can you help me.

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
