### ISSUE TITLE
sudo su does not work

### ISSUE THREAD

**Issue by mstfldmr** [openedx-unsupported/configuration#2798]
On a newly created Vagrant instance, `sudo su edxapp` command does not work, neighter does it give an error. `/edc/app/edxapp/edxapp_env` is not executed, PATH variable is not set and thus `paver` can not be found.

```
vagrant@precise64:~$ sudo su edxapp
vagrant@precise64:~$ 
vagrant@precise64:~$ 
vagrant@precise64:~$ paver devstack lms
No command 'paver' found, did you mean:
 Command 'pager' from package 'most' (universe)
 Command 'pager' from package 'w3m' (main)
 Command 'pager' from package 'lv' (universe)
 Command 'pager' from package 'less' (main)
 Command 'pager' from package 'jless' (universe)
 Command 'pager' from package 'util-linux' (main)
paver: command not found
vagrant@precise64:~$ 
```

The file /edc/app/edxapp/edxapp_env exists.

The shell for edxapp user is set to /bin/false in /etc/passwd:
`edxapp:x:1003:1006::/edx/app/edxapp:/bin/false`

**Comment by mstfldmr** [comment]
It was possible to switch to **edxapp** user with the command `sudo -Hu edxapp bash`.

```
vagrant@precise64:~$ sudo -Hu edxapp bash
edxapp@precise64:~/edx-platform$ cd
edxapp@precise64:~$ source edxapp_env 

```

**Comment by nedbat** [comment]
@mstfldmr you haven't said what kind of installation this is.  A fullstack installation is not meant to have a shell for edxapp.  If this was a devstack installation, then it looks like it didn't complete properly.  Can you give us more details?

**Comment by mstfldmr** [comment]
Hi @nedbat  it's a Devstack installation on Mac.

I followed:
- http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/devstack/install_devstack.html
- http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/devstack/run_devstack.html

**Comment by nedbat** [comment]
OK, then something went wrong during the install.  Do you still have the output?  If not, then it might be easier to start over to see where it went wrong.

**Comment by mstfldmr** [comment]
No, I don't have the output. Installation took too long and my Macbook froze. Later, I did `vagrant reload` and `vagrant provision`.

Is there a way to complete it, or should I start over?

**Comment by janghaludu** [comment]
@nedbat It happened with me too. On a mac.

@mstfldmr Got the following error message after `vagrant up`
`The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

Got the same error again after `vagrant provision` twice.

``

**Comment by janghaludu** [comment]
@mstfldmr  The complete output is about 3000 lines long and I am unable to post it here due to character limit. New to github and programming in general. Can you suggest some relevant parts of the installation output that I can share?

Thanks

**Comment by nedbat** [comment]
@janghaludu this is not a good place to get support.  The openedx-ops mailing list (https://groups.google.com/forum/#!forum/openedx-ops) or the Slack #ops channel (https://open.edx.org/blog/open-edx-slack) are good places to discuss problems.

You can put the output in a pastebin (https://www.youtube.com/watch?v=oCS0kU5VFA4) before asking your question so that people can see the output.

**Comment by delabi** [comment]
Hey, so what's the reason behind your work around? @mstfldmr ?

**Comment by Kaidanov** [comment]
thanks to @mstfldmr . changed a bit.

```
vagrant@precise64:~$ sudo -Hu edxapp bash
edxapp@precise64:~$ cd edx-platform/     ---(if needed because paver command activated from that folder)
edxapp@precise64:~/edx-platform$ paver devstack lms
```

worked for me
