### ISSUE TITLE
TASK : [ analytics_pipeline | grant access to table storing test data in output database] ***  fatal : [ localhost ] = > One or more undefined variables: ' dict object ' has no attribute 'user' FATAL: Already Have all hosts failed - aborting 

### ISSUE THREAD

**Issue by dajaramillo** [openedx-unsupported/configuration#2859]
When i run  
ansible-playbook -i localhost, -c local analytics_single.yml
I get the following error:
TASK : [ analytics_pipeline | grant access to table storing test data in output database] **\* 
fatal : [ localhost ] = > One or more undefined variables: ' dict object ' has no attribute 'user'
FATAL: Already Have all hosts failed - aborting 
Please help me.

**Comment by bradenmacdonald** [comment]
This has been fixed with #2857
