### ISSUE TITLE
edx install failed on TASK: [mongo | install mongo server and recommends]  please help me!

### ISSUE THREAD

**Issue by 91jaeyoung** [openedx-unsupported/configuration#2880]
TASK: [mongo | install mongo server and recommends] **************************\* 

failed: [localhost] => {"failed": true}
stderr: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

stdout: Reading package lists...
Building dependency tree...
Reading state information...
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libmysqlclient-dev : Depends: libmysqlclient18 (= 5.5.47-0ubuntu0.14.04.1) but 5.6.29-1ubuntu12.04 is to be installed
 libmysqlclient18 : Depends: mysql-common (= 5.6.29-1ubuntu12.04)

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" --force-yes  install 'mongodb-org=2.6.5'' failed: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

FATAL: all hosts have already failed -- aborting

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
