### ISSUE TITLE
Can't force https when 'insights | install bower dependencies' fails

### ISSUE THREAD

**Issue by peterorwa** [openedx-unsupported/configuration#2891]
Hello,

When performing the task [insights | install bower dependencies] I get an error that the connection timed out.. I've tried the fix where you use `git config --global url."https://".insteadOf git://` and even `git config --global url.https://github.com/.insteadOf git://github.com/` and nothing changes; the log still shows it using git:// instead of https:// . When I run `git config --list` I can see the insteadOf rules added but the script doesn't use them. Anyone have an idea? Or is it possible to install insights seperately then run the main script again? 

My logs: 
TASK: [insights | install bower dependencies] *********************************
failed: [localhost] => {"changed": true, "cmd": ". /edx/app/insights/nodeenvs/insights/bin/activate && /edx/app/insights/edx_analytics_dashboard/node_modules/.bin/bower install --production --config.interactive=false", "delta": "0:16:45.118766", "end": "2016-03-26 21:39:46.443117", "rc": 1, "start": "2016-03-26 21:23:01.324351", "warnings": []}
stderr: bower edx-ui-toolkit#1e025d169f28632cf903274f3ef8aaf6e2fd6825        ECMDERR Failed to execute "git clone git://github.com/edx/edx-ui-toolkit.git /tmp/insights/bower/1afbae041d7882dbccd1adaf3684af45-18459-NU3LYz --progress", exit code of #128 fatal: read error: Connection timed out

Additional error details:
fatal: read error: Connection timed out
stdout: bower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0       not-cached git://github.com/overset/javascript-natural-sort.git#dbf4ca259b327a488bd1d7897fd46d80c414a7e0
bower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0          resolve git://github.com/overset/javascript-natural-sort.git#dbf4ca259b327a488bd1d7897fd46d80c414a7e0
bower edx-ui-toolkit#1e025d169f28632cf903274f3ef8aaf6e2fd6825     not-cached git://github.com/edx/edx-ui-toolkit.git#1e025d169f28632cf903274f3ef8aaf6e2fd6825
bower edx-ui-toolkit#1e025d169f28632cf903274f3ef8aaf6e2fd6825        resolve git://github.com/edx/edx-ui-toolkit.git#1e025d169f28632cf903274f3ef8aaf6e2fd6825
bower bootstrap-sass-official#v3.2.0+2                            not-cached git://github.com/twbs/bootstrap-sass.git#v3.2.0+2
bower bootstrap-sass-official#v3.2.0+2                               resolve git://github.com/twbs/bootstrap-sass.git#v3.2.0+2
bower bootstrapaccessibilityplugin#~1.0.3                         not-cached git://github.com/paypal/bootstrap-accessibility-plugin.git#~1.0.3
bower bootstrapaccessibilityplugin#~1.0.3                            resolve git://github.com/paypal/bootstrap-accessibility-plugin.git#~1.0.3
bower globalize#1.0.0-alpha.17                                    not-cached git://github.com/jquery/globalize.git#1.0.0-alpha.17
bower globalize#1.0.0-alpha.17                                       resolve git://github.com/jquery/globalize.git#1.0.0-alpha.17
bower backbone#~1.1.2                                             not-cached git://github.com/jashkenas/backbone.git#~1.1.2
bower backbone#~1.1.2                                                resolve git://github.com/jashkenas/backbone.git#~1.1.2
bower d3#~3.3.13                                                  not-cached git://github.com/mbostock-bower/d3-bower.git#~3.3.13
bower d3#~3.3.13                                                     resolve git://github.com/mbostock-bower/d3-bower.git#~3.3.13
bower requirejs#~2.1.15                                           not-cached git://github.com/jrburke/requirejs-bower.git#~2.1.15
bower requirejs#~2.1.15                                              resolve git://github.com/jrburke/requirejs-bower.git#~2.1.15
bower requirejs-plugins#~1.0.3                                    not-cached git://github.com/millermedeiros/requirejs-plugins.git#~1.0.3
bower requirejs-plugins#~1.0.3                                       resolve git://github.com/millermedeiros/requirejs-plugins.git#~1.0.3
bower underscore#~1.8.2                                           not-cached git://github.com/jashkenas/underscore.git#~1.8.2
bower underscore#~1.8.2                                              resolve git://github.com/jashkenas/underscore.git#~1.8.2
bower jasmine#~2.0.4                                              not-cached git://github.com/pivotal/jasmine.git#~2.0.4
bower jasmine#~2.0.4                                                 resolve git://github.com/pivotal/jasmine.git#~2.0.4
bower moment#~2.8.3                                               not-cached git://github.com/moment/moment.git#~2.8.3
bower moment#~2.8.3                                                  resolve git://github.com/moment/moment.git#~2.8.3
bower topojson#~1.4.3                                             not-cached git://github.com/mbostock/topojson-bower.git#~1.4.3
bower topojson#~1.4.3                                                resolve git://github.com/mbostock/topojson-bower.git#~1.4.3
bower datatables#~1.10.2                                          not-cached git://github.com/DataTables/DataTables.git#~1.10.2
bower datatables#~1.10.2                                             resolve git://github.com/DataTables/DataTables.git#~1.10.2
bower font-awesome#~4.2.0                                         not-cached git://github.com/FortAwesome/Font-Awesome.git#~4.2.0
bower font-awesome#~4.2.0                                            resolve git://github.com/FortAwesome/Font-Awesome.git#~4.2.0
bower cldr-data#26.0.3                                            not-cached git://github.com/rxaviers/cldr-data-bower.git#26.0.3
bower cldr-data#26.0.3                                               resolve git://github.com/rxaviers/cldr-data-bower.git#26.0.3
bower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0         checkout dbf4ca259b327a488bd1d7897fd46d80c414a7e0
bower nvd3#~1.1.15-beta                                           not-cached git://github.com/novus/nvd3.git#~1.1.15-beta
bower nvd3#~1.1.15-beta                                              resolve git://github.com/novus/nvd3.git#~1.1.15-beta
bower jquery#~1.11.1                                              not-cached git://github.com/jquery/jquery-dist.git#~1.11.1
bower jquery#~1.11.1                                                 resolve git://github.com/jquery/jquery-dist.git#~1.11.1
bower datamaps#~0.3.4                                             not-cached git://github.com/markmarkoh/datamaps.git#~0.3.4
bower datamaps#~0.3.4                                                resolve git://github.com/markmarkoh/datamaps.git#~0.3.4
bower edx-ui-toolkit#1e025d169f28632cf903274f3ef8aaf6e2fd6825       checkout 1e025d169f28632cf903274f3ef8aaf6e2fd6825

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
INFO:ansible.callback_plugins.datadog_tasks_timing:insights | install bower dependencies ------------------------------------------ 1005.19s
INFO:ansible.callback_plugins.datadog_tasks_timing:edxapp | gather {{ item }} static assets with paver ---------------------------- 444.11s
INFO:ansible.callback_plugins.datadog_tasks_timing:edxapp | install python requirements -------------------------------------------- 61.49s
INFO:ansible.callback_plugins.datadog_tasks_timing:server_utils | Install system packages ------------------------------------------ 33.87s
INFO:ansible.callback_plugins.datadog_tasks_timing:edx_service | get instance information ------------------------------------------ 30.11s
INFO:ansible.callback_plugins.datadog_tasks_timing:nginx | Install the nginx package ----------------------------------------------- 27.05s
INFO:ansible.callback_plugins.datadog_tasks_timing:mongo | install mongo server and recommends ------------------------------------- 26.53s
INFO:ansible.callback_plugins.datadog_tasks_timing:common | Install role-independent useful system packages ------------------------ 24.92s
INFO:ansible.callback_plugins.datadog_tasks_timing:edxapp | install system packages on which LMS and CMS rely ---------------------- 24.65s
INFO:ansible.callback_plugins.datadog_tasks_timing:edxapp_common | Install system packages ----------------------------------------- 23.91s
INFO:ansible.callback_plugins.datadog_tasks_timing:
Playbook edx_sandbox finished: Sat Mar 26 21:39:46 2016, 321 total tasks.  0:30:35 elapsed.

```
       to retry, use: --limit @/home/otienofx/edx_sandbox.retry
```

localhost                  : ok=345  changed=66   unreachable=0    failed=1

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
