### ISSUE TITLE
ERROR: command is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by erphao** [openedx-unsupported/configuration#2907]
https://openedx.atlassian.net/wiki/display/OpenOPS/Native+Open+edX+Ubuntu+12.04+64+bit+Installation
I use this blog to install,when 
cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"

it's error:command is not a legal parameter in an Ansible task or handler

I use :ansible --version
result:
ansible 1.9.3-edx
 configured module search path = None

**Comment by nedbat** [comment]
Sorry we have left this issue untended for so long.  GitHub issues are not meant for support questions.  Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.

**Comment by andresStanMaster** [comment]
i have the same problem could someone help please
![20160630_211056](https://cloud.githubusercontent.com/assets/20245196/16526478/1a80971e-3fba-11e6-92f1-9a2113d973fc.jpg)

**Comment by arbabnazar** [comment]
can you run with `-vvvv` and paste the error:

```
 sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost," -vvvv
```

**Comment by nedbat** [comment]
I would prefer you get support via the mailing lists or Slack.

**Comment by andresStanMaster** [comment]
arbabnazar the code doesnt work?????
