### ISSUE TITLE
EdX installation

### ISSUE THREAD

**Issue by tinoyjohn** [openedx-unsupported/configuration#2998]
Hi,

I am trying to install edX on my ubuntu 12.04 and followed the instructions here "https://openedx.atlassian.net/wiki/display/OpenOPS/Native+Open+edX+Ubuntu+12.04+64+bit+Installation" and i am facing a lot of errors during the process. I am unable to go forward with it as i am a noob. Can anyone help me out with the proper installation instructions?

Regards,
Tinoy John

**Comment by jibsheet** [comment]
Hi

GitHub issues are not meant for support questions. Please use the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) or [Slack channels](https://open.edx.org/blog/open-edx-slack) to get help.
