### ISSUE TITLE
Starting ElasticSearch Server ... fail!

### ISSUE THREAD

**Issue by huynq55** [openedx-unsupported/configuration#320]
I did all steps at https://github.com/edx/configuration/wiki to install edX on a single Ubuntu 12.04 (Precise) server.

But at last step: sudo ansible-playbook -c local --limit "localhost:127.0.0.1" \
./edx_sandbox.yml -i "localhost,"

it can not continue because of an error:

Task: [elasticsearch | Ensure elasticsearch is enabled and started]
failed: [localhost] => {"failed": true, "item": ""}
msg: \* Starting ElasticSearch Server
... fail!
FATAL: all hosts have already failed -- aborting

I dont know why i get this error. It's a fresh installation of Ubuntu server 12.04 on VMware.

Plz help me fix that, tks!

**Comment by RomainBrunias** [comment]
Hi, I have reached the same point as you did and I have exactly the same error.
I am running the edx_sandbox.yml in a precise32 box + vagrant.

**Comment by jarv** [comment]
please try this again against the latest release using recent docs and let us know if you still see the issue.
