### ISSUE TITLE
estimated cost for the shortstack EDX

### ISSUE THREAD

**Issue by mmjazzar** [openedx-unsupported/configuration#323]
thank you for your efforts in this great projet.

I wonder how does it cost to host EDX in Amazon CloudFormation ???

for the minmum requiremnts of resources, if I don't want to use redundant classes of servers for fault tolerance. I need just an estimation for 1k users in the beginning the cost  to decide if my budget would be enough for EDX or not.

thank you again

**Comment by mmjazzar** [comment]
any suggestions ?

**Comment by jbau** [comment]
At Stanford, where our platform runs ~20 courses, our monthly cost is on the order of $1K a month.  (order of magnitude.  mantissa is unspecified and could be anything)

**Comment by mmjazzar** [comment]
so for a small system also it will cost also a large number per month ??

**Comment by solitaryr** [comment]
You can use http://calculator.s3.amazonaws.com/calc5.html to estimate costs in Amazon.  You can browse the config json files to see what it would create and plug that into your selected region.
