### ISSUE TITLE
EDX Email configuration

### ISSUE THREAD

**Issue by iouss** [openedx-unsupported/configuration#3345]
Hello Guys,

I have tried to configure the email for EDX and Studio but i failed !! :( , I can't recive the activation email, I use the admin console to activate them manually.
Please could you tell me where is the file where I can change all email@example.com ?
Also, where can I change this link "http://localhost/login#forgot-password-modal" when I click on reset password ?

Thnaks for your help!

**Comment by jibsheet** [comment]
Hi - issues in this repository are for bugs in the configuration repo, not for general OpenEDX support.
You can find a list of resources here https://open.edx.org/getting-help
