### ISSUE TITLE
Analytics installation - protobuf download link need to be updated

### ISSUE THREAD

**Issue by Aelshafei** [openedx-unsupported/configuration#3353]
ansible playbook installation for analytics fail in the following task :

```
TASK: [hadoop_common | protobuf downloaded] ***********************************
failed: [localhost] => {"dest": "/var/tmp", "failed": true, "gid": 0, "group": "root", "mode": "01777", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "https://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz"}
msg: Request failed

FATAL: all hosts have already failed -- aborting
```

When trying the link, it can be seen not working and need to be replaced by the new links here :
https://github.com/google/protobuf/releases?after=v2.6.1

Can anyone of the contributors change the following file :
**/playbooks/edx-east/roles/hadoop_common/defaults/main.yml**

and update the following line :
`url: "https://protobuf.googlecode.com/files/protobuf-{{ HADOOP_COMMON_PROTOBUF_VERSION }}.tar.gz"
`

**Comment by oadussang** [comment]
same version needs to be used

https://github.com/google/protobuf/releases/tag/v2.5.0

**Comment by aqt01** [comment]
I have the same issue. I suggest to move to replace the link with 
https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz (the same version)

**Comment by ghost** [comment]
This error was corrected on: 
https://github.com/edx/configuration/commit/e50215e5a7c11d73adb24e318dd19171827e2993

I personally modified it for my personal use on eucalyptus.2 in this way

"https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-{{ HADOOP_COMMON_PROTOBUF_VERSION }}.tar.gz"
