### ISSUE TITLE
Xenial blocker: can't install openjdk-7-jdk

### ISSUE THREAD

**Issue by nedbat** [openedx-unsupported/configuration#3491]
Installing a Native install from ned/xenial-native, the installation eventually fails with:
```
TASK: [edx_service | Install a bunch of system packages on which edx_service relies] ***
failed: [localhost] => (item=libmysqlclient-dev,build-essential,gettext,openjdk-7-jdk) => {"failed": true, "item": "libmysqlclient-dev,build-essential,gettext,openjdk-7-jdk"}
msg: No package matching 'openjdk-7-jdk' is available

FATAL: all hosts have already failed -- aborting
```
@edx/analytics: Will openjdk-8 work for you?
/cc @edx/devops

**Comment by dsjen** [comment]
@nedbat -- I think jdk 8 should work.  We use closure to compress our javascript and were using 7 just because...  Do you need definitive confirmation?

**Comment by nedbat** [comment]
@dsjen I can try swapping it, but will need your help to verify that it does what you need.

**Comment by dsjen** [comment]
@nedbat -- ok!  Essentially if the JS is served up correctly on a production-like environment, we should be good to go.  I'm happy to help verify.

**Comment by nedbat** [comment]
Installing with openjdk-8-jdk was successful. Still need to try it when running.

**Comment by nedbat** [comment]
I'll close this installation issue, since the install is successful.
