### ISSUE TITLE
forum_ruby_version defaults to 1.9.3, out of support since Feb 2015 

### ISSUE THREAD

**Issue by fghaas** [openedx-unsupported/configuration#3589]
The default for `forum_ruby_version` in the forum role is `1.9.3-p551`. Support for Ruby 1.9.3 [ended in February 2015](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/), and running anything on this Ruby version must be considered a security risk.

**Comment by tobz** [comment]
We're in the process of moving back to 2.x.  The long story short is that there was some weirdness going on with memory usage when we switched to 2.3 before.
