### ISSUE TITLE
ecomworker can't connect to celery

### ISSUE THREAD

**Issue by nedbat** [openedx-unsupported/configuration#3611]
From Slack: https://openedx.slack.com/archives/ops/p1484672679001328

> the error message that the others have mentioned, it appears in */edx/var/log/ecomworker/edx.log* and says:
> 
> Jan 11 18:17:29 ip-172-31-20-176 [service_variant=ecomworker][celery.worker.consumer][env:no_env] ERROR [ip-172-31-20-176  1229] [consumer.py:364] - consumer: Cannot connect to amqp://celery:**@172.31.20.176:5672//: [Errno 111] Connection refused.
> 
> This is because RabbitMQ listens on port 5672 only on the *localhost* interface, while module *ecomworker* is trying to contact it via IP address assigned to the *eth0* interface. I believe the offending piece of configuration is set in the $BROKER_URL environment variable. In the already installed system, this can be modified in files */edx/etc/ecommerce.yml* and */edx/etc/ecomworker.yml* by setting *BROKER_URL:* *amqp://celery:celery@localhost:5672*. Here, *localhost* is used instead of the IP address of *eth0* interface. (Then, restart your machine to make sure it works).

This is using open-release/ficus.1rc1
cc @gsong

**Comment by k-solnushkin** [comment]
The change would _likely_ entail changing:

> \# Used as the default RabbitMQ IP.
> ECOMMERCE_BROKER_HOST: '{{ ansible_default_ipv4.address }}'

to:

> \# Used as the default RabbitMQ IP.
> ECOMMERCE_BROKER_HOST: 'localhost'   # Or '127.0.0.1'

in the *configuration* repository, in files *playbooks/roles/ecommerce/defaults/main.yml* and *playbooks/roles/ecomworker/defaults/main.yml*.

But I can see "git blame" telling me that exactly the opposite change was introduced in commit https://github.com/edx/configuration/commit/02ad039824138e439b0357db4f3a93352410d16d by Renzo Lucioni on 21 Sep 2015. There must have been very valid reasons why he decided to change that from *127.0.0.1* to *'{{ ansible_default_ipv4.address }}'*.

**Comment by gsong** [comment]
@edx/devops or @rlucioni Should the host IP be the default setting or should loopback be the default setting? We can also override at the playbook level or at `ansible-playbook` runtime.

@k-solnushkin Thank you for finding the root cause so quickly.

**Comment by rlucioni** [comment]
For context, here's the discussion on the PR where this was introduced: https://github.com/edx/configuration/pull/2295#discussion-diff-40365359.

**Comment by e0d** [comment]
Hmm, I'd like to here from @rlucioni about the change.  It should not matter here, but RabbitMQ itself is sensitive about having hostnames, rather than IPs, for cluster configuration.

**Comment by k-solnushkin** [comment]
@gsong Sure, George, glad I could be useful.

My findings were based on the ports where RabbitMQ is listening at in a fresh **ficus.1rc1** installation:

> $ sudo netstat -ntlp | grep beam
> tcp        0      0 127.0.0.1:5672          0.0.0.0:*               LISTEN      23581/beam
> tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      23581/beam
> tcp        0      0 0.0.0.0:55672           0.0.0.0:*               LISTEN      23581/beam
> tcp        0      0 0.0.0.0:34972           0.0.0.0:*               LISTEN      23581/beam

So, port 5672 is listening at **localhost** only, and the other 3 ports are listening on all interfaces (which may also be considered a security risk, in light of the recent MongoDB debacle)
