### ISSUE TITLE
error when "Installing edX on a single Ubuntu 12.04 (Precise) server"

### ISSUE THREAD

**Issue by aochoangden313** [openedx-unsupported/configuration#363]
Hello everyone, I am installing follow the guide from this link "https://github.com/edx/configuration/wiki", but when I Run the edx_sandbox.yml playbook in the configuration/playbooks directory by this command : 
cd /var/tmp/configuration/playbooks
sudo ansible-playbook -c local --limit "localhost:127.0.0.1" \
./edx_sandbox.yml -i "localhost,"

It give me a error "sudo: ansible-playbook: command not found"
How to fix it? 
Thank you so much!

**Comment by pchiu33** [comment]
Hi,

Did you follow all previous steps preceding the ansible-playbook command?
(especially the "sudo pip install -r requirements.txt" part)

## 

P.

2013/10/26 aochoangden313 notifications@github.com

**Comment by aochoangden313** [comment]
yes, I have requirements.txt on the configuration folder 
It have "ansible==1.3.2" at the last

**Comment by pchiu33** [comment]
You really have to go through _all_ the steps described here https://github.com/edx/configuration/wiki#installing-edx-on-a-single-ubuntu-1204-precise-server in order to have the edx sandbox running..

**Comment by aochoangden313** [comment]
yes, I has flow this guide. My mine is follow this steps and have this trouble. I will be try "sudo pip install -r requirements.txt" again
I just has started, so I don't know any thing about this :(

**Comment by pchiu33** [comment]
Could you send the console output of "sudo pip install -r requirements.txt"?

**Comment by aochoangden313** [comment]
Oh, after try "sudo pip install -r requirements.txt" again, I can do it. Maybe, I was wrong in a step ^^ thank you for support ^^

**Comment by aochoangden313** [comment]
Sorry Philippe Chiu, after I run the edx_sandbox.yml playbook in the configuration/playbooks directory  
!
this is my terminal 
[quan 2 - ubuntu](https://f.cloud.github.com/assets/5780452/1415044/2a4a45cc-3ed3-11e3-9a29-0f5428c0de60.png)
But I don't know how to connect the server. I write "localhost:80" to my browser, firefox on the ubuntu, but It can't connect. Can you help me?

**Comment by pchiu33** [comment]
Hi,

As long as the ansible-playbook command isn't finished you won't be able to properly access the sandbox. You should wait until you get an output that will look like :

PLAY RECAP *******************************************************************\* 
localhost                  : ok=XXX   changed=XXX    unreachable=0    failed=0   <--- this value must be 0

**Comment by aochoangden313** [comment]
After wating for it finish, it have some errors 
![quan 2 - ubuntu](https://f.cloud.github.com/assets/5780452/1446025/482801dc-4230-11e3-9285-a616954ee352.png)
I don't know how to fix it :( I has tried some times but it is still wrong :((

**Comment by pchiu33** [comment]
There seems to be an issue downloading some required Ubuntu package from
Ubuntu repositories.

2 hypothesis here :
- Check your internet connexion and try to identify why the packages are
  not properly downloaded (if you're not in the US, maybe you should try
  another ubuntu mirror closer to you - https://wiki.ubuntu.com/Mirrors)
- Are you running the "ansible-playbook" with sudo ? (likely since more
  than a 100 tasks ran properly)

## 

P.

2013/10/31 aochoangden313 notifications@github.com

**Comment by janadel** [comment]
Did you ever find a solution for this problem ?
Same problem here.

**Comment by aochoangden313** [comment]
I haven;t yet fix it. :( I did like the guide but I didn't understand why :(
I temporarily stopped it in time because of I must do another thing - more simple :(

**Comment by janadel** [comment]
Thanks for your answer.
I found it was due to low memory resources. I resized my vps to use 2 GB Ram and it worked fine.

**Comment by aochoangden313** [comment]
Thank you ^^ I will try it again

**Comment by hkim823** [comment]
Closing this issue, a lot has changed in 2 months with the setup of edX, please open a new issues if you are still having issues standing up edX.
