### ISSUE TITLE
Mysql user name generated by bash script is too long

### ISSUE THREAD

**Issue by danielmcquillen** [openedx-unsupported/configuration#3716]
The new `generate-passwords.sh` file sets the default username for `EDXAPP_MYSQL_REPLICA_USER` ansible variable to "edxapp_replica001"

This will cause an error on MySQL < 5.7.8 since it’s greater than 16 characters.

(A side note: it may be confusing to some users that username defaults are set in a file that mostly contains passwords. Perhaps rename bash script or include a comment at the top to indicate that more than just passwords are generated?)

**Comment by nedbat** [comment]
@e0d Know anything about this username length issue?
