### ISSUE TITLE
devstack doesn't have necessary codecs installed for HLS playback

### ISSUE THREAD

**Issue by gsong** [openedx-unsupported/configuration#3728]
@muhammad-ammar reported that HLS playback is needed for JavaScript testing. However, out of the box, devstack is not able to run the demo at <http://dailymotion.github.io/hls.js/demo> successfully. This is because the H.264 codec isn't installed by default.

The workaround is to install the package by hand within the VM:

```sh
sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y  ubuntu-restricted-extras
```

Long term we should convert this into a role and install into devstack.

/cc @edx/testeng @nedbat

**Comment by benpatterson** [comment]
@gsong Just for clarification...what system actually needs this (is it the browser, or is it the django app)? 

I'm assuming the `browsers` role would be a good place for this; however I wanted to ask if I am understanding it right.

**Comment by gsong** [comment]
@benpatterson: The browsers need this, presumably for some flavor of e2e testing.

@muhammad-ammar: Can you elaborate which specific tests you're trying to run that caused this issue to surface?

**Comment by muhammad-ammar** [comment]
Thanks @gsong for the quick solution.

@gsong @benpatterson I am currently adding [HLS playback support](https://github.com/edx/edx-platform/pull/14514) and now writing Jasmine tests. JS tests run in Firefox and due to the missing codec, HLS videos are not able to play.

**Comment by benpatterson** [comment]
Basic question, perhaps, @muhammad-ammar but will users need to download something special when using edX when you add this feature? In some ways the failure you're seeing when it fails to play anything...should we anticipate that happening to users?

**Comment by muhammad-ammar** [comment]
@benpatterson As per my understanding developed from hls.js, we don't need any separate codec. We just need the right version for a browser and HLS videos should be playable.  I have performed basic testing on Windows, Ubuntu and Mac OS and HLS videos are playable without need to download any codec. We will throughly test on different browsers on different operating systems. And to do this testing i am looking for some cloud based cross browser testing service.
