### ISSUE TITLE
Having an error when following "Installing edX on a single Ubuntu 12.04 (Precise) server"

### ISSUE THREAD

**Issue by tummykung** [openedx-unsupported/configuration#374]
Hi,

I adapted the previous one-line installer script to run the installation as follows on a newly created Ubuntu 12.04 on AWS: https://gist.github.com/tummykung/a8e86cf1d3e1f5244233

But I got an error: https://gist.github.com/tummykung/345ce934acc9c037dd18

So I ran

sudo ansible-playbook -vvvv -c local --limit @/home/ubuntu/edx_sandbox.retry ./edx_sandbox.yml -i "localhost," -e "EDXAPP_LMS_PREVIEW_NGINX_PORT=80 EDXAPP_LMS_BASE=$LMS_BASE"

Then I got another error: https://gist.github.com/tummykung/5fa6e09f42bfc88b4d0c

I'm not sure how to go from here. Any help is appreciated!

Thanks,
Tum

**Comment by jarv** [comment]
@tummykung are you still having issues? Have you been able to install from a clean 12.04 image using vagrant?

**Comment by tummykung** [comment]
I found out from the log file that there wasn't enough memory in the server. So I increased the space and this is okay now.
