### ISSUE TITLE
Docker image edxops/nginx:v1 not published

### ISSUE THREAD

**Issue by jmatsushita** [openedx-unsupported/configuration#3741]
Hi there,

This image is referenced in the docker-compose.yml file but isn't published.

Cheers!

Jun

**Comment by danilopimenta** [comment]
Generating this error:
Pulling nginx (edxops/nginx:v1)...
ERROR: manifest for edxops/nginx:v1 not found

**Comment by jibsheet** [comment]
I suspect you want to be working with the folks in https://github.com/edx/devstack (developer docker tools) rather than this docker compose file
