### ISSUE TITLE
Errors during Open edX migration task: Could not load Boto's S3 bindings

### ISSUE THREAD

**Issue by glocad** [openedx-unsupported/configuration#3766]
Hi Guys,

I set up an Open edX Ficus platform on my local physical machine and it works normally. I am trying to set up the same platform on a Google Cloud Platform (gcp) virtual machine but it fails with the following migration error:

```
TASK [edxapp : migrate] ********************************************************
failed: [localhost] (item=lms) => {"changed": true, "cmd": ["/edx/bin/edxapp-migrate-lms"], "delta": "0:00:02.032571", "end": "2017-03-21 07:52:27.582931", "failed": true, "item": "lms", "rc": 1, "start": "2017-03-21 07:52:25.550360", "stderr": "Traceback (most recent call last):\n  File \"manage.py\", line 111, in <module>\n    startup = importlib.import_module(edx_args.startup)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/edx/app/edxapp/edx-platform/lms/startup.py\", line 21, in <module>\n    import lms_xblock.runtime\n  File \"/edx/app/edxapp/edx-platform/lms/djangoapps/lms_xblock/runtime.py\", line 9, in <module>\n    from openedx.core.djangoapps.user_api.course_tag import api as user_course_tag_api\n  File \"/edx/app/edxapp/edx-platform/openedx/core/djangoapps/user_api/course_tag/api.py\", line 10, in <module>\n    from ..models import UserCourseTag\n  File \"/edx/app/edxapp/edx-platform/openedx/core/djangoapps/user_api/models.py\", line 20, in <module>\n    from student.models import UserProfile, Registration, PendingEmailChange  # pylint: disable=unused-import\n  File \"/edx/app/edxapp/edx-platform/common/djangoapps/student/models.py\", line 49, in <module>\n    from certificates.models import GeneratedCertificate\n  File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/__init__.py\", line 3, in <module>\n    from . import signals\n  File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/signals.py\", line 7, in <module>\n    from certificates.models import CertificateGenerationCourseSetting\n  File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/models.py\", line 69, in <module>\n    from lms.djangoapps.instructor_task.models import InstructorTask\n  File \"/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/models.py\", line 26, in <module>\n    from openedx.core.storage import get_storage\n  File \"/edx/app/edxapp/edx-platform/openedx/core/storage.py\", line 16, in <module>\n    from storages.backends.s3boto import S3BotoStorage\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/storages/backends/s3boto.py\", line 19, in <module>\n    raise ImproperlyConfigured(\"Could not load Boto's S3 bindings.\\n\"\ndjango.core.exceptions.ImproperlyConfigured: Could not load Boto's S3 bindings.\nSee https://github.com/boto/boto", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [localhost] (item=cms) => {"changed": true, "cmd": ["/edx/bin/edxapp-migrate-cms"], "delta": "0:00:02.579207", "end": "2017-03-21 07:52:30.266621", "failed": true, "item": "cms", "rc": 1, "start": "2017-03-21 07:52:27.687414", "stderr": "Traceback (most recent call last):\n  File \"manage.py\", line 112, in <module>\n    startup.run()\n  File \"/edx/app/edxapp/edx-platform/cms/startup.py\", line 39, in run\n    django.setup()\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py\", line 18, in setup\n    apps.populate(settings.INSTALLED_APPS)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py\", line 85, in populate\n    app_config = AppConfig.create(entry)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/config.py\", line 86, in create\n    module = import_module(entry)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/edx/app/edxapp/venvs/edxapp/src/edx-sga/edx_sga/__init__.py\", line 1, in <module>\n    from .sga import StaffGradedAssignmentXBlock\n  File \"/edx/app/edxapp/venvs/edxapp/src/edx-sga/edx_sga/sga.py\", line 23, in <module>\n    from student.models import user_by_anonymous_id\n  File \"/edx/app/edxapp/edx-platform/common/djangoapps/student/models.py\", line 49, in <module>\n    from certificates.models import GeneratedCertificate\n  File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/__init__.py\", line 3, in <module>\n    from . import signals\n  File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/signals.py\", line 7, in <module>\n    from certificates.models import CertificateGenerationCourseSetting\n  File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/models.py\", line 69, in <module>\n    from lms.djangoapps.instructor_task.models import InstructorTask\n  File \"/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/models.py\", line 26, in <module>\n    from openedx.core.storage import get_storage\n  File \"/edx/app/edxapp/edx-platform/openedx/core/storage.py\", line 16, in <module>\n    from storages.backends.s3boto import S3BotoStorage\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/storages/backends/s3boto.py\", line 19, in <module>\n    raise ImproperlyConfigured(\"Could not load Boto's S3 bindings.\\n\"\ndjango.core.exceptions.ImproperlyConfigured: Could not load Boto's S3 bindings.\nSee https://github.com/boto/boto", "stdout": "", "stdout_lines": [], "warnings": []}

RUNNING HANDLER [mongo : restart mongo] ****************************************
	to retry, use: --limit @/var/tmp/configuration/playbooks/edx_sandbox.retry

PLAY RECAP *********************************************************************
localhost                  : ok=196  changed=130  unreachable=0    failed=1   

INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: install python requirements --------------------------------------------------- 613.02s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: code sandbox | Install base sandbox requirements and create sandbox virtualenv  226.86s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: code sandbox | Install sandbox requirements into sandbox venv ------------------ 57.36s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: checkout edx-platform repo into /edx/app/edxapp/edx-platform ------------------- 51.81s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install python-software-properties if debian ----------------------------------- 43.73s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install mysql-5.6 and dependencies --------------------------------------------- 21.89s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install mongo server and recommends -------------------------------------------- 14.63s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install packages needed for single server -------------------------------------- 11.70s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install rabbit package using gdebi --------------------------------------------- 10.81s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: install node dependencies ------------------------------------------------------ 10.61s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing:
Playbook Configure instance(s) finished: 2017-03-21 07:52:30.282508, 343 total tasks.  0:20:13.652374 elapsed. 
```
The  stack trace above shows the problem `Could not load Boto's S3 bindings.`:

```
LMS:
Traceback (most recent call last):\n  
File \"manage.py\", line 111, in <module>\n    startup = importlib.import_module(edx_args.startup)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  
File \"/edx/app/edxapp/edx-platform/lms/startup.py\", line 21, in <module>\n    import lms_xblock.runtime\n  
File \"/edx/app/edxapp/edx-platform/lms/djangoapps/lms_xblock/runtime.py\", line 9, in <module>\n    from openedx.core.djangoapps.user_api.course_tag import api as user_course_tag_api\n  
File \"/edx/app/edxapp/edx-platform/openedx/core/djangoapps/user_api/course_tag/api.py\", line 10, in <module>\n    from ..models import UserCourseTag\n  
File \"/edx/app/edxapp/edx-platform/openedx/core/djangoapps/user_api/models.py\", line 20, in <module>\n    from student.models import UserProfile, Registration, PendingEmailChange  # pylint: disable=unused-import\n  
File \"/edx/app/edxapp/edx-platform/common/djangoapps/student/models.py\", line 49, in <module>\n    from certificates.models import GeneratedCertificate\n  
File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/__init__.py\", line 3, in <module>\n    from . import signals\n  
File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/signals.py\", line 7, in <module>\n    from certificates.models import CertificateGenerationCourseSetting\n  
File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/models.py\", line 69, in <module>\n    from lms.djangoapps.instructor_task.models import InstructorTask\n  
File \"/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/models.py\", line 26, in <module>\n    from openedx.core.storage import get_storage\n  
File \"/edx/app/edxapp/edx-platform/openedx/core/storage.py\", line 16, in <module>\n    from storages.backends.s3boto import S3BotoStorage\n  
File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/storages/backends/s3boto.py\", line 19, in <module>\n    
raise ImproperlyConfigured(\"Could not load Boto's S3 bindings.\\n\"\ndjango.core.exceptions.ImproperlyConfigured: Could not load Boto's S3 bindings.\nSee https://github.com/boto/boto"

CMS:
Traceback (most recent call last):\n  
File \"manage.py\", line 112, in <module>\n    startup.run()\n 
File \"/edx/app/edxapp/edx-platform/cms/startup.py\", line 39, in run\n    django.setup()\n 
File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py\", line 18, in setup\n    apps.populate(settings.INSTALLED_APPS)\n  
File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py\", line 85, in populate\n    app_config = AppConfig.create(entry)\n  
File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/config.py\", line 86, in create\n    module = import_module(entry)\n  
File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n 
File \"/edx/app/edxapp/venvs/edxapp/src/edx-sga/edx_sga/__init__.py\", line 1, in <module>\n    from .sga import StaffGradedAssignmentXBlock\n 
File \"/edx/app/edxapp/venvs/edxapp/src/edx-sga/edx_sga/sga.py\", line 23, in <module>\n    from student.models import user_by_anonymous_id\n  
File \"/edx/app/edxapp/edx-platform/common/djangoapps/student/models.py\", line 49, in <module>\n    from certificates.models import GeneratedCertificate\n  
File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/__init__.py\", line 3, in <module>\n    from . import signals\n  
File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/signals.py\", line 7, in <module>\n    from certificates.models import CertificateGenerationCourseSetting\n  
File \"/edx/app/edxapp/edx-platform/lms/djangoapps/certificates/models.py\", line 69, in <module>\n    from lms.djangoapps.instructor_task.models import InstructorTask\n  
File \"/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/models.py\", line 26, in <module>\n    from openedx.core.storage import get_storage\n  
File \"/edx/app/edxapp/edx-platform/openedx/core/storage.py\", line 16, in <module>\n    from storages.backends.s3boto import S3BotoStorage\n  
File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/storages/backends/s3boto.py\", line 19, in <module>\n    
raise ImproperlyConfigured(\"Could not load Boto's S3 bindings.\\n\"\ndjango.core.exceptions.ImproperlyConfigured: Could not load Boto's S3 bindings.\nSee https://github.com/boto/boto"
```

The installation steps I took for the vm are:
```
$ sudo apt-get update -y
$ sudo apt-get upgrade -y
$ sudo reboot

$ export OPENEDX_RELEASE=open-release/ficus.1
$ wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/ansible-bootstrap.sh -O - | sudo bash
$ source /edx/app/edx_ansible/venvs/edx_ansible/bin/activate
$ wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash
```
The gcp vm is an Ubuntu 16.04 LTS Xenial server machine with the following parameters: 2 vCPUs, 8 GB memory, 100 GB storage.

Any suggestion how to solve this ?

**Comment by mrgnr** [comment]
@glocad I ran into this same issue with Xenial on GCP. _This seems to be a GCP-specific issue._

I haven't gotten to the root of the issue yet, but a quick fix is to install the `google-compute-engine` package in the edxapp virtualenv:
```
$ /edx/app/edxapp/venvs/edxapp/bin/pip install google-compute-engine
```

**Comment by nedbat** [comment]
@mrgnr Thanks! I've added this as an Answer in the wiki: https://openedx.atlassian.net/wiki/pages/viewpage.action?pageId=158663390

**Comment by mrgnr** [comment]
I think I've gotten to the bottom of this. Machines on GCP have the [Cloud SDK tools](https://cloud.google.com/sdk/) installed by default, which use a globally-installed boto. It also creates a `/etc/boto.cfg`:

```
# This file is automatically created at boot time by the
# /usr/share/google/boto/boot_setup.py script. Do not edit this file
# directly.  If you need to add items to this file, create/edit
# /etc/boto.cfg.template instead and then re-run the script.

[GSUtil]
default_project_id = 755584093881
default_api_version = 2

[GoogleCompute]
service_account = default

[Plugin]
plugin_directory = /usr/share/google/boto/boto_plugins
```

This file is read by every boto installation, whether on the host or in a virtualenv. In the edxapp virtualenv, boto reads this file and tries to load plugins from `/usr/share/google/boto/boto_plugins`. Some of these plugins rely on packages not installed in the edxapp virtualenv (namely `google-compute-engine`), which is why boto throws an error on import.

A possible solution is to override settings in `/etc/boto.cfg` using a [local settings file](http://boto.cloudhackers.com/en/latest/boto_config_tut.html). I think we can simply create a `/edx/app/edxapp/.boto` file and override `plugin_directory` to fix this issue.

@glocad @nedbat

**Comment by mrgnr** [comment]
@glocad This patch should resolve the issue: https://github.com/edx/configuration/pull/3792

**Comment by glocad** [comment]
Thank you very much @mrgnr ! This was really helpful !

**Comment by AlaaSwedan** [comment]
Hey ....
i have this issue  how can I solve it ??? 

TASK [edxapp : migrate] ********************************************************
failed: [localhost] (item=lms) => {"changed": true, "cmd": ["/edx/bin/edxapp-migrate-lms"], "delta": "0:00:07.653487", "end": "2017-10-16 17:00:48.678957", "failed": true, "item": "lms", "rc": 1, "start": "2017-10-16 17:00:41.025470", "stderr": "Traceback (most recent call last):\n  File \"manage.py\", line 112, in <module>\n    startup.run()\n  File \"/edx/app/edxapp/edx-platform/lms/startup.py\", line 52, in run\n    django.setup()\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py\", line 18, in setup\n    apps.populate(settings.INSTALLED_APPS)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate\n    app_config.import_models(all_models)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/config.py\", line 198, in import_models\n    self.models_module = import_module(models_module_name)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/enterprise/models.py\", line 14, in <module>\n    from simple_history.models import HistoricalRecords\nImportError: No module named simple_history.models", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [localhost] (item=cms) => {"changed": true, "cmd": ["/edx/bin/edxapp-migrate-cms"], "delta": "0:00:06.981261", "end": "2017-10-16 17:00:55.943153", "failed": true, "item": "cms", "rc": 1, "start": "2017-10-16 17:00:48.961892", "stderr": "2017-10-16 11:00:55,476 WARNING 3875 [py.warnings] base.py:116 - /edx/app/edxapp/edx-platform/lms/djangoapps/survey/models.py:20: RemovedInDjango19Warning: Model class survey.models.SurveyForm doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.\n  class SurveyForm(TimeStampedModel):\n\n2017-10-16 11:00:55,479 WARNING 3875 [py.warnings] base.py:116 - /edx/app/edxapp/edx-platform/lms/djangoapps/survey/models.py:160: RemovedInDjango19Warning: Model class survey.models.SurveyAnswer doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.\n  class SurveyAnswer(TimeStampedModel):\n\nTraceback (most recent call last):\n  File \"manage.py\", line 112, in <module>\n    startup.run()\n  File \"/edx/app/edxapp/edx-platform/cms/startup.py\", line 34, in run\n    django.setup()\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py\", line 18, in setup\n    apps.populate(settings.INSTALLED_APPS)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py\", line 108, in populate\n    app_config.import_models(all_models)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/config.py\", line 198, in import_models\n    self.models_module = import_module(models_module_name)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/enterprise/models.py\", line 14, in <module>\n    from simple_history.models import HistoricalRecords\nImportError: No module named simple_history.models", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @/var/tmp/configuration/playbooks/edx_sandbox.retry

PLAY RECAP *********************************************************************
localhost                  : ok=177  changed=42   unreachable=0    failed=1   

INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: install python requirements ---------------------------------------------------- 96.26s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: install node dependencies ------------------------------------------------------ 78.07s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: install system packages on which LMS and CMS rely ------------------------------ 24.12s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Update apt-get ----------------------------------------------------------------- 17.08s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: migrate ------------------------------------------------------------------------ 15.23s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: create nodeenv ----------------------------------------------------------------- 14.09s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Add admin users ---------------------------------------------------------------- 13.00s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Start rabbit nodes -------------------------------------------------------------- 9.97s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install the nginx package ------------------------------------------------------- 9.41s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install ubuntu system packages -------------------------------------------------- 8.97s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing:
Playbook Configure instance(s) finished: 2017-10-16 15:00:55.970339, 321 total tasks.  0:09:01.927047 elapsed.

**Comment by nedbat** [comment]
@AlaaSwedan Your error report seems to have nothing to do with the topic of this issue.  To get help with installation problems, see https://open.edx.org/getting-help , thanks.

**Comment by AlaaSwedan** [comment]
@nedbat ok thanks for that   ...
but i installed again openedx in ubuntu 14.04  and there are missing folders like **edx_ansible** and **forum** ... what should i do to solve this problem  ???

**Comment by nedbat** [comment]
@AlaaSwedan I'm not sure how else to say this: we can't offer support on GitHub issues.  Use the mailing list or Slack to get help.

**Comment by AlaaSwedan** [comment]
@nedbat Ok thanks

**Comment by tr0043t** [comment]
I think I'm dealing with this issue with a new Ginkgo installation on a fresh 16.04 GCP instance. Various processes aren't starting, and I'm finding errors logged like:

==> cms_high_1-stderr.log <==
    from lms.djangoapps.instructor_task.models import InstructorTask
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/instructor_task/models.py", line 27, in <module>
    from openedx.core.storage import get_storage
  File "/edx/app/edxapp/edx-platform/openedx/core/storage.py", line 10, in <module>
    from storages.backends.s3boto import S3BotoStorage
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 13, in <module>
    from boto import __version__ as boto_version
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
AttributeError: 'module' object has no attribute 'plugin'

I see the discussion of fixes above but it's not clear to me exactly how to use them, or whether it involves a reinstall of any components or not. Can anyone provide clarification on exactly what's needed to clear this error? Thanks!

**Comment by tr0043t** [comment]
I should add that this is a native installation, and I already did:

/edx/app/edxapp/venvs/edxapp/bin/pip install google-compute-engine

this proceeded without any errors at the time, but after a reboot I still don't have an operational environment (e.g. no response to any of the edx-related ports on localhost). Thanks again.

**Comment by nedbat** [comment]
@laurenweinstein1 We can't provide support on GitHub issues.  See https://open.edx.org/getting-help for the mailing list and Slack options.

**Comment by AlaaSwedan** [comment]
![test egy002 courseware egymoocs 1](https://user-images.githubusercontent.com/28710039/34354096-a3e5a24e-ea34-11e7-8b98-1c142b5eef91.png)
hello 

i have this issue what i can do to solve it ...

**Comment by dehamzah** [comment]
For others facing this same issue.

When installing.
If setting environment variable `BOTO_CONFIG` doesn't work for you. It's because the edxapp always reading config from `/etc/boto.cfg`. You can just delete this file, and re-run the provisioning script.

But, after installation complete then you are restarting your instance, this file `/etc/boto.cfg` will be re-created, and can causing your edxapp not running*.

*See logs `$ sudo tail -f /edx/var/log/supervisor/*`

To stop this file being created automatically, remove the file script that creating this config.
By removing, i usually didn't really delete it, in case i need it later. Renaming it to other file name, can also mean 'removing'.

```
$ sudo mv /usr/lib/python3/dist-packages/google_compute_engine/boto/boto_config.py /usr/lib/python3/dist-packages/google_compute_engine/boto/boto_config.py.bak
```

Remove the boto config (if not already):

```
$ sudo rm /etc/boto.cfg
```

Reboot to see the effect. It should stop the `/etc/boto.cfg` being re-created.
