### ISSUE TITLE
Error while installing OpenEDX on Ubuntu 16.04 server

### ISSUE THREAD

**Issue by btrish** [openedx-unsupported/configuration#3779]
I was setting up Open EDX by following this documentation:
https://openedx.atlassian.net/wiki/display/OpenOPS/Native+Open+edX+Ubuntu+16.04+64+bit+Installation
After entering this code:
`wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash`
I am getting this error:
>TASK [nltk : download nltk data] ***********************************************
failed: [localhost] (item={u'url': u'http://nltk.github.io/nltk_data/packages/taggers/maxent_treebank_pos_tagger.zip', u'path': u'taggers/maxent_treebank_pos_tagger'}) => {"dest": "/usr/local/share/nltk_data/maxent_treebank_pos_tagger.zip", "failed": true, "item": {"path": "taggers/maxent_treebank_pos_tagger", "url": "http://nltk.github.io/nltk_data/packages/taggers/maxent_treebank_pos_tagger.zip"}, "msg": "Request failed", "response": "Connection failure: timed out", "state": "absent", "status_code": -1, "url": "http://nltk.github.io/nltk_data/packages/taggers/maxent_treebank_pos_tagger.zip"}
changed: [localhost] => (item={u'url': u'http://nltk.github.io/nltk_data/packages/corpora/stopwords.zip', u'path': u'corpora/stopwords'})
changed: [localhost] => (item={u'url': u'http://nltk.github.io/nltk_data/packages/corpora/wordnet.zip', u'path': u'corpora/wordnet'})
RUNNING HANDLER [mongo : restart mongo] ****************************************
        to retry, use: --limit @/var/tmp/configuration/playbooks/edx_sandbox.retry
PLAY RECAP *********************************************************************
localhost                  : ok=146  changed=90   unreachable=0    failed=1
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install python-software-properties if debian ---------------------------------- 290.69s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install mongo server and recommends ------------------------------------------- 247.22s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install mysql-5.6 and dependencies -------------------------------------------- 118.28s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install system packages -------------------------------------------------------- 93.30s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install rabbit package using gdebi --------------------------------------------- 80.39s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install the nginx package [0] -------------------------------------------------- 54.68s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: download nltk data ------------------------------------------------------------- 53.37s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install packages needed for single server -------------------------------------- 34.18s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Install supervisor in its venv [0] --------------------------------------------- 21.67s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Add the mongodb repo to the sources list --------------------------------------- 19.04s
INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing:
Playbook Configure instance(s) finished: 2017-03-24 07:20:40.357398, 269 total tasks.  0:23:20.109992 elapsed.

I am using a fresh installation of Ubuntu 16.04 server on VMware ESXi. Reinstallation isn't helping either. I double checked and I can assure that there are no problems with my internet connectivity. Any fix?

**Comment by pakholkav** [comment]
Hi btrish,

Were you able to fix this error?
I got the same error and don't know what to do.

**Comment by OMKARdama12** [comment]
![screenshot from 2017-12-23 21-58-01](https://user-images.githubusercontent.com/31235010/34511018-db543ad8-f07e-11e7-9661-ff87e2477728.png)
iam getting this error,any one can help me

**Comment by RDZuser** [comment]
I have the same situation and i could not find any solution

**Comment by ahouzan** [comment]
I'have also the same  situation.

**Comment by rcampos1952** [comment]
I have the same situation and i could not find any solution too


TASK [oraclejdk : Untar Oracle Java] *******************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "tar -C /usr/lib/jvm -zxvf /var/tmp/jdk-8u65-linux-x64.tar.gz", "delta": "0:00:00.041163", "end": "2018-05-22 16:18:37.389628", "failed": true, "rc": 2, "start": "2018-05-22 16:18:37.348465", "stderr": "\ngzip: stdin: not in gzip format\ntar: Child returned status 1\ntar: Error is not recoverable: exiting now", "stdout": "", "stdout_lines": [], "warnings": ["Consider using unarchive module rather than running tar"]}

**Comment by joedor0102** [comment]
@rcampos1952, download jdk-8u65-linux-x64.tar.gz and copy on your /var/tmp/, copy with scp orig dest

**Comment by joedor0102** [comment]
i have issue with:

TASK [insights : run collectstatic] ********************************************
changed: [localhost] => (item=collectstatic --noinput)
failed: [localhost] (item=compress) => {"changed": true, "cmd": "/edx/app/insights/venvs/insights/bin/python /edx/app/insights/edx_analytics_dashboard/manage.py compress", "delta": "0:00:00.926660", "end": "2018-06-03 21:41:01.455731", "failed": true, "item": "compress", "rc": 1, "start": "2018-06-03 21:41:00.529071", "stderr": "CommandError: An error occurred during rendering /edx/app/insights/edx_analytics_dashboard/analytics_dashboard/courses/templates/courses/base_grouped_content.html: Error: File to import not found or unreadable: ../bower_components/edx-pattern-library/pattern-library/sass/edx-pattern-library-ltr-compiled
       Parent style sheet: /edx/var/insights/staticfiles/sass/style-application.scss
        on line 19 of ../../../var/insights/staticfiles/sass/style-application.scss
>> @import \"../bower_components/edx-pattern-library/pattern-library/sass/edx-patt
   ^", "stdout": "Invalid template /edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/soapbox/templates/soapboxtest/test_fail_syntax.html: 'get_messages_for_page' did not receive value(s) for the argument(s): 'url'
Invalid template /edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/rest_framework/templates/rest_framework/filters/django_filter_crispyforms.html: 'crispy_forms_tags' is not a registered tag library.

somebody with some idea.

thanks.
