### ISSUE TITLE
Error while Install Open edX on ubuntu server

### ISSUE THREAD

**Issue by wutspuc** [openedx-unsupported/configuration#3826]
Help Me Please.
Install Error

TASK [edx_service : Install a bunch of system packages on which  edx_service  relies ] ***
fatal : [localhost] : Failed! => {"failed": true, "msg": "{u'debian' : u' {{ insights_debian_pkgs + insights_release_specific_debian_pkgs[ansible_distribution_release] }}' , u'redhat' :[]}: 'dict object' has no attribute u' trusty'"}

**Comment by Ettayeb** [comment]
Hello friend , seems like you are trying to install open edx on Ubuntu 14.04... well i got this error before and this is how you can fix it : 
open the file :  configuration/playbooks/roles/insights/meta/main.yml 
and add this line at the end of it : 
 trusty: "{{ insights_debian_pkgs + insights_release_specific_debian_pkgs[ansible_distribution_release] }}"

.................
Then you will get another error about Java.. you can fix it by : 
Opening this file :  configuration/playbooks/roles/insights/defaults/main.yml
then adding this at the end : 
  trusty:
- openjdk-7-jdk

===========
everything should be good now ^_^

**Comment by wutspuc** [comment]
Thank you.

**Comment by AlaaSwedan** [comment]
help me Please.
I got this install error
>>>>>>>
fatal: [localhost]: FAILED! => {"failed": true, "msg": "{u'debian': u'{{ insights_debian_pkgs + insights_release_specific_debian_pkgs[ansible_distribution_release] }}', u'redhat': []}: 'dict object' has no attribute u'trusty'"}

RUNNING HANDLER [mongo : restart mongo] ****************************************
	to retry, use: --limit @/var/tmp/configuration/playbooks/edx_sandbox.retry

PLAY RECAP *********************************************************************
localhost                  : ok=274  changed=188  unreachable=0    failed=1

**Comment by Ettayeb** [comment]
already answered

**Comment by AlaaSwedan** [comment]
this answer doesn't work when i add this line 
trusty: "{{ insights_debian_pkgs + insights_release_specific_debian_pkgs[ansible_distribution_release] }}"

 i got this error
ERROR! 'trusty' is not a valid attribute for a RoleMetadata

The error appears to have been in '/var/tmp/configuration/playbooks/roles/insights/meta/main.yml': line 13, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

#
dependencies:
^ here

**Comment by mariembmm** [comment]
I am installing open edx and I have this error.ani help?
failed: [localhost] 
(item=/edx/app/xqueue/xqueue/requirements.txt) => 
{"cmd": "/edx/app/xqueue/venvs/xqueue/bin/pip2 install -i https://pypi.python.org/simple 
--exists-action w -r /edx/app/xqueue/xqueue/requirements.txt", "failed": true, "item": "/edx/app/xqueue/xqueue/requirements.txt",
 "msg": "stdout: Collecting django<1.9,>=1.8 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 1))\n
 Downloading Django-1.8.19-py2.py3-none-any.whl (6.2MB)\nCollecting MySQL-python==1.2.5 
 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 2))\n 
 Downloading MySQL-python-1.2.5.zip (108kB)\nRequirement already satisfied: argparse==1.2.1 in /usr/lib/python2.7 
 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 3)) (1.2.1)\nCollecting boto==2.39.0 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 4))\n
 Downloading boto-2.39.0-py2.py3-none-any.whl (1.3MB)\nCollecting coverage==3.6b1 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 5))\n 
 Downloading coverage-3.6b1.tar.gz (224kB)\nCollecting django-nose==1.4.1 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 6))\n 
 Downloading django_nose-1.4.1-py2-none-any.whl\nCollecting dogstatsd-python==0.2 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 7))\n  
 Downloading dogstatsd-python-0.2.tar.gz\nCollecting edx-django-release-util==0.3.0 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 8))\n  
 Downloading edx_django_release_util-0.3.0-py2-none-any.whl\nCollecting gunicorn==0.16.1 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 9))\n 
 Downloading gunicorn-0.16.1.tar.gz (344kB)\nCollecting newrelic==2.64.0.48 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 10))\n  
 Downloading newrelic-2.64.0.48.tar.gz (712kB)\nCollecting nose==1.2.1 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 11))\n
 Downloading nose-1.2.1.tar.gz (400kB)\nCollecting nosexcover==1.0.7 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 12))\n 
 Downloading nosexcover-1.0.7.tar.gz\nCollecting path.py==2.4.1 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 13))\n  
 Downloading path.py-2.4.1.zip\nObtaining pika from git+https://github.com/pika/pika.git@a731347fc0#egg=pika 
 (from -r /edx/app/xqueue/xqueue/requirements.txt (line 14))\n 
 Cloning https://github.com/pika/pika.git (to revision a731347fc0) to /edx/app/xqueue/venvs/xqueue/src/pika\nfatal: Couldn't find remote ref a731347fc0\n
 \n:stderr:   Did not find branch or tag 'a731347fc0', assuming revision or ref.\nCommand \"git fetch -q https://github.com/pika/pika.git a731347fc0\" 
 failed with error code 128 in /edx/app/xqueue/venvs/xqueue/src/pika\n"}
