### ISSUE TITLE
Trouble installing on a single Ubuntu 12.04 virtual machine with Vagrant

### ISSUE THREAD

**Issue by tummykung** [openedx-unsupported/configuration#395]
I'm having trouble running the latest version of EdX. I'm using Ubuntu 12.04.2 LTS, VirtualBox 4.2.12r84980, Vagrant 1.3.2, and ansible 1.2.2. Here is the [error message](https://gist.github.com/tummykung/9d328c96082f016cac16) I get when I run the installation commands on the [wiki](https://github.com/edx/configuration/wiki).

Can anyone give assistance?

**Comment by feanil** [comment]
Before you do the vagrant provision you should make sure to install the
requirements locally, to make sure you have the correct version of ansible
installed.  So do a `pip install -r requirements.txt` in the configuration
repo before you run `vagrant up` or `vagrant provision`

**Comment by jarv** [comment]
I believe I've seen this issue before and the workaround is to run `vagrant provision` after the error, I think it's a timing issue when the box comes up.  If you continue to see problems with the new release let us know.
