### ISSUE TITLE
Failed Ansible Task: [mongo : Create super user with js]

### ISSUE THREAD

**Issue by abrantesasf** [openedx-unsupported/configuration#3963]
Hi,

I'm trying to install Open edX Ficus release on a test ubuntu server (following this doc: https://openedx.atlassian.net/wiki/display/OpenOPS/Native+Open+edX+Ubuntu+16.04+64+bit+Installation), but I'm getting this error message during installation:

`TASK [mongo : Create super user with js] *********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/bin/mongo admin /tmp/create_root.js", "delta": "0:00:00.081277", "end": "2017-07-03 07:42:02.964976", "failed": true, "rc": 253, "start": "2017-07-03 07:42:02.883699", "stderr": "", "stderr_lines": [], "stdout": "MongoDB shell version: 2.6.12\nconnecting to: admin\nError: 18 { ok: 0.0, errmsg: \"auth failed\", code: 18 }\n2017-07-03T07:42:02.962-0300 Error: not authorized on admin to execute command { usersInfo: \"admin\" } at src/mongo/shell/db.js:1342\nfailed to load: /tmp/create_root.js", "stdout_lines": ["MongoDB shell version: 2.6.12", "connecting to: admin", "Error: 18 { ok: 0.0, errmsg: \"auth failed\", code: 18 }", "2017-07-03T07:42:02.962-0300 Error: not authorized on admin to execute command { usersInfo: \"admin\" } at src/mongo/shell/db.js:1342", "failed to load: /tmp/create_root.js"]}
        to retry, use: --limit @/edx/app/edx_ansible/edx_ansible/playbooks/run_role.retry`

I have try to run this ansible task again with
`cd /edx/app/edx_ansible/edx_ansible/playbooks && sudo /edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook -i localhost, -c local run_role.yml -e 'role=mongo' -e 'mongo_create_users=True'`

but the same error message is raised. I do not know if this is a bug in that ansible task.

`/edx/bin/show-repo-heads` shows the following:
`/edx/bin/show-repo-heads
---- /edx/app/edx_ansible/edx_ansible ----
2017-06-30 16:43:42 -0400 (5623a1da) GitHub: Insights Cloudfront CDN configuration (#3961)  (HEAD -> master, origin/master, origin/HEAD)

---- /edx/app/edxapp/edx-platform ----
2017-04-12 11:36:53 -0400 (9832c14220) GitHub: Merge pull request #14860 from edx/dsjen/update-mathjax  (HEAD, tag: open-release/ficus.3, tag: nedbat/test/ficus.3.3, tag: nedbat/test/ficus.3.2, tag: nedbat/test/ficus.3.1)`

This test server is a Dell T410 running Ubuntu 16.04, with Xeon Quad-Core 2.4GHz processor and 4GB RAM.

**Comment by nedbat** [comment]
Hi, sorry you've had difficulty.  GitHub issues are not the best place to get support.  The mailing list and Slack channels are explained here: http://open.edx.org/getting-help.  If it turns out there's a bug in the configuration scripts, we can re-open an issue here.  Thanks.
