### ISSUE TITLE
Port forwarding not configured?

### ISSUE THREAD

**Issue by tashmore** [openedx-unsupported/configuration#406]
After running "vagrant up", I point a browser at localhost:80 (from the host machine) as stated in the [instructions](https://github.com/edx/configuration/wiki#installing-edx-on-a-single-ubuntu-1204-virtual-machine-with-vagrant), but I get a "Connection reset by peer" error. I can successfully connect to 192.168.33.10:80.

Is something wrong with port forwarding? How is port forwarding currently configured?  Adding the following line to my Vagrantfile allows me to connect to localhost:8080:

```
config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
```

However, if I change the 8080 to 80, nginx fails to start.

I'm running Ubuntu 12.04.3 LTS and edx-platform release croissant. I've run `sudo pip install -r configuration/requirements.txt`.

```
tba:shortstack$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Clearing any previously set forwarded ports...
[default] Fixed port collision for 22 => 2222. Now on port 2200.
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2200 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /vagrant
tba:shortstack$ curl -I localhost:80
curl: (56) Recv failure: Connection reset by peer
tba:shortstack$ curl -I 192.168.33.10:80
HTTP/1.1 200 OK
Server: nginx/1.1.19
Date: Sun, 03 Nov 2013 22:15:00 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Cookie, Accept-Language
Content-Language: en
Set-Cookie: csrftoken=SUqF5yrdLPUqCQ3SZecTMSkavuTbdi0j; expires=Sun, 02-Nov-2014 22:15:00 GMT; Max-Age=31449600; Path=/
```

**Comment by jarv** [comment]
can you try this again using the recent docs:
https://github.com/edx/configuration/wiki/edX-Developer-Stack
https://github.com/edx/configuration/wiki/edX-Production-Stack
and let us know if you still see an issue?
