### ISSUE TITLE
Failed to provision Devstack

### ISSUE THREAD

**Issue by gsahbi** [openedx-unsupported/configuration#4132]
vagrant provisioning failed,

**Log output :**
==> default: TASK [edxapp : migrate] ********************************************************
==> default: failed: [localhost] (item=lms) => {"changed": true, "cmd": ["/edx/bin/edxapp-migrate-lms"], "delta": "0:00:20.229691
end": "2017-10-05 11:18:31.673613
failed": true, "item": "lms
rc": 1, "start": "2017-10-05 11:18:11.443922
stderr": "2017-10-05 07:18:22,859 WARNING 18970 [py.warnings] base.py:116 - /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/openassessment/workflow/models.py:46: RemovedInDjango19Warning: Model class openassessment.workflow.models.AssessmentWorkflow doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class AssessmentWorkflow(TimeStampedModel, StatusModel):

2017-10-05 07:18:28,007 INFO 18970 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File \"manage.py\", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute_from_command_line
    utility.execute()
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 445, in execute
    output = self.handle(*args, **options)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 47, in __init__
    self.build_graph()
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 308, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 291, in _reraise_missing_dependency
    raise exc
django.db.migrations.graph.NodeNotFoundError: Migration grades.0012_computegradessetting dependencies reference nonexistent parent node (u'grades', u'0011_null_edited_time')
stderr_lines": 

2017-10-05 07:18:28,007 INFO 18970 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File \"manage.py\", line 116, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute_from_command_line
    utility.execute()
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 445, in execute
    output = self.handle(*args, **options)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/executor.py\", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 47, in __init__
    self.build_graph()
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 308, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/migrations/loader.py\", line 291, in _reraise_missing_dependency
    raise exc
django.db.migrations.graph.NodeNotFoundError: Migration grades.0012_computegradessetting dependencies reference nonexistent parent node (u'grades', u'0011_null_edited_time')"], "stdout": "
stdout_lines": []}
==> default: changed: [localhost] => (item=cms)
==> default: 	to retry, use: --limit @/edx/app/edx_ansible/edx_ansible/playbooks/vagrant-devstack.retry
==> default:
==> default: PLAY RECAP *********************************************************************
==> default: localhost                  : ok=163  changed=39   unreachable=0    failed=1
==> default:
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: checkout edx-platform repo into /edx/app/edxapp/edx-platform ------------------ 549.86s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: Take security updates during ansible runs ------------------------------------- 524.11s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: install python requirements --------------------------------------------------- 130.45s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: install node dependencies ------------------------------------------------------ 93.05s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: migrate ------------------------------------------------------------------------ 40.67s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: pip install virtualenv --------------------------------------------------------- 25.04s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: compiling all py files in the edx-platform repo -------------------------------- 21.39s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: Install security packages ------------------------------------------------------ 11.27s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: Git checkout edx_ansible repo into edx_ansible_code_dir ------------------------ 10.44s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing: trust rabbit's packagecloud repository ----------------------------------------- 10.22s
==> default: INFO:/edx/app/edx_ansible/edx_ansible/playbooks/callback_plugins/task_timing:
==> default: Playbook Configure instance(s) finished: 2017-10-05 11:18:51.920656, 250 total tasks.  0:26:37.983619 elapsed.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Installation finished at 2017-10-05 14:18:52

 **my setup** 

vagrant@vagrant:~$ /edx/bin/show-repo-heads
---- /edx/app/demo/edx-demo-course ----
2017-05-19 14:17:27 -0700 (99d47c2) GitHub: Merge pull request #20 from zukefresh/george/update-readme  (HEAD -> nedbat/test/ginkgo.1rc1.1, origin/open-release/ginkgo.master, origin/nedbat/test/ginkgo.1rc1.1, origin/nedbat/ginkgo-test, origin/master, origin/HEAD, master)
---- /edx/app/discovery/discovery ----
2017-07-14 12:20:36 -0400 (14edb1b) Renzo Lucioni: Upgrade to DRF 3.6.3  (grafted, HEAD -> nedbat/test/ginkgo.1rc1.1, origin/nedbat/test/ginkgo.1rc1.1)
---- /edx/app/ecomworker/ecomworker ----
2017-07-03 15:15:21 -0400 (a65019c) Renzo Lucioni: Upgrade New Relic agent to 2.86.3.70  (grafted, HEAD -> nedbat/test/ginkgo.1rc1.1, origin/nedbat/test/ginkgo.1rc1.1)
---- /edx/app/edx_ansible/edx_ansible ----
2017-08-14 13:14:57 -0400 (8f6dd7bfc) Ned Batchelder: Vagrantfile updates for ginkgo.1  (HEAD, tag: open-release/ginkgo.1, origin/nedbat/test/ginkgo.1.1)
---- /edx/app/edxapp/edx-platform ----
2017-08-10 10:36:20 -0400 (37052afe31) GitHub: Merge pull request #15781 from edx/nedbat/learner-2172-ginkgo  (HEAD, tag: open-release/ginkgo.1, origin/nedbat/test/ginkgo.1.1)
---- /edx/app/notifier/src ----
2017-04-24 16:43:10 +0200 (10cd830) GitHub: Merge pull request #43 from open-craft/mtyaka/task-model  (HEAD -> nedbat/test/ginkgo.1rc1.1, origin/open-release/ginkgo.master, origin/nedbat/test/ginkgo.1rc1.1, origin/nedbat/ginkgo-test, origin/master, origin/HEAD, master)
v

**Comment by nedbat** [comment]
We can't support installation problems in GitHub issues.  See https://open.edx.org/getting-help for Slack and mailing list details.  Thanks.

**Comment by gsahbi** [comment]
This is a reproducible issue on a vanilla setup .  so how to differentiate between installation difficulties and other issues related to the playbook itself ? this repo is all about installations 

Anyway thanks, let's try to find an answer elsewhere
