### ISSUE TITLE
TASK [edxapp : migrate] getting failed

### ISSUE THREAD

**Issue by gurunathg** [openedx-unsupported/configuration#4175]
When I'm trying to run any database migration, every time it is failing at step of edxapp : migrate.

`TASK [edxapp : migrate] ********************************************************
failed: [localhost] (item=lms) => {"changed": true, "cmd": ["/edx/bin/edxapp-migrate-lms"], "delta": "0:04:58.188980", "end": "2017-10-26 01:14:15.137864", "failed": true, "item": "lms", "rc": 1, "start": "2017-10-26 01:09:16.948884", "stderr": "2017-10-25 21:09:21,176 INFO 18199 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125\nTraceback (most recent call last):\n  File \"manage.py\", line 116, in <module>\n    execute_from_command_line([sys.argv[0]] + django_args)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute_from_command_line\n    utility.execute()\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 346, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/management/base.py\", line 394, in run_from_argv\n`

Complete error log : https://pastebin.com/1vCTvYg4

Can any one help me in fixing this.

**Comment by ly2ly** [comment]
Hello,
Have you find any solution?
