### ISSUE TITLE
Enabling search and filter by category

### ISSUE THREAD

**Issue by Suraj-KD** [openedx-unsupported/configuration#4272]
Hello Guys,

I followed the tutorial in order to enable the edx-search. The search is working well on studio but unfortunately it seems that something is wrong on LMS.

In fact, the search form is displayed on lms but when I try to search a course on LMS, no matching world is found..

See below, attached screenshoots

In addition, I would like to be able to filter the courses on LMS by category such as "business", "science", "politique" etc.
Is this feature currently available on Open-Edx ? If so, how can I make it run? Otherwise, could someone help me to build this feature or simply provide me a documentation about how to do this?

I'm running open-edx on a hosted Ubuntu 16

Hey @tusbar, sorry to bother, but if you have any background about the above issue and the complementary feature, I would be grateful if you could help. Thanks in advance!

I am facing the same issue like one which is raised before. Link for the previous is mentioned below,

Link : https://github.com/edx/configuration/issues/2288

I have performed all the steps suggested in the previous issue, but i am unable to see the changes.

Please look at this once and let me know if you have any solution.
thanks

**Comment by cequn** [comment]
i got the same issue in hawthorn.1, can anyone help?

**Comment by nedbat** [comment]
Issues are not the place to get help.  See https://openedx.org/getting-help for Slack and mailing lists.
