### ISSUE TITLE
Problem with service configuration

### ISSUE THREAD

**Issue by gitim** [openedx-unsupported/configuration#436]
Hello. I am trying to install edx on aws. I have finally completed the first step: Infrastructure provisioning, and I am ready for the next step: Service configuration. But there isn't such page in wiki and i can't find any how to. Can someone give me a link or give short overview of Service configuration?

**Comment by jarv** [comment]
Unfortunately we don't have any detailed documentation about the configuration, I think a better place for this type of question is the edx-code list.
-John

**Comment by gitim** [comment]
I found such question in edx-code list, it was posted in august, but hadn't any answer. I up it five days ago, but anybody hasn't answered yet.

**Comment by jarv** [comment]
Ah ok, well I'm happy to help you out then.  Any specific questions about
service configuration or are you looking for general documentation?
Unfortunately we don't have any docs for it but a good place to start is
https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml
.
The variables in all-caps are configuration items that vary in different
environments.  The defaults are appropriate for running a single server.

On Fri, Nov 15, 2013 at 10:13 AM, Timur Gibadullin <notifications@github.com

**Comment by gitim** [comment]
Yes, I am looking for general documentation. 
As far as i know .yml is run with ansible. If I'll run this .yml file with ansible, does it it automatically install all edx code? Or there are not trivial steps, and i should separately install  and configure each service?

**Comment by jarv** [comment]
> As far as i know .yml is run with ansible. If I'll run this .yml file with ansible, does it it automatically install all edx code?

Each application has json configuration files that are stored on disk.  Ansible will write out these configuration when you do a code update.  Here are instructions for updating edxapp or forums after it has been deployed - As far as i know .yml is run with ansible. If I'll run this .yml file with ansible, does it it automatically install all edx code?

If you follow [these instructions](https://github.com/edx/configuration/wiki/edX-Developer-Stack) you will see the config files for edx-platform in the `/edx/app/edxapp` directory.

> Or there are not trivial steps, and i should separately install and configure each service?

Ansible is used to script the steps to deploy, configure and re-configure the application.
