### ISSUE TITLE
Native Open edX Ubuntu 16.04 64 bit Installation---behind a proxy:-----TASK [forum : initialize elasticsearch]  fatal:

### ISSUE THREAD

**Issue by jerrybox** [openedx-unsupported/configuration#4384]
- Configuration ref:

  sudo vi /etc/environment
    http_proxy=http://127.0.0.1:8123/
    https_proxy=http://127.0.0.1:8123/
    ftp_proxy=http://127.0.0.1:8123/
    socks_proxy=http://127.0.0.1:8123/
    no_proxy=“localhost,127.0.0.1“
    JAVA_OPTS="-DproxyHost=127.0.0.1 -DproxyPort=8123"
    MAVEN_OPTS="-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=8123"

  sudo vi /etc/sudoers
    Defaults        env_reset
  +   Defaults        env_keep+="http_proxy https_proxy ftp_proxy socks_proxy no_proxy JAVA_OPTS MAVEN_OPTS"

  sudo vi /etc/apt/apt.conf
   
    Acquire::http::proxy "http://127.0.0.1:8123";
    Acquire::https::proxy "http://127.0.0.1:8123";

- other refs:
      
       sudo /etc/init.d/polipo start
       sudo sslocal -c /etc/shadowsocks.json -d start

#Steps to replicate:
- command:
  export OPENEDX_RELEASE=open-release/ginkgo.2

  wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/ansible-bootstrap.sh -O - | sudo bash

  wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/generate-passwords.sh -O - | bash

  wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash

     step 3：failed

- error：
  TASK [forum : git checkout forum repo into /edx/app/forum/cs_comments_service] ***
ok: [localhost]

  TASK [forum : install comments service bundle] *********************************
changed: [localhost]

  TASK [forum : initialize elasticsearch] ****************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/edx/app/forum/cs_comments_service/bin/rake", "search:initialize"], "delta": "0:00:06.168521", "end": "2018-03-16 13:36:19.646949", "failed": true, "rc": 1, "start": "2018-03-16 13:36:13.478428", "stderr": "/edx/app/forum/cs_comments_service/lib/tasks/deep_search.rake:7: warning: already initialized constant ROOT\n/edx/app/forum/cs_comments_service/lib/tasks/kpis.rake:7: warning: already initialized constant ROOT\n/edx/app/forum/cs_comments_service/models/constants.rb:2: warning: already initialized constant COURSE_ID\nrake aborted!\nElasticsearch::Transport::Transport::Errors::BadGateway: [502] \n/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'\n/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'\n/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'\n/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/client.rb:128:in `perform_request'\n/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-api-1.1.2/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'\n/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-api-1.1.2/lib/elasticsearch/api/actions/indices/exists_alias.rb:44:in `block in exists_alias'\n/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-api-1.1.2/lib/elasticsearch/api/utils.rb:197:in `__rescue_from_not_found'\n/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-api-1.1.2/lib/elasticsearch/api/actions/indices/exists_alias.rb:43:in `exists_alias'\n/edx/app/forum/cs_comments_service/lib/task_helpers.rb:92:in `exists_alias'\n/edx/app/forum/cs_comments_service/lib/task_helpers.rb:146:in `initialize_index'\n/edx/app/forum/cs_comments_service/lib/tasks/search.rake:40:in `block (2 levels) in <top (required)>'\nTasks: TOP => search:initialize\n(See full trace by running task with --trace)", "stderr_lines": ["/edx/app/forum/cs_comments_service/lib/tasks/deep_search.rake:7: warning: already initialized constant ROOT", "/edx/app/forum/cs_comments_service/lib/tasks/kpis.rake:7: warning: already initialized constant ROOT", "/edx/app/forum/cs_comments_service/models/constants.rb:2: warning: already initialized constant COURSE_ID", "rake aborted!", "Elasticsearch::Transport::Transport::Errors::BadGateway: [502] ", "/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'", "/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'", "/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'", "/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/client.rb:128:in `perform_request'", "/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-api-1.1.2/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'", "/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-api-1.1.2/lib/elasticsearch/api/actions/indices/exists_alias.rb:44:in `block in exists_alias'", "/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-api-1.1.2/lib/elasticsearch/api/utils.rb:197:in `__rescue_from_not_found'", "/edx/app/forum/.gem/ruby/1.9.1/gems/elasticsearch-api-1.1.2/lib/elasticsearch/api/actions/indices/exists_alias.rb:43:in `exists_alias'", "/edx/app/forum/cs_comments_service/lib/task_helpers.rb:92:in `exists_alias'", "/edx/app/forum/cs_comments_service/lib/task_helpers.rb:146:in `initialize_index'", "/edx/app/forum/cs_comments_service/lib/tasks/search.rake:40:in `block (2 levels) in <top (required)>'", "Tasks: TOP => search:initialize", "(See full trace by running task with --trace)"], "stdout": "W, [2018-03-16T13:36:18.864219 #26851]  WARN -- : Overwriting existing field _id in class User.", "stdout_lines": ["W, [2018-03-16T13:36:18.864219 #26851]  WARN -- : Overwriting existing field _id in class User."]}

  RUNNING HANDLER [forum : restart the forum service] ****************************
	to retry, use: --limit @/var/tmp/configuration/playbooks/edx_sandbox.retry

  PLAY RECAP *********************************************************************
localhost                  : ok=385  changed=107  unreachable=0    failed=1   

  INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: gather {{ item }} static assets with paver [1] -------------------------------- 435.13s
  INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: run collectstatic [1] --------------------------------------------------------- 207.40s
  INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: install node dependencies [0] ------------------------------------------------- 191.14s
  INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: install node dependencies [1] ------------------------------------------------- 187.90s
  INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: install python requirements [0] ----------------------------------------------- 143.97s
  INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: install python requirements [1] ----------------------------------------------- 125.64s
  INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: Create nodeenv ----------------------------------------------------------------- 60.43s
  INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: migrate [0] -------------------------------------------------------------------- 42.19s
  INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: create nodeenv [1] ------------------------------------------------------------- 39.28s
  INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing: create nodeenv [0] ------------------------------------------------------------- 39.21s
  INFO:/var/tmp/configuration/playbooks/callback_plugins/task_timing:
Playbook Configure instance(s) finished: 2018-03-16 05:36:19.677103, 730 total tasks.  0:36:33.512179 elapsed. 

 - reason：
     the log of my VPS：
      2018-03-11 23:01:57 INFO     connecting localhost:9200 from 119.23.74.247:40044
      2018-03-11 23:01:57 ERROR    IP ::1 is in forbidden list, reject

    why    localhost：9200  bypass the proxy and get  502？？
              but   curl http://127.0.0.1:9200
                     curl http://localhost:9200    
              are  normal ,  get request from elasticsearch

**Comment by shingiru** [comment]
https://github.com/lostisland/faraday/issues/487

Open edX forum component is built on old Ruby on Rails version. And it uses old faraday library as http client. And the library ignore no-proxy env setting value. On the contrary, the library use proxy setting value. Therefore, one of quick walk-around would be commenting out some proxy related source of its library as following.

sudo vi /edx/app/forum/.gem/ruby/1.9.1/gems/faraday-0.11.0/lib/faraday/connection.rb
#req.options = self.options.merge(:proxy => self.proxy) // 392 line

**Comment by jerrybox** [comment]
@shingiru  Thanks. You are right.
I solve it by adding one task before and after the installation script as follow:
vim /var/tmp/configuration/playbooks/roles/forum/tasks/deploy.yml +63
```
  - name: before initialize elasticsearch
    shell: "unset http_proxy"

  - name: initialize elasticsearch
    command: "{{ forum_code_dir }}/bin/rake search:initialize"
    args:
      chdir: "{{ forum_code_dir }}"
    become_user: "{{ forum_user }}"
    environment: "{{ forum_base_env }}"
    when: migrate_db is defined and migrate_db|lower == "yes"
    run_once: yes
    tags:
      - migrate
      - migrate:db

  - name: after initialize elasticsearch
    shell: "export http_proxy='http://127.0.0.1:8123/'"
```
