### ISSUE TITLE
Mongo db doesn't start when deploying edxapp on EC2

### ISSUE THREAD

**Issue by tummykung** [openedx-unsupported/configuration#464]
Hi,

I followed this [instruction](https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation) how to install edx on Ubuntu 12.04. I used the newest release version (November 14). I ran the following command on an EC2 server.
When I run,

```
sudo ansible-playbook -vvvv -c local --limit "localhost:127.0.0.1" ./edx_sandbox.yml -i "localhost," -e "EDXAPP_LMS_PREVIEW_NGINX_PORT=80 EDXAPP_LMS_BASE=ecx-xx-xxx-xxx-xx.us-west-1.compute.amazonaws.com"
```

I get this error:
https://gist.github.com/tummykung/6bf5f0659f964746991d

I'm not sure how to resolve this. Any help is appreciated.

Thanks,
Tum

**Comment by noahfx** [comment]
I have the same exact problem but I run `sudo ansible-playbook -c local --limit "localhost:127.0.0.1" ./edx_sandbox.yml -i "localhost,"` 

I realease that the mongod is not running but I don't know if is due to the chage of the package from mongodb to mongodb-10gen.

**Comment by tummykung** [comment]
I looked at the mongodb log file, and saw this:

Thu Nov 14 04:00:03.601 [initandlisten] ERROR: Insufficient free space for journal files
Thu Nov 14 04:00:03.601 [initandlisten] Please make at least 3379MB available in /edx/var/mongo/mongodb/journal or use --smallfiles

Perhaps medium isn't enough?

**Comment by noahfx** [comment]
I have the same output 
`
Sun Nov 24 04:22:05.811 [initandlisten] options: { bind_ip: "127.0.0.1", config: "/etc/mongodb.conf", dbpath: "/edx/var/mongo/mongodb", journal: "true", logappend: "True", logpath: "/edx/var/log/mongo/mongodb.log", port: 27017 }
Sun Nov 24 04:22:05.844 [initandlisten] journal dir=/edx/var/mongo/mongodb/journal
Sun Nov 24 04:22:05.844 [initandlisten] recover : no journal files present, no recovery needed
Sun Nov 24 04:22:05.844 [initandlisten] 
Sun Nov 24 04:22:05.844 [initandlisten] ERROR: Insufficient free space for journal files
Sun Nov 24 04:22:05.844 [initandlisten] Please make at least 3379MB available in /edx/var/mongo/mongodb/journal or use --smallfiles`

**Comment by tummykung** [comment]
I increased the space by using m1.large type. It passed that mongodb problem, but encountered another problem

```
TASK: [edxapp | gather  static assets with rake] ******************************
.
.
.
OSError: [Errno 28] No space left on device
collectstatic failed!
stdout:   overwrite lms/static/sass/application-extend1.css
  overwrite lms/static/sass/application-extend2.css
  overwrite lms/static/sass/application.css
  overwrite lms/static/sass/course.css

FATAL: all hosts have already failed -- aborting
```

Why does it need so much space? I'll try to increase the space again and see how it goes.

**Comment by tummykung** [comment]
I increased the space one more level -- now I set my EC2 type to m1.xlarge. This time I get this error:
https://github.com/edx/configuration/issues/487

**Comment by e0d** [comment]
A medium should be large enough, we run the full stack on mediums ourselves.  Also, disk space and instance size are not necessarily related.  We use mediums with a 50G root, EBS backed, volume.  Can you try this configuration?

**Comment by tummykung** [comment]
I changed to m1.medium and encountered a mongodb error: https://gist.github.com/tummykung/2fea6e5afe571a4177a9

**Comment by hkim823** [comment]
Closing this since so much has changed in 3 months, but looking at the gist, dev/xvda1 at 8GB will never work if you are trying to run the whole stack in one stance, 50GB recommended for root volume.
