### ISSUE TITLE
Error install bower dependencies Task insights - Native Open edX Ubuntu 16.04 64 bit Installation

### ISSUE THREAD

**Issue by estaesunaversiondeprueba** [openedx-unsupported/configuration#4645]
Hi I tried "Native Open edX Ubuntu 16.04 64 bit Installation":
- https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/146440579/Native+Open+edX+Ubuntu+16.04+64+bit+Installation

In a clean machine starts the process, But get an error in:
	
> 4. Install Open edX:
> wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash
> 

```
TASK [insights : install bower dependencies] ***********************************
fatal: [localhost]: FAILED! => 
...
"stderr": "bower jasmine#~2.0.4                                                 
    EINVRES Request to https://bower.herokuapp.com/packages/jasmine failed with 502",
..
```

All the Urls on https://bower.herokuapp.com gets the message:

> This Bower version is deprecated. Please update it: npm install -g bower. The new registry address is https://registry.bower.io

The repo needs to update their dependencies? or what is the problem/solution?

Thanks.

**Comment by hoichong** [comment]
This seems to be the solution:
https://stackoverflow.com/questions/51020317/einvres-request-to-https-bower-herokuapp-com-packages-failed-with-502

**Comment by nedbat** [comment]
You shouldn't need to modify .bowerrc.  The ginkgo.master branch will install successfully.

If you continue to have problems, please report them on the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops).  Tell us what version you are trying to install, how you installed it, and any other information you have that could help us narrow down the problem.

**Comment by bhaskar8088** [comment]
What if we need to install ficus.4 and not ginkgo ? Can we install ginkgo.master and checkout to ficus.4 and use it ?

If .bowerrc need to be changed for ficus.4, this is what I am doing:

Ok, I will try what is mentioned in stackoverflow answer.

How can I continue playbook after that ? I am using native installation and started installing with command:

nohup ./sandbox.sh > mylog.log &

After the error, I modified .bowerrc.

How can I continue installation ? Log mentioned this:  --limit @/var/tmp/configuration/playbooks/edx_sandbox.retry

But dont know exact command to use it. Thanks.
