### ISSUE TITLE
Missing Variables for Journals causing errors during installation

### ISSUE THREAD

**Issue by jpmateo022** [openedx-unsupported/configuration#4652]
Hi Guys,

Does anyone know how to fix this?

I'm using OpenEdx Native Installation Ubuntu 16.04. Last it was working fine but I tried the installation yesterday to have a fresh OpenEdx then suddenly this error appears.

TASK [edx_django_service : run post-migrate commands] **************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "{{ journals_post_migrate_commands }}: [{u'when': True, u'command': u'./manage.py create_site --sitename \"DemoSite\" --hostname \"journals-{{ EDXAPP_SITE_NAME }}\" --port \"80\" --lms-url-root \"{{ JOURNALS_LMS_URL_ROOT }}\" --lms-public-url-root-override \"{{ JOURNALS_LMS_URL_ROOT }}\" --discovery-api-url \"{{ JOURNALS_DISCOVERY_API_URL }}\" --ecommerce-api-url \"{{ JOURNALS_ECOMMERCE_API_URL }}\" --discovery-partner-id \"edX\" --ecommerce-partner-id \"edX\" --currency-codes USD --client-secret \"{{ JOURNALS_SOCIAL_AUTH_EDX_OIDC_SECRET }}\" --client-id \"{{ JOURNALS_SOCIAL_AUTH_EDX_OIDC_KEY }}\" --discovery-journal-api-url \"{{ JOURNALS_DISCOVERY_JOURNALS_API_URL }}\" --ecommerce-journal-api-url \"{{ JOURNALS_ECOMMERCE_JOURNALS_API_URL }}\" --ecommerce-public-url-root \"{{ JOURNALS_ECOMMERCE_BASE_URL }}\"\\n'}, {u'when': True, u'command': u'./manage.py create_org --key \"edX\" --sitename \"DemoSite\"'}, {u'become_user': u'{{ journals_user }}', u'environment': u'{{ journals_environment }}', u'when': False, u'command': u'{{ COMMON_BIN_DIR }}/python.journals {{ COMMON_BIN_DIR }}/manage.journals publish_journals --create \"Demo Journal\" --org \"edX\" --price \"100.00\"\\n'}]: 'JOURNALS_LMS_URL_ROOT' is undefined"}

It seems these variables are missing in ansible:

JOURNALS_LMS_URL_ROOT
JOURNALS_DISCOVERY_SERVICE_URL
JOURNALS_DISCOVERY_API_URL
JOURNALS_DISCOVERY_JOURNALS_API_URL
JOURNALS_ECOMMERCE_BASE_URL
JOURNALS_ECOMMERCE_API_URL
JOURNALS_ECOMMERCE_JOURNALS_API_URL

I Actually don't know what value I will be using

**Comment by jpmateo022** [comment]
Hi Guys,

May I know if you were able to look into this?

**Comment by jpmateo022** [comment]
Hi,

May I know if someone was able to look into this?

![image](https://user-images.githubusercontent.com/26633918/42145077-9bdefd92-7df1-11e8-8bbf-c13f71ede92d.png)

**Comment by cequn** [comment]
i got the same issue with you, can't find these vars, and btw, how do you fix the error when run oauth task, the invalid url of journals? mine is 'http://journals:18606',

**Comment by jpmateo022** [comment]
Hi OpenEdx Team,

I know it's a free work but It's been a show stopper for me and I've been stuck in this for more than a week. Hope you can help us.

**Comment by nedbat** [comment]
@jpmateo022 @cequn GitHub issues are not the place to get support.  Have you tried the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops) ?
