### ISSUE TITLE
Ansible task that install bower dependencies failing due to bower repository at . http://bower.herokuapp.com/ 

### ISSUE THREAD

**Issue by hoichong** [openedx-unsupported/configuration#4655]
Ansible task that install bower dependencies failing due to bower repository at . http://bower.herokuapp.com/ is no more available.

Suggested fix is this:
https://stackoverflow.com/questions/51020317/einvres-request-to-https-bower-herokuapp-com-packages-failed-with-502

Here is a typical error message when doing this task...

TASK [insights : install bower dependencies] *******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ". /edx/app/insights/venvs/insights/bin/activate && . /edx/app/insights/nodeenvs/insights/bin/activate && /edx/app/insights/edx_analytics_dashboard/node_modules/.bin/bower install --production --config.interactive=false", "delta": "0:00:03.843747", "end": "2018-06-29 07:14:41.839502", "failed": true, "rc": 1, "start": "2018-06-29 07:14:37.995755", "stderr": "bower bootstrap-sass-official#v3.3.0                                 EINVRES Request to https://bower.herokuapp.com/packages/bootstrap-sass-official failed with 502", "stderr_lines": ["bower bootstrap-sass-official#v3.3.0                                 EINVRES Request to https://bower.herokuapp.com/packages/bootstrap-sass-official failed with 502"], "stdout": "bower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0       not-cached git://github.com/overset/javascript-natural-sort.git#dbf4ca259b327a488bd1d7897fd46d80c414a7e0\nbower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0          resolve git://github.com/overset/javascript-natural-sort.git#dbf4ca259b327a488bd1d7897fd46d80c414a7e0\nbower edx-ui-toolkit#29759050aff2f4f3cb6921432855ad057bd69bb1     not-cached git://github.com/edx/edx-ui-toolkit.git#29759050aff2f4f3cb6921432855ad057bd69bb1\nbower edx-ui-toolkit#29759050aff2f4f3cb6921432855ad057bd69bb1        resolve git://github.com/edx/edx-ui-toolkit.git#29759050aff2f4f3cb6921432855ad057bd69bb1\nbower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0         checkout dbf4ca259b327a488bd1d7897fd46d80c414a7e0\nbower edx-ui-toolkit#29759050aff2f4f3cb6921432855ad057bd69bb1       checkout 29759050aff2f4f3cb6921432855ad057bd69bb1\nbower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0         resolved git://github.com/overset/javascript-natural-sort.git#dbf4ca259b\nbower edx-ui-toolkit#29759050aff2f4f3cb6921432855ad057bd69bb1       resolved git://github.com/edx/edx-ui-toolkit.git#29759050af", "stdout_lines": ["bower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0       not-cached git://github.com/overset/javascript-natural-sort.git#dbf4ca259b327a488bd1d7897fd46d80c414a7e0", "bower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0          resolve git://github.com/overset/javascript-natural-sort.git#dbf4ca259b327a488bd1d7897fd46d80c414a7e0", "bower edx-ui-toolkit#29759050aff2f4f3cb6921432855ad057bd69bb1     not-cached git://github.com/edx/edx-ui-toolkit.git#29759050aff2f4f3cb6921432855ad057bd69bb1", "bower edx-ui-toolkit#29759050aff2f4f3cb6921432855ad057bd69bb1        resolve git://github.com/edx/edx-ui-toolkit.git#29759050aff2f4f3cb6921432855ad057bd69bb1", "bower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0         checkout dbf4ca259b327a488bd1d7897fd46d80c414a7e0", "bower edx-ui-toolkit#29759050aff2f4f3cb6921432855ad057bd69bb1       checkout 29759050aff2f4f3cb6921432855ad057bd69bb1", "bower natural-sort#dbf4ca259b327a488bd1d7897fd46d80c414a7e0         resolved git://github.com/overset/javascript-natural-sort.git#dbf4ca259b", "bower edx-ui-toolkit#29759050aff2f4f3cb6921432855ad057bd69bb1       resolved git://github.com/edx/edx-ui-toolkit.git#29759050af"]}
        to retry, use: --limit @/var/tmp/configuration/playbooks/edx_sandbox.retry

**Comment by DerekCrosson** [comment]
I'm getting the same error.

Server specs:
Ubuntu 16.04.4 x64
4 vCPU
8GB RAM
160 GB disk

Using native installation.

**Comment by DerekCrosson** [comment]
Does anyone know which file I must edit to change the bower repo? I can't seem to find it...

**Comment by DerekCrosson** [comment]
Okay, for anyone who runs into the same problem, here's how I changed the bower repo:

Searched my server for the following file:
sudo find / -iname '. bowerrc*'

Then opened the file:
sudo vi /edx/app/ecommerce/ecommerce/.bowerrc

Added the following (don't forget to add a comma at the end of the previous line):
"registry": "https://registry.bower.io"

Ran the following command again:
wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/sandbox.sh -O - | bash

**Comment by nedbat** [comment]
You shouldn't need to modify .bowerrc.  The ginkgo.master branch will install successfully.

If you continue to have problems, please report them on the [mailing list](https://groups.google.com/forum/#!forum/openedx-ops).  Tell us what version you are trying to install, how you installed it, and any other information you have that could help us narrow down the problem.

**Comment by shruti-perpetualny** [comment]
@DerekCrosson , I m also facing same bower issue, I have tried to follow you but it is asking for edxapp password.
Do you know the password?
