### ISSUE TITLE
the -vvv option to anisble-playbook? 

### ISSUE THREAD

**Issue by kern3020** [openedx-unsupported/configuration#47]
Hello, 

A command in the README.md file, refers to a '-vvv' option to the ansible-playbook.

``````
    $ git diff README.md 
    diff --git a/README.md b/README.md
    index ba1371d..46fe36a 100644
    --- a/README.md
    +++ b/README.md
    @@ -168,7 +168,7 @@ playbooks

       ```
       cd playbooks
    -  ansible-playbook  -vvv cloudformation.yml -i inventory.ini  -e 'region=<aws_region> key=<key_name> name=<st
    +  ansible-playbook cloudformation.yml -i inventory.ini  -e 'region=<aws_region> key=<key_name> name=<stack_na
       ```

     * _aws_region_: example: `us-east-1`. Which AWS EC2 region to build stack in.
``````

Is this a typo? When I read the manage for this command for ansible 1.2, I didn't see it. If it is a typo or should it be '-v' or simply omitted? 

-jk

**Comment by jrbl** [comment]
You can say -v or -vv or -vvv. Stack them up as deep as you'd like.

**Comment by kern3020** [comment]
Thanks! I see. many APIs use an integer to define the verbosity level.  Here they use the number of 'v's. Got it.

**Comment by jarv** [comment]
Yeah that just adds extra verbosity, it's probably overkill.
