### ISSUE TITLE
Installation failed due to LibSass warning

### ISSUE THREAD

**Issue by pjotrsavitski** [openedx-unsupported/configuration#4815]
Installation process fails due to LibSass version issuing a warning about the stylesheet files. This is due to some of the syntax being retired. Yet this is not an **end of the line** issue and the process does not fail.

Is there a quickfix for this situation? The process is automated and there does not seem to be any easy way to control the versions of installed components (e.g. force an older version of LibSass to be installed).

### Repo heads:
---- /edx/app/analytics_api/analytics_api ----
2018-08-06 14:40:49 -0400 (9ed9aaf) Ned Batchelder: Upgrade django and all its dependencies.  (grafted, HEAD, tag: open-release/hawthorn.2, tag: open-release/hawthorn.1)
---- /edx/app/ecommerce/ecommerce ----
2018-08-03 11:20:28 -0400 (1fe5c3f) Ned Batchelder: Update to the latest patch version of Django.  (grafted, HEAD, tag: open-release/hawthorn.2, tag: open-release/hawthorn.1)
---- /edx/app/ecomworker/ecomworker ----
2017-12-06 12:57:10 -0500 (8bd14f8) Cory Lee: OPS-2492 Add redis dependency  (grafted, HEAD, tag: open-release/hawthorn.2, tag: open-release/hawthorn.1rc3, tag: open-release/hawthorn.1rc2, tag: open-release/hawthorn.1rc1, tag: open-release/hawthorn.1, tag: nedbat/test/h.1.1)
---- /edx/app/edx_ansible/edx_ansible ----
2018-10-01 16:00:54 -0400 (7a64d49) GitHub: Use prod.py instead of aws.py (#4795)  (HEAD -> master, origin/master, origin/HEAD)
---- /edx/app/edxapp/edx-platform ----
2018-09-17 15:50:59 -0400 (58d2ac8) Ned Batchelder: Edit test value to be valid URL format  (HEAD, tag: open-release/hawthorn.2, origin/open-release/hawthorn.master)
---- /edx/app/insights/edx_analytics_dashboard ----
2018-08-03 11:22:48 -0400 (ca07e29) Ned Batchelder: Upgrade django version.  (grafted, HEAD, tag: open-release/hawthorn.2, tag: open-release/hawthorn.1)

### Steps to replicate:
 * Install as described in: https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/146440579/Native+Open+edX+Ubuntu+16.04+64+bit+Installation
 * Issue arises during the step **4** and process fails

### Failed task and feedback

`TASK [insights : run webpack] **************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ". /edx/app/insights/nodeenvs/insights/bin/activate && /edx/app/insights/edx_analytics_dashboard/node_modules/.bin/webpack --config webpack.prod.config.js", "delta": "0:01:13.367353", "end": "2018-10-02 13:18:28.511826", "failed": true, "rc": 137, "start": "2018-10-02 13:17:15.144473", "stderr": "DEPRECATION WARNING on line 22, column 8 of stdin:\nIncluding .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.\nUse a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.\n\nDEPRECATION WARNING on line 25, column 8 of stdin:\nIncluding .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.\nUse a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.\n\nDEPRECATION WARNING on line 22, column 8 of stdin:\nIncluding .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.\nUse a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.\n\nDEPRECATION WARNING on line 25, column 8 of stdin:\nIncluding .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.\nUse a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.\n\nKilled", "stderr_lines": ["DEPRECATION WARNING on line 22, column 8 of stdin:", "Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.", "Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.", "", "DEPRECATION WARNING on line 25, column 8 of stdin:", "Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.", "Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.", "", "DEPRECATION WARNING on line 22, column 8 of stdin:", "Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.", "Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.", "", "DEPRECATION WARNING on line 25, column 8 of stdin:", "Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.", "Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.", "", "Killed"], "stdout": "", "stdout_lines": []}`

**Comment by wbs306** [comment]
Have you solved it? I'm facing the same problem.

**Comment by pjotrsavitski** [comment]
> Have you solved it? I'm facing the same problem.

Sorry, did not find any solution. It went through on the live server (for whatever reason).

Messing around with my local VM did not seem like something that was really worth it (considering the 4 hour execution cycle).

As a wild guess, I would say there could be a way to force the system to install an older version of LibSass, that way the warnings would never get triggered. But that would require some additional trickery before the process begins.

**Comment by wbs306** [comment]
> > Have you solved it? I'm facing the same problem.
> 
> Sorry, did not find any solution. It went through on the live server (for whatever reason).
> 
> Messing around with my local VM did not seem like something that was really worth it (considering the 4 hour execution cycle).
> 
> As a wild guess, I would say there could be a way to force the system to install an older version of LibSass, that way the warnings would never get triggered. But that would require some additional trickery before the process begins.

I'm trying to downgrade libsass-python to v0.10.0, but there are some compilation errors in my VM when installing libsass.
I also try to correct the file, but it appears another error.
So I remove insight which needed libsass, unfortunately, mysql throw "strict mode" error.

Overall, I have no way to solve it, wish it will be fixed.

**Comment by pjotrsavitski** [comment]
Hmm .... I am not sure why are you trying to do that with libsass-python

In my case it seems to be happening within the Webpack build process, that one has nothing to do with Python and is all about Node.js

Please do check the command beign used (at least in my case) `/edx/app/insights/nodeenvs/insights/bin/activate && /edx/app/insights/edx_analytics_dashboard/node_modules/.bin/webpack --config webpack.prod.config.js"`

It does activate the virtual environment for the insights module, but the one doing the heavy lifting is Node.js specific process.

If you do check the file named `webpack.prod.config.js` and located in this `/edx/app/insights/edx_analytics_dashboard` directory, it will give you the idea where the files with issues are.

The code pointed to this directory `/edx/app/insights/edx_analytics_dashboard/analytics_dashboard/static`

Running `grep -r "\.css" *` in it might be enough to determine the lines in question.

The issue could be the one described [here](https://github.com/sass/node-sass/issues/2362)

My version of `node-sass` is 4.9.0, the new one might fix it. Or it could be possible to force install an older one that did not have that problem. BTW, it seems that the newest beta version (does get mentioned in the issue thread) might have resolved the issue.

It seems to be one of the three: force use older version of `node-sass`, force use the newest version of `node-sass` with the fix, change the imports somehow.

**Comment by wbs306** [comment]
Emmmm, I noticed libsass-python is needed in `/edx/app/insights/edx_analytics_dashboard/requirements/base.txt` so I tried it.

This issue seems like resolved without any modifications when I install `open-release/hawthorn.2` just now, the task `[insights : run webpack]` runs successfully. But, unfortunately, another issue appears...

**Comment by pjotrsavitski** [comment]
Sorry, did not try again (I did by with the same VM instance and it already had some user accounts present, so it failed; did not feel like waiting for a few more hours).

Just as a wild guess: if you do not need to run it in production, then you could try running the Devstack with Docker. It should have prebuilt images so all should be working well enough.

**Comment by wbs306** [comment]
I just want to learn something about that, so I tried it again and again. Thanks for your help.:smiley:

**Comment by pjotrsavitski** [comment]
You are welcome.

The process is a bit limiting as there are some assumptions being made (like the user accounts should not exist) and if you have gotten far enough with that and something else fails. Well, tough luck.

I might give that a go again, but not very soon. You might also try one other thing, join the Slack channel and ask around. They might give better advice and fast.

**Comment by wbs306** [comment]
Got it, it might be a batter way.
