### ISSUE TITLE
Header error typo?

### ISSUE THREAD

**Issue by solitaryr** [openedx-unsupported/configuration#483]
I got the following error while running the command to add requirements (sudo pip install -r requirements.txt)

/var/tmp/configuration/build/lxml/src/lxml/includes/etree_defs.h:9:31: fatal error: libxml/xmlversion.h: No such file or directory

However, that file did exist on my system but the xsltversion.h file was missing.  Once I added the libxslt-dev package, it compiled cleanly.  Unfortunately, the header file referenced in the error above disappeared before I could verify that the error was a typo.

**Comment by e0d** [comment]
This looks like a requirement that we removed in error, which project were you installing and which OS and version?

**Comment by solitaryr** [comment]
I was following the directions here: https://github.com/edx/configuration/wiki/edX-Developer-Stack.  I was running this on Ubuntu 12.04.

**Comment by feanil** [comment]
These requirements issues should be fixed can you please try again with the latest version.
