### ISSUE TITLE
problem with rake "Installing edX on a single Ubuntu 12.04 (Precise) server"

### ISSUE THREAD

**Issue by troublestarter** [openedx-unsupported/configuration#487]
Hi All, and thanks you for your futur support

All steps are good but the only one wich fail is this one : 

TASK: [edxapp | gather  static assets with rake] ******************************
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:11.392584", "end": "2013-11-22 18:08:31.350517", "item": "lms", "rc": 1, "start": "2013-11-22 18:08:19.957933"}
stderr: mkdir -p /edx/app/edxapp/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback
xmodule_assets common/static/xmodule
2013-11-22 12:08:21,202 INFO 3055 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee`
sass --style compressed --load-path ./common/static/sass --update -E utf-8 */static
rake aborted!
Command failed with status (1): [sass --style compressed --load-path ./comm...]
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in`call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `sh'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in`sh'
/edx/app/edxapp/edx-platform/rakelib/assets.rake:86:in `block (3 levels) in <top (required)>'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in`call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in`each'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:184:in`block in invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:215:in`block (2 levels) in invoke_prerequisites_concurrently'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/promise.rb:63:in `call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/promise.rb:63:in`chore'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/promise.rb:45:in `work'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/thread_pool.rb:103:in`process_queue_item'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/thread_pool.rb:117:in `block (2 levels) in start_thread'
Tasks: TOP => gather_assets => assets => assets:all => assets:sass
(See full trace by running task with --trace)
stdout:   overwrite cms/static/sass/style-app.css
  overwrite cms/static/sass/style-xmodule.css
      error lms/static/sass/application-extend1.scss (Line 23: File to import not found or unreadable: .
Load paths:
  /edx/app/edxapp/edx-platform
  /edx/app/edxapp/edx-platform/common/static/sass
  /edx/app/edxapp/edx-platform/cms/static
  /edx/app/edxapp/edx-platform/common/static
  /edx/app/edxapp/edx-platform/lms/static)
      error lms/static/sass/application-extend2.scss (Line 23: File to import not found or unreadable: .
Load paths:
  /edx/app/edxapp/edx-platform
  /edx/app/edxapp/edx-platform/common/static/sass
  /edx/app/edxapp/edx-platform/cms/static
  /edx/app/edxapp/edx-platform/common/static
  /edx/app/edxapp/edx-platform/lms/static)
      error lms/static/sass/application.scss (Line 22: File to import not found or unreadable: .
Load paths:
  /edx/app/edxapp/edx-platform
  /edx/app/edxapp/edx-platform/common/static/sass
  /edx/app/edxapp/edx-platform/cms/static
  /edx/app/edxapp/edx-platform/common/static
  /edx/app/edxapp/edx-platform/lms/static)
      error lms/static/sass/course.scss (Line 14: File to import not found or unreadable: .
Load paths:
  /edx/app/edxapp/edx-platform
  /edx/app/edxapp/edx-platform/common/static/sass
  /edx/app/edxapp/edx-platform/cms/static
  /edx/app/edxapp/edx-platform/common/static
  /edx/app/edxapp/edx-platform/lms/static)
  overwrite lms/static/sass/ie.css
changed: [localhost] => (item=cms)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/administrateur/edx_sandbox.retry

localhost                  : ok=116  changed=26   unreachable=0    failed=1

Thanks to the team

**Comment by tummykung** [comment]
I have the same problem!

**Comment by troublestarter** [comment]
For MongoDB i've no problem. But still Rake problem. Here are some notes :
- My configuration is :
  Ubuntu 12.04 ( last download version )
- cat /etc/lsb-release
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=12.04
  DISTRIB_CODENAME=precise
  DISTRIB_DESCRIPTION="Ubuntu 12.04.3 LTS"
- uname -a :
  Linux openedx 3.2.0-56-generic #86-Ubuntu SMP Wed Oct 23 09:20:45 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
- df -h
  Filesystem                    Size  Used Avail Use% Mounted on
  /dev/mapper/openedx--vg-root   28G  3.7G   23G  15% /
  udev                          977M  4.0K  977M   1% /dev
  tmpfs                         400M  184K  399M   1% /run
  none                          5.0M     0  5.0M   0% /run/lock
  none                          998M     0  998M   0% /run/shm
  /dev/xvda1                    228M   25M  192M  12% /boot

**Comment by e0d** [comment]
Please try running this from your host:

```
source /edx/app/edxapp/edxapp_env 
cd /edx/app/edxapp/edx-platform/
sudo -u edxapp -E PATH="/edx/app/edxapp/venvs/edxapp/bin:/edx/app/edxapp/edx-platform/bin:/edx/app/edxapp/.rbenv/bin:/edx/app/edxapp/.rbenv/shims:/edx/app/edxapp/.gem/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" SERVICE_VARIANT=lms /edx/app/edxapp/edx-platform/bin/rake lms:gather_assets:aws
```

**Comment by troublestarter** [comment]
Hi e0d, same problem i think

Here is the result :

administrateur@openedx:/var/tmp/configuration/playbooks$ source /edx/app/edxapp/edxapp_env
administrateur@openedx:/var/tmp/configuration/playbooks$ cd /edx/app/edxapp/edx-platform/
administrateur@openedx:/edx/app/edxapp/edx-platform$ sudo -u edxapp -E PATH="/edx/app/edxapp/venvs/edxapp/bin:/edx/app/edxapp/edx-platform/bin:/edx/app/edxapp/.rbenv/bin:/edx/app/edxapp/.rbenv/shims:/edx/app/edxapp/.gem/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" SERVICE_VARIANT=lms /edx/app/edxapp/edx-platform/bin/rake lms:gather_assets:aws
[sudo] password for administrateur:

./manage.py lms --settings aws preprocess_assets --traceback
xmodule_assets common/static/xmodule
2013-11-24 14:30:07,853 INFO 31286 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
sass --style compressed --load-path ./common/static/sass --update -E utf-8 */staticnode_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee`

```
  error lms/static/sass/application-extend1.scss (Line 23: File to import not found or unreadable: .
```

Load paths:
  /edx/app/edxapp/edx-platform
  /edx/app/edxapp/edx-platform/common/static/sass
  /edx/app/edxapp/edx-platform/cms/static
  /edx/app/edxapp/edx-platform/common/static
  /edx/app/edxapp/edx-platform/lms/static)
      error lms/static/sass/application-extend2.scss (Line 23: File to import not found or unreadable: .
Load paths:
  /edx/app/edxapp/edx-platform
  /edx/app/edxapp/edx-platform/common/static/sass
  /edx/app/edxapp/edx-platform/cms/static
  /edx/app/edxapp/edx-platform/common/static
  /edx/app/edxapp/edx-platform/lms/static)
      error lms/static/sass/application.scss (Line 22: File to import not found or unreadable: .
Load paths:
  /edx/app/edxapp/edx-platform
  /edx/app/edxapp/edx-platform/common/static/sass
  /edx/app/edxapp/edx-platform/cms/static
  /edx/app/edxapp/edx-platform/common/static
  /edx/app/edxapp/edx-platform/lms/static)
      error lms/static/sass/course.scss (Line 14: File to import not found or unreadable: .
Load paths:
  /edx/app/edxapp/edx-platform
  /edx/app/edxapp/edx-platform/common/static/sass
  /edx/app/edxapp/edx-platform/cms/static
  /edx/app/edxapp/edx-platform/common/static
  /edx/app/edxapp/edx-platform/lms/static)
rake aborted!
Command failed with status (1): [sass --style compressed --load-path ./comm...]
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in`call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils.rb:45:in `sh'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/file_utils_ext.rb:37:in`sh'
/edx/app/edxapp/edx-platform/rakelib/assets.rake:86:in `block (3 levels) in <top (required)>'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in`call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in`each'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:184:in`block in invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/task.rb:215:in`block (2 levels) in invoke_prerequisites_concurrently'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/promise.rb:63:in `call'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/promise.rb:63:in`chore'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/promise.rb:45:in `work'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/thread_pool.rb:103:in`process_queue_item'
/edx/app/edxapp/.gem/gems/rake-10.0.4/lib/rake/thread_pool.rb:117:in `block (2 levels) in start_thread'
Tasks: TOP => gather_assets => assets => assets:all => assets:sass
(See full trace by running task with --trace)

**Comment by tummykung** [comment]
After trying this:

```
source /edx/app/edxapp/edxapp_env 
cd /edx/app/edxapp/edx-platform/
sudo -u edxapp -E PATH="/edx/app/edxapp/venvs/edxapp/bin:/edx/app/edxapp/edx-platform/bin:/edx/app/edxapp/.rbenv/bin:/edx/app/edxapp/.rbenv/shims:/edx/app/edxapp/.gem/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" SERVICE_VARIANT=lms /edx/app/edxapp/edx-platform/bin/rake lms:gather_assets:aws
```

I still have the same problem here as well: https://gist.github.com/tummykung/23e50b770c35638a272f

**Comment by tummykung** [comment]
It seems that @import base/base has a problem?

**Comment by jarv** [comment]
I believe this is the issue where THEME_NAME is by default set to an empty string in lms.env.json.  We worked around this is the master branch of edx-platform but it not currently on the release branch (and probably won't be until next week at the earliest).

@troublestarter @tummykung  Assuming you are following these instructions https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation you will want to set the edx-platform commit to master.

```
sudo ansible-playbook -c local --limit "localhost:127.0.0.1" \
./edx_sandbox.yml -i "localhost," -e "edx_platform_commit=master"
```

**Comment by troublestarter** [comment]
Can you tell me how i will be notified of that fix ? You will post it here again ?

Thanks

**Comment by jarv** [comment]
The next official release of the configuration repo will have it (next week). For now if you use the master branch of edx-platform you can work around it.  Let me know if that doesn't work for you.

**Comment by samjackson8847** [comment]
I have the same problem! I am following these instructions https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation I tried the blow code too .

sudo ansible-playbook -c local --limit "localhost:127.0.0.1" ./edx_sandbox.yml -i "localhost," -e "edx_platform_commit=master"

but still getting the same error.Someone help me

**Comment by fastpakr** [comment]
I'm also seeing this problem running the installation using both master and release branch installation options.  All of the errors refer to the line numbers for calls to "@import 'base/base';"

**Comment by jarv** [comment]
There was a recent commit in master that broke gather_assets because THEME_NAME is set to '', https://github.com/edx/edx-platform/commit/08c9fd94d922c570eb1ec78e2d4cb64491e732ea specifically.
Should be resolved soon.

**Comment by samjackson8847** [comment]
Thanks for the feedback I have checked in edx/app/edxapp/lms.env.json the THEME_NAME is an empty string Is there a way to overcome this bug ?

**Comment by fastpakr** [comment]
Thanks jarv!

Looks like this should be fixed on the master side now.
https://github.com/edx/edx-platform/commit/85453f703eceee182528636bc7fbd4856d34f261

**Comment by samjackson8847** [comment]
Thanks fastpakr that works like charm Now i am facing error as below

Task: [elasticsearch | Ensure elasticsearch is enabled and started]
failed: [localhost] => {"failed": true, "item": ""}
msg: \* Starting ElasticSearch Server
... fail!

I have installed java in my ubuntu 32 bit system is there anyway to overcome this?
