### ISSUE TITLE
Problem with updating edx-platform on a single server

### ISSUE THREAD

**Issue by tummykung** [openedx-unsupported/configuration#489]
I followed [these instructions](https://github.com/edx/configuration/wiki/Updating-configuration-versions-on-a-single-server-or-vagrant) to update edx-platform after installing a dev stack following [these instructions](https://github.com/edx/configuration/wiki/edX-Developer-Stack).

I run into this error.

```
$ ansible-playbook deploy_edxapp.yml  -i "192.168.33.10,"  --user vagrant --tags deploy -e 'edx_platform_commit=master'
.
.
.
TASK: [writing  supervisor script] ******************************************** 
failed: [192.168.33.10] => (item=lms) => {"failed": true, "item": "lms"}
msg: Destination directory /edx/app/supervisor/conf.d does not exist
failed: [192.168.33.10] => (item=cms) => {"failed": true, "item": "cms"}
msg: Destination directory /edx/app/supervisor/conf.d does not exist

FATAL: all hosts have already failed -- aborting
```

 I have made sure that `ssh vagrant@192.168.33.10` works.
Any help is appreciated!

**Comment by wedaly** [comment]
@tummykung Thanks for catching that -- the "Updating configuration versions" won't work for devstack unless you add some extra args.  I've removed the link from the devstack wiki page.

The preferred way to update devstack is to use `vagrant provision`, which will re-run the correct Ansible deploy scripts.  I'm planning on updating the wiki pages soon to better document this process.
