### ISSUE TITLE
Add task to generate i18n

### ISSUE THREAD

**Issue by ovnicraft** [openedx-unsupported/configuration#501]
When deploy its needed a task to generate i18n files.

**Comment by pku9104038** [comment]
hi I want to deploy a Chinese version, do you know how to deploy edx with another language? thanks

**Comment by feanil** [comment]
@pku9104038 do you mean deploying with Chinese as the default language?  Right now the chinese translations are not complete.  Once they are, we'll add the language the the platform and you can set it as the default.  There is not much left to translate and if you want you can signup on transifex and help: https://www.transifex.com/projects/p/edx-platform/language/zh_CN/

**Comment by feanil** [comment]
@ovnicraft right now the i18n files are generated and checked in as an offline task.  Right now we don't have plans of automating it and making it a part of the deploy workflow but I would be happy to look at a PR for such a feature if you would like to build it out.

**Comment by pku9104038** [comment]
@feanil I have sign up transifex for Chinese translation several week. Now I want to test some translate result of them. In fact I am not so familar with how to deploy a second language version, even without automating. If you can give me some advice will very helpful. Anyway, thank you very much.

**Comment by feanil** [comment]
@sarina are there publicly available instructions for how to test translations locally?

**Comment by sarina** [comment]
@pku9104038 if you have the Chinese translations locally, you should be able to just change `LANGUAGE_CODE` in `lms/envs/common.py` to `zh-CN` or `zh-TW`. Alternatively you can visit a local url and append `?preview-lang=zh-CN` to set your session to Chinese (will deactivate when you log out).

We have a maillist for translations issues. I recommend looking through the archive and if your questions aren't answered, making a new post.

https://groups.google.com/forum/#!forum/openedx-translation

See also:
https://github.com/edx/edx-platform/blob/master/docs/en_us/developers/source/i18n.rst
https://github.com/edx/edx-platform/blob/master/docs/en_us/developers/source/i18n_translators_guide.rst

**Comment by sarina** [comment]
Also please note @ovnicraft we have lots of i18n generation scripts present in https://github.com/edx/edx-platform/tree/master/i18n

You can invoke these scripts directly (eg `python i18n/generate.py`) or use pre-defined rake tasks, see https://github.com/edx/edx-platform/blob/master/rakelib/i18n.rake
