### ISSUE TITLE
Install from 'master' branch is failing

### ISSUE THREAD

**Issue by solitaryr** [openedx-unsupported/configuration#510]
Opened this issue under edx-platform, https://github.com/edx/edx-platform/issues/1812, but have gotten past that point now.  Now I am getting what I can only guess is an ansible issue.  I am now getting this message and am having trouble tracking down where it may be coming from:

TASK: [edxapp | openid workaround - NOT FOR PRODUCTION] **********************\* 
changed: [localhost]

TASK: [create  application config] *******************************************\* 
fatal: [localhost] => {'msg': "Encountered unknown tag 'do'.", 'failed': True}
fatal: [localhost] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "Encountered unknown tag 'do'.", 'failed': True}]}

FATAL: all hosts have already failed -- aborting

I started this just before the T-giving break.

**Comment by solitaryr** [comment]
I believe I have tracked it down to this file: playbooks/roles/edxapp/tasks/service_variant_config.yml included from playbooks/roles/edxapp/tasks/deploy.yml.  The first line has '- name: "create {{ item }} application config"'.  Since the error has a double space between "create" and "application" (which failed to show up above), it would seem that the "item" variable is not being passed successfully.  Not sure how to fix this.

**Comment by solitaryr** [comment]
Also, here is the command initially used:

sudo ansible-playbook -c local --limit "localhost:127.0.0.1" /var/tmp/configuration/playbooks/edx_sandbox.yml -i "localhost," -e 'EDXAPP_PREVIEW_LMS_BASE=preview.mooc.example.com  EDXAPP_LMS_BASE=sandbox.mooc.example.com  EDXAPP_LMS_PREVIEW_NGINX_PORT=80 EDXAPP_CMS_NGINX_PORT=80 EDXAPP_LMS_NGINX_PORT=80 edx_platform_commit=master'

the limit is being rerun with --limit @/home/ubuntu/edx_sandbox.retry for subsequent runs.  It is using ansible 1.3.2 (latest available for Ubuntu 12.04)

**Comment by brainstorm** [comment]
I tried making those changes since the `config.update` shouldn't require output spilled into the jinja template (by the name, it seems like it just updates environment variables?):

```
diff --git a/playbooks/roles/edxapp/templates/cms.auth.json.j2 b/playbooks/roles/edxapp/templates/cms.auth.json.j2
index 6f1859f..522770b 100644
--- a/playbooks/roles/edxapp/templates/cms.auth.json.j2
+++ b/playbooks/roles/edxapp/templates/cms.auth.json.j2
@@ -1,2 +1,2 @@
-{% do cms_auth_config.update(EDXAPP_AUTH_EXTRA) %}
+{{ cms_auth_config.update(EDXAPP_AUTH_EXTRA) or '' }}
 {{ cms_auth_config | to_nice_json }}
diff --git a/playbooks/roles/edxapp/templates/cms.env.json.j2 b/playbooks/roles/edxapp/templates/cms.env.json.j2
index f24a6d9..732446c 100644
--- a/playbooks/roles/edxapp/templates/cms.env.json.j2
+++ b/playbooks/roles/edxapp/templates/cms.env.json.j2
@@ -1,2 +1,2 @@
-{% do cms_env_config.update(EDXAPP_ENV_EXTRA) %}
+{{ cms_env_config.update(EDXAPP_ENV_EXTRA) or '' }}
 {{ cms_env_config | to_nice_json }}
diff --git a/playbooks/roles/edxapp/templates/lms-preview.auth.json.j2 b/playbooks/roles/edxapp/templates/lms-preview.auth.json.j2
index 833b8d8..e8acf6a 100644
--- a/playbooks/roles/edxapp/templates/lms-preview.auth.json.j2
+++ b/playbooks/roles/edxapp/templates/lms-preview.auth.json.j2
@@ -1,2 +1,2 @@
-{% do lms_auth_config.update(EDXAPP_AUTH_EXTRA) %}
+{{ lms_auth_config.update(EDXAPP_AUTH_EXTRA) or '' }}
 {{ lms_preview_auth_config | to_nice_json }}
diff --git a/playbooks/roles/edxapp/templates/lms-preview.env.json.j2 b/playbooks/roles/edxapp/templates/lms-preview.env.json.j2
index 959b19c..9de91c6 100644
--- a/playbooks/roles/edxapp/templates/lms-preview.env.json.j2
+++ b/playbooks/roles/edxapp/templates/lms-preview.env.json.j2
@@ -1,2 +1,2 @@
-{% do lms_preview_env_config.update(EDXAPP_ENV_EXTRA) %}
+{{ lms_preview_env_config.update(EDXAPP_ENV_EXTRA) or '' }}
 {{ lms_preview_env_config | to_nice_json }}
diff --git a/playbooks/roles/edxapp/templates/lms.auth.json.j2 b/playbooks/roles/edxapp/templates/lms.auth.json.j2
index 3b547a5..8e2966b 100644
--- a/playbooks/roles/edxapp/templates/lms.auth.json.j2
+++ b/playbooks/roles/edxapp/templates/lms.auth.json.j2
@@ -1,2 +1,2 @@
-{% do lms_auth_config.update(EDXAPP_AUTH_EXTRA) %}
+{{ lms_auth_config.update(EDXAPP_AUTH_EXTRA) or '' }}
 {{ lms_auth_config | to_nice_json }}
diff --git a/playbooks/roles/edxapp/templates/lms.env.json.j2 b/playbooks/roles/edxapp/templates/lms.env.json.j2
index efdadf3..9093ad4 100644
--- a/playbooks/roles/edxapp/templates/lms.env.json.j2
+++ b/playbooks/roles/edxapp/templates/lms.env.json.j2
@@ -1,2 +1,2 @@
-{% do lms_env_config.update(EDXAPP_ENV_EXTRA) %}
+{{ lms_env_config.update(EDXAPP_ENV_EXTRA) or '' }}
 {{ lms_env_config | to_nice_json }}
```

But then I got the following error:

```
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:45.614488", "end": "2013-12-06 19:27:23.214616", "item": "lms", "rc": 1, "start": "2013-12-06 19:26:37.600128"}
stderr: mkdir -p /edx/app/edxapp/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback
xmodule_assets common/static/xmodule
2013-12-06 14:26:47,397 INFO 13561 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "./manage.py", line 91, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 26, in run
    modulestore(store_name)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 113, in modulestore
    settings.MODULESTORE[name].get('OPTIONS', {})
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 70, in create_modulestore_instance
    **_options
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 37, in __init__
    store['OPTIONS']
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 52, in create_modulestore_instance
    _options[key] = load_function(_options[key])
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 38, in load_function
    return getattr(import_module(module_path), name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named edxmako.shortcuts
asset preprocessing failed!
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee`
changed: [localhost] => (item=cms)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=115  changed=28   unreachable=0    failed=1
```

**Comment by brainstorm** [comment]
Seems to be related to the following forum thread:

https://groups.google.com/forum/#!topic/edx-code/vyb4CdA5M80

**Comment by solitaryr** [comment]
Thanks...I can confirm that this gets me to the same point. I have slightly more output...

TASK: [edxapp | gather  static assets with rake] *****************************\* 
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p /tmp/ansible-1386367075.49-261809997047838 && chmod a+rx /tmp/ansible-1386367075.49-261809997047838 && echo /tmp/ansible-1386367075.49-261809997047838']  
<localhost> REMOTE_MODULE command SERVICE_VARIANT=lms rake lms:gather_assets:aws executable=/bin/bash chdir=/edx/app/edxapp/edx-platform #USE_SHELL
<localhost> PUT /tmp/tmpU6ooNo TO /tmp/ansible-1386367075.49-261809997047838/command
<localhost> EXEC ['/bin/sh', '-c', 'chmod a+r /tmp/ansible-1386367075.49-261809997047838/command']
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=tonmswabfvvamjoijmurtdyqsdnxpfbm] password: " -u edxapp /bin/sh -c '"'"'RBENV_ROOT=/edx/app/edxapp/.rbenv GEM_HOME=/edx/app/edxapp/.gem PATH=/edx/app/edxapp/venvs/edxapp/bin:/edx/app/edxapp/edx-platform/bin:/edx/app/edxapp/.rbenv/bin:/edx/app/edxapp/.rbenv/shims:/edx/app/edxapp/.gem/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin NO_PREREQ_INSTALL=1 GEM_PATH=/edx/app/edxapp/.gem SKIP_WS_MIGRATIONS=1 LANG=en_US.UTF-8 /usr/bin/python /tmp/ansible-1386367075.49-261809997047838/command'"'"''  
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:10.348578", "end": "2013-12-06 21:58:06.007319", "item": "lms", "rc": 1, "start": "2013-12-06 21:57:55.658741"}  
stderr: mkdir -p /edx/app/edxapp/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback  
xmodule_assets common/static/xmodule  
2013-12-06 16:57:57,565 INFO 10680 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125  
Traceback (most recent call last):
  File "./manage.py", line 91, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 26, in run
    modulestore(store_name)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 113, in modulestore
    settings.MODULESTORE[name].get('OPTIONS', {})
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 70, in create_modulestore_instance
    **_options
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 37, in __init__
    store['OPTIONS']
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 52, in create_modulestore_instance
    _options[key] = load_function(_options[key])
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 38, in load_function
    return getattr(import_module(module_path), name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    **import**(name)
ImportError: No module named mitxmako.shortcuts
asset preprocessing failed!
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee` 
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p /tmp/ansible-1386367086.03-8601287649985 && chmod a+rx /tmp/ansible-1386367086.03-8601287649985 && echo /tmp/ansible-1386367086.03-8601287649985']
<localhost> REMOTE_MODULE command SERVICE_VARIANT=cms rake cms:gather_assets:aws executable=/bin/bash chdir=/edx/app/edxapp/edx-platform #USE_SHELL
<localhost> PUT /tmp/tmpw24Ww4 TO /tmp/ansible-1386367086.03-8601287649985/command
<localhost> EXEC ['/bin/sh', '-c', 'chmod a+r /tmp/ansible-1386367086.03-8601287649985/command']
<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=bbjuqtrnsloprungtotwqsnanmchnecp] password: " -u edxapp /bin/sh -c '"'"'RBENV_ROOT=/edx/app/edxapp/.rbenv GEM_HOME=/edx/app/edxapp/.gem PATH=/edx/app/edxapp/venvs/edxapp/bin:/edx/app/edxapp/edx-platform/bin:/edx/app/edxapp/.rbenv/bin:/edx/app/edxapp/.rbenv/shims:/edx/app/edxapp/.gem/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin NO_PREREQ_INSTALL=1 GEM_PATH=/edx/app/edxapp/.gem SKIP_WS_MIGRATIONS=1 LANG=en_US.UTF-8 /usr/bin/python /tmp/ansible-1386367086.03-8601287649985/command'"'"''
changed: [localhost] => (item=cms) => {"changed": true, "cmd": "SERVICE_VARIANT=cms rake cms:gather_assets:aws ", "delta": "0:00:40.516605", "end": "2013-12-06 21:58:46.713961", "item": "cms", "rc": 0, "start": "2013-12-06 21:58:06.197356", "stderr": "./manage.py cms --settings aws preprocess_assets --traceback \nxmodule_assets common/static/xmodule\n2013-12-06 16:58:07,468 INFO 10747 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125\nsass --style compressed --load-path ./common/static/sass --update -E utf-8 */static\nnode_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee` \n./manage.py cms --settings aws collectstatic --traceback --noinput > /dev/null\n2013-12-06 16:58:32,641 INFO 10785 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125", "stdout": "  overwrite cms/static/sass/style-app-extend1.css\n  overwrite cms/static/sass/style-app.css\n  overwrite cms/static/sass/style-xmodule.css\n  overwrite lms/static/sass/application-extend1.css\n  overwrite lms/static/sass/application-extend2.css\n  overwrite lms/static/sass/application.css\n  overwrite lms/static/sass/course.css\n  overwrite lms/static/sass/ie.css"}

FATAL: all hosts have already failed -- aborting

**Comment by solitaryr** [comment]
Ok...I made the fix referenced in the thread above and it gets this far and fails:

TASK: [rabbitmq | add rabbitmq cluster configuration] ************************\* 
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1386369728.13-1425225080048 && echo $HOME/.ansible/tmp/ansible-1386369728.13-1425225080048']
fatal: [localhost] => {'msg': "Encountered unknown tag 'do'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.", 'failed': True}
fatal: [localhost] => {'msg': "Encountered unknown tag 'do'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.", 'failed': True}

**Comment by wedaly** [comment]
@solitaryr The Jinja extension for the `do` tag should be enabled by the `ansible.cfg` file located in configuration/playbooks/ansible.cfg:

```
jinja2_extensions=jinja2.ext.do
```

According to [the Ansible docs](http://www.ansibleworks.com/docs/intro_configuration.html), Ansible finds this configuration file in the current working directory.  Are you running `ansible-playbook` from the `playbooks` directory?

**Comment by solitaryr** [comment]
Apparently not...I'll retry Monday and update.

**Comment by brainstorm** [comment]
@wedaly Thanks for that, I guess it could be stated in the `edx-sandbox.yml` header to avoid confusion (I know there's a wiki already but people might go directly to the .yml, as I did).

Now, the current problem for me is the opposite from the mailing list thread... instead of getting this:

`ImportError: No module named mitxmako.shortcuts`

I get this:

`ImportError: No module named edxmako.shortcuts`

:/

```
TASK: [edxapp | edxapp | gather  static assets with rake] *********************
failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:46.555581", "end": "2013-12-09 13:08:34.229831", "item": "lms", "rc": 1, "start": "2013-12-09 13:07:47.674250"}
stderr: mkdir -p /edx/app/edxapp/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback
xmodule_assets common/static/xmodule
2013-12-09 08:07:57,248 INFO 18659 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
Traceback (most recent call last):
  File "./manage.py", line 91, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 26, in run
    modulestore(store_name)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 113, in modulestore
    settings.MODULESTORE[name].get('OPTIONS', {})
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 70, in create_modulestore_instance
    **_options
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 37, in __init__
    store['OPTIONS']
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 52, in create_modulestore_instance
    _options[key] = load_function(_options[key])
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 38, in load_function
    return getattr(import_module(module_path), name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named edxmako.shortcuts
asset preprocessing failed!
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee`
changed: [localhost] => (item=cms)

FATAL: all hosts have already failed -- aborting
```

@malinsandstrom

**Comment by solitaryr** [comment]
Moving into the playbooks got me past that...

**Comment by solitaryr** [comment]
Looks like it ran through cleanly this time.  To summarize, the fixes to the templates referenced in the thread above fixed my issues.  It appears that the pull request may not have actually been applied to the master branch as of Friday (I re-cloned the master branch and had to manually apply them).  Other than https://github.com/edx/edx-platform/issues/1812, which appears to be a timing issue (server didn't start up quickly enough for script), I seem to have an active system now.

**Comment by brainstorm** [comment]
@solitaryr Really? Can you do a pull request or a `git diff` over here?

**Comment by solitaryr** [comment]
Not sure exactly how to do that but I just re-pulled the configuration from master and confirmed that the "do" is still there..for example from cms_auth_config.j2

{% do cms_auth_config.update(EDXAPP_AUTH_EXTRA) %}
{{ cms_auth_config | to_nice_json }}

Unless I misread the pull request, it appears that it was supposed to have been merged into master branch.  I'm trying to find the pull request that was supposedly merged...I recall someone else updated it that it wasn't completed.

Having a hell of a time finding the pull request but the first line was changed to:

{{ cms_auth_config.update(EDXAPP_AUTH_EXTRA) or '' }}

Note the missing "do".

Also note: it's possible I'm misremembering that it was in a pull request and not just the diff posted above.  However, what is posted above fixed my issues with the templates.

**Comment by brainstorm** [comment]
Thanks for the feedback and help!

I just got past those errors that by moving the whole thing to `/var/tmp` and running the command:

`ansible-playbook -c local --limit "localhost:127.0.0.1" ./edx_sandbox.yml -i "localhost," -e "edx_platform_commit=master"`

But then I get this new issue:

```
TASK: [xqueue | xqueue | create xqueue auth file] *****************************
fatal: [localhost] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 485, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 685, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/action_plugins/template.py", line 91, in run
    local_md5 = utils.md5s(resultant)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 523, in md5s
    digest.update(data)
TypeError: must be string or buffer, not dict


FATAL: all hosts have already failed -- aborting
```

This last one seems to be an ansible bug actually...

**Comment by solitaryr** [comment]
as long as I am in the /var/tmp/configuration/playbooks folder (per the wiki), everything runs clean (after applying the patch) with a clone from yesterday.  I don't think just copying the yaml file up will help since some of the services expect the relevant modules to be immediately below where you run from.  I also make a point to use sudo since some of the scripts require root privs...

sudo ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -vvvv -c local --limit "localhost:127.0.0.1" /var/tmp/configuration/playbooks/edx_sandbox.yml -i "localhost," -e 'edx_platform_commit=master'

Above command gave me more verbose output and kept the temp script around to review.

**Comment by brainstorm** [comment]
After killing the whole instance and recreating it, it worked :)

A little side-note before closing the issue though: The AWS CloudFormation single-instance template:

https://github.com/edx/configuration/blob/master/cloudformation_templates/edx-server-single-instance.json#L157

Does not open the ports `18000` and `18010` needed to access the general user portal and the studio part (creation of courses).

IMHO, it should by default.
