### ISSUE TITLE
assets not being built

### ISSUE THREAD

**Issue by yarko** [openedx-unsupported/configuration#526]
with two identical cloned edx trees, with HEAD at:

```
commit beda1f8bbf0140ba19b85539a7753a8941aabaf1
Merge: b33bb1a e26fc08
Author: David Baumgold <david@davidbaumgold.com>
Date:   Wed Dec 4 13:37:44 2013 -0800
```

Issue: LMS home page - 5 external social media icon links (lower right of page)

configuration..devstack Vagrant instance fails to create / reference icon images;
edx-platform Vagrant fullstack instance builds/generates / displays icon images correctly.

**Comment by hkim823** [comment]
this is an old issue, just cleaning things up, closing this for now
