### ISSUE TITLE
Ansible idiom updates

### ISSUE THREAD

**Issue by mpdehaan** [openedx-unsupported/configuration#542]
This part I see in various places:

```
- apt: pkg={{','.join(local_dev_pkgs)}} install_recommends=yes
```

This can be simplified as:

```
- apt: pkg={{ item }} install_recommends=yes
  with_items:  local_dev_pkgs
```

Ansible will still execute things in one apt transaction as it knows what to do.

Also, though this is more of a recent version thing

```
with_items: "{{ foo }}"
```

can/should be:

```
  with_items: foo
```

**Comment by e0d** [comment]
Was it always the case that ansible did the installation in a single transaction?  I had thought we specifically used this to work around the transaction issue.

**Comment by mpdehaan** [comment]
It's been the case for a pretty long time (well over a year) that if you are using certain package modules with_items is joined to a comma seperated list.

I am not sure exactly when that went in, but I'm sure anything version >=1.0 does that.
