### ISSUE TITLE
Ubuntu 12.04 Installation hangs at "install nltk data using rendered shell script"

### ISSUE THREAD

**Issue by rmurray68** [openedx-unsupported/configuration#551]
The Ubuntu 12.04 installation method on an AWS instance now hangs.

It goes all the way to the playbook task: "install nltk data using rendered shell script"

It does not show a particular error. Some symptoms and testing are:
- It stays at that task for over 1 hour. SSH session times out and the pipe is broken
- Tried to use "screen" to allow the Playbook tasks to run even upon a SSH disconnect. Let the task get to the install nlik step. But it sat there for over 3 hours with no progress.

Please advise if there is any particular log to include I can re-build and restart a new one.

**Comment by e0d** [comment]
This task should not take anything like that long.  We've recently started experiencing the same thing.  If you lsof the process is alpino.zip open and frozen at 1MB in size?

**Comment by rmurray68** [comment]
I am not sure where it got hung again.. I had to let it sit for over 2 hours.  Here was the output on the failure:

TASK: [ora | install nltk data using rendered shell script] *******************
failed: [localhost] => {"cmd": ["/edx/app/ora/venvs/ora/bin/python -m nltk.downloader -d /edx/var/ora/nltk_data all"], "failed": true, "item": "", "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

I am going to attempt to enable the logging of Ansible an see if I can can capture where it is getting hung.

**Comment by rmurray68** [comment]
Update - Re-ran the playbook with -v for verbose.  Here it the same error:

2013-12-17 17:01:24,317 p=11558 u=root |  TASK: [ora | install nltk data using rendered shell script] ******************\* 
2013-12-17 17:01:24,506 p=11558 u=root |  failed: [localhost] => {"cmd": ["/edx/app/ora/venvs/ora/bin/python -m nltk.downloader -d /edx/var/ora/nltk_data all"], "failed": true, "item": "", "rc": 2}
2013-12-17 17:01:24,507 p=11558 u=root |  msg: [Errno 2] No such file or directory
2013-12-17 17:01:24,507 p=11558 u=root |  FATAL: all hosts have already failed -- aborting
2013-12-17 17:01:24,508 p=11558 u=root |  PLAY RECAP *******************************************************************\* 
2013-12-17 17:01:24,508 p=11558 u=root |             to retry, use: --limit @/home/ubuntu/edx_sandbox.retry

2013-12-17 17:01:24,509 p=11558 u=root |  localhost                  : ok=239  changed=189  unreachable=0    failed=1

**Comment by juananpe** [comment]
Same problem here. As I have stated in the edx-code mailing list:

"I'm trying to install edx fullstack version (using Vagrant + Ansible) 
It looks like I'm facing a problem with this task:
"TASK: [ora | install nltk data using rendered shell script]"
because the installation gets stuck there for 2 hours without any message. No error, no warning, no nothing. I don't know what to do... I have tried to reinstall many times, but I always get the same message..."

I'm willing to help trying any workaround or quick&dirty fix that you suggest.

**Comment by sinux** [comment]
Same problem Here:

TASK: [ora | install nltk data using rendered shell script] *******************
failed: [localhost] => {"cmd": ["/edx/app/ora/venvs/ora/bin/python -m nltk.downloader -d /edx/var/ora/nltk_data all"], "failed": true, "item": "", "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/edx/edx_sandbox.retry

localhost                  : ok=232  changed=62   unreachable=0    failed=1

Any Ideas?

**Comment by jarv** [comment]
This is still an issue unfortunately, I think we are going to mirror the distribution. The problem is this file http://nltk.github.com/nltk_data/packages/corpora/framenet_v15.zip which also fails when I try to fetch it in the browser.

**Comment by juananpe** [comment]
It seems that it is online again. I have saved a copy here: https://dl.dropboxusercontent.com/u/284325/MOOCs/edx/nltk/framenet_v15.zip
I'm wondering if a change in /etc/hosts setting nltk.github.com to my Apache server's IP (offering a copy of the framenet_v15.zip file in the same folder, nltk_data/packages/corpora/), could do the trick... Let's try it !

**Comment by jarv** [comment]
I've merged a fix into master for this, we will now download nltk using our own mirror of the distribution.
