### ISSUE TITLE
Ubuntu 12.04 Installation edx_sandbox.yml not found

### ISSUE THREAD

**Issue by rmurray68** [openedx-unsupported/configuration#556]
Using the instructions for Ubuntu 12.04 and the "master" as of 9:10pm EST on 12/17/13
(latest commit 45f063afcd)

This is on an Ubuntu 12.0.4 AMI on Amazon AWS. Not using Vagrant.

Received the following error:

ubuntu@ip-10-139-40-104:/var/tmp/configuration/playbooks$ sudo ansible-playbook -c local --limit "localhost:127.0.0.1" ./edx_sandbox.yml -i "localhost," -e "edx_platform_version=master" -v
ERROR: the playbook: ./edx_sandbox.yml could not be found

**Comment by jarv** [comment]
This should be resolved now. The old edx_sandbox.yml was suffering from bit-rot, the new one matches the vagrant fullstack install.
