### ISSUE TITLE
Ubuntu 12.04 Installation fails at install nltkdata

### ISSUE THREAD

**Issue by rmurray68** [openedx-unsupported/configuration#558]
Using the Ubuntu 12.04 installation and the latest commit and edx_sandbox.yml.
- Unbuntu 12.04 Linux AMI on Amazon AWS
- Commit = latest commit 3f928dbca7

Fails at the following step:

TASK: [ora | install nltk data using rendered shell script] *******************
failed: [localhost] => {"cmd": ["/edx/app/ora/venvs/ora/bin/python -m nltk.downloader -d /edx/var/ora/nltk_data all"], "failed": true, "item": "", "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/ubuntu/edx_sandbox.retry

localhost                  : ok=246  changed=196  unreachable=0    failed=1

**Comment by jarv** [comment]
dupe of https://github.com/edx/configuration/issues/551
