### ISSUE TITLE
failed in "TASK: [discern | install python requirements for discern and ease] ************"

### ISSUE THREAD

**Issue by kundan1985** [openedx-unsupported/configuration#562]
Hi,

I am trying to install edx-configuration on fresh linux ubuntu server which is Xen virtual machine of rackspace, Using "https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation" but when i am going to run
 sudo ansible-playbook -c local ./edx_sandbox.yml \
 -i "localhost," -e "edx_platform_version=master"  
this command it throws error and message is
 failed in "TASK: [discern | install python requirements for discern and ease] 
I already tried with delete VM and follow instillation process again and again. it Alwasys failed in this step.
Here is logs:-

TASK: [discern | install python requirements for discern and ease] ************
failed: [localhost] => (item=/edx/app/discern/discern/requirements.txt) => {"cmd": "/edx/app/discern/venvs/discern/bin/pip install -r /edx/app/discern/discern/requirements.txt", "failed": true, "item": "/edx/app/discern/discern/requirements.txt"}
msg: stdout: Downloading/unpacking scipy==0.11.0 (from -r /edx/app/discern/discern/requirements.txt (line 1))
  Running setup.py egg_info for package scipy
    Running from scipy source directory.
    blas_opt_info:
    blas_mkl_info:
      libraries mkl,vml,guide not found in /edx/app/discern/venvs/discern/lib
      libraries mkl,vml,guide not found in /usr/local/lib
      libraries mkl,vml,guide not found in /usr/lib
      NOT AVAILABLE

```
atlas_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in /edx/app/discern/venvs/discern/lib
  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
Setting PTATLAS=ATLAS
customize GnuFCompiler
Could not locate executable g77
Could not locate executable f77
customize IntelFCompiler
Could not locate executable ifort
Could not locate executable ifc
customize LaheyFCompiler
Could not locate executable lf95
customize PGroupFCompiler
Could not locate executable pgfortran
customize AbsoftFCompiler
Could not locate executable f90
customize NAGFCompiler
Found executable /usr/bin/f95
customize VastFCompiler
customize CompaqFCompiler
Could not locate executable fort
customize IntelItaniumFCompiler
Could not locate executable efort
Could not locate executable efc
customize IntelEM64TFCompiler
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using config
compiling '_configtest.c':

/* This file is generated from numpy/distutils/system_info.py */
void ATL_buildinfo(void);
int main(void) {
  ATL_buildinfo();
  return 0;
}
```

and its continue to 25000 more lines.

Please help me to fix this issue.

Thanks,Kundan

**Comment by hkim823** [comment]
@kundan1985 lots changed in the time since you've posted this, can you please respond if you are still having issues standing up edX?

**Comment by hkim823** [comment]
Closing due to lack of response
