### ISSUE TITLE
release/devstack fails

### ISSUE THREAD

**Issue by yarko** [openedx-unsupported/configuration#564]
These comments refer to a completely clean directory / fresh install attempt (helping someone on the google group), based on wiki instructions of this date.

This is a gaggle of issues:

RE:  @wedaly commit 853792ae8197e882b62e07b195ff567b516bc174

(These comments refer primarily to vagrant/release/devstack/Vagrantfile, but also refer to the un-reviewed wiki instructions):
- new script @ line #4 not robust; should test assumptions / existence of directory;
- line #25 comment:  "TODO: replace with base box that has edx_ansible ..."
  This is a problem / the problem:  the script assumes this state, yet this commit does not fulfill that promise.
- line #49 comment:  "... assume edx_ansible role installed..."
  This should not assume:  either confirm, or add script to test / confirm.

As is, this devstack with existing wiki instructions completely fails installation:

``` ...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] The guest additions on this VM do not match the installed version of
VirtualBox! In most cases this is fine, but in rare cases it can
cause things such as shared folders to not work properly. If you see
shared folder errors, please update the guest additions within the
virtual machine and reload your VM.

Guest Additions Version: 4.2.0
VirtualBox Version: 4.3
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /vagrant
[default] Exporting NFS shared folders...
Preparing to edit /etc/exports. Administrator privileges will be required...
[default] Mounting NFS shared folders...
[default] Running provisioner: shell...
[default] Running: inline script
stdin: is not a tty
/tmp/vagrant-shell: line 1: /edx/app/edx_ansible/venvs/edx_ansible/bin/activate: No such file or directory
/tmp/vagrant-shell: line 2: cd: /edx/app/edx_ansible/edx_ansible/playbooks: No such file or directory
/tmp/vagrant-shell: line 3: ansible-playbook: command not found
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chmod +x /tmp/vagrant-shell && /tmp/vagrant-shell

Stdout from the command:



Stderr from the command:

stdin: is not a tty
/tmp/vagrant-shell: line 1: /edx/app/edx_ansible/venvs/edx_ansible/bin/activate: No such file or directory
/tmp/vagrant-shell: line 2: cd: /edx/app/edx_ansible/edx_ansible/playbooks: No such file or directory
/tmp/vagrant-shell: line 3: ansible-playbook: command not found

```

**Comment by wedaly** [comment]
Hi @yarko -- sorry about that!  We updated the wiki thinking the empanada release was going out on Wednesday, but with folks going on vacation didn't finish building and uploading the devstack base box.  Sorry for dropping the ball. @feanil built the base box last night, so I expect this to get resolved in the next few hours.

**Comment by TangXT** [comment]
Now，could it works？I want to try

**Comment by yarko** [comment]
Hi @wedaly - thanks for the update (I've been spending a lot of time trying to coach people off the groups mailings).  I've put an "escape hatch" in case of trouble in the wiki (since this might happen again?) suggesting that building a base-box yourself is one possibility.   I worry that the "in case of trouble" section is getting large.  (should it be moved to the end?  to it's own page?).

W.R.T. this issue:   regardless, the script at top could be a little more robust / give more useful messages; a one-liner test / echo would help a lot; something along the lines of:

[ -d /edx/app/edx_ansible/venvs/edx_ansible ] || (echo "Something appears incomplete in base box provisioning."; exit 1)

**Comment by wedaly** [comment]
Should be fixed with #565.  I'll send out an email to the edx-code list with an update shortly.

@yarko Thanks for all your help and for updating the wiki.  I agree that the troubleshooting section is getting a little long; you're welcome to move it to the end of the page or a separate page if you think that would be clearer.

I also agree that the script could be more robust.  I'll put in a separate PR to add that logic later today, but since the immediate problem has been fixed in master, I'm going to close this issue.

**Comment by yarko** [comment]
sounds good to me;  I'm "doing" it with the fix now (looks like AWS
permissions are good);  we'll see how that goes.

**Comment by gammoudiisoumaya** [comment]
hello !
i have problem when i use to install the Open edX Developer Stack
at the first I had problem with the virtualbox version :
GuestAdditions versions on your host (4.3.28) and guest (4.3.16) do not match
so i install the virtualbox 4.3.16 but now i have new problem :
==> default: stdin: is not a tty
==> default: [WARNING]: It is unneccessary to use '{{' in loops, leave variables in loop
==> default: expressions bare.

**Comment by feanil** [comment]
@gammoudiisoumaya if you are still having this problem, please open a new issue and provide more of the output.  The info you have provided so far has a warning but nothing that indicates the error you ran into.
