### ISSUE TITLE
edx production installation update

### ISSUE THREAD

**Issue by janadel** [openedx-unsupported/configuration#568]
I am trying to update an edx production installation on an Ubuntu 12.0.4 VPS by using the following procedure https://github.com/edx/configuration/wiki/Updating-configuration-versions-on-a-single-server-or-vagrant .
The problem is that file deploy_edxapp.yml is missing.

**Comment by edx-secure** [comment]
I think those instructions have a mistake in them.  Can you try with
forum.yml instead?  That is what you would use to update the forums.  If
you want to update the platform you can use 'edxapp.yaml'  The name got
changed a while back.
