### ISSUE TITLE
No manual commands printed following successful creation of stack

### ISSUE THREAD

**Issue by jeffelman** [openedx-unsupported/configuration#571]
The configuration wiki shows a screenshot of manual commands that are printed in the Outputs tab, following successful stack creation. I was able to create the stack successfully (using AWS's CF console), w/no failures of any components reported in Events. However, at the end (CREATE_COMPLETE) the only output is 

KEY                                VALUE                   DESCRIPTION
EdxSecurityGroup    [...not shown...]       EC2 Security Group with access to the Edx server

This seems to be all that the current edx-reference-architecture.json in fact prints at the end. Are the manual commands no longer necessary? And if not, how can I retrieve the host, passwd, and other info that is shown in the screenshot? Thanks.

**Comment by e0d** [comment]
I believe that the commands, which were mostly work arounds for cloud formation limitations, are no-longer required and that the docs should be updated.  @feanil can you confirm?

**Comment by edx-secure** [comment]
Yes,  those workarounds are no longer needed.
