### ISSUE TITLE
Problem in deployment on single server VPS 

### ISSUE THREAD

**Issue by engmsaleh** [openedx-unsupported/configuration#573]
I have followed the 
https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation

When I reached to 
sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost," -e "edx_platform_version=master"
## I got the following error: 

TASK: [edxapp | install python base-requirements] ****************************\* 
failed: [localhost] => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i http://localhost:4040/root/pypi/+simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt ", "delta": "0:03:04.282931", "end": "2013-12-22 17:49:09.674895", "item": "", "rc": 137, "start": "2013-12-22 17:46:05.391964"}
stderr: Killed
stdout: Obtaining file:///edx/app/edxapp/edx-platform/common/lib/calc (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 2))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/calc

**Comment by hkim823** [comment]
This should be run from the working directory per  cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost," closing this issue
