### ISSUE TITLE
can't reach port 18000 for lms - is it normal ?

### ISSUE THREAD

**Issue by troublestarter** [openedx-unsupported/configuration#581]
Hi all

I've follow the documentation  : edX Ubuntu 12.04 Installation
Installing edX on a single Ubuntu 12.04 (Precise) server

All the installation is ok without error.

I have access to port 80 and 18080 without problem but the port 18000 is never reacheable...

Somebody now why ?

Thx

**Comment by feanil** [comment]
What version of configuration are you running with.  Those port mappings were updated a while back.  You can see what they are set to for your setup by looking at the nginx sites-enabled.
