### ISSUE TITLE
 How do I use the Vagrant VM with my fork of edx/platform?

### ISSUE THREAD

**Issue by janadel** [openedx-unsupported/configuration#582]
Hi,
I am trying to update my vagrant VM with my own fork by using 
ansible-playbook edxapp.yml -i "192.168.33.10," --user vagrant
--tags deploy -e 'edx_platform_repo=https://github.com/my_repo
edx_platform_commit=master'` 
but i receive 

fatal: [192.168.33.10] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue

FATAL: all hosts have already failed -- aborting

Would it be possible to give me a step by step guide how to sync my devstack with my fork ?

When I use the vagrant VM do I have to install edx/configuration or not ?

Thanks in advance.

**Comment by hkim823** [comment]
There's no step by step guide, but yarko in another issue did say you can try to use git itself to just clone your fork in your own box and use that code instead.

**Comment by yarko** [comment]
You can just specify your repo & version.  For now, you need to make some
mods to Vagrantfile.  Examples of what variables you can modify to point to
other forks are in build-version.yml. see notes in
https://gist.github.com/yarko/10711787

I should have a PR for this sometime after gophercon.
