### ISSUE TITLE
edx-platform update from my own fork

### ISSUE THREAD

**Issue by janadel** [openedx-unsupported/configuration#591]
Hi,
I am trying to update me devstack using my own edx-platform fork.
I use 
ansible-playbook -c local edxapp.yml -i "192.168.33.10," --user vagrant --tags deploy -e "edx_platform_repo=https://github.com/janadel/edx-platform.git edx_platform_version=master"

but my installation does not use my own repo but it uses edx/edx-platform instead.
How can I update me devstack using my own fork ?

Thanks in advance

**Comment by yarko** [comment]
On Mon, Dec 30, 2013 at 2:55 AM, janadel notifications@github.com wrote:

> Hi,
> I am trying to update me devstack using my own edx-platform fork.
> I use
> ansible-playbook -c local edxapp.yml -i "192.168.33.10," --user vagrant
> --tags deploy -e "edx_platform_repo=
> https://github.com/janadel/edx-platform.git edx_platform_version=master"
> 
> but my installation does not use my own repo but it uses edx/edx-platform
> instead.
> How can I update me devstack using my own fork ?

Probably the way you want to approach this is:
- checkout your repository to your machine:
  - git clone https://github.com/janadel/edx-platform.git
- you may want to follow edx contribution pattern, in case you find some
  bug that you may want to contribute (using this for yourself will only
  ensure a clean separation from "workspace" and "it works" space ;-) )
  - git checkout -b 'janadel/first-bringup'  # for example;
- in your workstation (prior to your first "vagrant up"), set
  VAGRANT_MOUNT_BASE to the directory above your edx-platform checkout.   The
  devstack wiki has example of setting this.
  - you may also want to checkout cs_comment_service and ora here.  I
    haven't tried, but I expect if you do not, then Vagrantfile will
    take care
    of populating these for you (but you should confirm);

Note you may also find it useful to have one repository for your clone and
the edx repository - for this you really want to have your work on
branches.    Read up on 'get remote' - you can set two remotes - for
example origin (if you want this as edx) and janadel (for your fork).   In
this way, you will be able to pull a patch or branch (or even new commits
to the edx master branch), and cherry-pick (merge) those into your work.
It may take a little to get accustomed to it, but once you do you will find
it worthwhile [if anyone else has better workflow suggestions, please chime
in - I'm not any more than an advanced-novice on git use].

I hope this is helpful.

Regards,
Yarko

Thanks in advance

**Comment by yarko** [comment]
Sorry - spell checker made an unnoticed "correction":

On Mon, Dec 30, 2013 at 11:16 AM, Yarko Tymciurak yarkot1@gmail.com wrote:

> On Mon, Dec 30, 2013 at 2:55 AM, janadel notifications@github.com wrote:
> 
> > Hi,
> > I am trying to update me devstack using my own edx-platform fork.
> > I use
> > ansible-playbook -c local edxapp.yml -i "192.168.33.10," --user vagrant
> > --tags deploy -e "edx_platform_repo=
> > https://github.com/janadel/edx-platform.git edx_platform_version=master"
> > 
> > but my installation does not use my own repo but it uses edx/edx-platform
> > instead.
> > How can I update me devstack using my own fork ?
> 
> Probably the way you want to approach this is:
> - checkout your repository to your machine:
>   - git clone https://github.com/janadel/edx-platform.git
> - you may want to follow edx contribution pattern, in case you find
>   some bug that you may want to contribute (using this for yourself will only
>   ensure a clean separation from "workspace" and "it works" space ;-) )
>   - git checkout -b 'janadel/first-bringup'  # for example;
> - in your workstation (prior to your first "vagrant up"), set
>   VAGRANT_MOUNT_BASE to the directory above your edx-platform checkout.   The
>   devstack wiki has example of setting this.
>   - you may also want to checkout cs_comment_service and ora here.  I
>     haven't tried, but I expect if you do not, then Vagrantfile will take care
>     of populating these for you (but you should confirm);
> 
> Note you may also find it useful to have one repository for your clone and
> the edx repository - for this you really want to have your work on
> branches.    Read up on 'get remote' - you can set two remotes - for
> example origin (if you

Read up on 'git remote'...

... for example:  http://git-scm.com/book/en/Git-Basics-Working-with-Remotes

**Comment by janadel** [comment]
Thanks for your help.
I don't yet understand why when I use :

ansible-playbook -c local edxapp.yml -i "192.168.33.10," --user vagrant --tags deploy -e "edx_platform_repo=https://github.com/janadel/edx-platform.git edx_platform_version=master"
 with -e 'edx_platform_repo=https://github.com/janadel/edx-platform.git' my repo is not used and the edx/edx-platform repo is used.
It may be important to note that I checked with a production installation and still have the same problem(-e 'edx_platform_repo=https://github.com/janadel/edx-platform.git' is ignored)

**Comment by hkim823** [comment]
it doesn't work because edx_platform_repo is currently points to the edX GitHub account, you can change the variable to your form and see if that helps.
