### ISSUE TITLE
Need restrictive permission set for IAM user to allow CloudFormation instantiation

### ISSUE THREAD

**Issue by frooble** [openedx-unsupported/configuration#594]
The AWS install (https://github.com/edx/configuration/wiki/AWS-Installation) via CloudFormation requires a large number of permissions (VPC, RDS, IAM role creation, etc) that would need to be set up for an IAM user (non-root AWS account user). 

Is there a list of the _most_ restrictive set of permissions that will enable the Cloud Formation to instantiate the edx stack and operate properly when this stack is instantiated by a IAM user of an AWS account?

**Comment by e0d** [comment]
There is not currently. We typically run cloudformation as an admin, non root, user and then rely on Iam roles for constraining access to AWS services by edx services.
