### ISSUE TITLE
permission denied  /home/supervisor, when run the edx_sandbox.yml

### ISSUE THREAD

**Issue by lg2578** [openedx-unsupported/configuration#596]
permission denied  /home/supervisor, when run the edx_sandbox.yml
the same for /home/supervisor/.distlib etc..
chown it to current user works.

**Comment by daeynasvistas** [comment]
the same problem here:
https://github.com/edx/configuration/issues/595

**Comment by feanil** [comment]
This should be fixed by https://github.com/edx/configuration/pull/603
