### ISSUE TITLE
failed when task ensure elasticsearch is enabled and started,please help me

### ISSUE THREAD

**Issue by lg2578** [openedx-unsupported/configuration#597]
msg \* starting elasticsearch server
...fail!
the pre step is download elasticsearch server ,shows skipping.

**Comment by daeynasvistas** [comment]
problem with java installation. 
workaround:
install java manually

sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java7-installer

but.. you will probably get another error at TASK 215
this one: https://github.com/edx/xqueue/issues/73
