### ISSUE TITLE
error when create /home/supervisor

### ISSUE THREAD

**Issue by focusheart** [openedx-unsupported/configuration#601]
When executing the following: 
$ sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"

An error occur and display this mainly:

Permission denied: mkdir /home/supervisor

After change the /home to 777, it passed

**Comment by daeynasvistas** [comment]
https://github.com/edx/configuration/issues/595

**Comment by feanil** [comment]
This should be fixed by https://github.com/edx/configuration/pull/603
