### ISSUE TITLE
[mongo | wait for mongo server to start] Error

### ISSUE THREAD

**Issue by lduarte1991** [openedx-unsupported/configuration#604]
Whenever I try to provision, it hangs for 300 secs at the [mongo | wait for mongo server to start] line and then fails. The full message is below:

TASK: [mongo | wait for mongo server to start] *******************************\* 
failed: [localhost] => {"elapsed": 300, "failed": true, "item": ""}
msg: Timeout when waiting for 127.0.0.1:27017

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/vagrant-devstack.retry

localhost                  : ok=43   changed=1    unreachable=0    failed=1   

No error message

**Comment by edx-secure** [comment]
Can you login to the server and look at the logs for mongo.  They should be
at '/edx/var/log/mongodb.log'.  Sometimes mongodb failes to start if there
is not sufficient space for its database on disk or because there is not
enough memory on the box.

**Comment by lduarte1991** [comment]
You're absolutely right, I was using the wrong disk drive and ran out of space. Thanks!

**Comment by prestb** [comment]
@lduarte1991 Please how did you solve your problem? thanks
