### ISSUE TITLE
Is this a bug ?

### ISSUE THREAD

**Issue by janadel** [openedx-unsupported/configuration#607]
Hi,
I try to update my production installation but I want to use my own forked repo.
I use :

ansible-playbook -c local edxapp.yml -i "192.168.33.10," --user vagrant --tags deploy -e "edx_platform_repo=https://github.com/janadel/edx-platform.git edx_platform_version=master"
with -e 'edx_platform_repo=https://github.com/janadel/edx-platform.git' but my repo is not used and the original edx/edx-platform repo is used.

Is this normal ,it this the right way to do this job or is there any bug ?

Thanks in advance.

**Comment by jbau** [comment]
You might try setting the edx_platform_repo var in your playbook (edxapp.yml) instead.  Ansible’s variable precedence is sometimes wacky.

**Comment by janadel** [comment]
Thanks for replying.
edxapp.yml has not vars.I changed main.yml of the edx app role.However still the same problem .My repo is not used.
Do I have to add my repo as a remote source with git remote add ?

**Comment by jbau** [comment]
you shouldn’t have to add your repo as a remote in git. You can add your own vars stanza in edxapp.yml, like here: http://docs.ansible.com/playbooks_intro.html#playbook-language-example

**Comment by janadel** [comment]
I changed edxapp.yml like this:
- name: Deploy edxapp
  hosts: all
  sudo: True
  gather_facts: True
  vars_files:
  - ["{{ secure_vars }}", "dummy.yml"]
    vars:
    edx_platform_repo: "https://github.com/janadel/edx-platform.git"
    roles:
  - edxapp

Still my repo is not used

**Comment by jarv** [comment]
I'm pretty sure I remember seeing this bug in the git Ansible module. Basically once your remote is set once you can't change it.  I think the easiest workaround will be to `rm -rf` the edxapp/edx-platform directory before the run.

**Comment by janadel** [comment]
You are brilliant.
Thank you,Thank you,Thank you.
It finally worked after a week .
