### ISSUE TITLE
Crashing edx_sandbox.yml playbook on Ubuntu 12.04 (full vs relative path)

### ISSUE THREAD

**Issue by droopy4096** [openedx-unsupported/configuration#615]
Hi, I have started with vagrant.sh install, but after first failure I ran it again via ansible, just to get rake errors:

/usr/local/bin/ansible-playbook -c local ./edx_sandbox.yml -i localhost,
...

failed: [localhost] => (item=lms) => {"changed": true, "cmd": "SERVICE_VARIANT=lms rake lms:gather_assets:aws ", "delta": "0:00:11.169128", "end": "2014-01-09 15:41:34.984681", "item": "lms", "rc": 1, "start": "2014-01-09 15:41:23.815553"}
2014-01-09 15:41:34,991 p=1952 u=root |  stderr: mkdir -p /edx/app/edxapp/edx-platform/.ws_migrations_complete
./manage.py lms --settings aws preprocess_assets --traceback 
xmodule_assets common/static/xmodule
2014-01-09 17:41:24,422 INFO 4719 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
node_modules/.bin/coffee --compile `find lms/ cms/ common/ -type f -name *.coffee` 
sass --style compressed --cache-location /tmp/sass-cache --load-path ./common/static/sass --update -E utf-8 */static
rake aborted!

full log at:
https://gist.github.com/droopy4096/8343536

**Comment by droopy4096** [comment]
using full path to ansible playbook "fixed" it as per:

https://groups.google.com/forum/#!msg/edx-code/Q_KMNd3rDpU/ImeNoyrMc9cJ

 This needs to be addressed both in docs and in vagrant.sh script IMO

**Comment by hkim823** [comment]
per line  cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost," it's addressed, closing issue.
