### ISSUE TITLE
Cant install of edx-platform from vagrant. (The guest machine entered an invalid state)

### ISSUE THREAD

**Issue by ankitmittaliitb** [openedx-unsupported/configuration#616]
Following is the error when i try to install edx via vagrant on a digital ocean vps (Ubuntu 12.04)

root@edx:~/devstack# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 8000 => 8000 (adapter 1)
[default] -- 8001 => 8001 (adapter 1)
[default] -- 4567 => 4567 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

**Comment by feanil** [comment]
@ankitmittaliitb  It looks like that is actually an issue with your vagrant setup.  The VM never boots.   If you open up 'virtualbox' and start the vm up from there does it work?

**Comment by hkim823** [comment]
@ankitmittaliitb closing this issue, if you are stil having an issue let us know

**Comment by rando305** [comment]
I still have this issue.  I open up the virtualbox gui and see nothing when i do a vagrant up.
This all worked last week, this week it doesn't. Help would be greatly appreciated.  I upgraded to the latest Virtualbox. I'm using vagrant 1.4.3 on Ubuntu 12.04 (Precise). Any assistance would be greatly appreciated.

**Comment by hkim823** [comment]
As this looks like its a problem with the host machine, not the VM guest, I'm not sure how much support can be given.  You may want to look into seeing if someone on the VirtualBox and/or Vagrant forums could be of help.

**Comment by ankitmittaliitb** [comment]
That still doesnt help. Can you wait for some time more till there is more
clarity and I dig up vagrant and virtualbox forums?

On Wed, Feb 26, 2014 at 8:44 PM, Han Su Kim notifications@github.comwrote:

> As this looks like its a problem with the host machine, not the VM guest,
> I'm not sure how much support can be given. You may want to look into
> seeing if someone on the VirtualBox and/or Vagrant forums could be of help.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/edx/configuration/issues/616#issuecomment-36134969
> .

## 

-Ankit Mittal

**Comment by rando305** [comment]
Yes! thank you.
There seemed to be incompatibilities between the virtualbox and vagrant editions. The default configurations for a 64-bit box seemed to be older versions than what the edx/configuration/wiki recommends.
I forced the issue to get versions asked for.  
I'm stuck.  
Thanks for your help

**Comment by rando305** [comment]
The error message gives me:
If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

When I open up VirtualBox - I don't see anything happen.

**Comment by rando305** [comment]
Any update? Any suggestions to where the Virtualbox/vagrant forum is to be found?

**Comment by hkim823** [comment]
Sorry for the confusion, I mean the general vagrant and virtualbox communities, not edX specific, as they maybe more helpful at this time to troubleshoot your issue.  

As we've and others outside of edX have tested the most recently builds and we cannot reproduce this issue, it leads me to believe that it's a general VBox and Vagrant issue.  Make sure you use the latest versions of both as that's what we usually work with.

**Comment by crouti** [comment]
Same problem here with following versions:

``````
ii  virtualbox-4.3                                  4.3.20-96996~Ubuntu~raring            amd64        Oracle VM VirtualBox
ii  vagrant                                         1:1.7.2                               amd64        no description given
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty```

Any clue how to solve this ?
thank you very much
``````
