### ISSUE TITLE
i installed productionstack,started,but how to login ubuntu,what is the default password for root?

### ISSUE THREAD

**Issue by dtbdtb** [openedx-unsupported/configuration#623]
hi  evryone:
 i installed productionstack,started,but how to login ubuntu,what is the default password for root?
and i want to login to modify ipaddress 
who can help me ?
and where can i get docs for config and admin edx?
your prompt reply would be deeply appreciated!!

**Comment by jarv** [comment]
please use github issues to report bugs and the edx-code list https://groups.google.com/forum/#!forum/edx-code to ask questions.
