### ISSUE TITLE
"edX Ubuntu 12.04 Installation" fails on internal network with controlled internet access

### ISSUE THREAD

**Issue by nomadhermit** [openedx-unsupported/configuration#648]
Following the procedure for "edX Ubuntu 12.04 Installation"  https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation on a network that only allows (per security team) port 80 and port 443 outbound to internet, the process fails in two locations when running:

```
sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
```

The first failure is at:  
         TASK: [common | Add git apt repository]

The issue appears to be related to Ansible 1.3.x and trying to use port 13711 to access keyserver... unfortunately upgrading to Ansible 1.4 fixes this but breaks other things in the installation. 
However the following appears to fix the existing Ansible 1.3.x without breaking anything before running the ansible playbook:

```
sudo sed -i "s#'keyserver.ubuntu.com'#'hkp://keyserver.ubuntu.com:80'#" /usr/share/ansible/packaging/apt_repository
```

The second failure occurs at:
          TASK: [Xqueue | install python post-requirements]

The issue appears to be related to a git call to clone pika from github using port 9418 insteal of http(s) for the.  The work around to fix this after the failure is the following:

```
sudo -u xqueue cp /edx/app/xqueue/xqueue/requirements.txt /edx/app/xqueue/xqueue/post-requirements.txt 

sudo -u xqueue vi /edx/app/xqueue/xqueue/post-requirements.txt
```

Change the following line and save:
From:  

```
-e git://github.com/pika/pika.git@a731347fc0#egg=pika
```

To:

```
-e git+https://github.com/pika/pika.git@a731347fc0#egg=pika
```

Then re-run 

```
sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
```

Which now finished successfully.

**Comment by feanil** [comment]
We see this error some times as well.  DevPi is a caching proxy of PyPi which we use because connectivity to PyPi is occasionally unreliable.  Unfortunately on first bringup you're always relying on PyPi to be healthy which is not always the case.  Hopefully this will work better the second time around.
