### ISSUE TITLE
sudo su edxapp not working

### ISSUE THREAD

**Issue by ahmadio** [openedx-unsupported/configuration#649]
I just updated my devstack using `vagrant provision` then when running `sudo su edxapp` nothing happens, the prompt still the same `vagrant@precise64:~$` event it is not changing to the edx-platform dir.
any hints how to figure out what is wrong?

**Comment by ahmadio** [comment]
BTW `sudo su forum` is working fine

**Comment by wedaly** [comment]
@ahmadix This most likely means that the provisioning scripts did not complete successfully (one of the last steps in the script adds a login shell for the `edxapp` user).

Try re-running the scripts using `vagrant provision` and look in the console for errors.

**Comment by hkim823** [comment]
@ahmadix closing this issue, open a new one if your still having issues
