### ISSUE TITLE
VirtualBox 4.3.6 (latest) doesnt seem to work with Vagrant 1.3.4 

### ISSUE THREAD

**Issue by marcotuts** [openedx-unsupported/configuration#655]
When attempting to set up devstack using: Vagrant 1.3.4 and VirtualBox 4.3.6, I received the following: 

marco:devstack marco$ vagrant up
Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2
marco:devstack marco$ vagrant -v
Vagrant 1.3.4

**Comment by yarko** [comment]
I am using VirtualBox 4.3.6 (with I think 4.2 VBox extensions), and vagrant
1.4.3 ---  you should be able to just upgrade your vagrant.

**Comment by marcotuts** [comment]
@yarko  - thanks for confirming that. I may have had an issue not properly clearing old vagrant files or improperly closing down a VM that led to this. If you were able to use VirtualBox 4.3.6 I will close this issue. If someone runs into it again and turns up this issue using a web search they can reopen it. Perhaps something else about my setup led to the error.
