### ISSUE TITLE
ERROR: the playbook: forums.yml could not be found

### ISSUE THREAD

**Issue by ahmadio** [openedx-unsupported/configuration#656]
trying to update forums in a single ubuntu installation

`root@ip-10-33-211-161:/edx/bin# sudo ./update forums master
ERROR: the playbook: forums.yml could not be found
`
where should the forums.yml be?

**Comment by jarv** [comment]
thanks for the bug report, if you change `forums.yml` to `forum.yml` it should work. I just fixed this on the master branch.
