### ISSUE TITLE
Devstack fails with npm dependencies

### ISSUE THREAD

**Issue by fpopineau** [openedx-unsupported/configuration#659]
Hi,

I'm running Vagrant 1.4.3 together with VirtualBox 4.3 under Windows 8.
Devstack fails to install with:

TASK: [edxapp | Set the npm registry] *****************************************

skipping: [localhost]

TASK: [edxapp | Install edx-platform npm dependencies] ************************

failed: [localhost] => {"changed": true, "cmd": "npm install ", "delta": "0:00:0
1.426675", "end": "2014-01-19 14:07:02.813966", "item": "", "rc": 255, "start":
"2014-01-19 14:07:01.387291"}
stderr: npm WARN package.json edx@0.1.0 No repository field.
npm http GET http://registry.npmjs.org/coffee-script
npm http 304 http://registry.npmjs.org/coffee-script
npm ERR! Error: UNKNOWN, symlink '../coffee-script/bin/coffee'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/isaacs/npm/issues

npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /edx/app/edxapp/edx-platform
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.23
npm ERR! path ../coffee-script/bin/coffee
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /edx/app/edxapp/edx-platform/npm-debug.log
npm ERR! not ok code 0

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************

Howevever, from the vm I can perfectly install coffee-script:
vagrant@precise64:~$ sudo npm install -g coffee-script
npm http GET https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/coffee-script
/usr/local/bin/coffee -> /usr/local/lib/node_modules/coffee-script/bin/coffee
/usr/local/bin/cake -> /usr/local/lib/node_modules/coffee-script/bin/cake
coffee-script@1.6.3 /usr/local/lib/node_modules/coffee-script
vagrant@precise64:~$

Any idea of what's going wrong?

Thanks for any help

Fabrice Popineau

**Comment by tusbar** [comment]
This is probably relevant: http://askubuntu.com/questions/269727/npm-errors-when-installing-packages-on-windows-share.

**Comment by fpopineau** [comment]
Well maybe, but I'm not so sure because as I have shown: from the vm, I can
install coffee-script without any error.
In anyway, where am I supposed to add this npm option to try it?
(I wonder if the problem is not related to npm and recent releases of
nodejs)

Thanks for your help.

Fabrice

2014/1/20 Bertrand Marron notifications@github.com

**Comment by tusbar** [comment]
Running `npm install -g coffee-script` installs it globally, in `/usr/local/lib/node_modules`.

The `edxapp` role does not install coffee-script globally, it just runs `npm install` (installing the dependencies listed in `package.config`) from within `edxapp_code_dir`. That folder is shared with your host, and this is probably why you’re getting this error.

**Comment by fpopineau** [comment]
Ok, understood, thanks.
I managed to install edx-platform under Windows and devstack under Ubuntu.
As I understand it, the tricks that made edx-platform run Under Windows can't be
extended to devstack. If someone has a hack, I'll be glad to hear about it.

Update: I manage to install devstack under Windows too. However it is a bit more tricky than installing edx-platform.
You need to follow all the instructions about handling symlinks with Git/Cygwin as stated here :
https://github.com/edx/edx-platform/wiki/Simplified-install-with-vagrant#dealing-with-line-endings-and-symlinks-under-windows
I also had to do it from a normal user account. My account is member of the Administrators group. As such, it can't create symlinks. Only normal users can, or the Administrator. As it is not recommended to run VirtualBox as Administrator, I had to 
- create a normal user account
- use secpol to authorize symlinks creation
  http://ahtik.com/blog/fixing-your-virtualbox-shared-folder-symlink-error/
- reboot
  There is still a glitch where as-is, it failed to install until I upgraded npm and node in the virtual machine.
  Now it is up and running.
