### ISSUE TITLE
A install question

### ISSUE THREAD

**Issue by bys** [openedx-unsupported/configuration#686]
When i start to install edx use " Ubuntu 12.04 Installation " and there is a ERROR : 
TASK: [mongo | install mongo server and recommends] **************************\* 
failed: [localhost] => {"failed": true, "item": ""}
msg: 'apt-get install 'mongodb-10gen=2.4.7' ' failed: E: There are problems and -y was used without --force-yes

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/baiysh/edx_sandbox.retry

localhost                  : ok=33   changed=2    unreachable=0    failed=1   

but i have installed mongodb-10gen : 
sudo apt-get install mong
mongodb                        mongodb-10gen-unstable-shell   mongodb-dev                    mongodb-org-unstable-tools
mongodb-10gen                  mongodb-10gen-unstable-tools   mongodb-org-unstable           mongodb-server
mongodb-10gen-unstable         mongodb18-10gen                mongodb-org-unstable-mongos    mongrel
mongodb-10gen-unstable-mongos  mongodb20-10gen                mongodb-org-unstable-server    mongrel-doc
mongodb-10gen-unstable-server  mongodb-clients                mongodb-org-unstable-shell     

what can i do next?

**Comment by pku9104038** [comment]
if you install edx on a virtual machine, my suggestion is to recreate a new virtual machine and try it again.
i have meet similar problem before, but my problem cause by
1. install edx, but failed at a tasks after this one,
2. run sudo apt-get update, sudo apt-get upgrade ,that will upgrade mongo packages
3. try to install edx again will always stop this task.
I have to recreate a new virtual machine for install edx.

**Comment by pku9104038** [comment]
or , may be you can just remark this task from mongo tasks, then try it again if you sure you mongo have installed well

**Comment by bys** [comment]
@pku9104038 
i have tried to use all the methods of installiation BUT no one can success.......
i think it is a problem that there is something wrong with my sources.list.
could you send me yours?

**Comment by feanil** [comment]
@bys Are you installing this on an existing machine?  Can you post a gist of your sources.list?

**Comment by hkim823** [comment]
@bys please let us know if this is still a problem

**Comment by bys** [comment]
@feanil @hkim823 @pku9104038 
this problem still exist.
I am come from China , and my source list is **_.163.**_.
but last week , i reset source list to mit`s and recreat a ubuntu 12.04.3 (real machine) the problem disappeared.
Then i change to another computer, but just reset source list to mit, and this problem still exist.
3 days ago,i thought i should not give up and try again .BUT........................
so plz check this problem.

**Comment by feanil** [comment]
Hi @bys Can youl please post your errors and sources.list online(you can use gist.github.com) and provide us a link to them here.  Since we are not in China this is a little difficult to reproduce.  In theory, the mongo role should install the PPA it needs automatically.

**Comment by bys** [comment]
Hi @feanil .
I have resolved this problem.
But i must tell you something:

we will see "msg: 'apt-get install 'mongodb-10gen=2.4.7' ' failed: E: There are problems and -y was used without --force-yes " when we start install mongdb and faild.
now the mongdb has update to 2.4.9 .
I removed newer mongdb the problem resolved.
so there is something wrong with bash shell scripte.

**Comment by ThePanguan** [comment]
my mongdb has update to 2.4.10 ,how to remove ?

**Comment by ThePanguan** [comment]
@bys
my mongdb has update to 2.4.10 ,how to remove ?

**Comment by bys** [comment]
hi：you can remove it by apt-get remove + "name" and of course you need root.

------------------ 原始邮件 ------------------
发件人: "刘磊"notifications@github.com; 
发送时间: 2014年7月8日(星期二) 晚上8:53
收件人: "edx/configuration"configuration@noreply.github.com; 
抄送: "奔跑"170721107@qq.com; 
主题: Re: [configuration] A install question (#686)

@bys
 my mongdb has update to 2.4.10 ,how to remove ? 

&mdash;
