### ISSUE TITLE
Vagrant 1.4.3 and Virtualbox 4.3.6 does not work (Win64)

### ISSUE THREAD

**Issue by ghost** [openedx-unsupported/configuration#696]
I updated Virtualbox and installed Vagrant after that. vagrant up results in a windows error:

<pre>vboxheadless.exe has stopped working</pre>

I found old issues regarding that problem but all were solved :(

**Comment by hkim823** [comment]
Which stack were you trying to stand up?  Which instruction were you using?  Try to do a fresh install and reply back if this is still an issue or not.

**Comment by ghost** [comment]
Thanks for your reply :) . I tried reinstalling virtual box and vagrant  but it results in the same error. BTW I was trying to up http://files.vagrantup.com/precise64.box. But I found a workaround. vboxheadless.exe crashes always when trying to mount /vagrant and only in headless mode. When I boot the virtual machine one time from virtualbox gui, it doesn't crash anymore after that, even in headless mode. So I can "vagrant up" now until I destroy the machine.
Oh I forgot to mention that my shared folder is located on a network drive, maybe thats why vboxheadless.exe crashes when trying to mount it.

**Comment by hkim823** [comment]
This sounds like this is an issue with your setup more than something that can be fixed by edX, and doing a quick search around, looks like Windows + Vagrant + vboxheadless can be funny for a lot of people.  I'm going to close this issue in the meantime.
