### ISSUE TITLE
nginx config path in /etc/nginx/nginx.conf wrong

### ISSUE THREAD

**Issue by solitaryr** [openedx-unsupported/configuration#704]
Hey,

While digging for a different issue, i notice the path for the nginx conf path in /etc/nginx/nginx.conf appears to be incorrect.  Diff below should fix...also, the directory needs to be created.  I doubt this has been a problem as there is currently nothing there.

<pre>
*** nginx.conf.orig     Mon Jan 27 19:07:50 2014
--- nginx.conf  Mon Jan 27 18:59:47 2014
***************
*** 42,48 ****
                                  '"$http_referer" "$http_user_agent"';
  
          access_log /edx/var/log/nginx/access.log p_combined;
!         error_log /edx/var/log/error.log;
  
          ##
          # Gzip Settings
--- 42,48 ----
                                  '"$http_referer" "$http_user_agent"';
  
          access_log /edx/var/log/nginx/access.log p_combined;
!         error_log /edx/var/log/nginx/error.log;
  
          ##
          # Gzip Settings
</pre>

**Comment by jarv** [comment]
thanks, fixed in https://github.com/edx/configuration/pull/705
