### ISSUE TITLE
missing user in mongo db?

### ISSUE THREAD

**Issue by solitaryr** [openedx-unsupported/configuration#718]
I just did a fresh install from the master branch and I'm seeing this message repeated in my /edx/var/log/mongo/mongodb.log

auth: couldn't find user edxapp@edxapp, edxapp.system.users

I've added the user to the mongo edxapp database but this seems like something that is missed in the setup.

**Comment by feanil** [comment]
Is this a devstack install or a local install?

**Comment by solitaryr** [comment]
This was using Ubuntu install instructions.

**Comment by trbm** [comment]
I'm having the same problem, just out of the blue. It wasn't happening yesterday morning but now nothing will run. Any ideas?

**Comment by solitaryr** [comment]
Did you run the update script?  Anything useful in your logs?
