### ISSUE TITLE
error while provisioning - edxapp | syncdb and migrate 

### ISSUE THREAD

**Issue by rashivkp** [openedx-unsupported/configuration#753]
I was trying to configure edx developerstack. 
while provisioning , migration fails with following error

failed: [localhost] => {"changed": true, "cmd": " /edx/app/edxapp/venvs/edxapp/bin/python manage.py lms syncdb --migrate --noinput --settings=aws_migrate ", "delta": "0:00:02.254611", "end": "2014-02-07 07:02:08.690460", "item": "", "rc": 1, "start": "2014-02-07 07:02:06.435849"}

django.core.exceptions.ImproperlyConfigured: No database password was provided for running migrations.  This is fatal.

**Comment by feanil** [comment]
Hi Rashid,

There was a bug in code that was merged in yesterday.  This should be fixed now.

**Comment by ramirezterrix** [comment]
I can confirm this using the vagrant one step installation on a fresh Ubuntu 12.04 running in a VirtualMachine.
Supressing the error by changing the db_migration variable in the playbook to "no" lead to an error with the jpg converting module. (wich might or might not be connected to the first error).

Iam just now running manual installation without vagrant - and it passed the test

**Comment by rashivkp** [comment]
@feanil I don't know if it fixed or not, but now comes another issue with mysql authentication. Do I need to update the vagrant box ?  now I just tried to run _vagrant up_ with updated repos. 

TASK: [edxlocal | create a database for edxapp] ******************************\* 
failed: [localhost] => {"failed": true, "item": ""}
msg: unable to connect, check login_user and login_password are correct, or alternatively check ~/.my.cnf contains credentials

**Comment by feanil** [comment]
Hi Rashid,

I've updated the edx_local database settings.  You'll need to destroy your vagrant box and start over but this should fix the issues.  I was able to build both the devstack and fullstack VMs last night.

**Comment by rashivkp** [comment]
@feanil I fixed it by manually changing the password of mysql user _root_. 
and continued with _vagrant provision_
ref #766 . 
I think, the error is still there. I have already tried destroying VM. but all the time I ended up with this authentication error.

**Comment by fmyzjs** [comment]
@feanil  how to update the edx_local database settings? Could you give me a favour

**Comment by feanil** [comment]
In what context?  What sort of setup do you have?  Vagrant or Ubuntu Server?  Which instructions are you following?

**Comment by fmyzjs** [comment]
@feanil Ubuntu Server  based on https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation#wiki-installing-edx-on-a-single-ubuntu-1204-precise-server-from-scratch

**Comment by feanil** [comment]
You can follow what Rashid did. https://github.com/edx/configuration/issues/766

Update the passwords here to match what is in the edx-local role which is under 'playbooks/roles/edx_local'.
