### ISSUE TITLE
what mean?

### ISSUE THREAD

**Issue by ghost** [openedx-unsupported/configuration#779]
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build_root/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-1oM8f4-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pycrypto
Storing debug log for failure in /home/parallels/.pip/pip.log

**Comment by hkim823** [comment]
Can you give a bit more information?  What were you doing, where did this occur, what is your larger goal you are trying to accomplish?
