### ISSUE TITLE
We need a different motd for devstack

### ISSUE THREAD

**Issue by jzoldak** [openedx-unsupported/configuration#782]
The changes from #776 resulted in the motd also being displayed when you `vagrant ssh` into devstack, and in that case the message itself is misleading.

Perhaps we should overwrite the default motd via the local-dev role.
This also gives us the opportunity to configure it with some helpful instructions, like to sudo su edxapp and use the rake task to start up the lms, etc.

**Comment by jarv** [comment]
Sure - though this is going to be pretty low priority for us right now.  PRs accepted! :)
