### ISSUE TITLE
Problem Installing Ubuntu 12.04

### ISSUE THREAD

**Issue by armeniadam** [openedx-unsupported/configuration#785]
Please help me resolve this

root@ubuntu10-64:/var/tmp/configuration/playbooks# failed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/repo.txt) => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i http://localhost:4040/root/pypi/+simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/repo.txt ", "delta": "0:00:10.406224", "end": "2014-02-13 13:11:46.785649", "item": "/edx/app/edxapp/edx-platform/requirements/edx/repo.txt", "rc": 1, "start": "2014-02-13 13:11:36.379425"}
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks# stderr: fatal: Unable to create '/edx/app/edxapp/venvs/edxapp/src/lettuce/.git/index.lock': File exists.
stderr:: command not found
If no other git process is currently running, this probably means a
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# If no other git process is currently running, this probably means a
If: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# git process crashed in this repository earlier. Make sure no other git
stdout: Obtaining file:///edx/app/edxapp/edx-platform (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 2))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/calc (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 3))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/calc

git: 'process' is not a git command. See 'git --help'.
root@ubuntu10-64:/var/tmp/configuration/playbooks# process is running and remove the file manually to continue.
process: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# stdout: Obtaining file:///edx/app/edxapp/edx-platform (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 2))
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform
Obtaining file:///edx/app/edxapp/edx-platform/common/lib/capa (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 4))
Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining file:///edx/app/edxapp/edx-platform/common/lib/calc (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 3))
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/calc
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/capa
Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining file:///edx/app/edxapp/edx-platform/common/lib/capa (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 4))
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/capa
Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining file:///edx/app/edxapp/edx-platform/common/lib/chem (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 5))
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/chem
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/symmath

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/xmodule (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 8))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/xmodule

Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining file:///edx/app/edxapp/edx-platform/common/lib/sandbox-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 6))
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/sandbox-packages
Obtaining django-staticfiles from git+https://github.com/edx/django-staticfiles.git@d89aae2a82f2b#egg=django-staticfiles (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 10))
Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining file:///edx/app/edxapp/edx-platform/common/lib/symmath (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 7))
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/symmath
  Updating /edx/app/edxapp/venvs/edxapp/src/django-staticfiles clone (to d89aae2a82f2b)
Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining file:///edx/app/edxapp/edx-platform/common/lib/xmodule (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 8))
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/xmodule
  Could not find a tag or branch 'd89aae2a82f2b', assuming commit.
  Running setup.py egg_info for package django-staticfiles

```
warning: no previously-included files matching '*.pyc' found anywhere in distribution
```

Running: command not found
Obtaining django-pipeline from git+https://github.com/edx/django-pipeline.git@88ec8a011e481918fdc9d2682d4017c835acd8be#egg=django-pipeline (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 11))
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining django-staticfiles from git+https://github.com/edx/django-staticfiles.git@d89aae2a82f2b#egg=django-staticfiles (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 10))
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Updating /edx/app/edxapp/venvs/edxapp/src/django-staticfiles clone (to d89aae2a82f2b)
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Could not find a tag or branch 'd89aae2a82f2b', assuming commit.
  Could not find a tag or branch '00424a1290328f60b52c5ad22e4fe22f16a29d12', assuming commit.
  Running setup.py egg_info for package django-wiki

Could: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package django-staticfiles
Obtaining lettuce from git+https://github.com/gabrielfalcao/lettuce.git@cccc3978ad2df82a78b6f9648fe2e9baddd22f88#egg=lettuce (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 13))
Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks#     warning: no previously-included files matching '*.pyc' found anywhere in distribution
  Updating /edx/app/edxapp/venvs/edxapp/src/lettuce clone (to cccc3978ad2df82a78b6f9648fe2e9baddd22f88)
warning:: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining django-pipeline from git+https://github.com/edx/django-pipeline.git@88ec8a011e481918fdc9d2682d4017c835acd8be#egg=django-pipeline (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 11))
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Updating /edx/app/edxapp/venvs/edxapp/src/django-pipeline clone (to 88ec8a011e481918fdc9d2682d4017c835acd8be)
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Could not find a tag or branch '88ec8a011e481918fdc9d2682d4017c835acd8be', assuming commit.
  Could not find a tag or branch 'cccc3978ad2df82a78b6f9648fe2e9baddd22f88', assuming commit.
  Complete output from command /usr/bin/git reset --hard -q cccc3978ad2df82a78b6f9648fe2e9baddd22f88:

---

Cleaning up...
Command /usr/bin/git reset --hard -q cccc3978ad2df82a78b6f9648fe2e9baddd22f88 failed with error code 128 in /edx/app/edxapp/venvs/edxapp/src/lettuce
Storing complete log in /edx/app/edxapp/.pip/pip.log
Could: command not found
failed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/github.txt) => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i http://localhost:4040/root/pypi/+simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt ", "delta": "0:00:08.025632", "end": "2014-02-13 13:11:55.051538", "item": "/edx/app/edxapp/edx-platform/requirements/edx/github.txt", "rc": 1, "start": "2014-02-13 13:11:47.025906"}
stderr: fatal: Unable to create '/edx/app/edxapp/venvs/edxapp/src/lettuce/.git/index.lock': File exists.
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package django-pipeline
If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining django-wiki from git+https://github.com/edx/django-wiki.git@00424a1290328f60b52c5ad22e4fe22f16a29d12#egg=django-wiki (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 12))
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Updating /edx/app/edxapp/venvs/edxapp/src/django-wiki clone (to 00424a1290328f60b52c5ad22e4fe22f16a29d12)
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Could not find a tag or branch '00424a1290328f60b52c5ad22e4fe22f16a29d12', assuming commit.
stdout: Obtaining django-staticfiles from git+https://github.com/edx/django-staticfiles.git@d89aae2a82f2b#egg=django-staticfiles (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 10))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-staticfiles clone (to d89aae2a82f2b)
  Could not find a tag or branch 'd89aae2a82f2b', assuming commit.
  Running setup.py egg_info for package django-staticfiles

Could: command not found
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package django-wiki
Obtaining django-pipeline from git+https://github.com/edx/django-pipeline.git@88ec8a011e481918fdc9d2682d4017c835acd8be#egg=django-pipeline (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 11))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-pipeline clone (to 88ec8a011e481918fdc9d2682d4017c835acd8be)
  Could not find a tag or branch '88ec8a011e481918fdc9d2682d4017c835acd8be', assuming commit.
  Running setup.py egg_info for package django-pipeline

Obtaining django-wiki from git+https://github.com/edx/django-wiki.git@00424a1290328f60b52c5ad22e4fe22f16a29d12#egg=django-wiki (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 12))
Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining lettuce from git+https://github.com/gabrielfalcao/lettuce.git@cccc3978ad2df82a78b6f9648fe2e9baddd22f88#egg=lettuce (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 13))
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Updating /edx/app/edxapp/venvs/edxapp/src/lettuce clone (to cccc3978ad2df82a78b6f9648fe2e9baddd22f88)
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Could not find a tag or branch 'cccc3978ad2df82a78b6f9648fe2e9baddd22f88', assuming commit.
  Updating /edx/app/edxapp/venvs/edxapp/src/django-wiki clone (to 00424a1290328f60b52c5ad22e4fe22f16a29d12)
  Could not find a tag or branch '00424a1290328f60b52c5ad22e4fe22f16a29d12', assuming commit.
  Running setup.py egg_info for package django-wiki

Obtaining lettuce from git+https://github.com/gabrielfalcao/lettuce.git@cccc3978ad2df82a78b6f9648fe2e9baddd22f88#egg=lettuce (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 13))
  Updating /edx/app/edxapp/venvs/edxapp/src/lettuce clone (to cccc3978ad2df82a78b6f9648fe2e9baddd22f88)
Could: command not found
  Could not find a tag or branch 'cccc3978ad2df82a78b6f9648fe2e9baddd22f88', assuming commit.
  Complete output from command /usr/bin/git reset --hard -q cccc3978ad2df82a78b6f9648fe2e9baddd22f88:
## root@ubuntu10-64:/var/tmp/configuration/playbooks#   Complete output from command /usr/bin/git reset --hard -q cccc3978ad2df82a78b6f9648fe2e9baddd22f88:

Cleaning up...
Command /usr/bin/git reset --hard -q cccc3978ad2df82a78b6f9648fe2e9baddd22f88 failed with error code 128 in /edx/app/edxapp/venvs/edxapp/src/lettuce
Storing complete log in /edx/app/edxapp/.pip/pip.log
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/local.txt)

FATAL: all hosts have already failed -- aborting
Complete: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# ----------------------------------------
----------------------------------------: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# Cleaning up...
Cleaning: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# Command /usr/bin/git reset --hard -q cccc3978ad2df82a78b6f9648fe2e9baddd22f88 failed with error code 128 in /edx/app/edxapp/venvs/edxapp/src/lettuce
Command: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# Storing complete log in /edx/app/edxapp/.pip/pip.log
Storing: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# failed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/github.txt) => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i http://localhost:4040/root/pypi/+simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt ", "delta": "0:00:08.025632", "end": "2014-02-13 13:11:55.051538", "item": "/edx/app/edxapp/edx-platform/requirements/edx/github.txt", "rc": 1, "start": "2014-02-13 13:11:47.025906"}
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks# stderr: fatal: Unable to create '/edx/app/edxapp/venvs/edxapp/src/lettuce/.git/index.lock': File exists.
stderr:: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# If no other git process is currently running, this probably means a
If: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# git process crashed in this repository earlier. Make sure no other git
git: 'process' is not a git command. See 'git --help'.
root@ubuntu10-64:/var/tmp/configuration/playbooks# process is running and remove the file manually to continue.
process: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# stdout: Obtaining django-staticfiles from git+https://github.com/edx/django-staticfiles.git@d89aae2a82f2b#egg=django-staticfiles (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 10))
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Updating /edx/app/edxapp/venvs/edxapp/src/django-staticfiles clone (to d89aae2a82f2b)
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Could not find a tag or branch 'd89aae2a82f2b', assuming commit.
Could: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package django-staticfiles
Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks#     warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning:: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining django-pipeline from git+https://github.com/edx/django-pipeline.git@88ec8a011e481918fdc9d2682d4017c835acd8be#egg=django-pipeline (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 11))
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Updating /edx/app/edxapp/venvs/edxapp/src/django-pipeline clone (to 88ec8a011e481918fdc9d2682d4017c835acd8be)
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Could not find a tag or branch '88ec8a011e481918fdc9d2682d4017c835acd8be', assuming commit.
Could: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package django-pipeline
Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining django-wiki from git+https://github.com/edx/django-wiki.git@00424a1290328f60b52c5ad22e4fe22f16a29d12#egg=django-wiki (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 12))
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Updating /edx/app/edxapp/venvs/edxapp/src/django-wiki clone (to 00424a1290328f60b52c5ad22e4fe22f16a29d12)
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Could not find a tag or branch '00424a1290328f60b52c5ad22e4fe22f16a29d12', assuming commit.
Could: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Running setup.py egg_info for package django-wiki
Running: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# Obtaining lettuce from git+https://github.com/gabrielfalcao/lettuce.git@cccc3978ad2df82a78b6f9648fe2e9baddd22f88#egg=lettuce (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 13))
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Updating /edx/app/edxapp/venvs/edxapp/src/lettuce clone (to cccc3978ad2df82a78b6f9648fe2e9baddd22f88)
-bash: syntax error near unexpected token `('
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Could not find a tag or branch 'cccc3978ad2df82a78b6f9648fe2e9baddd22f88', assuming commit.
Could: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#   Complete output from command /usr/bin/git reset --hard -q cccc3978ad2df82a78b6f9648fe2e9baddd22f88:
Complete: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# ----------------------------------------
----------------------------------------: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# Cleaning up...
Cleaning: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# Command /usr/bin/git reset --hard -q cccc3978ad2df82a78b6f9648fe2e9baddd22f88 failed with error code 128 in /edx/app/edxapp/venvs/edxapp/src/lettuce
Command: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# Storing complete log in /edx/app/edxapp/.pip/pip.log
Storing: command not found
root@ubuntu10-64:/var/tmp/configuration/playbooks# changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/local.txt)
-bash: syntax error near unexpected token`('
root@ubuntu10-64:/var/tmp/configuration/playbooks#
root@ubuntu10-64:/var/tmp/configuration/playbooks# FATAL: all hosts have already failed -- aborting
FATAL:: command not found

**Comment by feanil** [comment]
These errors are really hard to read, can you possible put them in a gist?  Also which set of instructions were you following?

**Comment by Ophir2** [comment]
Hi I am a newbie to most of the edx technologies.
I also have Installation problems.

I tried to run edx on Vitrualbox on windows and I have problem with accessing from the host to the guest. I cam get to port 2222 from the host but for all the rest I can't. When I try to ping the guest I get ttl expired in transit. I can access the localhost from the guest however.

I switched today to Ubuntu 12.04 and no luck again.
according to https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation#wiki-installing-edx-on-a-single-ubuntu-1204-precise-server-from-scratch

I started with the oneliner

<script 
   src="https://gist.github.com/Ophir2/8977641.js">
</script>

https://gist.github.com/Ophir2/8977641#file-edx-installation-problem

I tried the step by step later and the same error.

I will appreciate your help 

BTW : How do I embed the gist? (I did cut and paste of the url from the Embed this gist but I can't see it as part of the comment.)

Thanks again

**Comment by hkim823** [comment]
Hi @Ophir2.  Have you seen our Vagrant setup instructions which are the easiest ways to setup edX for testing and development?  https://github.com/edx/configuration/wiki

From the looks of your gist very quickly, it sounds like your installation of Ubuntu python environment isn't setup correctly.  Are you sure that the `sudo apt-get install -y build-essential software-properties-common python-software-properties curl git-core libxml2-dev libxslt1-dev python-pip python-apt python-dev` ran correctly?

**Comment by Ophir2** [comment]
Hi Han.
Thanks for your response.

I did looked at https://github.com/edx/configuration/wiki

Actually I tried 3 out of the 4 configuration and all reaulted with errors.
I tried
edX Developer Stackhttps://github.com/edx/configuration/wiki/edX-Developer-Stack-
for development, not production
edX Production Stackhttps://github.com/edx/configuration/wiki/edX-Production-Stack-
this is all edX services running on a single server in a production
like
configuration
edX Ubuntu 12.04
installationhttps://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation#wiki-installing-edx-on-a-single-ubuntu-1204-precise-server-from-scratch-
this will install edX on an existing Ubuntu 12.04 server

Regarding the Ubuntu I tried both ways the One step installation with
vagrant and the
Manual installation (without vagrant).

Both failed with the same result.
The manual failed at the
cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local
./edx_sandbox.yml -i "localhost,"

which is the last manual command while the command "sudo apt-get install -y
build-essential software-properties-common python-software-properties curl
git-core libxml2-dev libxslt1-dev python-pip python-apt python-dev"
passed ok.

I spent a lot of time trying all options with no luck till now.

**Comment by hkim823** [comment]
So I just noticed something, why is your apt-get connected to Lucid and not Precise?  This is only tested to be working with Ubuntu 12.04 Precise, not 10.04 Lucid.  Where are you getting your Ubuntu from?

**Comment by Ophir2** [comment]
Hi Han,

It took me long time to response.
Anyway I am interested to try to be part of the edx development.
As of today most of the technologies that edx uses are new to me.
Therefore I have a slow start.

I spent time learning python, and reading about some of the other
technologies (virtualbox, vagrant, django, nginx).
Then I started from scratch to play with the system.
I actually came across similar problems but now I can express my questions
better :-)

I will appreciate if you can help me or refer me to knowledge that will
help me regarding the following.

I am playing with some virtual machines
My setup  :  VirtualBox running on Windows 7.

1) fullstack machine

I worked with
https://github.com/edx/configuration/wiki/edx-Production-stack--installation-using-Vagrant-Virtualbox
Going through

mkdir fullstack
cd fullstack
curl https://raw.githubusercontent.com/edx/configuration/master/vagrant/release/fullstack/Vagrantfile

> Vagrantfile
> vagrant plugin install vagrant-hostsupdater
> vagrant up

Bingo, one for you - the site is up and running  and I connect it from the
host (this is new since last time I tried this I had to change the network
setting to bridged to make it work) !
1) I can now access the edx site through 192.168.33.10
2) I can now access the studi edx site through 192.168.33.10:18010

Problem 1:
The vagrant command report the following
...
[default] The guest additions on this VM do not match the installed version
of
VirtualBox! In most cases this is fine, but in rare cases it can
prevent things such as shared folders from working properly. If you see
shared folder errors, please make sure the guest additions within the
virtual machine match the version of VirtualBox you have installed on
your host and reload your VM.

Guest Additions Version: 4.2.0
VirtualBox Version: 4.3
...

I can't use the guest additions in this machine to do cut & paste.
Things I already tried :
1) I tried earlier version of VirtualBox - did not solve so I came back to
the latest version
2)  I tried opening the VirtualBox GUI and then used the menu command to
insert guest additions CD image, but it does not work.
    this is the error I received

  Result Code:

E_FAIL (0x80004005)

Component:

Console

Interface:

IConsole {8ab7c520-2442-4b66-8d74-4ff1e195d2b6}

Callee:

IMachine {480cf695-2d8d-4256-9c7c-cce4184fa048}

3) I installed gnome on the machine and with the guest gui I mounted the cd
and run it but it failed

OK, this is a minor issue so I played with the system a bit and created a
new course for myself.

Now for the real thing - devstack.

1) running the vagrant up I get - it hangs for ever never ending the
command
BTW I got same warning about  guest additions for Virtual box (see below)

C:\Users\Ido Ophir\Documents\Coursera\edxnew\devstack>vagrant up

> Bringing machine 'default' up with 'virtualbox' provider...
> [default] Importing base box 'gugelhupf-devstack'...
> [default] Matching MAC address for NAT networking...
> [default] Setting the name of the VM...
> [default] Clearing any previously set forwarded ports...
> [default] Clearing any previously set network interfaces...
> [default] Preparing network interfaces based on configuration...
> [default] Forwarding ports...
> [default] -- 22 => 2222 (adapter 1)
> [default] -- 8000 => 8000 (adapter 1)
> [default] -- 8001 => 8001 (adapter 1)
> [default] -- 4567 => 4567 (adapter 1)
> [default] Running 'pre-boot' VM customizations...
> [default] Booting VM...
> [default] Waiting for machine to boot. This may take a few minutes...
> DL is deprecated, please use Fiddle
> [default] Machine booted and ready!
> [default] The guest additions on this VM do not match the installed
> version of
> VirtualBox! In most cases this is fine, but in rare cases it can
> prevent things such as shared folders from working properly. If you see
> shared folder errors, please make sure the guest additions within the
> virtual machine match the version of VirtualBox you have installed on
> your host and reload your VM.
> 
> Guest Additions Version: 4.2.0
> VirtualBox Version: 4.3
> [default] Configuring and enabling network interfaces...
> [default] Mounting shared folders...
> [default] -- /vagrant
> [default] -- /edx/app/ora/ora
> [default] -- /edx/app/edxapp/edx-platform
> [default] -- /edx/app/forum/cs_comments_service
> [default] Running provisioner: shell...
> [default] Running: inline script
> stdin: is not a tty
> 
> PLAY [Deploy the edx_ansible role]
> 
> ---
> 
> TASK: [edx_ansible | git checkout edx_ansible repo into
> edx_ansible_code_dir] ***
> changed: [localhost]
> 
> TASK: [edx_ansible | install edx_ansible venv requirements]
> 
> ---
> 
> changed: [localhost]
> 
> TASK: [edx_ansible | create update script]
> 
> ---
> 
> ok: [localhost]
> 
> TASK: [edx_ansible | create a symlink for update.sh]
> 
> ---
> 
> ok: [localhost]
> 
> TASK: [edx_ansible | dump all vars to yaml]
> 
> ---
> 
> fatal: [localhost] => input file not found at
> /edx/app/edx_ansible/edx_ansible/playbooks/edx-east/roles/edx_ansible/temp
> lates/dumpall.yml.j2 or
> /edx/app/edx_ansible/edx_ansible/playbooks/edx-east/dumpall.yml.j2
> 
> FATAL: all hosts have already failed -- aborting
> 
> PLAY RECAP
> 
> ---
> 
> ```
>        to retry, use: --limit @/root/edx_ansible.retry
> ```
> 
> localhost                  : ok=4    changed=2    unreachable=1    failed=0
> 
> PLAY [Configure instance(s)]
> 
> ---
> 
> GATHERING FACTS
> 
> ---
> 
> ok: [localhost]
> 
> TASK: [edx_ansible | git checkout edx_ansible repo into
> edx_ansible_code_dir] ***
> ok: [localhost]
> 
> TASK: [edx_ansible | install edx_ansible venv requirements]
> 
> ---
> 
> ok: [localhost]
> 
> TASK: [edx_ansible | create update script]
> 
> ---
> 
> ok: [localhost]
> 
> TASK: [edx_ansible | create a symlink for update.sh]
> 
> ---
> 
> ok: [localhost]
> 
> TASK: [edx_ansible | create a symlink for var file]
> 
> ---
> 
> ok: [localhost]
> 
> TASK: [edx_ansible | create a symlink for ansible-playbook]
> 
> ---
> 
> changed: [localhost]
> 
> TASK: [edx_ansible | create a symlink for the playbooks dir]
> 
> ---
> 
> changed: [localhost]
> 
> TASK: [edxapp | setup the edxapp env]
> 
> ---
> 
> changed: [localhost]
> 
> TASK: [edxapp | create ssh script for git (not authenticated)]
> 
> ---
> 
> changed: [localhost]
> 
> TASK: [edxapp | create ssh script for git (authenticated)]
> 
> ---
> 
> skipping: [localhost]
> 
> TASK: [edxapp | install read-only ssh key]
> 
> ---
> 
> skipping: [localhost]
> 
> TASK: [edxapp | checkout edx-platform repo into {{edxapp_code_dir}}]
> 
> ---

Here is hung.

Your help will be appreciated,
regards,
Ido
