### ISSUE TITLE
Error on running edx install on Ubuntu 12.04

### ISSUE THREAD

**Issue by pkarjala** [openedx-unsupported/configuration#786]
Attempted to install edx on a local OpenStack instance we have running.  Using a base Ubuntu 12.04 install while following the instructions at https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation

When I reached TASK: [edxapp | install python base-requirements] ****************************\* in the installer process I got the following error stream:

https://gist.github.com/pat-trick/cccc7e81ab267a52afff

I've seen this issue cropping up at various places:

https://github.com/edx/configuration/issues/785
https://groups.google.com/forum/#!topic/edx-code/fRG6fv-HRvw
https://groups.google.com/forum/#!topic/edx-code/48b62N0gtI4

Some digging around points to the following post as a potential fix, as the OpenStack instance we're running does have some limitations:

https://github.com/edx/configuration/issues/648

I'm going to go ahead and spin up a new VM and see if running the instructions again will resolve this issue; possible I missed a step or had a typo somewhere.  Will update the issue report with results.

**Comment by feanil** [comment]
Closing this as a duplicate of #648

**Comment by pkarjala** [comment]
FYI, turned out not to be a duplicate of #648; ended up resolving on new server by running

cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"

until error appeared as in previous gist, then doing a server reboot and running the command again.  Second time around it ran the entire installer to completion without issue.

This implies that a service is not yet up and running like anticipated during the initial install, but is after the reboot.  Alternatively, that a configuration has not loaded allowing access to the requsite ports on boot.  Or another issue that I haven't caught yet.  Either way, up and running now!
