### ISSUE TITLE
A Install ERROR

### ISSUE THREAD

**Issue by bys** [openedx-unsupported/configuration#790]
TASK: [edxapp | gem install bundler] *****************************************\* 
failed: [localhost] => {"changed": true, "cmd": "gem install bundle\n \n  ", "delta": "0:00:06.521560", "end": "2014-02-17 15:28:11.885502", "item": "", "rc": 1, "start": "2014-02-17 15:28:05.363942"}
stderr: File not found: lib
ERROR:  While generating documentation for bundle-0.0.1
... MESSAGE:   exit
... RDOC args: --ri --op /edx/app/edxapp/.gem/doc/bundle-0.0.1/ri lib --title bundle-0.0.1 Documentation --quiet
stdout: Successfully installed bundle-0.0.1
1 gem installed
Installing ri documentation for bundle-0.0.1...

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/baiyingshan/edx_sandbox.retry

localhost                  : ok=102  changed=18   unreachable=0    failed=1   

what can i do next? Plz help!!!

**Comment by hkim823** [comment]
Which instructions are you running when you run into this?

**Comment by bys** [comment]
@hkim823
 I use Ubuntu 12.04 installation and run the last step of manual operation.

**Comment by bys** [comment]
@hkim823
By the way I have fixed this problem .
I change gem configfile (/edx/***/.gemrc) and add a new line : gem : --no-document.

**Comment by sunshinekitty** [comment]
I ran into this as well, and am surprised that this is still an issue.  I fixed this by re-installing rdoc.

```
gem install rdoc
```
