### ISSUE TITLE
Unknown id: forum

### ISSUE THREAD

**Issue by gitim** [openedx-unsupported/configuration#813]
Hello! I have installed Developer Stack with vagrant, installation was successful. And I'm trying to run forum. Within VM I'm trying to switch to the forum account: sudo su forum. But I get this error message: Unknown id: forum. sudo su edxapp doesn't work too. However, lms and cms work fine (I running them with rake command). I tried vagrant reload and vagrant provision but it didn't help. Can you help me? Can I manually add these users?

**Comment by hkim823** [comment]
Hm, I just spun up a new vagrant Devstack and can , and I just made a change to our instructions that involved getting the right Vagrantfile to curl, if you recently just spun up using the instructions at https://github.com/edx/configuration/wiki/edX-Developer-Stack you were getting an incomplete setup.  

Try it again, destroy the box you have and redownload a new box.

**Comment by gitim** [comment]
It works! Thanks a lot!
