### ISSUE TITLE
TASK: [edxapp | install python base-requirements] ERROR

### ISSUE THREAD

**Issue by bys** [openedx-unsupported/configuration#817]
I have a problem:

TASK: [edxapp | install python base-requirements] ****************************\* 
failed: [localhost] => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i http://localhost:4040/root/pypi/+simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt ", "delta": "0:02:51.100218", "end": "2014-02-26 09:29:01.284118", "item": "", "rc": 2, "start": "2014-02-26 09:26:10.183900"}
stdout: Obtaining file:///edx/app/edxapp/edx-platform (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 2))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/calc (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 3))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/calc

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/capa (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 4))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/capa

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/chem (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 5))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/chem

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/sandbox-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 6))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/sandbox-packages

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/symmath (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 7))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/symmath

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/xmodule (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 8))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/xmodule

Downloading/unpacking git+https://github.com/mfogel/django-settings-context-processor.git (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 126))
  Cloning https://github.com/mfogel/django-settings-context-processor.git to /tmp/pip-0txTnn-build
  Running setup.py egg_info for package from git+https://github.com/mfogel/django-settings-context-processor.git

Downloading/unpacking git+https://github.com/mitocw/django-cas.git (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 129))
  Cloning https://github.com/mitocw/django-cas.git to /tmp/pip-w7keze-build
  Running setup.py egg_info for package from git+https://github.com/mitocw/django-cas.git

Obtaining django-staticfiles from git+https://github.com/edx/django-staticfiles.git@d89aae2a82f2b#egg=django-staticfiles (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 10))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-staticfiles clone (to d89aae2a82f2b)
  Could not find a tag or branch 'd89aae2a82f2b', assuming commit.
  Running setup.py egg_info for package django-staticfiles

```
warning: no previously-included files matching '*.pyc' found anywhere in distribution
```

Obtaining django-pipeline from git+https://github.com/edx/django-pipeline.git@88ec8a011e481918fdc9d2682d4017c835acd8be#egg=django-pipeline (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 11))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-pipeline clone (to 88ec8a011e481918fdc9d2682d4017c835acd8be)
  Could not find a tag or branch '88ec8a011e481918fdc9d2682d4017c835acd8be', assuming commit.
  Running setup.py egg_info for package django-pipeline

Obtaining django-wiki from git+https://github.com/edx/django-wiki.git@00424a1290328f60b52c5ad22e4fe22f16a29d12#egg=django-wiki (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 12))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-wiki clone (to 00424a1290328f60b52c5ad22e4fe22f16a29d12)
  Could not find a tag or branch '00424a1290328f60b52c5ad22e4fe22f16a29d12', assuming commit.
  Running setup.py egg_info for package django-wiki

Obtaining lettuce from git+https://github.com/gabrielfalcao/lettuce.git@cccc3978ad2df82a78b6f9648fe2e9baddd22f88#egg=lettuce (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 13))
  Updating /edx/app/edxapp/venvs/edxapp/src/lettuce clone (to cccc3978ad2df82a78b6f9648fe2e9baddd22f88)
  Could not find a tag or branch 'cccc3978ad2df82a78b6f9648fe2e9baddd22f88', assuming commit.
  Running setup.py egg_info for package lettuce

Obtaining pystache-custom from git+https://github.com/dementrock/pystache_custom.git@776973740bdaad83a3b029f96e415a7d1e8bec2f#egg=pystache_custom-dev (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 14))
  Updating /edx/app/edxapp/venvs/edxapp/src/pystache-custom clone (to 776973740bdaad83a3b029f96e415a7d1e8bec2f)
  Could not find a tag or branch '776973740bdaad83a3b029f96e415a7d1e8bec2f', assuming commit.
  Running setup.py egg_info for package pystache-custom

Obtaining zendesk from git+https://github.com/eventbrite/zendesk.git@d53fe0e81b623f084e91776bcf6369f8b7b63879#egg=zendesk (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 15))
  Updating /edx/app/edxapp/venvs/edxapp/src/zendesk clone (to d53fe0e81b623f084e91776bcf6369f8b7b63879)
  Could not find a tag or branch 'd53fe0e81b623f084e91776bcf6369f8b7b63879', assuming commit.
  Running setup.py egg_info for package zendesk

Obtaining XBlock from git+https://github.com/edx/XBlock.git@893cd83dfb24405ce81b07f49c1c2e3053cdc865#egg=XBlock (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 18))
  Updating /edx/app/edxapp/venvs/edxapp/src/xblock clone (to 893cd83dfb24405ce81b07f49c1c2e3053cdc865)
  Could not find a tag or branch '893cd83dfb24405ce81b07f49c1c2e3053cdc865', assuming commit.
  Running setup.py egg_info for package XBlock

Obtaining codejail from git+https://github.com/edx/codejail.git@e3d98f9455#egg=codejail (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 19))
  Updating /edx/app/edxapp/venvs/edxapp/src/codejail clone (to e3d98f9455)
  Could not find a tag or branch 'e3d98f9455', assuming commit.
  Running setup.py egg_info for package codejail

Obtaining diff-cover from git+https://github.com/edx/diff-cover.git@v0.2.9#egg=diff_cover (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 20))
  Updating /edx/app/edxapp/venvs/edxapp/src/diff-cover clone (to v0.2.9)
  Running setup.py egg_info for package diff-cover

Obtaining js-test-tool from git+https://github.com/edx/js-test-tool.git@v0.1.5#egg=js_test_tool (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 21))
  Updating /edx/app/edxapp/venvs/edxapp/src/js-test-tool clone (to v0.1.5)
  Running setup.py egg_info for package js-test-tool

Obtaining django-waffle from git+https://github.com/edx/django-waffle.git@823a102e48#egg=django-waffle (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 22))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-waffle clone (to 823a102e48)
  Could not find a tag or branch '823a102e48', assuming commit.
  Running setup.py egg_info for package django-waffle

Obtaining event-tracking from git+https://github.com/edx/event-tracking.git@f0211d702d#egg=event-tracking (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 23))
  Updating /edx/app/edxapp/venvs/edxapp/src/event-tracking clone (to f0211d702d)
  Could not find a tag or branch 'f0211d702d', assuming commit.
  Running setup.py egg_info for package event-tracking

Obtaining bok-choy from git+https://github.com/edx/bok-choy.git@62de7b576a08f36cde5b030c52bccb1a2f3f8df1#egg=bok_choy (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 24))
  Updating /edx/app/edxapp/venvs/edxapp/src/bok-choy clone (to 62de7b576a08f36cde5b030c52bccb1a2f3f8df1)
  Could not find a tag or branch '62de7b576a08f36cde5b030c52bccb1a2f3f8df1', assuming commit.
  Running setup.py egg_info for package bok-choy

Obtaining django-splash from git+https://github.com/edx-solutions/django-splash.git@9965a53c269666a30bb4e2b3f6037c138aef2a55#egg=django-splash (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 25))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-splash clone (to 9965a53c269666a30bb4e2b3f6037c138aef2a55)
  Could not find a tag or branch '9965a53c269666a30bb4e2b3f6037c138aef2a55', assuming commit.
  Running setup.py egg_info for package django-splash

Obtaining acid-xblock from git+https://github.com/edx/acid-block.git@bf61f0fcd5916a9236bb5681c98374a48a13a74c#egg=acid-xblock (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 26))
  Updating /edx/app/edxapp/venvs/edxapp/src/acid-xblock clone (to bf61f0fcd5916a9236bb5681c98374a48a13a74c)
  Could not find a tag or branch 'bf61f0fcd5916a9236bb5681c98374a48a13a74c', assuming commit.
  Running setup.py egg_info for package acid-xblock

Downloading/unpacking beautifulsoup4==4.1.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 9))
  Running setup.py egg_info for package beautifulsoup4

Downloading/unpacking beautifulsoup==3.2.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 10))
  Downloading BeautifulSoup-3.2.1.tar.gz
  Running setup.py egg_info for package beautifulsoup

Downloading/unpacking bleach==1.2.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 11))
  Downloading bleach-1.2.2.tar.gz
  Running setup.py egg_info for package bleach

Downloading/unpacking html5lib==0.95 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 12))
  Running setup.py egg_info for package html5lib

Downloading/unpacking boto==2.13.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 13))
  Running setup.py egg_info for package boto

```
warning: no files found matching 'boto/mturk/test/*.doctest'
warning: no files found matching 'boto/mturk/test/.gitignore'
```

Downloading/unpacking celery==3.0.19 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 14))
  Running setup.py egg_info for package celery
    Upgrade: no old version found.

```
no previously-included directories found matching '*.pyc'
```

Downloading/unpacking dealer==0.2.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 15))
  Downloading dealer-0.2.3.tar.gz
  Running setup.py egg_info for package dealer

```
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.orig' found under directory '*'
```

Downloading/unpacking distribute>=0.6.28,<0.7 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 16))
  Running setup.py egg_info for package distribute

Downloading/unpacking django-celery==3.0.17 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 17))
  Running setup.py egg_info for package django-celery

```
no previously-included directories found matching 'bin/*.pyc'
no previously-included directories found matching 'tests/*.pyc'
no previously-included directories found matching 'docs/*.pyc'
no previously-included directories found matching 'extra/*.pyc'
no previously-included directories found matching 'djcelery/*.pyc'
no previously-included directories found matching 'docs/.build'
no previously-included directories found matching 'examples/*.pyc'
```

Downloading/unpacking django-countries==1.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 18))
  Running setup.py egg_info for package django-countries

Downloading/unpacking django-extensions==1.2.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 19))
  Running setup.py egg_info for package django-extensions

Downloading/unpacking django-filter==0.6.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 20))
  Downloading django-filter-0.6.tar.gz
  Running setup.py egg_info for package django-filter

```
warning: no files found matching 'AUTHORS.txt'
```

Downloading/unpacking django-followit==0.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 21))
  Downloading django-followit-0.0.3.tar.gz
  Running setup.py egg_info for package django-followit

```
warning: no files found matching 'tox.ini'
warning: no previously-included files matching '*.pyc' found under directory 'followit'
warning: manifest_maker: MANIFEST.in, line 5: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...

no previously-included directories found matching 'dist'
no previously-included directories found matching 'build'
warning: manifest_maker: MANIFEST.in, line 8: unknown action 'global'

warning: no previously-included files found matching 'settings.py'
warning: no previously-included files found matching 'manage.py'
warning: no previously-included files found matching '__init__.py'
warning: no previously-included files found matching 'urls.py'
warning: manifest_maker: MANIFEST.in, line 13: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...

warning: manifest_maker: MANIFEST.in, line 14: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...
```

Downloading/unpacking django-keyedcache==1.4-6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 22))
  Downloading django-keyedcache-1.4-6.tar.gz
  Running setup.py egg_info for package django-keyedcache

```
warning: no files found matching '*' under directory 'keyedcache/templatetags'
```

Downloading/unpacking django-kombu==0.9.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 23))
  Downloading django-kombu-0.9.4.tar.gz
  Running setup.py egg_info for package django-kombu

Downloading/unpacking django-mako==0.1.5pre (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 24))
  Downloading django-mako-0.1.5pre.tar.gz
  Running setup.py egg_info for package django-mako

Downloading/unpacking django-model-utils==1.4.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 25))
  Downloading django-model-utils-1.4.0.tar.gz
  Running setup.py egg_info for package django-model-utils

Downloading/unpacking django-masquerade==0.1.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 26))
  Running setup.py egg_info for package django-masquerade

Downloading/unpacking django-mptt==0.5.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 27))
  Running setup.py egg_info for package django-mptt

```
warning: no files found matching '*.json' under directory 'mptt'
```

Downloading/unpacking django-openid-auth==0.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 28))
  Running setup.py egg_info for package django-openid-auth

Downloading/unpacking django-robots==0.9.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 29))
  Downloading django-robots-0.9.1.tar.gz
  Running setup.py egg_info for package django-robots

Downloading/unpacking django-sekizai==0.6.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 30))
  Downloading django-sekizai-0.6.1.tar.gz
  Running setup.py egg_info for package django-sekizai

Downloading/unpacking django-ses==0.4.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 31))
  Downloading django-ses-0.4.1.tar.gz
  Running setup.py egg_info for package django-ses

Downloading/unpacking django-storages==1.1.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 32))
  Downloading django-storages-1.1.5.tar.gz
  Running setup.py egg_info for package django-storages

Downloading/unpacking django-threaded-multihost==1.4-1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 33))
  Downloading django-threaded-multihost-1.4-1.tar.gz
  Running setup.py egg_info for package django-threaded-multihost
    zip_safe flag not set; analyzing archive contents...

```
Installed /edx/app/edxapp/venvs/edxapp/build/django-threaded-multihost/setuptools_hg-0.4-py2.7.egg
```

Downloading/unpacking django-method-override==0.1.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 34))
  Downloading django-method-override-0.1.0.tar.gz
  Running setup.py egg_info for package django-method-override

Downloading/unpacking djangorestframework==2.3.5 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 35))
  Running setup.py egg_info for package djangorestframework

Downloading/unpacking django==1.4.8 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 36))
  Running setup.py egg_info for package django

Downloading/unpacking feedparser==5.1.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 37))
  Running setup.py egg_info for package feedparser

Downloading/unpacking fs==0.4.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 38))
  Running setup.py egg_info for package fs

Downloading/unpacking GitPython==0.3.2.RC1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 39))
  Running setup.py egg_info for package GitPython

```
warning: no files found matching 'README'
```

Downloading/unpacking glob2==0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 40))
  Downloading glob2-0.3.tar.gz
  Running setup.py egg_info for package glob2

Downloading/unpacking gunicorn==0.17.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 41))
  Running setup.py egg_info for package gunicorn

Downloading/unpacking lazy==1.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 42))
  Downloading lazy-1.1.zip
  Running setup.py egg_info for package lazy

Downloading/unpacking lxml==3.0.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 43))
  Running setup.py egg_info for package lxml
    Building lxml version 3.0.1.
    Building without Cython.
    Using build configuration of libxslt 1.1.26
    Building against libxml2/libxslt in the following directory: /usr/lib/x86_64-linux-gnu

```
warning: no previously-included files found matching '*.py'
warning: no files found matching '*.txt' under directory 'src/lxml/tests'
```

Downloading/unpacking mako==0.9.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 44))
  Running setup.py egg_info for package mako

```
warning: no files found matching '*.xml' under directory 'examples'
warning: no files found matching '*.mako' under directory 'examples'
warning: no files found matching 'ez_setup.py'
no previously-included directories found matching 'doc/build/output'
```

Downloading/unpacking Markdown==2.2.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 45))
  Running setup.py egg_info for package Markdown

Downloading/unpacking mongoengine==0.7.10 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 46))
  Running setup.py egg_info for package mongoengine
    0.7.10

```
no previously-included directories found matching 'docs/_build'
```

Downloading/unpacking networkx==1.7 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 47))
  Running setup.py egg_info for package networkx

```
warning: no files found matching 'scripts/*'
warning: no files found matching 'networkx/tests/*.txt'
warning: no files found matching 'networkx/*/*/tests/*.txt'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc/build'
no previously-included directories found matching 'doc/source/reference/generated'
no previously-included directories found matching 'doc/source/examples'
no previously-included directories found matching 'doc/source/static/examples'
no previously-included directories found matching 'doc/source/templates/gallery.html'
```

Downloading/unpacking nltk==2.0.4 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 48))
  Running setup.py egg_info for package nltk
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmp4RUjLF
    Now working in /tmp/tmp4RUjLF/distribute-0.6.21
    Building a Distribute egg in /edx/app/edxapp/venvs/edxapp/build/nltk
    /edx/app/edxapp/venvs/edxapp/build/nltk/distribute-0.6.21-py2.7.egg

```
warning: no previously-included files matching '*~' found anywhere in distribution
```

Downloading/unpacking oauthlib==0.5.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 49))
  Running setup.py egg_info for package oauthlib

Downloading/unpacking paramiko==1.9.0 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 50))
  Running setup.py egg_info for package paramiko

Downloading/unpacking path.py==3.0.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 51))
  Downloading path.py-3.0.1.zip
  Running setup.py egg_info for package path.py

Downloading/unpacking Pillow==1.7.8 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 52))
  Running setup.py egg_info for package Pillow

```
warning: no previously-included files found matching '.hgignore'
warning: no previously-included files found matching '.hgtags'
warning: no previously-included files found matching 'BUILDME.bat'
warning: no previously-included files found matching 'make-manifest.py'
warning: no previously-included files found matching 'SHIP'
warning: no previously-included files found matching 'SHIP.bat'
warning: no previously-included files matching '*' found under directory 'Tests'
```

Requirement already satisfied (use --upgrade to upgrade): pip>=1.4 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 53))
Downloading/unpacking polib==1.0.3 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 54))
  Running setup.py egg_info for package polib

Downloading/unpacking pycrypto>=2.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 55))
  Running setup.py egg_info for package pycrypto

Downloading/unpacking pygments==1.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 56))
  Running setup.py egg_info for package pygments

Downloading/unpacking pygraphviz==1.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 57))
  Running setup.py egg_info for package pygraphviz
    Trying pkg-config
    library_path=
    include_path=/usr/include/graphviz

```
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc/build'
```

Downloading/unpacking pymongo==2.4.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 58))
  Running setup.py egg_info for package pymongo

Downloading/unpacking pyparsing==1.5.6 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 59))
  Error timed out while getting http://localhost:4040/root/pypi/+f/5404de54e6d0ae71ce354d8db3576ac1/pyparsing-1.5.6.zip#md5=5404de54e6d0ae71ce354d8db3576ac1 (from http://localhost:4040/root/pypi/+simple/pyparsing/)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 1092, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 1238, in unpack_url
    retval = unpack_http_url(link, location, self.download_cache, self.download_dir)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/download.py", line 602, in unpack_http_url
    resp = _get_response_from_url(target_url, link)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/download.py", line 638, in _get_response_from_url
    resp = urlopen(target_url)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/download.py", line 176, in __call__
    response = self.get_opener(scheme=scheme).open(url)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

Storing complete log in /edx/app/edxapp/.pip/pip.log

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/baiyingshan/edx_sandbox.retry

localhost                  : ok=113  changed=22   unreachable=0    failed=1   

what should i do next?
By the way i use the way that install edx to ubuntu 12.04

**Comment by edx-secure** [comment]
Looks like the pip install timed out.  Try re running it.  This a known
issue with PyPi.
