### ISSUE TITLE
Another problem "edX Ubuntu 12.04 Installation"

### ISSUE THREAD

**Issue by FranciscoGomez** [openedx-unsupported/configuration#818]
The network uses proxy, and controlled internet access, but think is not problem https://github.com/edx/configuration/issues/648
result:

TASK: [edxapp | install python base-requirements] ****************************\* 
failed: [localhost] => {"changed": true, "cmd": "/edx/app/edxapp/venvs/edxapp/bin/pip install -i http://localhost:4040/root/pypi/+simple --exists-action w --use-mirrors -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt ", "delta": "0:00:35.077833", "end": "2014-02-25 23:44:54.599173", "item": "", "rc": 1, "start": "2014-02-25 23:44:19.521340"}
stdout: Obtaining file:///edx/app/edxapp/edx-platform (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 2))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/calc (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 3))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/calc

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/capa (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 4))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/capa

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/chem (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 5))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/chem

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/sandbox-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 6))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/sandbox-packages

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/symmath (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 7))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/symmath

Obtaining file:///edx/app/edxapp/edx-platform/common/lib/xmodule (from -r /edx/app/edxapp/edx-platform/requirements/edx/local.txt (line 8))
  Running setup.py egg_info for package from file:///edx/app/edxapp/edx-platform/common/lib/xmodule

Downloading/unpacking git+https://github.com/mfogel/django-settings-context-processor.git (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 126))
  Cloning https://github.com/mfogel/django-settings-context-processor.git to /tmp/pip-NcEBBx-build
  Running setup.py egg_info for package from git+https://github.com/mfogel/django-settings-context-processor.git

Downloading/unpacking git+https://github.com/mitocw/django-cas.git (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 129))
  Cloning https://github.com/mitocw/django-cas.git to /tmp/pip-Oub7tF-build
  Running setup.py egg_info for package from git+https://github.com/mitocw/django-cas.git

Obtaining django-staticfiles from git+https://github.com/edx/django-staticfiles.git@d89aae2a82f2b#egg=django-staticfiles (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 10))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-staticfiles clone (to d89aae2a82f2b)
  Could not find a tag or branch 'd89aae2a82f2b', assuming commit.
  Running setup.py egg_info for package django-staticfiles

```
warning: no previously-included files matching '*.pyc' found anywhere in distribution
```

Obtaining django-pipeline from git+https://github.com/edx/django-pipeline.git@88ec8a011e481918fdc9d2682d4017c835acd8be#egg=django-pipeline (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 11))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-pipeline clone (to 88ec8a011e481918fdc9d2682d4017c835acd8be)
  Could not find a tag or branch '88ec8a011e481918fdc9d2682d4017c835acd8be', assuming commit.
  Running setup.py egg_info for package django-pipeline

Obtaining django-wiki from git+https://github.com/edx/django-wiki.git@00424a1290328f60b52c5ad22e4fe22f16a29d12#egg=django-wiki (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 12))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-wiki clone (to 00424a1290328f60b52c5ad22e4fe22f16a29d12)
  Could not find a tag or branch '00424a1290328f60b52c5ad22e4fe22f16a29d12', assuming commit.
  Running setup.py egg_info for package django-wiki

Obtaining lettuce from git+https://github.com/gabrielfalcao/lettuce.git@cccc3978ad2df82a78b6f9648fe2e9baddd22f88#egg=lettuce (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 13))
  Updating /edx/app/edxapp/venvs/edxapp/src/lettuce clone (to cccc3978ad2df82a78b6f9648fe2e9baddd22f88)
  Could not find a tag or branch 'cccc3978ad2df82a78b6f9648fe2e9baddd22f88', assuming commit.
  Running setup.py egg_info for package lettuce

Obtaining pystache-custom from git+https://github.com/dementrock/pystache_custom.git@776973740bdaad83a3b029f96e415a7d1e8bec2f#egg=pystache_custom-dev (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 14))
  Updating /edx/app/edxapp/venvs/edxapp/src/pystache-custom clone (to 776973740bdaad83a3b029f96e415a7d1e8bec2f)
  Could not find a tag or branch '776973740bdaad83a3b029f96e415a7d1e8bec2f', assuming commit.
  Running setup.py egg_info for package pystache-custom

Obtaining zendesk from git+https://github.com/eventbrite/zendesk.git@d53fe0e81b623f084e91776bcf6369f8b7b63879#egg=zendesk (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 15))
  Updating /edx/app/edxapp/venvs/edxapp/src/zendesk clone (to d53fe0e81b623f084e91776bcf6369f8b7b63879)
  Could not find a tag or branch 'd53fe0e81b623f084e91776bcf6369f8b7b63879', assuming commit.
  Running setup.py egg_info for package zendesk

Obtaining XBlock from git+https://github.com/edx/XBlock.git@893cd83dfb24405ce81b07f49c1c2e3053cdc865#egg=XBlock (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 18))
  Updating /edx/app/edxapp/venvs/edxapp/src/xblock clone (to 893cd83dfb24405ce81b07f49c1c2e3053cdc865)
  Could not find a tag or branch '893cd83dfb24405ce81b07f49c1c2e3053cdc865', assuming commit.
  Running setup.py egg_info for package XBlock

Obtaining codejail from git+https://github.com/edx/codejail.git@e3d98f9455#egg=codejail (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 19))
  Updating /edx/app/edxapp/venvs/edxapp/src/codejail clone (to e3d98f9455)
  Could not find a tag or branch 'e3d98f9455', assuming commit.
  Running setup.py egg_info for package codejail

Obtaining diff-cover from git+https://github.com/edx/diff-cover.git@v0.2.9#egg=diff_cover (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 20))
  Updating /edx/app/edxapp/venvs/edxapp/src/diff-cover clone (to v0.2.9)
  Running setup.py egg_info for package diff-cover

Obtaining js-test-tool from git+https://github.com/edx/js-test-tool.git@v0.1.5#egg=js_test_tool (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 21))
  Updating /edx/app/edxapp/venvs/edxapp/src/js-test-tool clone (to v0.1.5)
  Running setup.py egg_info for package js-test-tool

Obtaining django-waffle from git+https://github.com/edx/django-waffle.git@823a102e48#egg=django-waffle (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 22))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-waffle clone (to 823a102e48)
  Could not find a tag or branch '823a102e48', assuming commit.
  Running setup.py egg_info for package django-waffle

Obtaining event-tracking from git+https://github.com/edx/event-tracking.git@f0211d702d#egg=event-tracking (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 23))
  Updating /edx/app/edxapp/venvs/edxapp/src/event-tracking clone (to f0211d702d)
  Could not find a tag or branch 'f0211d702d', assuming commit.
  Running setup.py egg_info for package event-tracking

Obtaining bok-choy from git+https://github.com/edx/bok-choy.git@62de7b576a08f36cde5b030c52bccb1a2f3f8df1#egg=bok_choy (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 24))
  Updating /edx/app/edxapp/venvs/edxapp/src/bok-choy clone (to 62de7b576a08f36cde5b030c52bccb1a2f3f8df1)
  Could not find a tag or branch '62de7b576a08f36cde5b030c52bccb1a2f3f8df1', assuming commit.
  Running setup.py egg_info for package bok-choy

Obtaining django-splash from git+https://github.com/edx-solutions/django-splash.git@9965a53c269666a30bb4e2b3f6037c138aef2a55#egg=django-splash (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 25))
  Updating /edx/app/edxapp/venvs/edxapp/src/django-splash clone (to 9965a53c269666a30bb4e2b3f6037c138aef2a55)
  Could not find a tag or branch '9965a53c269666a30bb4e2b3f6037c138aef2a55', assuming commit.
  Running setup.py egg_info for package django-splash

Obtaining acid-xblock from git+https://github.com/edx/acid-block.git@bf61f0fcd5916a9236bb5681c98374a48a13a74c#egg=acid-xblock (from -r /edx/app/edxapp/edx-platform/requirements/edx/github.txt (line 26))
  Updating /edx/app/edxapp/venvs/edxapp/src/acid-xblock clone (to bf61f0fcd5916a9236bb5681c98374a48a13a74c)
  Could not find a tag or branch 'bf61f0fcd5916a9236bb5681c98374a48a13a74c', assuming commit.
  Running setup.py egg_info for package acid-xblock

Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4==4.1.3 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup==3.2.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): bleach==1.2.2 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): html5lib==0.95 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): boto==2.13.3 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): celery==3.0.19 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): dealer==0.2.3 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): distribute>=0.6.28,<0.7 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): django-celery==3.0.17 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): django-countries==1.5 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): django-extensions==1.2.5 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): django-filter==0.6.0 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): django-followit==0.0.3 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): django-keyedcache==1.4-6 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 22))
Requirement already satisfied (use --upgrade to upgrade): django-kombu==0.9.4 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): django-mako==0.1.5pre in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 24))
Requirement already satisfied (use --upgrade to upgrade): django-model-utils==1.4.0 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 25))
Requirement already satisfied (use --upgrade to upgrade): django-masquerade==0.1.6 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 26))
Requirement already satisfied (use --upgrade to upgrade): django-mptt==0.5.5 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 27))
Requirement already satisfied (use --upgrade to upgrade): django-openid-auth==0.4 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 28))
Requirement already satisfied (use --upgrade to upgrade): django-robots==0.9.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 29))
Requirement already satisfied (use --upgrade to upgrade): django-sekizai==0.6.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 30))
Requirement already satisfied (use --upgrade to upgrade): django-ses==0.4.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 31))
Requirement already satisfied (use --upgrade to upgrade): django-storages==1.1.5 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 32))
Requirement already satisfied (use --upgrade to upgrade): django-threaded-multihost==1.4-1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 33))
Requirement already satisfied (use --upgrade to upgrade): django-method-override==0.1.0 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 34))
Requirement already satisfied (use --upgrade to upgrade): djangorestframework==2.3.5 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 35))
Requirement already satisfied (use --upgrade to upgrade): django==1.4.8 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 36))
Requirement already satisfied (use --upgrade to upgrade): feedparser==5.1.3 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 37))
Requirement already satisfied (use --upgrade to upgrade): fs==0.4.0 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 38))
Requirement already satisfied (use --upgrade to upgrade): GitPython==0.3.2.RC1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 39))
Requirement already satisfied (use --upgrade to upgrade): glob2==0.3 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 40))
Requirement already satisfied (use --upgrade to upgrade): gunicorn==0.17.4 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 41))
Requirement already satisfied (use --upgrade to upgrade): lazy==1.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 42))
Requirement already satisfied (use --upgrade to upgrade): lxml==3.0.1 in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 43))
Downloading/unpacking mako==0.9.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 44))
  Cannot fetch index base URL http://localhost:4040/root/pypi/+simple/
  Could not find any downloads that satisfy the requirement mako==0.9.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 44))
Cleaning up...
No distributions at all found for mako==0.9.1 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 44))
Storing complete log in /edx/app/edxapp/.pip/pip.log

FATAL: all hosts have already failed -- aborting

**Comment by hkim823** [comment]
It looks like PyPi wasn't responding. Others have seen similar issues. Try again and see if this is still an issue.

**Comment by FranciscoGomez** [comment]
Thanks for the reply.
But I've been trying 20 days.
Another answer than keep trying?
Thank you.

**Comment by hkim823** [comment]
What happens if you just manually try to install mako?  Just type pip install mako?

**Comment by deependersingla** [comment]
@hkim823  I am facing the same issue, mako get installed.

**Comment by hkim823** [comment]
A clue I see, it's trying to use http://localhost:4040/root/pypi/+simple/ to locate pip requrementes and thus I do think your network might be somewhat to blame here.  Can you make sure you have free and unrestricted access to PyPi?
