### ISSUE TITLE
edX Developer Stack - Vagrantfile

### ISSUE THREAD

**Issue by sasasaftic** [openedx-unsupported/configuration#827]
Message: undefined method `require_version' for Vagrant:Module

I'm using vagrant 1.3.5
I did:

```
mkdir devstack
cd devstack
curl https://raw.githubusercontent.com/edx/configuration/master/vagrant/release/devstack/Vagrantfile > Vagrantfile
vagrant up
```

I got this error:

```
Message: undefined method `require_version' for Vagrant:Module
```

I just deleted that line and everything works, but I think that you should fix that.

**Comment by hkim823** [comment]
I just realized, that the Vagrant.require_version is a Vagrant 1.4 feature, thus the 1.3..4 requirement doesn't really hold.  I'll edit that now.  Please upgrade your version of Vagrant, the latest is 1.4.3 and works great with the current devstack.

**Comment by hkim823** [comment]
This has been corrected with new Vagrantfiles, please download and upgrade to at least Vagrant 1.4, closing this issue.
