### ISSUE TITLE
how to activate users in production stack ???

### ISSUE THREAD

**Issue by praveen-pal** [openedx-unsupported/configuration#834]
where i can find logs in which user activation link is generated ?
( when a user register it shows, a  link has sent to activate your account).
 where i can get this link in production stack ?
  please suggest some solution.

```
 i tried to find logs in  /edx/var/log/  and in  /edx/var/log/supervisor   
but i did not  get the activation link
```

   please suggest some solution.
   thank you

**Comment by hkim823** [comment]
On the edx-code mailing list I think you got the right answer.  Also you can activate via the Django admin console.

**Comment by anqsdwe** [comment]
thank you Kim! your answer helps me every time !
