### ISSUE TITLE
Installing on ubuntu 12.04 - got stuck on this msg in terminal 

### ISSUE THREAD

**Issue by webshocker** [openedx-unsupported/configuration#835]
TASK: [edxapp | setup the edxapp env] ****************************************\* 
ok: [localhost]

TASK: [edxapp | create ssh script for git (not authenticated)] ***************\* 
ok: [localhost]

TASK: [edxapp | create ssh script for git (authenticated)] *******************\* 
skipping: [localhost]

TASK: [edxapp | install read-only ssh key] ***********************************\* 
skipping: [localhost]

TASK: [edxapp | checkout edx-platform repo into {{edxapp_code_dir}}] *********\* 
< nothing happens here for hrs..... it stays like this only >

i've already tried to install it using the following guide a dozen times - but it always gets stuck here : 

TASK: [edxapp | checkout edx-platform repo into {{edxapp_code_dir}}] *********\* 

https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation

using this : 
wget https://raw2.github.com/edx/configuration/master/util/install/vagrant.sh -O - | bash

i m on a ubuntu 12.04 server , with xubuntu-desktop

thanks in advance

**Comment by e0d** [comment]
This looks like a networking issue connecting to github, which may be transient.  From the same box, can you git clone https://github.com/edx/edx-platform?

**Comment by webshocker** [comment]
yes, i just did it  - what next ?

**Comment by webshocker** [comment]
Pls someone help me here - i tried it again on a fresh ubuntu install - it still got stuck at the same spot.

**Comment by e0d** [comment]
Can you confirm you don't have a full disk? If not can you run lsof on the process,  so we can try to figure out what it is doing.

**Comment by webshocker** [comment]
done - lms and cms working now, got this error now,

TASK: [rabbitmq | add rabbit repository] *************************************\* 
failed: [localhost] => {"failed": true, "item": "", "parsed": false}
invalid output was: SUDO-SUCCESS-bxaifzaxqxvtbrqunkvqweknhheabjgw
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1393999945.53-29423628431295/apt_repository", line 1411, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1393999945.53-29423628431295/apt_repository", line 378, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/deprecation.py", line 98, in deprecated_function
    return func(_args, *_kwds)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 441, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/main/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/restricted/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/universe/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/multiverse/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/main/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/restricted/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/universe/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/multiverse/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/main/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/restricted/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/universe/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/multiverse/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/main/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/restricted/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/universe/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/multiverse/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/main/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/restricted/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/universe/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/multiverse/source/Sources  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/main/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/restricted/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/universe/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/multiverse/binary-i386/Packages  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise/main/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise/multiverse/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise/restricted/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise/universe/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/main/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/multiverse/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/restricted/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-updates/universe/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/main/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/multiverse/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/restricted/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-backports/universe/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/main/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/multiverse/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/restricted/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, W:Failed to fetch http://mirrors.mit.edu/ubuntu/dists/precise-security/universe/i18n/Translation-en  Unable to connect to mirrors.mit.edu:http:
, E:Some index files failed to download. They have been ignored, or old ones used instead.

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/edx_sandbox.retry

localhost                  : ok=200  changed=60   unreachable=0    failed=1

**Comment by acarrasquillo** [comment]
I have that same error

**Comment by hkim823** [comment]
Looks like a network error, is it still happening right now?

**Comment by fmyzjs** [comment]
Looks like a network error

**Comment by hkim823** [comment]
If you are still having an issue please send it to edx-code mailing list, or reopen the issue, Closing this for now.
