### ISSUE TITLE
Virtual appliance

### ISSUE THREAD

**Issue by johnfelipe** [openedx-unsupported/configuration#87]
Please build a virtual appliance for virtual box o vmware, is possible or give me support for build one in centos, why centos, cause is my linux preferred

Tnks

**Comment by jbau** [comment]
please see development setup instructions in edx/edx-platform. is development what you want your environment for?

**Comment by jtauber** [comment]
As this would best be done by the community and discussed on edx-code mailing, I'm going to close this issue here.

**Comment by johnfelipe** [comment]
Hi, i have a lot issue for launch in vmware

Tnks
