### ISSUE TITLE
Unable to build devstack from scratch using latest vagrantfile

### ISSUE THREAD

**Issue by marcotuts** [openedx-unsupported/configuration#883]
Below is the console output mid-"vagrant up"  

TASK: [edxapp | create  application config] **********************************\* 
fatal: [localhost] => {'msg': "One or more undefined variables: 'EDXAPP_UPDATE_STATIC_FILES_KEY' is undefined", 'failed': True}
fatal: [localhost] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "One or more undefined variables: 'EDXAPP_UPDATE_STATIC_FILES_KEY' is undefined", 'failed': True}]}

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/vagrant-devstack.retry

localhost                  : ok=29   changed=20   unreachable=1    failed=0   

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chmod +x /tmp/vagrant-shell && /tmp/vagrant-shell

Stdout from the command:

PLAY [Deploy the edx_ansible role] *******************************************\* 

TASK: [edx_ansible | git checkout edx_ansible repo into edx_ansible_code_dir] **\* 
changed: [localhost]

TASK: [edx_ansible | install edx_ansible venv requirements] ******************\* 
ok: [localhost]

TASK: [edx_ansible | create update script] ***********************************\* 
ok: [localhost]

TASK: [edx_ansible | create a symlink for update.sh] *************************\* 
ok: [localhost]

TASK: [edx_ansible | dump all vars to yaml] **********************************\* 
changed: [localhost]

TASK: [edx_ansible | clean up var file, removing all version vars] ***********\* 
changed: [localhost] => (item=^edx_platform_version:)
changed: [localhost] => (item=^edx_platform_commit:)
changed: [localhost] => (item=^xqueue_version:)
changed: [localhost] => (item=^forum_version:)
changed: [localhost] => (item=^xserver_version:)
changed: [localhost] => (item=^discern_ease_version:)
changed: [localhost] => (item=^ora_ease_version:)
changed: [localhost] => (item=^discern_version:)
changed: [localhost] => (item=^ora_version:)
changed: [localhost] => (item=^configuration_version:)
changed: [localhost] => (item=^ease_version:)
changed: [localhost] => (item=^certs_version:)
changed: [localhost] => (item=^tags:)
changed: [localhost] => (item=^_original_file:)

TASK: [edx_ansible | create a symlink for var file] **************************\* 
ok: [localhost]

PLAY RECAP *******************************************************************\* 
localhost                  : ok=7    changed=3    unreachable=0    failed=0   

PLAY [Configure instance(s)] *************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [localhost]

TASK: [edx_ansible | git checkout edx_ansible repo into edx_ansible_code_dir] **\* 
changed: [localhost]

TASK: [edx_ansible | install edx_ansible venv requirements] ******************\* 
changed: [localhost]

TASK: [edx_ansible | create update script] ***********************************\* 
ok: [localhost]

TASK: [edx_ansible | create a symlink for update.sh] *************************\* 
ok: [localhost]

TASK: [edx_ansible | dump all vars to yaml] **********************************\* 
changed: [localhost]

TASK: [edx_ansible | clean up var file, removing all version vars] ***********\* 
changed: [localhost] => (item=^edx_platform_version:)
changed: [localhost] => (item=^edx_platform_commit:)
changed: [localhost] => (item=^xqueue_version:)
changed: [localhost] => (item=^forum_version:)
changed: [localhost] => (item=^xserver_version:)
changed: [localhost] => (item=^discern_ease_version:)
changed: [localhost] => (item=^ora_ease_version:)
changed: [localhost] => (item=^discern_version:)
changed: [localhost] => (item=^ora_version:)
changed: [localhost] => (item=^configuration_version:)
changed: [localhost] => (item=^ease_version:)
changed: [localhost] => (item=^certs_version:)
changed: [localhost] => (item=^tags:)
changed: [localhost] => (item=^_original_file:)

TASK: [edx_ansible | create a symlink for var file] **************************\* 
ok: [localhost]

TASK: [edxapp | setup the edxapp env] ****************************************\* 
changed: [localhost]

TASK: [edxapp | create ssh script for git (not authenticated)] ***************\* 
changed: [localhost]

TASK: [edxapp | create ssh script for git (authenticated)] *******************\* 
skipping: [localhost]

TASK: [edxapp | install read-only ssh key] ***********************************\* 
skipping: [localhost]

TASK: [edxapp | checkout edx-platform repo into {{edxapp_code_dir}}] *********\* 
changed: [localhost]

TASK: [edxapp | git clean after checking out edx-platform] *******************\* 
changed: [localhost]

TASK: [edxapp | checkout theme] **********************************************\* 
skipping: [localhost]

TASK: [edxapp | remove read-only ssh key] ************************************\* 
skipping: [localhost]

TASK: [edxapp | create checksum for requirements, package.json and Gemfile] **\* 
changed: [localhost]

TASK: [edxapp | stat path=/var/tmp/edxapp.req.new] ***************************\* 
ok: [localhost]

TASK: [edxapp | stat path=/var/tmp/edxapp.req.installed] *********************\* 
ok: [localhost]

TASK: [edxapp | Updating requirement files for git mirror] *******************\* 
changed: [localhost]

TASK: [edxapp | gem install bundler] *****************************************\* 
changed: [localhost]

TASK: [edxapp | bundle install] **********************************************\* 
changed: [localhost]

TASK: [edxapp | Set the npm registry] ****************************************\* 
skipping: [localhost]

TASK: [edxapp | Install edx-platform npm dependencies] ***********************\* 
changed: [localhost]

TASK: [edxapp | install python pre-requirements] *****************************\* 
ok: [localhost]

TASK: [edxapp | install python base-requirements] ****************************\* 
changed: [localhost]

TASK: [edxapp | install python post-requirements] ****************************\* 
ok: [localhost]

TASK: [edxapp | install python post-post requirements] ***********************\* 
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/repo.txt)
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/github.txt)
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/local.txt)

TASK: [edxapp | install sandbox requirements into regular venv] **************\* 
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx-sandbox/base.txt)
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx-sandbox/local.txt)
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx-sandbox/post.txt)

TASK: [edxapp | code sandbox | put sandbox apparmor profile in complain mode] **\* 
skipping: [localhost]

TASK: [edxapp | code sandbox | Install base sandbox requirements and create sandbox virtualenv] **\* 
skipping: [localhost]

TASK: [edxapp | code sandbox | Install sandbox requirements into sandbox venv] **\* 
skipping: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx-sandbox/local.txt)
skipping: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx-sandbox/post.txt)

TASK: [edxapp | code sandbox | put code sandbox into aa-enforce or aa-complain mode, depending on EDXAPP_SANDBOX_ENFORCE] **\* 
skipping: [localhost]

TASK: [edxapp | compiling all py files in the edx-platform repo] *************\* 
changed: [localhost]

TASK: [edxapp | give other read permissions to the virtualenv] ***************\* 
changed: [localhost]

TASK: [edxapp | create checksum for installed requirements] ******************\* 
changed: [localhost]

TASK: [edxapp | openid workaround] *******************************************\* 
changed: [localhost]

TASK: [edxapp | create  application config] **********************************\* 
fatal: [localhost] => {'msg': "One or more undefined variables: 'EDXAPP_UPDATE_STATIC_FILES_KEY' is undefined", 'failed': True}
fatal: [localhost] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "One or more undefined variables: 'EDXAPP_UPDATE_STATIC_FILES_KEY' is undefined", 'failed': True}]}

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/vagrant-devstack.retry

localhost                  : ok=29   changed=20   unreachable=1    failed=0   

Stderr from the command:

stdin: is not a tty

**Comment by feanil** [comment]
I suspect this is because of a change I made on Friday.  Can you change this line(https://github.com/edx/configuration/blob/master/vagrant/release/devstack/Vagrantfile#L19) to point to 'master' instead of 'release' and try again?

**Comment by marcotuts** [comment]
@feanil I'm trying this now, but I see it is in master again so I'll close this issue for now. Thanks!

edit: ah I can't close it. :) Ok open it stays for now.

**Comment by marcotuts** [comment]
As an update, I tried from scratch with the latest and I'm still unable to build the environment. looks like a different error though I think. 

TASK: [edxapp | writing  supervisor script] **********************************\* 
failed: [localhost] => (item=lms) => {"failed": true, "item": "lms"}
msg: Destination directory /edx/app/supervisor/conf.available.d does not exist
failed: [localhost] => (item=cms) => {"failed": true, "item": "cms"}
msg: Destination directory /edx/app/supervisor/conf.available.d does not exist

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/vagrant-devstack.retry

localhost                  : ok=30   changed=20   unreachable=0    failed=1   

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chmod +x /tmp/vagrant-shell && /tmp/vagrant-shell

Stdout from the command:

PLAY [Deploy the edx_ansible role] *******************************************\* 

TASK: [edx_ansible | git checkout edx_ansible repo into edx_ansible_code_dir] **\* 
changed: [localhost]

TASK: [edx_ansible | install edx_ansible venv requirements] ******************\* 
changed: [localhost]

TASK: [edx_ansible | create update script] ***********************************\* 
ok: [localhost]

TASK: [edx_ansible | create a symlink for update.sh] *************************\* 
ok: [localhost]

TASK: [edx_ansible | dump all vars to yaml] **********************************\* 
changed: [localhost]

TASK: [edx_ansible | clean up var file, removing all version vars] ***********\* 
changed: [localhost] => (item=^edx_platform_version:)
changed: [localhost] => (item=^edx_platform_commit:)
changed: [localhost] => (item=^xqueue_version:)
changed: [localhost] => (item=^forum_version:)
changed: [localhost] => (item=^xserver_version:)
changed: [localhost] => (item=^discern_ease_version:)
changed: [localhost] => (item=^ora_ease_version:)
changed: [localhost] => (item=^discern_version:)
changed: [localhost] => (item=^ora_version:)
changed: [localhost] => (item=^configuration_version:)
changed: [localhost] => (item=^ease_version:)
changed: [localhost] => (item=^certs_version:)
changed: [localhost] => (item=^tags:)
changed: [localhost] => (item=^_original_file:)

TASK: [edx_ansible | create a symlink for var file] **************************\* 
ok: [localhost]

PLAY RECAP *******************************************************************\* 
localhost                  : ok=7    changed=4    unreachable=0    failed=0   

PLAY [Configure instance(s)] *************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [localhost]

TASK: [edx_ansible | git checkout edx_ansible repo into edx_ansible_code_dir] **\* 
ok: [localhost]

TASK: [edx_ansible | install edx_ansible venv requirements] ******************\* 
ok: [localhost]

TASK: [edx_ansible | create update script] ***********************************\* 
changed: [localhost]

TASK: [edx_ansible | create a symlink for update.sh] *************************\* 
ok: [localhost]

TASK: [edx_ansible | create a symlink for ansible-playbook] ******************\* 
changed: [localhost]

TASK: [edx_ansible | create a symlink for the playbooks dir] *****************\* 
changed: [localhost]

TASK: [edx_ansible | dump all vars to yaml] **********************************\* 
skipping: [localhost]

TASK: [edx_ansible | create symlink for config file] *************************\* 
skipping: [localhost]

TASK: [edx_ansible | clean up var file, removing all version vars and internal ansible vars (anything not caps)] **\* 
skipping: [localhost]

TASK: [edxapp | setup the edxapp env] ****************************************\* 
changed: [localhost]

TASK: [edxapp | create ssh script for git (not authenticated)] ***************\* 
changed: [localhost]

TASK: [edxapp | create ssh script for git (authenticated)] *******************\* 
skipping: [localhost]

TASK: [edxapp | install read-only ssh key] ***********************************\* 
skipping: [localhost]

TASK: [edxapp | checkout edx-platform repo into {{edxapp_code_dir}}] *********\* 
changed: [localhost]

TASK: [edxapp | git clean after checking out edx-platform] *******************\* 
changed: [localhost]

TASK: [edxapp | checkout theme] **********************************************\* 
skipping: [localhost]

TASK: [edxapp | remove read-only ssh key] ************************************\* 
skipping: [localhost]

TASK: [edxapp | create checksum for requirements, package.json and Gemfile] **\* 
changed: [localhost]

TASK: [edxapp | stat path=/var/tmp/edxapp.req.new] ***************************\* 
ok: [localhost]

TASK: [edxapp | stat path=/var/tmp/edxapp.req.installed] *********************\* 
ok: [localhost]

TASK: [edxapp | Updating requirement files for git mirror] *******************\* 
changed: [localhost]

TASK: [edxapp | gem install bundler] *****************************************\* 
changed: [localhost]

TASK: [edxapp | bundle install] **********************************************\* 
changed: [localhost]

TASK: [edxapp | Set the npm registry] ****************************************\* 
skipping: [localhost]

TASK: [edxapp | Install edx-platform npm dependencies] ***********************\* 
changed: [localhost]

TASK: [edxapp | install python pre-requirements] *****************************\* 
ok: [localhost]

TASK: [edxapp | install python base-requirements] ****************************\* 
changed: [localhost]

TASK: [edxapp | install python post-requirements] ****************************\* 
ok: [localhost]

TASK: [edxapp | install python post-post requirements] ***********************\* 
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/repo.txt)
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/github.txt)
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx/local.txt)

TASK: [edxapp | install sandbox requirements into regular venv] **************\* 
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx-sandbox/base.txt)
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx-sandbox/local.txt)
changed: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx-sandbox/post.txt)

TASK: [edxapp | code sandbox | put sandbox apparmor profile in complain mode] **\* 
skipping: [localhost]

TASK: [edxapp | code sandbox | Install base sandbox requirements and create sandbox virtualenv] **\* 
skipping: [localhost]

TASK: [edxapp | code sandbox | Install sandbox requirements into sandbox venv] **\* 
skipping: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx-sandbox/local.txt)
skipping: [localhost] => (item=/edx/app/edxapp/edx-platform/requirements/edx-sandbox/post.txt)

TASK: [edxapp | code sandbox | put code sandbox into aa-enforce or aa-complain mode, depending on EDXAPP_SANDBOX_ENFORCE] **\* 
skipping: [localhost]

TASK: [edxapp | compiling all py files in the edx-platform repo] *************\* 
changed: [localhost]

TASK: [edxapp | give other read permissions to the virtualenv] ***************\* 
changed: [localhost]

TASK: [edxapp | create checksum for installed requirements] ******************\* 
changed: [localhost]

TASK: [edxapp | openid workaround] *******************************************\* 
changed: [localhost]

TASK: [edxapp | create  application config] **********************************\* 
changed: [localhost] => (item=lms)
changed: [localhost] => (item=cms)

TASK: [edxapp | create  auth file] *******************************************\* 
ok: [localhost] => (item=lms)
ok: [localhost] => (item=cms)

TASK: [edxapp | writing  supervisor script] **********************************\* 
failed: [localhost] => (item=lms) => {"failed": true, "item": "lms"}
msg: Destination directory /edx/app/supervisor/conf.available.d does not exist
failed: [localhost] => (item=cms) => {"failed": true, "item": "cms"}
msg: Destination directory /edx/app/supervisor/conf.available.d does not exist

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/vagrant-devstack.retry

localhost                  : ok=30   changed=20   unreachable=0    failed=1   

Stderr from the command:

stdin: is not a tty

**Comment by rminderhoud** [comment]
Also experiencing the `msg: Destination directory /edx/app/supervisor/conf.available.d does not exist` error on master

**Comment by feanil** [comment]
The issue should be fixed with https://github.com/edx/configuration/pull/895/files

Tested it locally on devstack and then seems to work.  Will merge it once the CI tests pass.

**Comment by feanil** [comment]
This got merged in yesterday evening, please try again and let me know if you're still seeing issues.
