### ISSUE TITLE
Ora unmet python requirement

### ISSUE THREAD

**Issue by solitaryr** [openedx-unsupported/configuration#897]
Got the following error today updating with latest master branch:

Downloading/unpacking matplotlib==1.2.0 (from -r /edx/app/ora/ora/requirements.txt (line 6))
  Could not find a version that satisfies the requirement matplotlib==1.2.0 (from -r /edx/app/ora/ora/requirements.txt (line 6)) (from versions: 0.86.1, 0.86.2, 0.86, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.3.1)
  Some externally hosted files were ignored (use --allow-external to allow).
Cleaning up...
No distributions matching the version for matplotlib==1.2.0 (from -r /edx/app/ora/ora/requirements.txt (line 6))

There was a similar xqueue message that was merged today.  Would it be safe to use 1.3.1?

**Comment by solitaryr** [comment]
Apparently, I can't override this manually since it checks it out of the master branch as part of the install.  For the record, I was trying to use 1.2.1 since that appears to be the last stable 1.2.x series.

**Comment by feanil** [comment]
The requirements change would be on the edx-ora project itself, I would open up an issue here(https://github.com/edx/edx-ora) to see if the ORA team would be willing to make the requirements upgrade.
