### ISSUE TITLE
discern, deploy.yml

### ISSUE THREAD

**Issue by mercefan** [openedx-unsupported/configuration#898]
I'm not able to make a pull request, so I write this issue.

Discern failed to me when updating. It seems the problem is in the deploy.yml file from:
- playbooks/roles/discern/tasks/deploy.yml
  https://github.com/edx/configuration/blob/master/playbooks/roles/discern/tasks/deploy.yml

In line 12, it should be written src instead of dest.

**Comment by feanil** [comment]
@mercefan This PR should fix it(https://github.com/edx/configuration/pull/895), it's being tested now.

**Comment by mercefan** [comment]
I haven't found that PR. In that case, I wouldn't write this issue. You can close this, so. Thank you.
