### ISSUE TITLE
dev vagrant does not clone edx-platform and friends

### ISSUE THREAD

**Issue by pmitros** [openedx-unsupported/configuration#901]
I tried to create a devstack. It failed because edx-platform was missing. 

https://gist.github.com/pmitros/2d58aa026bb527f2e135

When I grabbed edx-platform, it failed on cs_comments_service, and so on and so forth.

**Comment by jarv** [comment]
What OS are you doing this from?

**Comment by pmitros** [comment]
Ubuntu 13.10.

**Comment by jarv** [comment]
Any chance you are using an encrypted volume? I know nfs exports won't work
with ubuntu's encryption.

**Comment by pmitros** [comment]
Normal, unencrypted volume.

**Comment by feanil** [comment]
And just to verify, your versions of Vagrant and Virtualbox match the
versions suggested on the wiki?  Also what shell are you using and have you
set the override for the location where the repositories are nfs mounted?

**Comment by pmitros** [comment]
Huh. You're right. Vagrant somehow reverted versions on my system during apt installs/uninstalls. 

It works now. Just for the sake of leaving behind a real bug report, in that case, the command did fail with: 

sudo: /usr/bin/exportfs: command not found

exportfs is in /usr/sbin on my system. Adding a symlink fixes it. From there, it works fine.

**Comment by feanil** [comment]
I think that is a bug in Vagrant not in our vagrant file.
