### ISSUE TITLE
discern deploy issue

### ISSUE THREAD

**Issue by solitaryr** [openedx-unsupported/configuration#902]
Hey,

I opened this under https://github.com/edx/discern/issues/151 and posting it here in anticipation of being told to add it here :-)...

Attempting to do a new install today and ran into the following error with master branch:

TASK: [discern | enable supervisor scripts - discern, discern_celery] ********\* 
failed: [localhost] => (item=discern) => {"failed": true, "item": "discern"}
msg: src and dest are required for creating links

failed: [localhost] => (item=discern_celery) => {"failed": true, "item": "discern_celery"}
msg: src and dest are required for creating links

FATAL: all hosts have already failed -- aborting

I think I tracked it down to this block in the discern task deploy.yml file

<pre>
- name: enable supervisor scripts - discern, discern_celery
  file: >
    dest={{ supervisor_available_dir }}/{{ item }}.conf
    dest={{ supervisor_cfg_dir }}/{{ item }}.conf
    owner={{ supervisor_user }}
    state=link
    force=yes
    mode=0644
  sudo_user: "{{ supervisor_user }}"
  with_items: ['discern', 'discern_celery']
  when: not disable_edx_services
</pre>

One of the dest= should be src= and I'm assuming it should be

<pre>
- name: enable supervisor scripts - discern, discern_celery
  file: >
    src={{ supervisor_available_dir }}/{{ item }}.conf
    dest={{ supervisor_cfg_dir }}/{{ item }}.conf
    owner={{ supervisor_user }}
    state=link
    force=yes
    mode=0644
  sudo_user: "{{ supervisor_user }}"
  with_items: ['discern', 'discern_celery']
  when: not disable_edx_services
</pre>

**Comment by solitaryr** [comment]
If it's wrong, that at least got me past this...now I'm looking forward to the next failure.  Just need someone from edX to confirm the above.

**Comment by edx-secure** [comment]
Yea, that's the correct fix. There is a PR for this that was just merged. (
https://github.com/edx/configuration/pull/895)

**Comment by hkim823** [comment]
@solitaryr can you confirm this issue is closed?
