### ISSUE TITLE
edX Ubuntu 12.04 Installation

### ISSUE THREAD

**Issue by manishamehta** [openedx-unsupported/configuration#917]
When I run this command, following steps given on https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation#installing-edx-on-a-single-ubuntu-1204-precise-server-from-scratch, 

cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost," 

it gives me an error gem bundler error, forbidden 403

**Comment by manishamehta** [comment]
error is could not find valid gem 'bundler' (=1.3.2)  in any repository, header 'Content-type' value denied 403, how to remove this,
Thanks in advance.

**Comment by hkim823** [comment]
Can you post the full stacktrace in a gist?  That would be helpful for us to troubleshoot it.

**Comment by manishamehta** [comment]
Following I got and installation stopped.
Thanking you in advance,

TASK: [rbenv | install bundler] **********************************************\* 
failed: [localhost] => {"changed": true, "cmd": "gem install bundler -v 1.3.2 ", "delta": "0:00:04.946851", "end": "2014-03-27 13:36:40.624641", "item": "", "rc": 1, "start": "2014-03-27 13:36:35.677790"}
stderr: ERROR:  Could not find a valid gem 'bundler' (= 1.3.2) in any repository
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden: header 'Content-Type' value denied 403 (http://production.s3.rubygems.org/latest_specs.4.8.gz)

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/home/edx/edx_sandbox.retry

localhost                  : ok=68   changed=12   unreachable=0    failed=1

**Comment by manishamehta** [comment]
Sorry, By mistake I clicked close button, it's still open.
Thanks.

**Comment by hkim823** [comment]
That sounds looks like a network error where you are not able to download something from rubygems.org check your network / internet connection.  The software has a lot of network dependencies outside of just the code to be able to compile properly.

**Comment by manishamehta** [comment]
Sir,
I tried to install using gem install bundler 1.3.2  and succeed to install but again when I run cd /var/tmp/configuration/playbooks && sudo ansible-playbook -c local ./edx_sandbox.yml -i "localhost,"
gave me same error

**Comment by hkim823** [comment]
Can you post the whole error in a gist? https://gist.github.com/
