### ISSUE TITLE
how to install on debain (my own server/computer)

### ISSUE THREAD

**Issue by suraxy** [openedx-unsupported/configuration#92]
I have already run 

 pip install -r fabric-requirements.txt

 pip install -r  ansible-requirements.txt

but  how can I start it ?

**Comment by e0d** [comment]
This project is building a reference implementation of the edX platform.  The code that we run on the server side isn't open source yet, but will be soon.  Running this project would build an AWS VPC with numerous servers in it.  We also plan to get ansible running with Vagrant, but that's not available yet.

**Comment by ddiazUNSJ** [comment]
I have a question.
I have a question. At the moment is possible to configure and run an instance of the platform edx on Amazon Web Services to manage my university courses.
Thanks in advance

**Comment by kern3020** [comment]
Hello @ddiazUNSJ,

I am not affiliated with edX. I know much of the source code hasn't been released yet(e.g., the LMS, Studio, etc). edX has [announced](http://www.prnewswire.com/news-releases/stanford-university-to-collaborate-with-edx-on-development-of-non-profit-open-source-edx-platform-201213681.html) it's intent to open source everything by June 1st but that is a Saturday. Let's give them until June 3rd. 

So, for those are not affiliated with edX, we will have to way awhile longer. 

-jk

**Comment by jbau** [comment]
the edx/edx-platform repo is now open!
