### ISSUE TITLE
Python/Vagrant.sh install error creating egg.  "Maximum recusion depth exceeded"

### ISSUE THREAD

**Issue by justinperkins1** [openedx-unsupported/configuration#937]
Following directions at: https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-Installation when I issue the cmd: "wget https://raw.github.com/edx/configuration/master/util/install/vagrant.sh -O - | bash" then it runs for a long while, and eventually fails like so:

[code]

...(before this point, pages upon pages of script-called-script-called-script tree)...

RuntimeError: maximum recursion depth exceeded

/edx/app/discern/venvs/discern/build/MySQL-python/distribute-0.6.28-py2.7.egg

Traceback (most recent call last):

File "", line 17, in

File "/edx/app/discern/venvs/discern/build/MySQL-python/setup.py", line 7, in

use_setuptools()

File "distribute_setup.py", line 145, in use_setuptools

return _do_download(version, download_base, to_dir, download_delay)

File "distribute_setup.py", line 125, in _do_download

_build_egg(egg, tarball, to_dir)

File "distribute_setup.py", line 116, in _build_egg

raise IOError('Could not build the egg.')

IOError: Could not build the egg.

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /edx/app/discern/venvs/discern/build/MySQL-python
Storing debug log for failure in /edx/app/discern/.pip/pip.log

ok: [localhost] => (item=/edx/app/discern/ease/requirements.txt)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
to retry, use: --limit @/home/user/edx_sandbox.retry

localhost : ok=318 changed=72 unreachable=0 failed=1

user@EdX-dev:~$

[\code]

note: I am fairly sure this can be fixed by a judicious insertion of "sys.setrecursionlimit(2000)" or something in that ballpark. I suspect the scripts calling scripts calling scripts have grown past the default of 999 nested calls, but this isn't a looping recursion (I don't think) and is hitting a recursion defensive default of python, accidentally. (by which I mean, it isn't a loop looping around and around 999 times, it's actually many many nested scripts, I suspect)

Not sure it helps, but the os is ubuntu 12.04 freshly installed from .iso in a VMware esx 5.1 VM, and other then the apt-get update instructions, only vmtools has been installed prior to running vagrant.sh

**Comment by hkim823** [comment]
Are we positive we're running 12.04 server 64 bit?

**Comment by justinperkins1** [comment]
positive. I believe this issue is being addressed, see: https://github.com/edx/discern/pull/154

also, the same error in a different context. looks like MySQL-python 1.2.4c1 needs to be MySQL-python 1.2.5 and that should fix it:
http://stackoverflow.com/questions/21198881/error-when-trying-to-install-django-cms-in-virtualenv-w-mysql-on-mac-osx

I will test now and post if I find success/failure

**Comment by phobossion** [comment]
How do you apply the change to the vagrant install, given that the change hasn't been merged to master yet?

**Comment by defance** [comment]
My pull request has been merged to discern master. Check it out. Does it solve you problem? I so, issue can be closed, I suppose.
