### ISSUE TITLE
Devstack install fails with newrelic version requirement

### ISSUE THREAD

**Issue by pmitros** [openedx-unsupported/configuration#953]
Installing devstack fails on newrelic. 

Removing the newrelic version (so line is just 'newrelic' instead of 'newrelic==2.18.1.15') from the requirements, removing the re-pull of edx-platform, and rerunning ansible allows the process to continue. 

Starting the LMS fails since paver is uninstalled. Running: 
  /edx/bin/pip.edxapp install paver 
Installs it. psutils is missing at this point as well, and requires a pip install. 

At this point, the LMS runs without issues. 

OS is Mac. 

On a related note: I would suggest changing the documentation to give a rough high-level, technical walk-through of the install process and how to repeat it by hand. Right now, the process is very smooth when it works, but when it breaks, debugging an issue like this takes a lot of tracing through code. A simple directory of what files are used during the install process, where they are and what they do, and possibly the commands for how use them would be very helpful.

**Comment by hkim823** [comment]
I agree with having a high level document about how edX is installed in these cases, and how to reproduce it and troubleshoot ansible runs.

**Comment by hkim823** [comment]
In the meantime, this might work, once you vagrant ssh

```
source /edx/app/edx_ansible/venvs/edx_ansible/bin/activate
cd /edx/app/edx_ansible/edx_ansible/playbooks
/edx/bin/update configuration release
ansible-playbook -i localhost, -c local vagrant-devstack.yml -e configuration_version=release
```

**Comment by pmitros** [comment]
@hkim823 That was similar to my first step. The issue details all the issues needed to resolve the issues. Re-reading, I can see how this may not have been clear. To be very specific, in order to successfully install devstack, as of yesterday morning, you need to: 
1. Run vagrant up as per instructions. 
2. Change newrelic to omit the specific version in the requirements file. 
3. Disable re-pulling of edx-platform in ansible config so the above change doesn't get overridden. 
4. Rerun ansible playbook. 
5. Manually install paver and psutils. 

Once this is done, devstack appears to work fine.

**Comment by hkim823** [comment]
@pmitros I was seeing the same issue when you reported it, my fix to just run ansible again without the deploy tag also resolved my issue, with newrelic being installed correctly

**Comment by rlucioni** [comment]
@hkim823, I had the same issue as @pmitros, but your fixed resolved the newrelic failures for me. I still had to install paver and psutil manually.

**Comment by hkim823** [comment]
We've seen made updates to configuration and merged them back into master, including using paver and getting around this issue in particular.  Please try it again.  I'm going to close this issue.
