### ISSUE TITLE
Installion error for cms

### ISSUE THREAD

**Issue by manishamehta** [openedx-unsupported/configuration#961]
While Installing edx platform,
When I run this command, 
./manage.py cms syncdb --migrate
gives following
No handlers could be found for logger "DEALER"
Traceback  (most recent call last):
 File "./manage.py" line 90, in <module>,
...
....
...
File /usr/local/lib/python2.7/dist-packages/dealer/git.py" line 77 init_repo
  raise TypeError(e)
TypeError: fatal : Not a git repository (or any of the parent directories): .git

**Comment by feanil** [comment]
@manishamehta can you provide a bit of context for this.  What set of instructions were you following?

**Comment by manishamehta** [comment]
Hello Fenil,
I am following this steps,
http://nkokkos.wordpress.com/2013/10/09/setting-up-edx-platform-on-ubutnu/

but it is solved after running following commands,

after running following commands,
$ git add “*”
$git config –global user.email “you@example.com”
$ git commit -m “Your commit message”
$ git log

run
$./manage.py cms syncdb –migrate

will solve the errors
