### ISSUE TITLE
How to access studio?

### ISSUE THREAD

**Issue by tansaku** [openedx-unsupported/configuration#974]
I'm tinkering with edx production box via vagrant install.  I can access the LMS via:

http://192.168.33.10/

however I don't know how to access studio to create courses etc.  Would that just be running on another port or something?

**Comment by feanil** [comment]
if you want to reach studio through nginx you'll have to setup a fake host name pointing to this ip that resolves to 'studio.local' but you can also go to studio and lms directly on their gunicorn ports.

https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L474-L479
