### ISSUE TITLE
web installation problem

### ISSUE THREAD

**Issue by 1L02** [openedx-unsupported/configuration#98]
Hi, there

edx is now open source, and i had also brought aws services for that, 

however, i have be struggled for the past 48hours, with no luck to build this thing on amazon.

so i am here to see if anyone has some experience for doing that?

as i dunno even where to start, to build the platform up. :(

**Comment by e0d** [comment]
We need more information to help you, provide some specific issues that you are having either here or or the #edx-code channel on freenode.
