### ISSUE TITLE
rake lms[cms.dev,0.0.0.0:8000] error

### ISSUE THREAD

**Issue by manishamehta** [openedx-unsupported/configuration#983]
I am following steps from here,
http://nkokkos.wordpress.com/2013/10/09/setting-up-edx-platform-on-ubutnu,

When I run,

$rake lms[cms.dev,0.0.0.0:8000]
gives erRequirement already satisfied (use --upgrade to upgrade): Paver==1.2.1 in ./EDXENV/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): psutil==1.2.1 in ./EDXENV/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): lazy==1.1 in ./EDXENV/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): path.py==3.0.1 in ./EDXENV/lib/python2.7/site-packages (from -r requirements/edx/paver.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./EDXENV/lib/python2.7/site-packages (from lazy==1.1->-r requirements/edx/paver.txt (line 4))
Cleaning up...
Task lms has been deprecated. Use paver lms --settings=cms.dev --port=0.0.0.0:8125 instead. Waiting 5 seconds...
---> pavelib.servers.lms
---> pavelib.prereqs.install_prereqs
Ruby prereqs unchanged, skipping...
Node prereqs unchanged, skipping...
Python prereqs unchanged, skipping...
---> pavelib.assets.update_assets
python manage.py lms --settings=cms.dev preprocess_assets
xmodule_assets common/static/xmodule
node_modules/.bin/coffee --compile  `find /home/mpm1/edx/lms /home/mpm1/edx/cms /home/mpm1/edx/common -type f -name "*.coffee"`
warning : could nit find environment JSON file at /home/xxx/env.json
sass --style compressed --cache-location /tmp/sass-cache --load-path ./common/static/sass --update -E utf-8 */static
  overwrite cms/static/sass/style-app-extend1.css
  overwrite cms/static/sass/style-app.css
  overwrite cms/static/sass/style-xmodule.css
  overwrite lms/static/sass/application-extend1.css
  overwrite lms/static/sass/application-extend2.css
  overwrite lms/static/sass/application.css
  overwrite lms/static/sass/course.css
  overwrite lms/static/sass/ie.css
Enter CTL-C to end
fatal: No names found, cannot describe anything
...
...
....
....

  ..../runserver.py  line 55 in handle,  address:port pair
command error 0.0.0.0:0.0.0.0:8000 is not valid port number or address:port pair

Please help me

**Comment by feanil** [comment]
It looks like you gave rake the wrong parameters.  The second param is just the port number not the host and port.

Also rake has been deprecated, try running the corresponding paver command instead.
`paver lms --settings=lms.dev --port=8000`

**Comment by manishamehta** [comment]
Thanks it is working
Sorry, was busy with academics schedules
so today I checked
