### ISSUE TITLE
cloning into 'configuration' error

### ISSUE THREAD

**Issue by ghost** [openedx-unsupported/configuration#988]
git clone -b release https://github.com/edx/configuration

Error:
“cloning into ‘configuration’…
remote: Counting objects:22962,done
remote: Compressing objects: 100%(9800/9800),done.
error: RPC failed; result-56,HTTP code = 200iB 1Kib/s
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed” 

what mean this information please? How to solve?Thank you!

**Comment by e0d** [comment]
This is a github issue, try to reclone.
