### ISSUE TITLE
Problems after installation

### ISSUE THREAD

**Issue by defance** [openedx-unsupported/configuration#993]
Well, it's me again.

I did freshy install of edx-platform on 12.04 64bit. I am sure it is.

After installation all I get in browser is 502 (Bad gateway). I decided to send the server to reboot. After reboot I was unable to connect to it via ssh (permission denied, **public key**).

I am pretty sure, that previous versions of onfiguration were fine. But the freshy version has now some issues. What can be the key?

I stress this once more: I cannot send you logs for now as the server rejects ssh connection.

**Comment by feanil** [comment]
Is this an ec2 instance or a local machine?  What user are you trying to ssh as?

**Comment by hkim823** [comment]
Hi @defance I think you put in a issue at edx-platform that was related to the ssh issue, which I showed you the PR that should give you the option to turn on password based authentication for ssh.  

If you are still having issues, please let us know.

**Comment by defance** [comment]
@feanil It is virtual machine in remote virtualization environement. I tried to reload container but shill this VM is not longer accessible via ssh.

**Comment by defance** [comment]
@hkim823 I have no chance connecting to it. I have not touched any ssh configuration. And my command line is like following:\

```
d.ivanyushin@shuttle6:~$ ssh root@192.168.4.73
Permission denied (publickey).
```

As you can see, I am not even promted to input any password here.

Well. I am launching another copy of platform to deploy, I will tell you results then. I suppose, this one copy can be killed.

**Comment by jambonbill** [comment]
did you try

d.ivanyushin@shuttle6:~$ vagrant ssh

?

On 11 April 2014 15:17, Dmitry Ivanyushin notifications@github.com wrote:

> @hkim823 https://github.com/hkim823 I have no chance connecting to it.
> I have not touched any ssh configuration. And my command line is like
> following:
> d.ivanyushin@shuttle6:~$ ssh root@192.168.4.73
> Permission denied (publickey).
> As you can see, I am not even promted to input any password here.
> 
> Well. I am launching another copy of platform to deploy, I will tell you
> results then. I suppose, this one copy can be killed.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/edx/configuration/issues/993#issuecomment-40201996
> .

## 

pierre

**Comment by defance** [comment]
@jambonbill It is remote server, not local virtual vagrant environement.

**Comment by hkim823** [comment]
@defance the ansible playbook to install edx changes the ssh configuration to only allow for key based authentication but a recent change was made to put in the option, but you have to make sure to utilize that option before running any installation of edx so you don't get locked out again.

**Comment by defance** [comment]
@hkim823  I see... I modified playbook to use password auth. Issue is solved for now.
