### ISSUE TITLE
paver 

### ISSUE THREAD

**Issue by ThePanguan** [openedx-unsupported/configuration#997]
when i ssh to Unbuntu,use paver command,the unix say ,paver:command not found,how can i do ,I want to deploy the lms,help me ,thanks

**Comment by jambonbill** [comment]
google led me here :
http://stackoverflow.com/questions/16024654/install-python-paver-to-ubuntu
it say :

$ pip install -U Paver

On 11 April 2014 11:02, liulei notifications@github.com wrote:

> when i ssh to Unbuntu,use paver command,the unix say ,paver:command not
> found,how can i do ,I want to deploy the lms,help me ,thanks
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/edx/configuration/issues/997
> .

## 

pierre

**Comment by hkim823** [comment]
Paver should be getting installed with the latest versions of edx-platform and configuration.

```
vagrant up
vagrant ssh
sudo /edx/bin/update configuration master
sudo /edx/bin/update edx-platform master
```

**Comment by singingwolfboy** [comment]
This should be fixed by https://github.com/edx/configuration/pull/1001
